= Cassandra CQL Component
:doctitle: Cassandra CQL
:shortname: cql
:artifactid: camel-cassandraql
:description: Integrate with Cassandra 2.0 using the CQL3 API (not the Thrift API). Based on Cassandra Java Driver provided by DataStax.
:since: 2.15
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:camel-spring-boot-name: cassandraql

*Since Camel {since}*

*{component-header}*

http://cassandra.apache.org[Apache Cassandra] is an open source NoSQL
database designed to handle large amounts on commodity hardware. Like
Amazon's DynamoDB, Cassandra has a peer-to-peer and master-less
architecture to avoid a single point of failure and guaranty high
availability. Like Google's BigTable, Cassandra data is structured using
column families which can be accessed through the Thrift RPC API or an
SQL-like API called CQL.

[NOTE]
====
This component aims at integrating Cassandra 2.0+ using the CQL3 API instead of the Thrift API.
It's based on https://github.com/datastax/java-driver[Cassandra Java Driver] provided by DataStax.
====

// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END

// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

== Endpoint Connection Syntax

The endpoint can initiate the Cassandra connection or use an existing
one.

[cols="<,<",options="header",]
|======================================================================
|URI |Description
|`cql:localhost/keyspace` |Single host, default port, usual for testing
|`cql:host1,host2/keyspace` |Multi host, default port
|`cql:host1,host2:9042/keyspace` |Multi host, custom port
|`cql:host1,host2` |Default port and keyspace
|`cql:bean:sessionRef` |Provided Session reference
|======================================================================

To fine-tune the Cassandra connection (SSL options, pooling options,
load balancing policy, retry policy, reconnection policy...), create
your own Cluster instance and give it to the Camel endpoint.

== Messages

=== Incoming Message

The Camel Cassandra endpoint expects a bunch of simple objects (`Object`
or `Object[]` or `Collection<Object>`) which will be bound to the CQL
statement as query parameters. If the message body is null or empty, then
CQL query will be executed without binding parameters.

Headers:

* `CamelCqlQuery` (optional, `String` or `RegularStatement`): CQL query
either as a plain String or built using the `QueryBuilder`.

=== Outgoing Message

The Camel Cassandra endpoint produces one or many a Cassandra Row
objects depending on the `resultSetConversionStrategy`:

* `List<Row>` if `resultSetConversionStrategy` is `ALL` or
`LIMIT_[0-9]+`
* Single` Row` if `resultSetConversionStrategy` is `ONE`
* Anything else, if `resultSetConversionStrategy` is a custom
implementation of the `ResultSetConversionStrategy`

== Repositories

Cassandra can be used to store message keys or messages for the
idempotent and aggregation EIP.

Cassandra might not be the best tool for queuing use cases yet, read
http://www.datastax.com/dev/blog/cassandra-anti-patterns-queues-and-queue-like-datasets[Cassandra
anti-patterns queues and queue like datasets]. It's advised to use
LeveledCompaction and a small GC grace setting for these tables to allow
tombstoned rows to be removed quickly.

== Idempotent repository

The `NamedCassandraIdempotentRepository` stores messages keys in a
Cassandra table like this:

*CAMEL_IDEMPOTENT.cql*

[source,sql]
---------------------------------------------------------
CREATE TABLE CAMEL_IDEMPOTENT (
  NAME varchar,   -- Repository name
  KEY varchar,    -- Message key
  PRIMARY KEY (NAME, KEY)
) WITH compaction = {'class':'LeveledCompactionStrategy'}
  AND gc_grace_seconds = 86400;
---------------------------------------------------------

This repository implementation uses lightweight transactions, (also known
as Compare and Set) and requires Cassandra 2.0.7+.

Alternatively, the `CassandraIdempotentRepository` does not have a
`NAME` column and can be extended to use a different data model.

[width="100%",cols="<34%,<33%,<33%",options="header",]
|=======================================================================
|Option |Default |Description

|`table` |`CAMEL_IDEMPOTENT` |Table name

|`pkColumns` |`NAME`,` KEY` |Primary key columns

|`name` |  | Repository name, value used for `NAME` column

|`ttl` |   | Key time to live

|`writeConsistencyLevel` |  | Consistency level used to insert/delete key: `ANY`, `ONE`, `TWO`,
`QUORUM`, `LOCAL_QUORUM`…

|`readConsistencyLevel` |  | Consistency level used to read/check key: `ONE`, `TWO`, `QUORUM`,
`LOCAL_QUORUM`…
|=======================================================================

== Aggregation repository

The `NamedCassandraAggregationRepository` stores exchanges by
correlation key in a Cassandra table like this:

*CAMEL_AGGREGATION.cql*

[source,sql]
---------------------------------------------------------
CREATE TABLE CAMEL_AGGREGATION (
  NAME varchar,        -- Repository name
  KEY varchar,         -- Correlation id
  EXCHANGE_ID varchar, -- Exchange id
  EXCHANGE blob,       -- Serialized exchange
  PRIMARY KEY (NAME, KEY)
) WITH compaction = {'class':'LeveledCompactionStrategy'}
  AND gc_grace_seconds = 86400;
---------------------------------------------------------

Alternatively, the `CassandraAggregationRepository` does not have a
`NAME` column and can be extended to use a different data model.

[width="100%",cols="<34%,<33%,<33%",options="header",]
|=======================================================================
|Option |Default |Description

|`table` |`CAMEL_AGGREGATION` |Table name

|`pkColumns` |`NAME`,`KEY` |Primary key columns

|`exchangeIdColumn` |`EXCHANGE_ID` |Exchange Id column

|`exchangeColumn` |`EXCHANGE` |Exchange content column

|`name` |  | Repository name, value used for `NAME` column

|`ttl` |  | Exchange time to live

|`writeConsistencyLevel` |  | Consistency level used to insert/delete exchange: `ANY`, `ONE`, `TWO`,
`QUORUM`, `LOCAL_QUORUM`…

|`readConsistencyLevel` |  | Consistency level used to read/check exchange: `ONE`, `TWO`, `QUORUM`,
`LOCAL_QUORUM`…
|=======================================================================

While deserializing, it's important to notice that the `unmarshallExchange` method will allow only all java packages and subpackages
and org.apache.camel packages and subpackages. The remaining classes will be blacklisted. So you'll need to change the filter in case of need.
This could be accomplished by changing the deserializationFilter field in the repository.

== Examples

To insert something on a table, you can use the following code:

[source,java]
---------------------------------------------------------
String CQL = "insert into camel_user(login, first_name, last_name) values (?, ?, ?)";
from("direct:input")
    .to("cql://localhost/camel_ks?cql=" + CQL);
---------------------------------------------------------

At this point, you should be able to insert data by using a list as body

[source,java]
---------------------------------------------------------
Arrays.asList("davsclaus", "Claus", "Ibsen");
---------------------------------------------------------

The same approach can be used for updating or querying the table.



include::spring-boot:partial$starter.adoc[]
