= Kubernetes Service Account Component
:doctitle: Kubernetes Service Account
:shortname: kubernetes-service-accounts
:artifactid: camel-kubernetes
:description: Perform operations on Kubernetes Service Accounts.
:since: 2.17
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported
//Manually maintained attributes
:group: Kubernetes
:camel-spring-boot-name: kubernetes

*Since Camel {since}*

*{component-header}*

The Kubernetes Service Account component is one of xref:kubernetes-summary.adoc[Kubernetes Components] which
provides a producer to execute Kubernetes Service Account operations.


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END
// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

== Supported producer operation

- listServiceAccounts
- listServiceAccountsByLabels
- getServiceAccount
- createServiceAccount
- updateServiceAccount
- deleteServiceAccount

== Kubernetes ServiceAccounts Produce Examples

- listServiceAccounts: this operation lists the sa on a kubernetes cluster

[source,java]
--------------------------------------------------------------------------------
from("direct:list").
    toF("kubernetes-service-accounts:///?kubernetesClient=#kubernetesClient&operation=listServiceAccounts").
    to("mock:result");
--------------------------------------------------------------------------------

This operation returns a List of services from your cluster

- listServiceAccountsByLabels:  this operation lists the sa by labels on a kubernetes cluster

[source,java]
--------------------------------------------------------------------------------
from("direct:listByLabels").process(new Processor() {
            @Override
            public void process(Exchange exchange) throws Exception {
                Map<String, String> labels = new HashMap<>();
                labels.put("key1", "value1");
                labels.put("key2", "value2");
                exchange.getIn().setHeader(KubernetesConstants.KUBERNETES_SERVICE_ACCOUNTS_LABELS, labels);
            }
        });
    toF("kubernetes-service-accounts:///?kubernetesClient=#kubernetesClient&operation=listServiceAccountsByLabels").
    to("mock:result");
--------------------------------------------------------------------------------

This operation returns a List of Services from your cluster, using a label selector (with key1 and key2, with value value1 and value2)


include::spring-boot:partial$starter.adoc[]
