= Kubernetes Components
//attributes written by hand, not generated
:doctitle: Kubernetes
:since: 2.17
:shortname: kubernetes
:artifactid: camel-kubernetes

*Since Camel {since}*

The Kubernetes components integrate your application with Kubernetes standalone or on top of Openshift.


== {doctitle} components

See the following for usage of each component:

indexDescriptionList::[attributes='group={doctitle}',descriptionformat=description]

== Installation

Maven users will need to add the following dependency to
their `pom.xml` for this component:
[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-kubernetes</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------


== Usage

=== Producer examples

Here we show some examples of producer using camel-kubernetes.

=== Create a pod

[source,java]
-------------------------------------------------------------
from("direct:createPod")
    .toF("kubernetes-pods://%s?oauthToken=%s&operation=createPod", host, authToken);
-------------------------------------------------------------

By using the `KubernetesConstants.KUBERNETES_POD_SPEC` header, you can specify your PodSpec and pass it to this operation.

=== Delete a pod

[source,java]
-------------------------------------------------------------
from("direct:createPod")
    .toF("kubernetes-pods://%s?oauthToken=%s&operation=deletePod", host, authToken);
-------------------------------------------------------------

By using the `KubernetesConstants.KUBERNETES_POD_NAME` header, you can specify your Pod name and pass it to this operation.

== Using Kubernetes ConfigMaps and Secrets

The `camel-kubernetes` component also provides xref:manual:ROOT:using-propertyplaceholder.adoc[Property Placeholder]
functions that load the property values from Kubernetes _ConfigMaps_ or _Secrets_.

For more information, see xref:manual:ROOT:using-propertyplaceholder.adoc[Property Placeholder].

:camel-spring-boot-name: kubernetes

include::spring-boot:partial$starter.adoc[]
