[[kubernetes-resources-quota-component]]
= Kubernetes Resources Quota Component
:docTitle: Kubernetes Resources Quota
:artifactId: camel-kubernetes
:description: Perform operations on Kubernetes Resources Quotas.
:since: 2.17
:supportLevel: Stable
:component-header: Only producer is supported
include::{cq-version}@camel-quarkus:ROOT:partial$reference/components/kubernetes-resources-quota.adoc[opts=optional]
//Manually maintained attributes
:group: Kubernetes

*Since Camel {since}*

*{component-header}*

The Kubernetes Resources Quota component is one of xref:kubernetes-summary.adoc[Kubernetes Components] which
provides a producer to execute Kubernetes Resource Quota operations.


// component options: START
// component options: END
// endpoint options: START
// endpoint options: END


== Supported producer operation

- listResourcesQuota
- listResourcesQuotaByLabels
- getResourcesQuota
- createResourcesQuota
- deleteResourcesQuota

== Kubernetes Resource Quota Producer Examples

- listResourcesQuota: this operation list the Resource Quotas on a kubernetes cluster

[source,java]
--------------------------------------------------------------------------------
from("direct:list").
    toF("kubernetes-resources-quota:///?kubernetesClient=#kubernetesClient&operation=listResourcesQuota").
    to("mock:result");
--------------------------------------------------------------------------------

This operation return a List of Resource Quotas from your cluster

- listResourcesQuotaByLabels:  this operation list the Resource Quotas by labels on a kubernetes cluster

[source,java]
--------------------------------------------------------------------------------
from("direct:listByLabels").process(new Processor() {
            @Override
            public void process(Exchange exchange) throws Exception {
                Map<String, String> labels = new HashMap<>();
                labels.put("key1", "value1");
                labels.put("key2", "value2");
                exchange.getIn().setHeader(KubernetesConstants.KUBERNETES_RESOURCES_QUOTA_LABELS, labels);
            }
        });
    toF("kubernetes-resources-quota:///?kubernetesClient=#kubernetesClient&operation=listResourcesQuotaByLabels").
    to("mock:result");
--------------------------------------------------------------------------------

This operation return a List of Resource Quotas from your cluster, using a label selector (with key1 and key2, with value value1 and value2)


include::{page-component-version}@camel-spring-boot::page$kubernetes-starter.adoc[]
