= Kubernetes Pods Component
:doctitle: Kubernetes Pods
:shortname: kubernetes-pods
:artifactid: camel-kubernetes
:description: Perform operations on Kubernetes Pods and get notified on Pod changes.
:since: 2.17
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:group: Kubernetes
:camel-spring-boot-name: kubernetes

*Since Camel {since}*

*{component-header}*

The Kubernetes Pods component is one of xref:kubernetes-summary.adoc[Kubernetes Components] which
provides a producer to execute Kubernetes Pods operations and a consumer to consume events related to Pod Objects.


// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
include::partial$component-endpoint-headers.adoc[]
// component options: END


== Usage

=== Supported producer operation

- `listPods`
- `listPodsByLabels`
- `getPod`
- `createPod`
- `updatePod`
- `deletePod`

== Examples

=== Kubernetes Pods Producer Examples

- `listPods`: this operation lists the pods on a kubernetes cluster

[tabs]
====
Java::
+
[source,java]
----
from("direct:list")
    .to("kubernetes-pods:///?kubernetesClient=#kubernetesClient&operation=listPods")
    .to("mock:result");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:list"/>
  <to uri="kubernetes-pods:///?kubernetesClient=#kubernetesClient&amp;operation=listPods"/>
  <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:list
    steps:
      - to:
          uri: kubernetes-pods:///
          parameters:
            kubernetesClient: "#kubernetesClient"
            operation: listPods
      - to:
          uri: mock:result
----
====

This operation returns a list of pods from your cluster

- `listPodsByLabels`: this operation lists the pods by labels on a kubernetes cluster

._Java-only: sets a Map header for label selection_
[source,java]
----
from("direct:listByLabels")
    .process(exchange -> {
        exchange.getIn().setHeader("CamelKubernetesPodLabels",
            Map.of("key1", "value1", "key2", "value2"));
    })
    .to("kubernetes-pods:///?kubernetesClient=#kubernetesClient&operation=listPodsByLabels")
    .to("mock:result");
----

This operation returns a list of pods from your cluster using a label selector (with key1 and key2, with value value1 and value2)

=== Kubernetes Pods Consumer Example

[tabs]
====
Java::
+
[source,java]
----
from("kubernetes-pods://{{kubernetes-host}}?oauthToken={{kubernetes-token}}")
    .to("log:result");
----

XML::
+
[source,xml]
----
<route>
  <from uri="kubernetes-pods://{{kubernetes-host}}?oauthToken={{kubernetes-token}}"/>
  <to uri="log:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: kubernetes-pods://{{kubernetes-host}}
      parameters:
        oauthToken: "{{kubernetes-token}}"
    steps:
      - to:
          uri: log:result
----
====

This consumer returns a message per event received for all Pods from all namespaces in the cluster.

You can narrow the scope of the consumer using the following query parameter combinations:

- `labelKey` + `labelValue` - Watch Pods with the specified label in any namespace.
- `namespace` - Watch all Pods in the specified namespace.
- `namespace` + `resourceName` - Watch the Pod with the specified name in the given namespace.
- `namespace` + `labelKey` + `labelValue` - Watch Pods with the specified label in the given namespace.


include::spring-boot:partial$starter.adoc[]
