= Kubernetes Resources Quota Component
:doctitle: Kubernetes Resources Quota
:shortname: kubernetes-resources-quota
:artifactid: camel-kubernetes
:description: Perform operations on Kubernetes Resources Quotas.
:since: 2.17
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported
//Manually maintained attributes
:group: Kubernetes
:camel-spring-boot-name: kubernetes

*Since Camel {since}*

*{component-header}*

The Kubernetes Resources Quota component is one of xref:kubernetes-summary.adoc[Kubernetes Components] which
provides a producer to execute Kubernetes Resource Quota operations.


// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
include::partial$component-endpoint-headers.adoc[]
// component options: END


== Usage

=== Supported producer operation

- `listResourcesQuota`
- `listResourcesQuotaByLabels`
- `getResourcesQuota`
- `createResourcesQuota`
- `updateResourceQuota`
- `deleteResourcesQuota`

== Examples

=== Kubernetes Resource Quota Producer Examples

- `listResourcesQuota`: this operation lists the resource quotas on a kubernetes cluster

[tabs]
====
Java::
+
[source,java]
----
from("direct:list")
    .to("kubernetes-resources-quota:///?kubernetesClient=#kubernetesClient&operation=listResourcesQuota")
    .to("mock:result");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:list"/>
  <to uri="kubernetes-resources-quota:///?kubernetesClient=#kubernetesClient&amp;operation=listResourcesQuota"/>
  <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:list
      steps:
        - to:
            uri: kubernetes-resources-quota:///
            parameters:
              kubernetesClient: "#kubernetesClient"
              operation: listResourcesQuota
        - to:
            uri: mock:result
----
====

This operation returns a list of resource quotas from your cluster

- `listResourcesQuotaByLabels`: this operation lists the resource quotas by labels on a kubernetes cluster

._Java-only: uses inline Processor with HashMap_
[source,java]
----
from("direct:listByLabels")
    .process(new Processor() {
        @Override
        public void process(Exchange exchange) throws Exception {
            Map<String, String> labels = new HashMap<>();
            labels.put("key1", "value1");
            labels.put("key2", "value2");
            exchange.getIn().setHeader("CamelKubernetesResourcesQuotaLabels", labels);
        }
    })
    .to("kubernetes-resources-quota:///?kubernetesClient=#kubernetesClient&operation=listResourcesQuotaByLabels")
    .to("mock:result");
----

This operation returns a list of resource quotas from your cluster using a label selector (with key1 and key2, with value value1 and value2)


include::spring-boot:partial$starter.adoc[]
