= Kubernetes ConfigMap Component
:doctitle: Kubernetes ConfigMap
:shortname: kubernetes-config-maps
:artifactid: camel-kubernetes
:description: Perform operations on Kubernetes ConfigMaps and get notified on ConfigMaps changes.
:since: 2.17
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:group: Kubernetes
:camel-spring-boot-name: kubernetes

*Since Camel {since}*

*{component-header}*

The Kubernetes ConfigMap component is one of xref:kubernetes-summary.adoc[Kubernetes Components] which
provides a producer to execute Kubernetes ConfigMap operations and a consumer to consume events related to ConfigMap objects.


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END

// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

== Usage

=== Supported producer operation

- `listConfigMaps`
- `listConfigMapsByLabels`
- `getConfigMap`
- `createConfigMap`
- `updateConfigMap`
- `deleteConfigMap`

== Examples

=== Kubernetes ConfigMaps Producer Examples

- `listConfigMaps`: this operation lists the configmaps

[source,java]
--------------------------------------------------------------------------------
from("direct:list").
    to("kubernetes-config-maps:///?kubernetesClient=#kubernetesClient&operation=listConfigMaps").
    to("mock:result");
--------------------------------------------------------------------------------

This operation returns a List of ConfigMaps from your cluster

- `listConfigMapsByLabels`: this operation lists the configmaps selected by label

[source,java]
--------------------------------------------------------------------------------
from("direct:listByLabels").process(new Processor() {

            @Override
            public void process(Exchange exchange) throws Exception {
                Map<String, String> labels = new HashMap<>();
                labels.put("key1", "value1");
                labels.put("key2", "value2");
                exchange.getIn().setHeader(KubernetesConstants.KUBERNETES_CONFIGMAPS_LABELS, labels);
            }
        });
    to("kubernetes-config-maps:///?kubernetesClient=#kubernetesClient&operation=listConfigMapsByLabels").
    to("mock:result");
--------------------------------------------------------------------------------

This operation returns a List of ConfigMaps from your cluster, using a label selector (with key1 and key2, with value value1 and value2)

=== Kubernetes ConfigMaps Consumer Example

[source,java]
--------------------------------------------------------------------------------
fromF("kubernetes-config-maps://%s?oauthToken=%s", host, authToken)
    .process(new KubernetesProcessor()).to("mock:result");

    public class KubernetesProcessor implements Processor {
        @Override
        public void process(Exchange exchange) throws Exception {
            Message in = exchange.getIn();
            ConfigMap cm = exchange.getIn().getBody(ConfigMap.class);
            log.info("Got event with configmap name: " + cm.getMetadata().getName() + " and action " + in.getHeader(KubernetesConstants.KUBERNETES_EVENT_ACTION));
        }
    }
--------------------------------------------------------------------------------

This consumer watches all ConfigMaps from all namespaces in the cluster by default.

You can narrow the scope of the consumer using the following query parameter combinations:

- `labelKey` + `labelValue` - Watch ConfigMaps with the specified label in any namespace.
- `namespace` - Watch all ConfigMaps in the specified namespace.
- `namespace` + `resourceName` - Watch the ConfigMap with the specified name in the given namespace.
- `namespace` + `labelKey` + `labelValue` - Watch ConfigMaps with the specified label in the given namespace.

== Using configmap properties function with Kubernetes

The `camel-kubernetes` component include the following configmap related functions:

* `configmap` - A function to lookup the string property from Kubernetes ConfigMaps.
* `configmap-binary` - A function to lookup the binary property from Kubernetes ConfigMaps.

Camel reads Configmaps from the Kubernetes API Server. And when RBAC is enabled on the cluster,
the ServiceAccount that is used to run the application needs to have the proper permissions for such access.

Before the Kubernetes property placeholder functions can be used they need to be configured with either (or both)

- path - A _mount path_ that must be mounted to the running pod, to load the configmaps or secrets from local disk.
- kubernetes client - *Autowired* An `io.fabric8.kubernetes.client.KubernetesClient` instance to use for connecting to the Kubernetes API server.

Camel will first use _mount paths_ (if configured) to lookup, and then fallback to use the `KubernetesClient`.

=== Using configmap with Kubernetes

Given a configmap named `myconfig` in Kubernetes that has two entries:

[source,properties]
----
drink = beer
first = Carlsberg
----

Then these values can be used in your Camel routes such as:

[source,xml]
----
<camelContext>
  <route>
    <from uri="direct:start"/>
    <log message="What {{configmap:myconfig/drink}} do you want?"/>
    <log message="I want {{configmap:myconfig/first}}"/>
  </route>
</camelContext>
----

You can also provide a default value in case a key does not exist:

[source,xml]
----
    <log message="I want {{configmap:myconfig/second:Heineken}}"/>
----

== Automatic Camel context reloading on Configmaps Refresh

Being able to reload Camel context on a Configmap Refresh could be done by specifying the following properties: 

[source,properties]
----
camel.vault.kubernetescm.refreshEnabled=true
camel.vault.kubernetescm.configmaps=Configmap
camel.main.context-reload-enabled = true
----

where `camel.vault.kubernetescm.refreshEnabled` will enable the automatic context reload and `camel.vault.kubernetescm.configmaps` is a regex representing or a comma separated lists of the configmaps we want to track for updates.

Whenever a configmap listed in the property, will be updated in the same namespace of the running application, the Camel context will be reloaded, refreshing the configmap value.

include::spring-boot:partial$starter.adoc[]
