[[kubernetes-persistent-volumes-claims-component]]
= Kubernetes Persistent Volume Claim Component
:docTitle: Kubernetes Persistent Volume Claim
:artifactId: camel-kubernetes
:description: Perform operations on Kubernetes Persistent Volumes Claims and get notified on Persistent Volumes Claim changes.
:since: 2.17
:supportLevel: Stable
:component-header: Only producer is supported
include::{cq-version}@camel-quarkus:ROOT:partial$reference/components/kubernetes-persistent-volumes-claims.adoc[opts=optional]
//Manually maintained attributes
:group: Kubernetes

*Since Camel {since}*

*{component-header}*

The Kubernetes Persistent Volume Claim component is one of xref:kubernetes-summary.adoc[Kubernetes Components] which
provides a producer to execute Kubernetes Persistent Volume Claims operations.


// component options: START
// component options: END
// endpoint options: START
// endpoint options: END


== Supported producer operation

- listPersistentVolumesClaims
- listPersistentVolumesClaimsByLabels
- getPersistentVolumeClaim
- createPersistentVolumeClaim
- deletePersistentVolumeClaim

== Kubernetes Persistent Volume Claims Producer Examples

- listPersistentVolumesClaims: this operation list the pvc on a kubernetes cluster

[source,java]
--------------------------------------------------------------------------------
from("direct:list").
    toF("kubernetes-persistent-volumes-claims:///?kubernetesClient=#kubernetesClient&operation=listPersistentVolumesClaims").
    to("mock:result");
--------------------------------------------------------------------------------

This operation return a List of pvc from your cluster

- listPersistentVolumesClaimsByLabels:  this operation list the pvc by labels on a kubernetes cluster

[source,java]
--------------------------------------------------------------------------------
from("direct:listByLabels").process(new Processor() {
            @Override
            public void process(Exchange exchange) throws Exception {
                Map<String, String> labels = new HashMap<>();
                labels.put("key1", "value1");
                labels.put("key2", "value2");
                exchange.getIn().setHeader(KubernetesConstants.KUBERNETES_PERSISTENT_VOLUMES_CLAIMS_LABELS, labels);
            }
        });
    toF("kubernetes-persistent-volumes-claims:///?kubernetesClient=#kubernetesClient&operation=listPersistentVolumesClaimsByLabels").
    to("mock:result");
--------------------------------------------------------------------------------

This operation return a List of pvc from your cluster, using a label selector (with key1 and key2, with value value1 and value2)


include::{page-component-version}@camel-spring-boot::page$kubernetes-starter.adoc[]
