= Kubernetes Persistent Volume Claim Component
:doctitle: Kubernetes Persistent Volume Claim
:shortname: kubernetes-persistent-volumes-claims
:artifactid: camel-kubernetes
:description: Perform operations on Kubernetes Persistent Volumes Claims and get notified on Persistent Volumes Claim changes.
:since: 2.17
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported
//Manually maintained attributes
:group: Kubernetes
:camel-spring-boot-name: kubernetes

*Since Camel {since}*

*{component-header}*

The Kubernetes Persistent Volume Claim component is one of xref:kubernetes-summary.adoc[Kubernetes Components] which
provides a producer to execute Kubernetes Persistent Volume Claims (PVC) operations.


// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
include::partial$component-endpoint-headers.adoc[]
// component options: END


== Usage

=== Supported producer operation

- `listPersistentVolumesClaims`
- `listPersistentVolumesClaimsByLabels`
- `getPersistentVolumeClaim`
- `createPersistentVolumeClaim`
- `updatePersistentVolumeClaim`
- `deletePersistentVolumeClaim`

== Example

=== Kubernetes Persistent Volume Claims Producer Examples

- `listPersistentVolumesClaims`: this operation lists the PVCs on a kubernetes cluster

[tabs]
====
Java::
+
[source,java]
----
from("direct:list")
    .to("kubernetes-persistent-volumes-claims:///?kubernetesClient=#kubernetesClient&operation=listPersistentVolumesClaims")
    .to("mock:result");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:list"/>
  <to uri="kubernetes-persistent-volumes-claims:///?kubernetesClient=#kubernetesClient&amp;operation=listPersistentVolumesClaims"/>
  <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:list
      steps:
        - to:
            uri: kubernetes-persistent-volumes-claims:///
            parameters:
              kubernetesClient: "#kubernetesClient"
              operation: listPersistentVolumesClaims
        - to:
            uri: mock:result
----
====

This operation returns a list of PVC from your cluster

- `listPersistentVolumesClaimsByLabels`: this operation lists the PVCs by labels on a kubernetes cluster

._Java-only: uses inline Processor with HashMap_
[source,java]
----
from("direct:listByLabels")
    .process(new Processor() {
        @Override
        public void process(Exchange exchange) throws Exception {
            Map<String, String> labels = new HashMap<>();
            labels.put("key1", "value1");
            labels.put("key2", "value2");
            exchange.getIn().setHeader("CamelKubernetesPersistentVolumesClaimsLabels", labels);
        }
    })
    .to("kubernetes-persistent-volumes-claims:///?kubernetesClient=#kubernetesClient&operation=listPersistentVolumesClaimsByLabels")
    .to("mock:result");
----

This operation returns a list of PVCs from your cluster using a label selector (with key1 and key2, with value value1 and value2)



include::spring-boot:partial$starter.adoc[]
