= Kubernetes Persistent Volume Component
:doctitle: Kubernetes Persistent Volume
:shortname: kubernetes-persistent-volumes
:artifactid: camel-kubernetes
:description: Perform operations on Kubernetes Persistent Volumes and get notified on Persistent Volume changes.
:since: 2.17
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported
//Manually maintained attributes
:group: Kubernetes
:camel-spring-boot-name: kubernetes

*Since Camel {since}*

*{component-header}*

The Kubernetes Persistent Volume component is one of xref:kubernetes-summary.adoc[Kubernetes Components] which
provides a producer to execute Kubernetes Persistent Volume operations.


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END
// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

== Supported producer operation

- listPersistentVolumes
- listPersistentVolumesByLabels
- getPersistentVolume

== Kubernetes Persistent Volumes Producer Examples

- listPersistentVolumes: this operation list the pv on a kubernetes cluster

[source,java]
--------------------------------------------------------------------------------
from("direct:list").
    toF("kubernetes-persistent-volumes:///?kubernetesClient=#kubernetesClient&operation=listPersistentVolumes").
    to("mock:result");
--------------------------------------------------------------------------------

This operation return a List of pv from your cluster

- listPersistentVolumesByLabels:  this operation list the pv by labels on a kubernetes cluster

[source,java]
--------------------------------------------------------------------------------
from("direct:listByLabels").process(new Processor() {
            @Override
            public void process(Exchange exchange) throws Exception {
                Map<String, String> labels = new HashMap<>();
                labels.put("key1", "value1");
                labels.put("key2", "value2");
                exchange.getIn().setHeader(KubernetesConstants.KUBERNETES_PERSISTENT_VOLUMES_LABELS, labels);
            }
        });
    toF("kubernetes-persistent-volumes:///?kubernetesClient=#kubernetesClient&operation=listPersistentVolumesByLabels").
    to("mock:result");
--------------------------------------------------------------------------------

This operation return a List of pv from your cluster, using a label selector (with key1 and key2, with value value1 and value2)


include::spring-boot:partial$starter.adoc[]
