= Kubernetes HPA Component
:doctitle: Kubernetes HPA
:shortname: kubernetes-hpa
:artifactid: camel-kubernetes
:description: Perform operations on Kubernetes Horizontal Pod Autoscalers (HPA) and get notified on HPA changes.
:since: 2.23
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:group: Kubernetes
:camel-spring-boot-name: kubernetes

*Since Camel {since}*

*{component-header}*

The Kubernetes HPA component is one of xref:kubernetes-summary.adoc[Kubernetes Components] which
provides a producer to execute kubernetes Horizontal Pod Autoscaler operations and a consumer to consume events related to Horizontal Pod Autoscaler objects.

// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END

// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

== Usage

=== Supported producer operation

- `listHPA`
- `listHPAByLabels`
- `getHPA`
- `createHPA`
- `updateHPA`
- `deleteHPA`

== Examples

=== Kubernetes HPA Producer Examples

- `listHPA`: this operation lists the HPAs on a kubernetes cluster

[source,java]
--------------------------------------------------------------------------------
from("direct:list").
    toF("kubernetes-hpa:///?kubernetesClient=#kubernetesClient&operation=listHPA").
    to("mock:result");
--------------------------------------------------------------------------------

This operation returns a list of HPAs from your cluster

- `listDeploymentsByLabels`: this operation lists the HPAs by labels on a kubernetes cluster

[source,java]
--------------------------------------------------------------------------------
from("direct:listByLabels").process(new Processor() {
            @Override
            public void process(Exchange exchange) throws Exception {
                Map<String, String> labels = new HashMap<>();
                labels.put("key1", "value1");
                labels.put("key2", "value2");
                exchange.getIn().setHeader(KubernetesConstants.KUBERNETES_HPA_LABELS, labels);
            }
        });
    toF("kubernetes-hpa:///?kubernetesClient=#kubernetesClient&operation=listHPAByLabels").
    to("mock:result");
--------------------------------------------------------------------------------

This operation returns a List of HPAs from your cluster using a label selector (with key1 and key2, with value value1 and value2)

=== Kubernetes HPA Consumer Example

[source,java]
--------------------------------------------------------------------------------
fromF("kubernetes-hpa://%s?oauthToken=%s", host, authToken)
    .process(new KubernetesProcessor()).to("mock:result");

    public class KubernetesProcessor implements Processor {
        @Override
        public void process(Exchange exchange) throws Exception {
            Message in = exchange.getIn();
            HorizontalPodAutoscaler hpa = exchange.getIn().getBody(HorizontalPodAutoscaler.class);
            log.info("Got event with hpa name: " + hpa.getMetadata().getName() + " and action " + in.getHeader(KubernetesConstants.KUBERNETES_EVENT_ACTION));
        }
    }
--------------------------------------------------------------------------------

This consumer returns a message per event received for all HorizontalPodAutoscalers from all namespaces in the cluster.

You can narrow the scope of the consumer using the following query parameter combinations:

- `labelKey` + `labelValue` - Watch HorizontalPodAutoscalers with the specified label in any namespace.
- `namespace` - Watch all HorizontalPodAutoscalers in the specified namespace.
- `namespace` + `resourceName` - Watch the HorizontalPodAutoscaler with the specified name in the given namespace.
- `namespace` + `labelKey` + `labelValue` - Watch HorizontalPodAutoscalers with the specified label in the given namespace.


include::spring-boot:partial$starter.adoc[]
