= Kubernetes Deployments Component
:doctitle: Kubernetes Deployments
:shortname: kubernetes-deployments
:artifactid: camel-kubernetes
:description: Perform operations on Kubernetes Deployments and get notified on Deployment changes.
:since: 2.20
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:group: Kubernetes
:camel-spring-boot-name: kubernetes

*Since Camel {since}*

*{component-header}*

The Kubernetes Deployments component is one of xref:kubernetes-summary.adoc[Kubernetes Components] which
provides a producer to execute Kubernetes Deployments operations and a consumer to consume events related to Deployments objects.

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
include::partial$component-endpoint-headers.adoc[]
// component options: END

== Usage

=== Supported producer operation

- `listDeployments`
- `listDeploymentsByLabels`
- `getDeployment`
- `createDeployment`
- `updateDeployment`
- `deleteDeployment`
- `scaleDeployment`

== Examples

=== Kubernetes Deployments Producer Examples

- `listDeployments`: this operation lists the deployments on a kubernetes cluster

[tabs]
====
Java::
+
[source,java]
----
from("direct:list")
    .to("kubernetes-deployments:///?kubernetesClient=#kubernetesClient&operation=listDeployments")
    .to("mock:result");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:list"/>
  <to uri="kubernetes-deployments:///?kubernetesClient=#kubernetesClient&amp;operation=listDeployments"/>
  <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:list
    steps:
      - to:
          uri: kubernetes-deployments:///
          parameters:
            kubernetesClient: "#kubernetesClient"
            operation: listDeployments
      - to:
          uri: mock:result
----
====

This operation returns a List of Deployment from your cluster

- `listDeploymentsByLabels`:  this operation lists the deployments by labels on a kubernetes cluster

._Java-only: sets a Map header for label selection_
[source,java]
----
from("direct:listByLabels")
    .process(exchange -> {
        exchange.getIn().setHeader("CamelKubernetesDeploymentsLabels",
            Map.of("key1", "value1", "key2", "value2"));
    })
    .to("kubernetes-deployments:///?kubernetesClient=#kubernetesClient&operation=listDeploymentsByLabels")
    .to("mock:result");
----

This operation returns a List of Deployments from your cluster, using a label selector (with key1 and key2, with value value1 and value2)

=== Kubernetes Deployments Consumer Example

[tabs]
====
Java::
+
[source,java]
----
from("kubernetes-deployments://{{kubernetes-host}}?oauthToken={{kubernetes-token}}")
    .to("log:result");
----

XML::
+
[source,xml]
----
<route>
  <from uri="kubernetes-deployments://{{kubernetes-host}}?oauthToken={{kubernetes-token}}"/>
  <to uri="log:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: kubernetes-deployments://{{kubernetes-host}}
      parameters:
        oauthToken: "{{kubernetes-token}}"
    steps:
      - to:
          uri: log:result
----
====

This consumer returns a message per event received for all Deployments from all namespaces in the cluster.

You can narrow the scope of the consumer using the following query parameter combinations:

- `labelKey` + `labelValue` - Watch Deployments with the specified label in any namespace.
- `namespace` - Watch all Deployments in the specified namespace.
- `namespace` + `resourceName` - Watch the Deployment with the specified name in the given namespace.
- `namespace` + `labelKey` + `labelValue` - Watch Deployments with the specified label in the given namespace.

include::spring-boot:partial$starter.adoc[]
