= Openshift Build Config Component
:doctitle: Openshift Build Config
:shortname: openshift-build-configs
:artifactid: camel-kubernetes
:description: Perform operations on OpenShift Build Configs.
:since: 2.17
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported
//Manually maintained attributes
:group: Kubernetes
:camel-spring-boot-name: kubernetes

*Since Camel {since}*

*{component-header}*

The OpenShift Build Config component is one of xref:kubernetes-summary.adoc[Kubernetes Components] which
provides a producer to execute Openshift Build Configs operations.


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END
// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

== Supported producer operation

- listBuildConfigs
- listBuildConfigsByLabels
- getBuildConfig

== Openshift Build Configs Producer Examples

- listBuilds: this operation lists the Build Configs on an Openshift cluster

[source,java]
--------------------------------------------------------------------------------
from("direct:list").
    toF("openshift-build-configs:///?kubernetesClient=#kubernetesClient&operation=listBuildConfigs").
    to("mock:result");
--------------------------------------------------------------------------------

This operation returns a List of Builds from your Openshift cluster

- listBuildsByLabels: this operation lists the build configs by labels on an Openshift cluster

[source,java]
--------------------------------------------------------------------------------
from("direct:listByLabels").process(new Processor() {
            @Override
            public void process(Exchange exchange) throws Exception {
                Map<String, String> labels = new HashMap<>();
                labels.put("key1", "value1");
                labels.put("key2", "value2");
                exchange.getIn().setHeader(KubernetesConstants.KUBERNETES_BUILD_CONFIGS_LABELS, labels);
            }
        });
    toF("openshift-build-configs:///?kubernetesClient=#kubernetesClient&operation=listBuildConfigsByLabels").
    to("mock:result");
--------------------------------------------------------------------------------

This operation returns a List of Build configs from your cluster, using a label selector (with key1 and key2, with value value1 and value2)


include::spring-boot:partial$starter.adoc[]
