= Openshift Builds Component
:doctitle: Openshift Builds
:shortname: openshift-builds
:artifactid: camel-kubernetes
:description: Perform operations on OpenShift Builds.
:since: 2.17
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported
//Manually maintained attributes
:group: Kubernetes
:camel-spring-boot-name: kubernetes

*Since Camel {since}*

*{component-header}*

The Openshift Builds component is one of xref:kubernetes-summary.adoc[Kubernetes Components] which
provides a producer to execute Openshift builds operations.


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END
// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

== Supported producer operation

- listBuilds
- listBuildsByLabels
- getBuild

== Openshift Builds Producer Examples

- listBuilds: this operation lists the Builds on an Openshift cluster

[source,java]
--------------------------------------------------------------------------------
from("direct:list").
    toF("openshift-builds:///?kubernetesClient=#kubernetesClient&operation=listBuilds").
    to("mock:result");
--------------------------------------------------------------------------------

This operation returns a List of Builds from your Openshift cluster

- listBuildsByLabels: this operation lists the builds by labels on an Openshift cluster

[source,java]
--------------------------------------------------------------------------------
from("direct:listByLabels").process(new Processor() {
            @Override
            public void process(Exchange exchange) throws Exception {
                Map<String, String> labels = new HashMap<>();
                labels.put("key1", "value1");
                labels.put("key2", "value2");
                exchange.getIn().setHeader(KubernetesConstants.KUBERNETES_BUILDS_LABELS, labels);
            }
        });
    toF("openshift-builds:///?kubernetesClient=#kubernetesClient&operation=listBuildsByLabels").
    to("mock:result");
--------------------------------------------------------------------------------

This operation returns a List of Builds from your cluster, using a label selector (with key1 and key2, with value value1 and value2)


include::spring-boot:partial$starter.adoc[]
