= Kamelet Component
:doctitle: Kamelet
:shortname: kamelet
:artifactid: camel-kamelet
:description: To call Kamelets
:since: 3.8
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
:core:
//Manually maintained attributes
:camel-spring-boot-name: kamelet

*Since Camel {since}*

*{component-header}*

The Kamelet Component provides support for interacting with the xref:manual::route-template.adoc[Camel Route Template] engine using Endpoint semantic.

== URI format

----
kamelet:templateId/routeId[?options]
----


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END

[NOTE]
====
The *kamelet* endpoint is *lenient*, which means that the endpoint accepts additional parameters that are passed to the xref:manual::route-template.adoc[Route Template] engine and consumed upon route materialization.
====

== Usage

=== Discovery

If a xref:manual::route-template.adoc[Route Template] is not found, the *kamelet* endpoint tries to load the related *kamelet* definition from the file system (by default `classpath:kamelets`). The default resolution mechanism expects _Kamelets_ files to have the extension `.kamelet.yaml`.

=== Error Handling

The error handling when using kamelets are using the same error handling
that are from the route where the kamelets are being used.

Suppose you have kamelets that would cause an exception during processing, such
as the source below. Now because the route has been configured with a _dead letter channel_
as the error handler, then the exception from the kamelet will be handled by the route error handler.
Which means you will se a WARN being logged.

[source,yaml]
----
- route:
    errorHandler:
      deadLetterChannel:
        deadLetterUri: log:dead?level=WARN
    id: myRoute
    from:
      uri: "kamelet:my-error-source/source"
      steps:
        - log: "${body}"
----

For sink kamelets then error handling also allows to perform retries.

So suppose you have the following route:

[source,yaml]
----
- route:
    errorHandler:
      deadLetterChannel:
        deadLetterUri: log:dead?level=WARN
        redeliveryPolicy:
          maximumRedeliveries: 5
          redeliveryDelay: "5000"
    id: myRoute
    from:
      uri: "direct:start"
      steps:
        - to:
            uri: "kamelet:my-error-sink/sink"
        - log: "${body}"
----

Then notice the error handler has been configured to do redeliveries up till 5 times with 5 sec delay between.
Suppose the sink kamelet is throwing an exception, then Camel will now perform the redelivery attempt
at the point of origin, which means inside the Kamelet.

== Examples

_Kamelets_ can be used as if they were standard Camel components.
For example, suppose that we have created a Route Template as follows:

[source,java]
----
routeTemplate("setMyBody")
    .templateParameter("bodyValue")
    .from("kamelet:source")
        .setBody().constant("{{bodyValue}}");
----

[IMPORTANT]
====
To let the *Kamelet* component wiring the materialized route to the caller processor, we need to be able to identify the input and output endpoint of the route and this is done by using `kamelet:source` to mark the input endpoint and `kamelet:sink` for the output endpoint.
====

Then the template can be instantiated and invoked as shown below:

[source,java]
----
from("direct:setMyBody")
    .to("kamelet:setMyBody?bodyValue=myKamelet");
----


Behind the scenes, the *Kamelet* component does the following things:

1. it instantiates a route out of the Route Template identified by the given `templateId` path parameter (in this case `setMyBody`)
2. it will act like the `direct` component and connect the current route to the materialized one.

If you had to do it programmatically, it would have been something like:

[source,java]
----
routeTemplate("setMyBody")
    .templateParameter("bodyValue")
    .from("direct:{{foo}}")
        .setBody().constant("{{bodyValue}}");

TemplatedRouteBuilder.builder(context, "setMyBody")
    .parameter("foo", "bar")
    .parameter("bodyValue", "myKamelet")
    .add();

from("direct:template")
    .to("direct:bar");

----

include::spring-boot:partial$starter.adoc[]
