= Kamelet Component
:doctitle: Kamelet
:shortname: kamelet
:artifactid: camel-kamelet
:description: To call Kamelets
:since: 3.8
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
:core:
//Manually maintained attributes
:camel-spring-boot-name: kamelet

*Since Camel {since}*

*{component-header}*

The Kamelet Component provides support for interacting with the xref:manual::route-template.adoc[Camel Route Template] engine using Endpoint semantic.

== URI format

[source]
----
kamelet:templateId/routeId[?options]
----


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END

[NOTE]
====
The *kamelet* endpoint is *lenient*, which means that the endpoint accepts additional parameters that are passed to the xref:manual::route-template.adoc[Route Template] engine and consumed upon route materialization.
====

== Discovery

If a xref:manual::route-template.adoc[Route Template] is not found, the *kamelet* endpoint tries to load the related *kamelet* definition from the file system (by default `classpath:/kamelets`). The default resolution mechanism expects _Kamelets_ files to have the extension `.kamelet.yaml`.

== Samples


_Kamelets_ can be used as if they were standard Camel components.
For example, suppose that we have created a Route Template as follows:

[source,java]
----
routeTemplate("setMyBody")
    .templateParameter("bodyValue")
    .from("kamelet:source")
        .setBody().constant("{{bodyValue}}");
----

[IMPORTANT]
====
To let the *Kamelet* component wiring the materialized route to the caller processor, we need to be able to identify the input and output endpoint of the route and this is done by using `kamelet:source` to mark the input endpoint and `kamelet:sink` for the output endpoint.
====

Then the template can be instantiated and invoked as shown below:

[source,java]
----
from("direct:setMyBody")
    .to("kamelet:setMyBody?bodyValue=myKamelet");
----


Behind the scenes, the *Kamelet* component does the following things:

1. it instantiates a route out of the Route Template identified by the given `templateId` path parameter (in this case `setMyBody`)
2. it will act like the `direct` component and connect the current route to the materialized one.

If you had to do it programmatically, it would have been something like:

[source,java]
----
routeTemplate("setMyBody")
    .templateParameter("bodyValue")
    .from("direct:{{foo}}")
        .setBody().constant("{{bodyValue}}");

TemplatedRouteBuilder.builder(context, "setMyBody")
    .parameter("foo", "bar")
    .parameter("bodyValue", "myKamelet")
    .add();

from("direct:template")
    .to("direct:bar");

----



include::spring-boot:partial$starter.adoc[]
