[[header-language]]
= Header Language
:docTitle: Header
:artifactId: camel-core-languages
:description: Get values of Camel Message headers.
:since: 1.5
:supportLevel: Stable
include::{cq-version}@camel-quarkus:ROOT:partial$reference/languages/header.adoc[opts=optional]

*Since Camel {since}*

The Header Expression Language allows you to extract values of named
headers.

== Header Options

// language options: START
The Header language supports 1 options, which are listed below.



[width="100%",cols="2,1m,1m,6",options="header"]
|===
| Name | Default | Java Type | Description
| trim | true | Boolean | Whether to trim the value to remove leading and trailing whitespaces and line breaks
|===
// language options: END

== Example usage

== Example usage

The recipientList element of the Spring DSL can utilize a header
expression like:

[source,xml]
----
      <route>
        <from uri="direct:a" />
        <recipientList>
          <header>myHeader</header>
        </recipientList>
      </route>
----

In this case, the list of recipients are contained in the header
'myHeader'.

And the same example in Java DSL:

[source,java]
----
from("direct:a").recipientList(header("myHeader"));
----

And with a slightly different syntax where you use the builder to the
fullest (i.e. avoid using parameters but using stacked operations,
notice that header is not a parameter but a stacked method call)

[source,java]
----
from("direct:a").recipientList().header("myHeader");
----

== Dependencies

The Header language is part of *camel-core*.
