[[rss-dataformat]]
= RSS DataFormat
:docTitle: RSS
:artifactId: camel-rss
:description: Transform from ROME SyndFeed Java Objects to XML and vice-versa.
:since: 2.1
:supportLevel: Stable
include::{cq-version}@camel-quarkus:ROOT:partial$reference/dataformats/rss.adoc[opts=optional]

*Since Camel {since}*

The RSS component ships with an RSS dataformat that can be used to
convert between String (as XML) and ROME RSS model objects.

* marshal = from ROME `SyndFeed` to XML `String`
* unmarshal = from XML `String` to ROME `SyndFeed`

A route using this would look something like this:

The purpose of this feature is to make it possible to use Camel's lovely
built-in expressions for manipulating RSS messages. As shown below, an
XPath expression can be used to filter the RSS message:

[TIP]
====
*Query parameters*

If the URL for the RSS feed uses query parameters, this component will
understand them as well, for example if the feed uses `alt=rss`, then
you can for example do 
`from("rss:http://someserver.com/feeds/posts/default?alt=rss&splitEntries=false&delay=1000").to("bean:rss");`
====

== Options

// dataformat options: START
The RSS dataformat has no options.
// dataformat options: END


include::camel-spring-boot::page$rss-starter.adoc[]
