= Once Component
:doctitle: Once
:shortname: once
:artifactid: camel-once
:description: Camel Once component
:since: 4.170
:supportlevel: Preview
:tabs-sync-option:
:component-header: Only consumer is supported
:core:
//Manually maintained attributes
:camel-spring-boot-name: once

*Since Camel {since}*

*{component-header}*

The Once component is used to generate a message only once. For example to trigger a message after Camel has been started,
or for development and testing purposes.

This component is designed to be very basic and only a few options.

You can find more features when using the xref:timer-component.adoc[Timer] component,
which also can be configured to only trigger once with `repeatCount=1`.

== URI format

----
once:name[?options]
----

Where `name` is a logical name.

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
include::partial$component-endpoint-headers.adoc[]
// component options: END


== Usage

== Example

To set up a route that generates an event every 60 seconds:

[source,java]
----
from("once:foo?body=file:data.json").to("bean:myBean?method=someMethodName");
----

The above route will trigger once and load the `data.json` from file system and use as message body.
And then route to call the bean.

And the route in XML DSL:

[source,xml]
-----
<route>
  <from uri="once:foo?body=file:data.json"/>
  <to uri="bean:myBean?method=someMethodName"/>
</route>
-----

=== Firing as soon as possible

By default, the component is fired after 1 seconds when Camel has been fully started.
If you want to fire messages in a Camel route as soon as possible, you can use a negative delay:

[source,xml]
----
<route>
  <from uri="once:foo?body=file.data.json&amp;delay=-1"/>
  <to uri="bean:myBean?method=someMethodName"/>
</route>
----

In this way, the timer will fire messages immediately.


include::spring-boot:partial$starter.adoc[]
