= Google Secret Manager Component
:doctitle: Google Secret Manager
:shortname: google-secret-manager
:artifactid: camel-google-secret-manager
:description: Manage Google Secret Manager Secrets
:since: 3.16
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported
//Manually maintained attributes
:group: Google
:camel-spring-boot-name: google-secret-manager

*Since Camel {since}*

*{component-header}*

The Google Secret Manager component provides access to https://cloud.google.com/secret-manager/[Google Cloud Secret Manager]

Maven users will need to add the following dependency to their pom.xml
for this component:

[source,xml]
------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-google-secret-manager</artifactId>
    <!-- use the same version as your Camel core version -->
    <version>x.x.x</version>
</dependency>

------------------------------------------------------

[[GoogleSecretManager-AuthenticationConfiguration]]

== Authentication Configuration

Google Secret Manager component authentication is targeted for use with the GCP Service Accounts.
For more information, please refer to https://github.com/googleapis/google-cloud-java#authentication[Google Cloud Authentication].

When you have the **service account key**, you can provide authentication credentials to your application code.
Google security credentials can be set through the component endpoint:

[source,java]
--------------------------------------------------------
String endpoint = "google-secret-manager://myCamelFunction?serviceAccountKey=/home/user/Downloads/my-key.json";
--------------------------------------------------------

Or by setting the environment variable `GOOGLE_APPLICATION_CREDENTIALS` :

--------------------------------------------------------
export GOOGLE_APPLICATION_CREDENTIALS="/home/user/Downloads/my-key.json"
--------------------------------------------------------


== URI Format

--------------------------------------------------------
google-secret-manager://functionName[?options]
--------------------------------------------------------

You can append query options to the URI in the following format,
`?options=value&option2=value&...`

For example, in order to call the function `myCamelFunction` from the project `myProject` and location `us-central1`, use the following snippet:

[source,java]
--------------------------------------------------------------------------------
from("google-secret-manager://myProject?serviceAccountKey=/home/user/Downloads/my-key.json&operation=createSecret")
  .to("direct:test");
--------------------------------------------------------------------------------



// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END
// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

=== Using GCP Secret Manager Properties Source

To use GCP Secret Manager, you need to provide `serviceAccountKey` file and GCP `projectId`.
This can be done using environmental variables before starting the application:

[source,bash]
----
export $CAMEL_VAULT_GCP_SERVICE_ACCOUNT_KEY=file:////path/to/service.accountkey
export $CAMEL_VAULT_GCP_PROJECT_ID=projectId
----

You can also configure the credentials in the `application.properties` file such as:

[source,properties]
----
camel.vault.gcp.serviceAccountKey = serviceAccountKey
camel.vault.gcp.projectId = projectId
----

If you want instead to use the https://cloud.google.com/docs/authentication/production[GCP default client instance], you'll need to provide the following env variables:

[source,bash]
----
export $CAMEL_VAULT_GCP_USE_DEFAULT_INSTANCE=true
export $CAMEL_VAULT_GCP_PROJECT_ID=projectId
----

You can also configure the credentials in the `application.properties` file such as:

[source,properties]
----
camel.vault.gcp.useDefaultInstance = true
camel.vault.gcp.projectId = region
----

At this point you'll be able to reference a property in the following way by using `gcp:` as prefix in the `{{ }}` syntax:

[source,xml]
----
<camelContext>
    <route>
        <from uri="direct:start"/>
        <to uri="{{gcp:route}}"/>
    </route>
</camelContext>
----

Where `route` will be the name of the secret stored in the GCP Secret Manager Service.

You could specify a default value in case the secret is not present on GCP Secret Manager:

[source,xml]
----
<camelContext>
    <route>
        <from uri="direct:start"/>
        <to uri="{{gcp:route:default}}"/>
    </route>
</camelContext>
----

In this case, if the secret doesn't exist, the property will fall back to `default` as value.

Also, you are able to get a particular field of the secret, if you have, for example, a secret named database of this form:

[source,json]
----
{
  "username": "admin",
  "password": "password123",
  "engine": "postgres",
  "host": "127.0.0.1",
  "port": "3128",
  "dbname": "db"
}
----

You're able to do get single secret value in your route, like for example:

[source,xml]
----
<camelContext>
    <route>
        <from uri="direct:start"/>
        <log message="Username is {{gcp:database/username}}"/>
    </route>
</camelContext>
----

Or re-use the property as part of an endpoint.

You could specify a default value in case the particular field of secret is not present on GCP Secret Manager:

[source,xml]
----
<camelContext>
    <route>
        <from uri="direct:start"/>
        <log message="Username is {{gcp:database/username:admin}}"/>
    </route>
</camelContext>
----

In this case, if the secret doesn't exist or the secret exists, but the username field is not part of the secret, the property will fall back to "admin" as value.

There is also the syntax to get a particular version of the secret for both the approach, with field/default value specified or only with secret:

[source,xml]
----
<camelContext>
    <route>
        <from uri="direct:start"/>
        <to uri="{{gcp:route@1}}"/>
    </route>
</camelContext>
----

This approach will return the RAW route secret with version '1'.

[source,xml]
----
<camelContext>
    <route>
        <from uri="direct:start"/>
        <to uri="{{gcp:route:default@1}}"/>
    </route>
</camelContext>
----

This approach will return the route secret value with version '1' or default value in case the secret doesn't exist or the version doesn't exist.

[source,xml]
----
<camelContext>
    <route>
        <from uri="direct:start"/>
        <log message="Username is {{gcp:database/username:admin@1}}"/>
    </route>
</camelContext>
----

This approach will return the username field of the database secret with version '1' or admin in case the secret doesn't exist or the version doesn't exist.

There are only two requirements: 
- Adding `camel-google-secret-manager` JAR to your Camel application.
- Give the service account used permissions to do operation at secret management level, (for example, accessing the secret payload, or being admin of secret manager service)

=== Automatic `CamelContext` reloading on Secret Refresh

Being able to reload Camel context on a Secret Refresh could be done by specifying the usual credentials (the same used for Google Secret Manager Property Function).

With Environment variables:

[source,bash]
----
export $CAMEL_VAULT_GCP_USE_DEFAULT_INSTANCE=true
export $CAMEL_VAULT_GCP_PROJECT_ID=projectId
----

or as plain Camel main properties:

[source,properties]
----
camel.vault.gcp.useDefaultInstance = true
camel.vault.gcp.projectId = projectId
----

Or by specifying a path to a service account key file, instead of using the default instance.

To enable the automatic refresh, you'll need additional properties to set:

[source,properties]
----
camel.vault.gcp.projectId= projectId
camel.vault.gcp.refreshEnabled=true
camel.vault.gcp.refreshPeriod=60000
camel.vault.gcp.secrets=hello*
camel.vault.gcp.subscriptionName=subscriptionName
camel.main.context-reload-enabled = true
----

where `camel.vault.gcp.refreshEnabled` will enable the automatic context reload, `camel.vault.gcp.refreshPeriod` is the interval of time between two different checks for update events and `camel.vault.gcp.secrets` is a regex representing the secrets we want to track for updates.

Note that `camel.vault.gcp.secrets` is not mandatory: if not specified the task responsible for checking updates events will take into accounts or the properties with an `gcp:` prefix.

The `camel.vault.gcp.subscriptionName` is the subscription name created in relation to the Google PubSub topic associated with the tracked secrets.

This mechanism while making use of the notification system related to Google Secret Manager: through this feature, every secret could be associated with one up to ten Google Pubsub Topics. These topics will receive
events related to the life cycle of the secret.

There are only two requirements: 
- Adding `camel-google-secret-manager` JAR to your Camel application.
- Give the service account used permissions to do operation at secret management level, (for example, accessing the secret payload, or being admin of secret manager service and also have permission over the Pubsub service)

=== Automatic `CamelContext` reloading on Secret Refresh - Required infrastructure's creation

You’ll need to install the gcloud cli from https://cloud.google.com/sdk/docs/install

Once the Cli has been installed we can proceed to log in and to set up the project with the following commands:

```
gcloud auth login
```

and

```
gcloud projects create <projectId> --name="GCP Secret Manager Refresh"
```

The project will need a service identity for using secret manager service and we’ll be able to have that through the command:

```
gcloud beta services identity create --service "secretmanager.googleapis.com" --project <project_id>
```

The latter command will provide a service account name that we need to export

```
export SM_SERVICE_ACCOUNT="service-...."
```

Since we want to have notifications about events related to a specific secret through a Google Pubsub topic we’ll need to create a topic for this purpose with the following command:

```
gcloud pubsub topics create "projects/<project_id>/topics/pubsub-gcp-sec-refresh"
```

The service account will need Secret Manager authorization to publish messages on the topic just created, so we’ll need to add an iam policy binding with the following command:

```
gcloud pubsub topics add-iam-policy-binding pubsub-gcp-sec-refresh --member "serviceAccount:${SM_SERVICE_ACCOUNT}" --role "roles/pubsub.publisher" --project <project_id>
```

We now need to create a subscription to the pubsub-gcp-sec-refresh just created and we’re going to call it sub-gcp-sec-refresh with the following command:

```
gcloud pubsub subscriptions create "projects/<project_id>/subscriptions/sub-gcp-sec-refresh" --topic "projects/<project_id>/topics/pubsub-gcp-sec-refresh"
```

Now we need to create a service account for running our application:

```
gcloud iam service-accounts create gcp-sec-refresh-sa --description="GCP Sec Refresh SA" --project <project_id>
```

Let’s give the SA an owner role:

```
gcloud projects add-iam-policy-binding <project_id> --member="serviceAccount:gcp-sec-refresh-sa@<project_id>.iam.gserviceaccount.com" --role="roles/owner"
```

Now we should create a Service account key file for the just create SA:

```
gcloud iam service-accounts keys create <project_id>.json --iam-account=gcp-sec-refresh-sa@<project_id>.iam.gserviceaccount.com
```

Let’s enable the Secret Manager API for our project

```
gcloud services enable secretmanager.googleapis.com --project <project_id>
```

Also the PubSub API needs to be enabled

```
gcloud services enable pubsub.googleapis.com --project <project_id>
```

If needed enable also the Billing API.

Now it’s time to create our secret, with topic notification:

```
gcloud secrets create <secret_name> --topics=projects/<project_id>/topics/pubsub-gcp-sec-refresh --project=<project_id>
```

And let’s add the value

```
gcloud secrets versions add <secret_name> --data-file=<json_secret> --project=<project_id>
```

You could now use the projectId and the service account json file to recover the secret.

=== Google Secret Manager Producer operations

Google Functions component provides the following operation on the producer side:

- `createSecret`
- `getSecretVersion`
- `deleteSecret`
- `listSecrets`

If you don't specify an operation by default, the producer will use the `createSecret` operation.

=== Google Secret Manager Producer Operation examples

- `createSecret`: This operation will create a secret in the Secret Manager service

[source,java]
--------------------------------------------------------------------------------
from("direct:start")
    .setHeader("GoogleSecretManagerConstants.SECRET_ID, constant("test"))
    .setBody(constant("hello"))
    .to("google-functions://myProject?serviceAccountKey=/home/user/Downloads/my-key.json&operation=createSecret")
    .log("body:${body}")
--------------------------------------------------------------------------------

- `getSecretVersion`: This operation will retrieve a secret value with the latest version in the Secret Manager service

[source,java]
--------------------------------------------------------------------------------
from("direct:start")
    .setHeader("GoogleSecretManagerConstants.SECRET_ID, constant("test"))
    .to("google-functions://myProject?serviceAccountKey=/home/user/Downloads/my-key.json&operation=getSecretVersion")
    .log("body:${body}")
--------------------------------------------------------------------------------

This will log the value of the secret "test".

- `deleteSecret`: This operation will delete a secret

[source,java]
--------------------------------------------------------------------------------
from("direct:start")
    .setHeader("GoogleSecretManagerConstants.SECRET_ID, constant("test"))
    .to("google-functions://myProject?serviceAccountKey=/home/user/Downloads/my-key.json&operation=deleteSecret")
--------------------------------------------------------------------------------

- `listSecrets`: This operation will return the secrets' list for the project myProject

[source,java]
--------------------------------------------------------------------------------
from("direct:start")
    .setHeader("GoogleSecretManagerConstants.SECRET_ID, constant("test"))
    .to("google-functions://myProject?serviceAccountKey=/home/user/Downloads/my-key.json&operation=listSecrets")
--------------------------------------------------------------------------------


include::spring-boot:partial$starter.adoc[]
