= SpEL Language
:doctitle: SpEL
:shortname: spel
:artifactid: camel-spring
:description: Evaluates a Spring expression (SpEL).
:since: 2.7
:supportlevel: Stable
:tabs-sync-option:
//Manually maintained attributes
:camel-spring-boot-name: spring

*Since Camel {since}*

Camel allows
https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#expressions[Spring Expression Language (SpEL)]
to be used as an Expression or Predicate in the DSL or XML Configuration.

[NOTE]
====
It is recommended to use SpEL in Spring runtimes.
Although you can use SpEL in other runtimes, there is some functionality that SpEL can only do in a Spring runtime.
====

== SpEL Options

// language options: START
include::partial$language-options.adoc[]
// language options: END

== Variables

The following Camel related variables are made available:

[width="100%",cols="10%,10%,80%",options="header",]
|=======================================================================
|Variable |Type |Description
|*this* |Exchange |the Exchange is the root object
|context |CamelContext |the CamelContext
|exchange |Exchange |the Exchange
|exchangeId |String |the exchange id
|exception |Throwable |the Exchange exception (if any)
|request |Message |the message
|message |Message |the message
|headers |Map |the message headers
|header(name) |Object |the message header by the given name
|header(name, type) |Type |the message header by the given name as the given type
|properties |Map |the exchange properties
|property(name) |Object |the exchange property by the given name
|property(name, type) |Type |the exchange property by the given name as the given type
|=======================================================================

== Example

You can use SpEL as an expression for xref:eips:recipientList-eip.adoc[Recipient
List] or as a predicate inside a xref:eips:filter-eip.adoc[Message
Filter]:

[source,xml]
----
<route>
  <from uri="direct:foo"/>
  <filter>
    <spel>#{request.headers.foo == 'bar'}</spel>
    <to uri="direct:bar"/>
  </filter>
</route>
----

And the equivalent in Java DSL:

[source,java]
----
from("direct:foo")
    .filter().spel("#{request.headers.foo == 'bar'}")
    .to("direct:bar");
----

=== Expression templating

SpEL expressions need to be surrounded by `#{` `}` delimiters since
expression templating is enabled. This allows you to combine SpEL
expressions with regular text and use this as an extremely lightweight
template language.

For example, if you construct the following route:

[source,java]
----
from("direct:example")
    .setBody(spel("Hello #{request.body}! What a beautiful #{request.headers['dayOrNight']}"))
    .to("mock:result");
----

In the route above, notice `spel` is a static method which we need to
import from `org.apache.camel.language.spel.SpelExpression.spel`, as we
use `spel` as an Expression passed in as a parameter
to the `setBody` method.
Though if we use the fluent API, we can do this instead:

[source,java]
----
from("direct:example")
    .setBody().spel("Hello #{request.body}! What a beautiful #{request.headers['dayOrNight']}")
    .to("mock:result");
----

Notice we now use the `spel` method from the `setBody()` method. And
this does not require us to statically import the `spel` method.

Then we send a message with the string "World" in the body, and a header
`dayOrNight` with value `day`:

[source,java]
----
template.sendBodyAndHeader("direct:example", "World", "dayOrNight", "day");
----

The output on `mock:result` will be _"Hello World! What a beautiful
day"_

=== Bean integration

You can reference beans defined in the xref:manual::registry.adoc[Registry]
in your SpEL expressions. For example, if you have a bean named "foo"
registered in the Spring `ApplicationContext`. You
can then invoke the "bar" method on this bean like this:

[source,text]
----
#{@foo.bar == 'xyz'}
----


== Loading script from external resource

You can externalize the script and have Apache Camel load it from a resource
such as `"classpath:"`, `"file:"`, or `"http:"`.
This is done using the following syntax: `"resource:scheme:location"`,
e.g., to refer to a file on the classpath you can do:

[source,java]
----
.setHeader("myHeader").spel("resource:classpath:myspel.txt")
----



include::spring-boot:partial$starter.adoc[]
