[[atmosphere-websocket-component]]
= Atmosphere Websocket Component
:docTitle: Atmosphere Websocket
:artifactId: camel-atmosphere-websocket
:description: Expose WebSocket endpoints using the Atmosphere framework.
:since: 2.14
:supportLevel: Stable
:component-header: Both producer and consumer are supported
include::{cq-version}@camel-quarkus:ROOT:partial$reference/components/atmosphere-websocket.adoc[opts=optional]

*Since Camel {since}*

*{component-header}*

The Atmosphere-Websocket component provides Websocket
based endpoints for a servlet communicating with
external clients over Websocket (as a servlet accepting websocket
connections from external clients). +
The component uses the xref:servlet-component.adoc[SERVLET] component and uses
the https://github.com/Atmosphere/atmosphere[Atmosphere] library to
support the Websocket transport in various Servlet containers (e..g.,
Jetty, Tomcat, ...).

Unlike the
xref:websocket-component.adoc[Websocket]
component that starts the embedded Jetty server, this component uses the
servlet provider of the container.

Maven users will need to add the following dependency to
their `pom.xml` for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-atmosphere-websocket</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------


// component options: START
// component options: END
// endpoint options: START
// endpoint options: END


== Reading and Writing Data over Websocket

An atmopshere-websocket endpoint can either write data to the socket or
read from the socket, depending on whether the endpoint is configured as
the producer or the consumer, respectively.

== Configuring URI to Read or Write Data

In the route below, Camel will read from the specified websocket
connection.

[source,java]
-------------------------------------------
from("atmosphere-websocket:///servicepath")
        .to("direct:next");
-------------------------------------------

And the equivalent Spring sample:

[source,xml]
------------------------------------------------------------
<camelContext xmlns="http://camel.apache.org/schema/spring">
  <route>
    <from uri="atmosphere-websocket:///servicepath"/>
    <to uri="direct:next"/>
  </route>
</camelContext>
------------------------------------------------------------

In the route below, Camel will read from the specified websocket
connection.

[source,java]
---------------------------------------------------
from("direct:next")
        .to("atmosphere-websocket:///servicepath");
---------------------------------------------------

And the equivalent Spring sample:

[source,xml]
------------------------------------------------------------
<camelContext xmlns="http://camel.apache.org/schema/spring">
  <route>
    <from uri="direct:next"/>
    <to uri="atmosphere-websocket:///servicepath"/>
  </route>
</camelContext>
------------------------------------------------------------

 


include::{page-component-version}@camel-spring-boot::page$atmosphere-websocket-starter.adoc[]
