= Jetty Websocket Component
:doctitle: Jetty Websocket
:shortname: websocket
:artifactid: camel-websocket
:description: Expose websocket endpoints using Jetty.
:since: 2.10
:supportlevel: Stable
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:camel-spring-boot-name: websocket

*Since Camel {since}*

*{component-header}*

The WebSocket component provides websocket
endpoints for communicating with clients using
websocket. The component uses Eclipse Jetty Server which implements the
http://tools.ietf.org/html/rfc6455[IETF] specification (drafts and RFC
6455). It supports the protocols ws:// and wss://. To use wss://
protocol, the SSLContextParameters must be defined.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-websocket</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
----

== URI format

---------------------------------------------------
websocket://hostname[:port][/resourceUri][?options]
---------------------------------------------------


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END

// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END


== Usage

In this example we let Camel exposes a websocket server which clients
can communicate with. The websocket server uses the default host and
port, which would be `0.0.0.0:9292`. +
 The example will send back an echo of the input. To send back a
message, we need to send the transformed message to the same endpoint
`"websocket://echo"`. This is needed +
 because by default the messaging is InOnly.

This example is part of an unit test, which you can find
https://svn.apache.org/repos/asf/camel/trunk/components/camel-websocket/src/test/java/org/apache/camel/component/websocket/WebsocketRouteExampleTest.java[here].
As a client we use Java's own HTTP client which offers support for web socket as well.

Here is another example where webapp resources location have been
defined to allow the Jetty Application Server to not only register the
WebSocket servlet but also to expose web resources for the browser.
Resources should be defined under the webapp directory.

[source,java]
-----------------------------------------------------------------------------------------------
from("activemq:topic:newsTopic")
   .routeId("fromJMStoWebSocket")
   .to("websocket://localhost:8443/newsTopic?sendToAll=true&staticResources=classpath:webapp");
-----------------------------------------------------------------------------------------------

== Setting up SSL for WebSocket Component

=== Using the JSSE Configuration Utility

The WebSocket component supports SSL/TLS configuration
through the xref:manual::camel-configuration-utilities.adoc[Camel JSSE
Configuration Utility].  This utility greatly decreases the amount of
component specific code you need to write and is configurable at the
endpoint and component levels.  The following examples demonstrate how
to use the utility with the Cometd component.

[[Websocket-Programmaticconfigurationofthecomponent]]
Programmatic configuration of the component

[source,java]
-----------------------------------------------------------------------------------------------
KeyStoreParameters ksp = new KeyStoreParameters();
ksp.setResource("/users/home/server/keystore.jks");
ksp.setPassword("keystorePassword");

KeyManagersParameters kmp = new KeyManagersParameters();
kmp.setKeyStore(ksp);
kmp.setKeyPassword("keyPassword");

TrustManagersParameters tmp = new TrustManagersParameters();
tmp.setKeyStore(ksp);

SSLContextParameters scp = new SSLContextParameters();
scp.setKeyManagers(kmp);
scp.setTrustManagers(tmp);

CometdComponent commetdComponent = getContext().getComponent("cometds", CometdComponent.class);
commetdComponent.setSslContextParameters(scp);
-----------------------------------------------------------------------------------------------

[[Websocket-SpringDSLbasedconfigurationofendpoint]]
Spring DSL based configuration of endpoint

[source,xml]
-------------------------------------------------------------------------------------------
...
  <camel:sslContextParameters
      id="sslContextParameters">
    <camel:keyManagers
        keyPassword="keyPassword">
      <camel:keyStore
          resource="/users/home/server/keystore.jks"
          password="keystorePassword"/>
    </camel:keyManagers>
    <camel:trustManagers>
      <camel:keyStore
          resource="/users/home/server/keystore.jks"
          password="keystorePassword"/>
    </camel:trustManagers>
  </camel:sslContextParameters>...
...
  <to uri="websocket://127.0.0.1:8443/test?sslContextParameters=#sslContextParameters"/>...
-------------------------------------------------------------------------------------------

[[Websocket-JavaDSLbasedconfigurationofendpoint]]
Java DSL based configuration of endpoint

[source,java]
----------------------------------------------------------------------------------------------------------
...
    protected RouteBuilder createRouteBuilder() throws Exception {
        return new RouteBuilder() {
            public void configure() {
                
                String uri = "websocket://127.0.0.1:8443/test?sslContextParameters=#sslContextParameters";
                
                from(uri)
                     .log(">>> Message received from WebSocket Client : ${body}")
                     .to("mock:client")
                     .loop(10)
                         .setBody().constant(">> Welcome on board!")
                         .to(uri);
...
----------------------------------------------------------------------------------------------------------



include::spring-boot:partial$starter.adoc[]
