= SCP Component
:doctitle: SCP
:shortname: scp
:artifactid: camel-jsch
:description: Copy files to/from remote hosts using the secure copy protocol (SCP).
:since: 2.10
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported
//Manually maintained attributes
:camel-spring-boot-name: jsch

*Since Camel {since}*

*{component-header}*

The Camel-Jsch component supports the
http://en.wikipedia.org/wiki/Secure_copy[SCP protocol] using the Client
API of the http://www.jcraft.com/jsch/[Jsch] project. Jsch is already
used in camel by the xref:ftp-component.adoc[FTP] component for the *sftp:*
protocol.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-jsch</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

== URI format

---------------------------------------
scp://host[:port]/destination[?options]
---------------------------------------

The file name can be specified either in the <path> part of the URI or
as a "CamelFileName" header on the message (`Exchange.FILE_NAME` if used
in code).


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END


== Limitations

Currently camel-jsch only supports a
https://www.javadoc.io/doc/org.apache.camel/camel-api/current/org/apache/camel/Producer.html[Producer]
(i.e. copy files to another host). 



include::spring-boot:partial$starter.adoc[]
