/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.builder.component.dsl;

import javax.annotation.Generated;
import org.apache.camel.Component;
import org.apache.camel.builder.component.AbstractComponentBuilder;
import org.apache.camel.builder.component.ComponentBuilder;
import org.apache.camel.component.xquery.XQueryComponent;

/**
 * Transforms the message using a XQuery template using Saxon.
 * 
 * Generated by camel-package-maven-plugin - do not edit this file!
 */
@Generated("org.apache.camel.maven.packaging.ComponentDslMojo")
public interface XQueryComponentBuilderFactory {

    /**
     * XQuery (camel-saxon)
     * Transforms the message using a XQuery template using Saxon.
     * 
     * Category: transformation
     * Since: 1.0
     * Maven coordinates: org.apache.camel:camel-saxon
     */
    static XQueryComponentBuilder xquery() {
        return new XQueryComponentBuilderImpl();
    }

    /**
     * Builder for the XQuery component.
     */
    interface XQueryComponentBuilder
            extends
                ComponentBuilder<XQueryComponent> {
        /**
         * To use the custom ModuleURIResolver.
         * 
         * The option is a: <code>net.sf.saxon.lib.ModuleURIResolver</code>
         * type.
         * 
         * Group: advanced
         */
        default XQueryComponentBuilder moduleURIResolver(
                net.sf.saxon.lib.ModuleURIResolver moduleURIResolver) {
            doSetProperty("moduleURIResolver", moduleURIResolver);
            return this;
        }
        /**
         * To use a custom Saxon configuration.
         * 
         * The option is a: <code>net.sf.saxon.Configuration</code> type.
         * 
         * Group: advanced
         */
        default XQueryComponentBuilder configuration(
                net.sf.saxon.Configuration configuration) {
            doSetProperty("configuration", configuration);
            return this;
        }
        /**
         * To set custom Saxon configuration properties.
         * 
         * The option is a:
         * <code>java.util.Map<java.lang.String,java.lang.Object></code> type.
         * 
         * Group: advanced
         */
        default XQueryComponentBuilder configurationProperties(
                java.util.Map<java.lang.String,java.lang.Object> configurationProperties) {
            doSetProperty("configurationProperties", configurationProperties);
            return this;
        }
        /**
         * Whether the component should use basic property binding (Camel 2.x)
         * or the newer property binding with additional capabilities.
         * 
         * The option is a: <code>boolean</code> type.
         * 
         * Default: false
         * Group: advanced
         */
        default XQueryComponentBuilder basicPropertyBinding(
                boolean basicPropertyBinding) {
            doSetProperty("basicPropertyBinding", basicPropertyBinding);
            return this;
        }
        /**
         * Whether the producer should be started lazy (on the first message).
         * By starting lazy you can use this to allow CamelContext and routes to
         * startup in situations where a producer may otherwise fail during
         * starting and cause the route to fail being started. By deferring this
         * startup to be lazy then the startup failure can be handled during
         * routing messages via Camel's routing error handlers. Beware that when
         * the first message is processed then creating and starting the
         * producer may take a little time and prolong the total processing time
         * of the processing.
         * 
         * The option is a: <code>boolean</code> type.
         * 
         * Default: false
         * Group: producer
         */
        default XQueryComponentBuilder lazyStartProducer(
                boolean lazyStartProducer) {
            doSetProperty("lazyStartProducer", lazyStartProducer);
            return this;
        }
        /**
         * Allows for bridging the consumer to the Camel routing Error Handler,
         * which mean any exceptions occurred while the consumer is trying to
         * pickup incoming messages, or the likes, will now be processed as a
         * message and handled by the routing Error Handler. By default the
         * consumer will use the org.apache.camel.spi.ExceptionHandler to deal
         * with exceptions, that will be logged at WARN or ERROR level and
         * ignored.
         * 
         * The option is a: <code>boolean</code> type.
         * 
         * Default: false
         * Group: consumer
         */
        default XQueryComponentBuilder bridgeErrorHandler(
                boolean bridgeErrorHandler) {
            doSetProperty("bridgeErrorHandler", bridgeErrorHandler);
            return this;
        }
    }

    class XQueryComponentBuilderImpl
            extends
                AbstractComponentBuilder<XQueryComponent>
            implements
                XQueryComponentBuilder {
        @Override
        protected XQueryComponent buildConcreteComponent() {
            return new XQueryComponent();
        }
        @Override
        protected boolean setPropertyOnComponent(
                Component component,
                String name,
                Object value) {
            switch (name) {
            case "moduleURIResolver": ((XQueryComponent) component).setModuleURIResolver((net.sf.saxon.lib.ModuleURIResolver) value); return true;
            case "configuration": ((XQueryComponent) component).setConfiguration((net.sf.saxon.Configuration) value); return true;
            case "configurationProperties": ((XQueryComponent) component).setConfigurationProperties((java.util.Map<java.lang.String,java.lang.Object>) value); return true;
            case "basicPropertyBinding": ((XQueryComponent) component).setBasicPropertyBinding((boolean) value); return true;
            case "lazyStartProducer": ((XQueryComponent) component).setLazyStartProducer((boolean) value); return true;
            case "bridgeErrorHandler": ((XQueryComponent) component).setBridgeErrorHandler((boolean) value); return true;
            default: return false;
            }
        }
    }
}