= JSONata Component
:doctitle: JSONata
:shortname: jsonata
:artifactid: camel-jsonata
:description: Transforms JSON payload using JSONata transformation.
:since: 3.5
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported
//Manually maintained attributes
:camel-spring-boot-name: jsonata

*Since Camel {since}*

*{component-header}*

The Jsonata component allows you to process JSON messages using the
https://jsonata.org/[JSONATA] specification. This can be
ideal when doing JSON to JSON transformation and other transformations from JSON.

Maven users will need to add the following dependency to
their `pom.xml` for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-jsonata</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------
 

== URI format

-----------------------
jsonata:specName[?options]
-----------------------

Where *specName* is the classpath-local URI of the specification to
invoke; or the complete URL of the remote specification
(e.g.: `\file://folder/myfile.vm`).


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
// component options: END

// endpoint options: START
include::partial$component-endpoint-options.adoc[]
// endpoint options: END

== Examples

=== Basic

For example, you could use something like:

[source,java]
--------------------------------------
from("activemq:My.Queue").
  to("jsonata:com/acme/MyResponse.json");
--------------------------------------

And a file-based resource:

[source,java]
---------------------------------------------------------------
from("activemq:My.Queue").
  to("jsonata:file://myfolder/MyResponse.json?contentCache=true").
  to("activemq:Another.Queue");
---------------------------------------------------------------

=== Frame bindings

It is possible to configure custom functions that can be called from Jsonata. For example you might want to be able to
inject environment variables:

[source,java]
---------------------------------------------------------------
from("activemq:My.Queue").
  to("jsonata:file://myfolder/MyResponse.json?contentCache=true&frameBinding=#customBindings").
  to("activemq:Another.Queue");
---------------------------------------------------------------

A custom binding might look like the following:

[source,java]
---------------------------------------------------------------
@NoArgsConstructor
public class CustomJsonataFrameBinding implements JsonataFrameBinding {
  @Override
  public void bindToFrame(Jsonata.Frame frame) {
    frame.bind("env", (String s) -> System.getenv(s));
  }
}
---------------------------------------------------------------

include::spring-boot:partial$starter.adoc[]
