= CSimple jOOR Component
:doctitle: CSimple jOOR
:shortname: csimple-joor
:artifactid: camel-csimple-joor
:description: jOOR compiler for csimple language
:since: 3.7
:supportlevel: Stable
:tabs-sync-option:
//Manually maintained attributes
:camel-spring-boot-name: csimple-joor

*Since Camel {since}*

The csimple (compiled simple) expression language can either be source code generated and compiled together
with your application using the regular Java compiler. Or compiled at runtime using jOOR during bootstrap.

This module includes the jOOR compiler for the csimple language for runtime compilation.

To use this, just include `camel-csimple-joor` in the classpath.

NOTE: Java 8 is not supported. Java 11 or newer is required.


== Limitations

The supported runtime is intended for Java standalone, Spring Boot, Camel Quarkus and other microservices runtimes.
It is not supported in OSGi, Camel Karaf or any kind of Java Application Server runtime.

jOOR does not support runtime compilation with Spring Boot using _fat jar_ packaging (https://github.com/jOOQ/jOOR/issues/69),
it works with exploded classpath.

== Dependencies

To use scripting languages in your camel routes you need to add a
dependency on *camel-csimple-joor*.

If you use Maven you could just add the following to your `pom.xml`,
substituting the version number for the latest and greatest release (see
the download page for the latest versions).

[source,xml]
---------------------------------------
<dependency>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-csimple-joor</artifactId>
  <version>x.x.x</version>
</dependency>
---------------------------------------

include::spring-boot:partial$starter.adoc[]
