[[pgevent-component]]
= PostgresSQL Event Component
:docTitle: PostgresSQL Event
:artifactId: camel-pgevent
:description: Send and receive PostgreSQL events via LISTEN and NOTIFY commands.
:since: 2.15
:supportLevel: Stable
:component-header: Both producer and consumer are supported
include::{cq-version}@camel-quarkus:ROOT:partial$reference/components/pgevent.adoc[opts=optional]

*Since Camel {since}*

*{component-header}*

This is a component for Apache Camel which allows for
Producing/Consuming PostgreSQL events related to the LISTEN/NOTIFY
commands added since PostgreSQL 8.3.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-pgevent</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

URI format

The pgevent component uses the following two styles of endpoint URI
notation:

-------------------------------------------------
pgevent:datasource[?parameters]
pgevent://host:port/database/channel[?parameters]
-------------------------------------------------


// component options: START
// component options: END
// endpoint options: START
// endpoint options: END


== Common problems

=== Unable to connect to PostgreSQL database using DataSource
Using the driver provided by PostgreSQL itself (`jdbc:postgresql:/...`) when using a DataSource to connect to a PostgreSQL database does not work.

Please use the pgjdbc-ng driver (`jdbc:pgsql:/...`) instead.



include::{page-component-version}@camel-spring-boot::page$pgevent-starter.adoc[]
