<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="camel"
    nsURI="http://camel.apache.org/routing/1.0" nsPrefix="camel">
  <eClassifiers xsi:type="ecore:EClass" name="Routes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="routes" upperBound="-1"
        eType="#//Route" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Route">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="from" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processors" upperBound="-1"
        eType="#//Processor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Processor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Send" eSuperTypes="#//Processor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//Processor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
