#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: "Incremental Build Runner"
description: "Build only affected projects"
inputs:
  mode:
    description: 'The mode to launch, it can be build or test'
    required: true
  pr-id:
    description: 'Id of the pull request'
    required: true
  github-token:
    description: 'The github token to access to the API'
    required: false
  skip-mvnd-install:
    description: 'Flag indicating whether the installation of mvnd should be skipped'
    required: false
    default: 'false'
  github-repo:
    description: 'The GitHub repository name (example, apache/camel)'
    required: false
    default: 'apache/camel'
  artifact-upload-suffix:
    description: 'Suffix for artifacts stored'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - id: install-mvnd
      uses: apache/camel/.github/actions/install-mvnd@main
      with:
        dry-run: ${{ inputs.skip-mvnd-install }}
    - name: maven build
      shell: bash
      run: ${{ github.action_path }}/incremental-build.sh ${{ steps.install-mvnd.outputs.mvnd-dir }}/mvnd ${{ inputs.mode }} ${{ inputs.pr-id }} ${{ inputs.github-repo }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - name: archive logs
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: incremental-${{ inputs.mode }}-${{ inputs.artifact-upload-suffix }}.log
        path: incremental-${{ inputs.mode }}.log
