= Vert.x WebSocket Component
:doctitle: Vert.x WebSocket
:shortname: vertx-websocket
:artifactid: camel-vertx-websocket
:description: Expose WebSocket endpoints and connect to remote WebSocket servers using Vert.x
:since: 3.5
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:camel-spring-boot-name: vertx-websocket

*Since Camel {since}*

*{component-header}*

The http://vertx.io/[Vert.x] WebSocket component provides WebSocket capabilities as a WebSocket server, or as a client to connect to an existing WebSocket.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-vertx-websocket</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

== URI format

---------------------------
vertx-websocket://hostname[:port][/resourceUri][?options]
---------------------------



// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END

// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

== Usage
The following example shows how to expose a WebSocket on http://localhost:8080/echo and returns an 'echo' response back to the same channel:

[source,java]
----
from("vertx-websocket:localhost:8080/echo")
    .transform().simple("Echo: ${body}")
    .to("vertx-websocket:localhost:8080/echo");
----

It's also possible to configure the consumer to connect as a WebSocket client on a remote address with the `consumeAsClient` option:

[source,java]
----
from("vertx-websocket:my.websocket.com:8080/chat?consumeAsClient=true")
    .log("Got WebSocket message ${body}");
----

== Path & query parameters

The WebSocket server consumer supports the configuration of parameterized paths. The path parameter value will be set
as a Camel exchange header:

[source,java]
----
from("vertx-websocket:localhost:8080/chat/{user}")
    .log("New message from ${header.user} >>> ${body}")
----

Similarly you can retrieve any query parameter values that were used by the WebSocket client to connect to the server endpoint:

[source,java]
----
from("direct:sendChatMessage")
    .to("vertx-websocket:localhost:8080/chat/camel?role=admin");

from("vertx-websocket:localhost:8080/chat/{user}")
    .log("New message from ${header.user} (${header.role}) >>> ${body}")
----

== Sending messages to peers connected to the vertx-websocket server consumer

NOTE: This section only applies when producing messages to a WebSocket hosted by the camel-vertx-websocket consumer.
It is not relevant when producing messages to an externally hosted WebSocket.

To send a message to all peers connected to a WebSocket hosted by the vertx-websocket server consumer, use the `sendToAll=true`
endpoint option, or the `CamelVertxWebsocket.sendToAll` header.

[source,java]
----
from("vertx-websocket:localhost:8080/chat")
    .log("Got WebSocket message ${body}");

from("direct:broadcastMessage")
    .setBody().constant("This is a broadcast message!")
    .to("vertx-websocket:localhost:8080/chat?sendToAll=true");
----

Alternatively, you can send messages to specific peers by using the `CamelVertxWebsocket.connectionKey` header.
Multiple peers can be specified as a comma separated list.

The value of the `connectionKey` can be determined whenever a peer triggers an event on the vertx-websocket
consumer, where a unique key identifying the peer will be propagated via the `CamelVertxWebsocket.connectionKey` header.

[source,java]
----
from("vertx-websocket:localhost:8080/chat")
    .log("Got WebSocket message ${body}");

from("direct:broadcastMessage")
    .setBody().constant("This is a broadcast message!")
    .setHeader(VertxWebsocketConstants.CONNECTION_KEY).constant("key-1,key-2,key-3")
    .to("vertx-websocket:localhost:8080/chat");
----

== SSL

By default, the `ws://` protocol is used, but secure connections with `wss://` are supported by configuring the consumer or producer
via the `sslContextParameters` URI parameter and the xref:manual::camel-configuration-utilities.adoc[Camel JSSE Configuration Utility]


include::spring-boot:partial$starter.adoc[]
