= Vert.x WebSocket Component
:doctitle: Vert.x WebSocket
:shortname: vertx-websocket
:artifactid: camel-vertx-websocket
:description: Expose WebSocket endpoints and connect to remote WebSocket servers using Vert.x
:since: 3.5
:supportlevel: Stable
:component-header: Both producer and consumer are supported
include::{cq-version}@camel-quarkus:ROOT:partial$reference/components/vertx-websocket.adoc[opts=optional]
//Manually maintained attributes
:camel-spring-boot-name: vertx-websocket

*Since Camel {since}*

*{component-header}*

The http://vertx.io/[Vert.x] WebSocket component provides WebSocket capabilities as a WebSocket server, or as a client to connect to an existing WebSocket.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-vertx-websocket</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

== URI format

---------------------------
vertx-websocket://hostname[:port][/resourceUri][?options]
---------------------------



// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END



== Message Headers

The WebSocket component uses 2 headers to indicate to either send
messages back to a single/current client, or to all clients.

[width="100%",cols="10%,90%",options="header",]
|=======================================================================
| Name | Description
|`VertxWebsocketConstants.SEND_TO_ALL` |Sends the message to all clients which are currently connected. You can
use the `sendToAll` option on the endpoint instead of using this header.
|`VertxWebsocketConstants.CONNECTION_KEY` |Sends the message to the client with the given connection key. You can
use a comma separated list of keys to send a message to multiple clients
|=======================================================================

== Usage
The following example shows how to expose a WebSocket on http://localhost:8080/echo and returns an 'echo' response back to the same channel:

[source,java]
----
from("vertx-websocket:localhost:8080/echo")
    .transform().simple("Echo: ${body}")
    .to("vertx-websocket:localhost:8080/echo");
----

== SSL

By default the `ws://` protocol is used, but secure connections with `wss://` are supported by configuring the consumer or producer
via the `sslContextParameters` URI parameter and the xref:manual::camel-configuration-utilities.adoc[Camel JSSE Configuration Utility]


include::spring-boot:partial$starter.adoc[]
