/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.dsl.jbang.core.commands;

import java.nio.file.Files;
import java.nio.file.Path;

import org.apache.camel.dsl.jbang.core.common.RuntimeType;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verifies how {@code camel run pom.xml} tells the runtime of an existing Maven project from its pom.
 */
class RunHelperDetectRuntimeTest {

    @TempDir
    Path dir;

    @Test
    void quarkusBomNamedWithProperties() throws Exception {
        // as generated by code.quarkus.io and used by camel-quarkus-examples
        Path pom = pom("""
                <properties>
                    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
                    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
                    <quarkus.platform.version>3.30.0</quarkus.platform.version>
                </properties>
                <dependencyManagement>
                    <dependencies>
                        <dependency>
                            <groupId>${quarkus.platform.group-id}</groupId>
                            <artifactId>${quarkus.platform.artifact-id}</artifactId>
                            <version>${quarkus.platform.version}</version>
                            <type>pom</type>
                            <scope>import</scope>
                        </dependency>
                    </dependencies>
                </dependencyManagement>
                """);
        assertThat(RunHelper.detectRuntimeFromPom(pom)).isEqualTo(RuntimeType.quarkus);
    }

    @Test
    void quarkusMavenPlugin() throws Exception {
        Path pom = pom("""
                <build>
                    <plugins>
                        <plugin>
                            <groupId>io.quarkus.platform</groupId>
                            <artifactId>quarkus-maven-plugin</artifactId>
                        </plugin>
                    </plugins>
                </build>
                """);
        assertThat(RunHelper.detectRuntimeFromPom(pom)).isEqualTo(RuntimeType.quarkus);
    }

    @Test
    void springBootBom() throws Exception {
        Path pom = pom("""
                <dependencyManagement>
                    <dependencies>
                        <dependency>
                            <groupId>org.apache.camel.springboot</groupId>
                            <artifactId>camel-spring-boot-bom</artifactId>
                            <version>4.23.0</version>
                            <type>pom</type>
                            <scope>import</scope>
                        </dependency>
                    </dependencies>
                </dependencyManagement>
                """);
        assertThat(RunHelper.detectRuntimeFromPom(pom)).isEqualTo(RuntimeType.springBoot);
    }

    @Test
    void springBootMavenPlugin() throws Exception {
        Path pom = pom("""
                <build>
                    <plugins>
                        <plugin>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-maven-plugin</artifactId>
                        </plugin>
                    </plugins>
                </build>
                """);
        assertThat(RunHelper.detectRuntimeFromPom(pom)).isEqualTo(RuntimeType.springBoot);
    }

    @Test
    void aPropertyThatRefersToItselfDoesNotLoop() throws Exception {
        Path pom = pom("""
                <properties>
                    <a>${b}</a>
                    <b>${a}</b>
                </properties>
                <dependencyManagement>
                    <dependencies>
                        <dependency>
                            <groupId>org.example</groupId>
                            <artifactId>${a}</artifactId>
                            <version>1.0</version>
                        </dependency>
                    </dependencies>
                </dependencyManagement>
                """);
        assertThat(RunHelper.detectRuntimeFromPom(pom)).isNull();
    }

    @Test
    void plainProject() throws Exception {
        Path pom = pom("""
                <dependencies>
                    <dependency>
                        <groupId>org.apache.camel</groupId>
                        <artifactId>camel-main</artifactId>
                    </dependency>
                </dependencies>
                """);
        assertThat(RunHelper.detectRuntimeFromPom(pom)).isNull();
    }

    private Path pom(String body) throws Exception {
        Path pom = dir.resolve("pom.xml");
        Files.writeString(pom, """
                <project xmlns="http://maven.apache.org/POM/4.0.0">
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>org.example</groupId>
                    <artifactId>demo</artifactId>
                    <version>1.0</version>
                """ + body + "</project>\n");
        return pom;
    }
}
