= Master Component
:doctitle: Master
:shortname: master
:artifactid: camel-master
:description: Have only a single consumer in a cluster consuming from a given endpoint; with automatic failover if the JVM dies.
:since: 2.20
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only consumer is supported
//Manually maintained attributes
:camel-spring-boot-name: master

*Since Camel {since}*

*{component-header}*

The Camel-Master endpoint provides a way to ensure only a single consumer in a cluster consumes from a given endpoint;
with automatic fail over if that JVM dies.

This can be handy if you need to consume from some legacy back end that either doesn't support concurrent
consumption or due to commercial or stability reasons, you can only have a single connection at any point in time.

== Using the master endpoint

Just prefix any camel endpoint with **master:someName:** where _someName_ is a logical name and is
used to acquire the master lock. e.g.

[source,java]
----
from("master:cheese:jms:foo")
  .to("activemq:wine");
----

In this example, the master component ensures that the route is only active in one node, at any given time, in the cluster.
So if there are 8 nodes in the cluster, then the master component will elect one route to be the leader, and only
this route will be active, and hence only this route will consume messages from `jms:foo`.
In case this route is stopped or unexpectedly terminated, then the master component will detect this,
and re-elect another node to be active, which will then become active and start consuming messages from `jms:foo`.

TIP: Apache ActiveMQ 5.x has such a feature out of the box called https://activemq.apache.org/exclusive-consumer.html[Exclusive Consumers].

== URI format

----
master:namespace:endpoint[?options]
----

Where endpoint is any Camel endpoint, you want to run in master/slave mode.


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END


== Example

You can protect a clustered Camel application to only consume files from one active node.


[source,java]
----
// the file endpoint we want to consume from
String url = "file:target/inbox?delete=true";

// use the camel master component in the clustered group named myGroup
// to run a master/slave mode in the following Camel url
from("master:myGroup:" + url)
    .log(name + " - Received file: ${file:name}")
    .delay(delay)
    .log(name + " - Done file:     ${file:name}")
    .to("file:target/outbox");
----

The master component leverages CamelClusterService you can configure using

* *Java*
+
[source,java]
----
ZooKeeperClusterService service = new ZooKeeperClusterService();
service.setId("camel-node-1");
service.setNodes("myzk:2181");
service.setBasePath("/camel/cluster");

context.addService(service)
----

* *Xml (Spring/Blueprint)*
+
[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="
     http://www.springframework.org/schema/beans
     http://www.springframework.org/schema/beans/spring-beans.xsd
     http://camel.apache.org/schema/spring
     http://camel.apache.org/schema/spring/camel-spring.xsd">


  <bean id="cluster" class="org.apache.camel.component.zookeeper.cluster.ZooKeeperClusterService">
    <property name="id" value="camel-node-1"/>
    <property name="basePath" value="/camel/cluster"/>
    <property name="nodes" value="myzk:2181"/>
  </bean>

  <camelContext xmlns="http://camel.apache.org/schema/spring" autoStartup="false">
    ...
  </camelContext>

</beans>
----

* *Spring boot*
+
[source,properties]
----
camel.component.zookeeper.cluster.service.enabled   = true
camel.component.zookeeper.cluster.service.id        = camel-node-1
camel.component.zookeeper.cluster.service.base-path = /camel/cluster
camel.component.zookeeper.cluster.service.nodes     = myzk:2181
----

== Implementations

Camel provides the following ClusterService implementations:

- camel-consul
- camel-file
- camel-infinispan
- camel-jgroups-raft
- camel-jgroups
- camel-kubernetes
- camel-zookeeper


include::spring-boot:partial$starter.adoc[]
