== Billboard TOP100 aggregation example

=== Introduction

The `+billboard_lyrics_1964-2015+` CSV dataset contains the TOP100 songs
with lyrics for each year. +
We can compute the TOP20 artists with most songs on Billboard using
Split and Aggregate EIPs. +
Build statistics is not the Camel core business but, as shown, you can
easily do it!

This is the final result:

[cols=",",options="header",]
|===
|Artist |Presences
|madonna |35
|elton john |26
|mariah carey |25
|stevie wonder |22
|janet jackson |22
|michael jackson |22
|whitney houston |19
|rihanna |19
|taylor swift |19
|pink |17
|the beatles |17
|kelly clarkson |17
|britney spears |16
|the black eyed peas |16
|chicago |15
|usher |14
|rod stewart |14
|aretha franklin |14
|katy perry |14
|phil collins |13
|===

=== Build and run

Build and run the test with this single command.

[source,sh]
----
mvn clean test
----

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/support.html[let us know].

We also love contributors, so
https://camel.apache.org/contributing.html[get involved] :-)

The Camel riders!
