[[joor-language]]
= jOOR Language
:docTitle: jOOR
:artifactId: camel-joor
:description: Evaluate a jOOR (Java compiled once at runtime) expression language.
:since: 3.7
:supportLevel: Preview
include::{cq-version}@camel-quarkus:ROOT:partial$reference/languages/joor.adoc[]

*Since Camel {since}*

The jOOR langauge allows to use Java code in your Camel expression, with some limitations.
The jOOR library integrates with the Java compiler and performs runtime compilation of Java code (with some limitiations).

NOTE: Java 8 is not supported. This requires Java 11 or 14.


== jOOR Options



// language options: START
The jOOR language supports 4 options, which are listed below.



[width="100%",cols="2,1m,1m,6",options="header"]
|===
| Name | Default | Java Type | Description
| preCompile | true | Boolean | Whether the expression should be pre compiled once during initialization phase. If this is turned off, then the expression is reloaded and compiled on each evaluation.
| resultType |  | String | Sets the class name of the result type (type from output)
| singleQuotes | true | Boolean | Whether single quotes can be used as replacement for double quotes. This is convenient when you need to work with strings inside strings.
| trim | true | Boolean | Whether to trim the value to remove leading and trailing whitespaces and line breaks
|===
// language options: END

== Variables

The jOOR language allows the following variables to be used in the script:

[width="100%",cols="2,1m,7",options="header"]
|===
| Variable | Java Type | Description
| context | Context | The CamelContext
| exchange | Exchange | The Camel Exchange
| message | Message | The Camel message
| body | Object | The message body
|===

== Sample

For example to transform the message using jOOR language to upper case

[source,java]
----
from("seda:orders")
  .transform().joor("message.getBody(String.class).toUpperCase()")
  .to("seda:upper");
----

And in XML DSL:
[source,xml]
----
<route>
   <from uri="seda:orders"/>
   <transform>
     <joor>message.getBody(String.class).toUpperCase()</joor>
   </transform>
   <to uri="seda:upper"/>
</route>
----

== Multi statements

It is possible to include multiple statements, for example where we in the first statement gets the `user` header.
And then in the 2nd statement we return a value whether the user is `null` or not.

[source,java]
----
from("seda:orders")
  .transform().joor("Object user = message.getHeader(\"user\"); return user != null ? \"User: \" + user : \"No user exists\";")
  .to("seda:user");
----

Notice how we have to quote strings in strings, and that is annoying, so instead we can use single quotes:

[source,java]
----
from("seda:orders")
  .transform().joor("Object user = message.getHeader('user'); return user != null ? 'User: ' + user : 'No user exists';")
  .to("seda:user");
----

== Hot re-load

You can turn of pre compilation for the jOOR language and then Camel will recompile the script for each message.
You can externalize the code into a resource file, which will be reloaded on each message as shown:

[source,java]
----
JoorLanguage joor = (JoorLanguage) context.resolveLanguage("joor");
joor.setPreCompile(false);

from("jms:incoming")
    .transform().joor("resource:file:src/main/resources/orders.joor")
    .to("jms:orders");
----

Here the jOOR script is externalized into the file `src/main/resources/orders.joor` which allows you to edit this source
file while running the Camel application and try the changes with hot-reloading.

In XML DSL its a little bit easier as you can turn off pre-compilation in the `<joor>` XML element:

[source,xml]
----
<route>
    <from uri="jms:incoming"/>
    <transform>
      <joor preCompile="false">resource:file:src/main/resources/orders.joor</joor>
    </transform>
    <to uri="jms:orders"/>
</route>
----

== Limitations

The jOOR Camel language is only supported as a block of Java code that gets compiled into a Java class with a single method.
The code that you can write is therefore limited to a number of Java statements.

The supported runtime is intended for Java standalone, Spring Boot, Camel Quarkus and other microservices runtimes.
It is not supported in OSGi, Camel Karaf or any kind of Java Application Server runtime.

== Dependencies

To use scripting languages in your camel routes you need to add a
dependency on *camel-joor*.

If you use Maven you could just add the following to your `pom.xml`,
substituting the version number for the latest and greatest release (see
the download page for the latest versions).

[source,xml]
---------------------------------------
<dependency>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-joor</artifactId>
  <version>x.x.x</version>
</dependency>
---------------------------------------
