== HTTP Component (deprecated)

*Available as of Camel version 1.0*

The *http:* component provides HTTP based link:endpoint.html[endpoints]
for consuming external HTTP resources (as a client to call external
servers using HTTP).

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-http</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

### URI format

[source,java]
------------------------------------------------------------------
http:hostname[:port][/resourceUri][?param1=value1][&param2=value2]
------------------------------------------------------------------

Will by default use port 80 for HTTP and 443 for HTTPS.

*camel-http vs camel-jetty*

You can only produce to endpoints generated by the HTTP component.
Therefore it should never be used as input into your camel Routes. To
bind/expose an HTTP endpoint via a HTTP server as input to a camel
route, you can use the link:jetty.html[Jetty Component] or the
link:servlet.html[Servlet Component]


### Examples

Call the url with the body using POST and return response as out
message. If body is null call URL using GET and return response as out
message

Java DSL

Spring DSL

[source,java]
------------------------------
from("direct:start")
  .to("http://myhost/mypath");
------------------------------

[source,xml]
--------------------------
<from uri="direct:start"/>
<to uri="http://oldhost"/>
--------------------------

You can override the HTTP endpoint URI by adding a header. Camel will
call the http://newhost. This is very handy for e.g. REST urls.

Java DSL

[source,java]
-----------------------------------------------------------------------------------
from("direct:start")
  .setHeader(Exchange.HTTP_URI, simple("http://myserver/orders/${header.orderId}"))
  .to("http://dummyhost");
-----------------------------------------------------------------------------------

URI parameters can either be set directly on the endpoint URI or as a
header

Java DSL

[source,java]
---------------------------------------------------------------------
from("direct:start")
  .to("http://oldhost?order=123&detail=short");
from("direct:start")
  .setHeader(Exchange.HTTP_QUERY, constant("order=123&detail=short"))
  .to("http://oldhost");
---------------------------------------------------------------------

Set the HTTP request method to POST

Java DSL

Spring DSL

[source,java]
----------------------------------------------------
from("direct:start")
  .setHeader(Exchange.HTTP_METHOD, constant("POST"))
  .to("http://www.google.com");
----------------------------------------------------

[source,xml]
----------------------------------------
<from uri="direct:start"/>
<setHeader headerName="CamelHttpMethod">
  <constant>POST</constant>
</setHeader>
<to uri="http://www.google.com"/>
<to uri="mock:results"/>
----------------------------------------

### Http Options




// component options: START
The HTTP component supports 8 options which are listed below.



[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *httpClientConfigurer* (advanced) | To use the custom HttpClientConfigurer to perform configuration of the HttpClient that will be used. |  | HttpClientConfigurer
| *httpConnectionManager* (advanced) | To use a custom HttpConnectionManager to manage connections |  | HttpConnectionManager
| *httpBinding* (producer) | To use a custom HttpBinding to control the mapping between Camel message and HttpClient. |  | HttpBinding
| *httpConfiguration* (producer) | To use the shared HttpConfiguration as base configuration. |  | HttpConfiguration
| *allowJavaSerialized Object* (producer) | Whether to allow java serialization when a request uses context-type=application/x-java-serialized-object This is by default turned off. If you enable this then be aware that Java will deserialize the incoming data from the request to Java and that can be a potential security risk. | false | boolean
| *useGlobalSslContext Parameters* (security) | Enable usage of global SSL context parameters. | false | boolean
| *headerFilterStrategy* (filter) | To use a custom org.apache.camel.spi.HeaderFilterStrategy to filter header to and from Camel message. |  | HeaderFilterStrategy
| *resolveProperty Placeholders* (advanced) | Whether the component should resolve property placeholders on itself when starting. Only properties which are of String type can use property placeholders. | true | boolean
|===
// component options: END









// endpoint options: START
The HTTP endpoint is configured using URI syntax:

----
http:httpUri
----

with the following path and query parameters:

==== Path Parameters (1 parameters):

[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *httpUri* | *Required* The url of the HTTP endpoint to call. |  | URI
|===

==== Query Parameters (38 parameters):

[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *disableStreamCache* (common) | Determines whether or not the raw input stream from Servlet is cached or not (Camel will read the stream into a in memory/overflow to file Stream caching) cache. By default Camel will cache the Servlet input stream to support reading it multiple times to ensure it Camel can retrieve all data from the stream. However you can set this option to true when you for example need to access the raw stream such as streaming it directly to a file or other persistent store. DefaultHttpBinding will copy the request input stream into a stream cache and put it into message body if this option is false to support reading the stream multiple times. If you use Servlet to bridge/proxy an endpoint then consider enabling this option to improve performance in case you do not need to read the message payload multiple times. The http/http4 producer will by default cache the response body stream. If setting this option to true then the producers will not cache the response body stream but use the response stream as-is as the message body. | false | boolean
| *headerFilterStrategy* (common) | To use a custom HeaderFilterStrategy to filter header to and from Camel message. |  | HeaderFilterStrategy
| *httpBinding* (common) | To use a custom HttpBinding to control the mapping between Camel message and HttpClient. |  | HttpBinding
| *bridgeEndpoint* (producer) | If the option is true HttpProducer will ignore the Exchange.HTTP_URI header and use the endpoint's URI for request. You may also set the option throwExceptionOnFailure to be false to let the HttpProducer send all the fault response back. | false | boolean
| *chunked* (producer) | If this option is false the Servlet will disable the HTTP streaming and set the content-length header on the response | true | boolean
| *connectionClose* (producer) | Specifies whether a Connection Close header must be added to HTTP Request. By default connectionClose is false. | false | boolean
| *copyHeaders* (producer) | If this option is true then IN exchange headers will be copied to OUT exchange headers according to copy strategy. Setting this to false allows to only include the headers from the HTTP response (not propagating IN headers). | true | boolean
| *httpMethod* (producer) | Configure the HTTP method to use. The HttpMethod header cannot override this option if set. |  | HttpMethods
| *ignoreResponseBody* (producer) | If this option is true The http producer won't read response body and cache the input stream | false | boolean
| *preserveHostHeader* (producer) | If the option is true HttpProducer will set the Host header to the value contained in the current exchange Host header useful in reverse proxy applications where you want the Host header received by the downstream server to reflect the URL called by the upstream client this allows applications which use the Host header to generate accurate URL's for a proxied service | false | boolean
| *throwExceptionOnFailure* (producer) | Option to disable throwing the HttpOperationFailedException in case of failed responses from the remote server. This allows you to get all responses regardless of the HTTP status code. | true | boolean
| *transferException* (producer) | If enabled and an Exchange failed processing on the consumer side and if the caused Exception was send back serialized in the response as a application/x-java-serialized-object content type. On the producer side the exception will be deserialized and thrown as is instead of the HttpOperationFailedException. The caused exception is required to be serialized. This is by default turned off. If you enable this then be aware that Java will deserialize the incoming data from the request to Java and that can be a potential security risk. | false | boolean
| *cookieHandler* (producer) | Configure a cookie handler to maintain a HTTP session |  | CookieHandler
| *okStatusCodeRange* (producer) | The status codes which are considered a success response. The values are inclusive. Multiple ranges can be defined separated by comma e.g. 200-204209301-304. Each range must be a single number or from-to with the dash included. | 200-299 | String
| *urlRewrite* (producer) | *Deprecated* Refers to a custom org.apache.camel.component.http.UrlRewrite which allows you to rewrite urls when you bridge/proxy endpoints. See more details at http://camel.apache.org/urlrewrite.html |  | UrlRewrite
| *httpClientConfigurer* (advanced) | Register a custom configuration strategy for new HttpClient instances created by producers or consumers such as to configure authentication mechanisms etc |  | HttpClientConfigurer
| *httpClientOptions* (advanced) | To configure the HttpClient using the key/values from the Map. |  | Map
| *httpConnectionManager* (advanced) | To use a custom HttpConnectionManager to manage connections |  | HttpConnectionManager
| *httpConnectionManager Options* (advanced) | To configure the HttpConnectionManager using the key/values from the Map. |  | Map
| *mapHttpMessageBody* (advanced) | If this option is true then IN exchange Body of the exchange will be mapped to HTTP body. Setting this to false will avoid the HTTP mapping. | true | boolean
| *mapHttpMessageFormUrl EncodedBody* (advanced) | If this option is true then IN exchange Form Encoded body of the exchange will be mapped to HTTP. Setting this to false will avoid the HTTP Form Encoded body mapping. | true | boolean
| *mapHttpMessageHeaders* (advanced) | If this option is true then IN exchange Headers of the exchange will be mapped to HTTP headers. Setting this to false will avoid the HTTP Headers mapping. | true | boolean
| *synchronous* (advanced) | Sets whether synchronous processing should be strictly used or Camel is allowed to use asynchronous processing (if supported). | false | boolean
| *proxyAuthDomain* (proxy) | Proxy authentication domain to use with NTML |  | String
| *proxyAuthHost* (proxy) | Proxy authentication host |  | String
| *proxyAuthMethod* (proxy) | Proxy authentication method to use |  | String
| *proxyAuthPassword* (proxy) | Proxy authentication password |  | String
| *proxyAuthPort* (proxy) | Proxy authentication port |  | int
| *proxyAuthScheme* (proxy) | Proxy authentication scheme to use |  | String
| *proxyAuthUsername* (proxy) | Proxy authentication username |  | String
| *proxyHost* (proxy) | Proxy hostname to use |  | String
| *proxyPort* (proxy) | Proxy port to use |  | int
| *authDomain* (security) | Authentication domain to use with NTML |  | String
| *authHost* (security) | Authentication host to use with NTML |  | String
| *authMethod* (security) | Authentication methods allowed to use as a comma separated list of values Basic Digest or NTLM. |  | String
| *authMethodPriority* (security) | Which authentication method to prioritize to use either as Basic Digest or NTLM. |  | String
| *authPassword* (security) | Authentication password |  | String
| *authUsername* (security) | Authentication username |  | String
|===
// endpoint options: END






### Message Headers

[width="100%",cols="10%,10%,80%",options="header",]
|=======================================================================
|Name |Type |Description

|`Exchange.HTTP_URI` |`String` |URI to call. Will override existing URI set directly on the endpoint.
This uri is the uri of the http server to call. Its not the same as the
Camel endpoint uri, where you can configure endpoint options such as
security etc. This header does not support that, its only the uri of the
http server.

|`Exchange.HTTP_METHOD` |`String` |HTTP Method / Verb to use (GET/POST/PUT/DELETE/HEAD/OPTIONS/TRACE)

|`Exchange.HTTP_PATH` |`String` |Request URI's path, the header will be used to build the request URI
with the HTTP_URI. *Camel 2.3.0:* If the path is start with "/", http
producer will try to find the relative path based on the
Exchange.HTTP_BASE_URI header or the
exchange.getFromEndpoint().getEndpointUri();

|`Exchange.HTTP_QUERY` |`String` |URI parameters. Will override existing URI parameters set directly on
the endpoint.

|`Exchange.HTTP_RESPONSE_CODE` |`int` |The HTTP response code from the external server. Is 200 for OK.

|`Exchange.HTTP_CHARACTER_ENCODING` |`String` |Character encoding.

|`Exchange.CONTENT_TYPE` |`String` |The HTTP content type. Is set on both the IN and OUT message to provide
a content type, such as `text/html`.

|`Exchange.CONTENT_ENCODING` |`String` |The HTTP content encoding. Is set on both the IN and OUT message to
provide a content encoding, such as `gzip`.

|`Exchange.HTTP_SERVLET_REQUEST` |`HttpServletRequest` |The `HttpServletRequest` object.

|`Exchange.HTTP_SERVLET_RESPONSE` |`HttpServletResponse` |The `HttpServletResponse` object.

|`Exchange.HTTP_PROTOCOL_VERSION` |`String` |*Camel 2.5:* You can set the http protocol version with this header, eg.
"HTTP/1.0". If you didn't specify the header, HttpProducer will use the
default value "HTTP/1.1"
|=======================================================================

The header name above are constants. For the spring DSL you have to use
the value of the constant instead of the name.

### Message Body

Camel will store the HTTP response from the external server on the OUT
body. All headers from the IN message will be copied to the OUT message,
so headers are preserved during routing. Additionally Camel will add the
HTTP response headers as well to the OUT message headers.

### Response code

Camel will handle according to the HTTP response code:

* Response code is in the range 100..299, Camel regards it as a success
response.
* Response code is in the range 300..399, Camel regards it as a
redirection response and will throw a `HttpOperationFailedException`
with the information.
* Response code is 400+, Camel regards it as an external server failure
and will throw a `HttpOperationFailedException` with the information.

*throwExceptionOnFailure*

The option, `throwExceptionOnFailure`, can be set to `false` to prevent
the `HttpOperationFailedException` from being thrown for failed response
codes. This allows you to get any response from the remote server. +
There is a sample below demonstrating this.


### HttpOperationFailedException

This exception contains the following information:

* The HTTP status code
* The HTTP status line (text of the status code)
* Redirect location, if server returned a redirect
* Response body as a `java.lang.String`, if server provided a body as
response

### Which HTTP method will be used

The following algorithm is used to determine what HTTP method should be used: +
 1. Use method provided as endpoint configuration (`httpMethod`). +
 2. Use method provided in header (`Exchange.HTTP_METHOD`). +
 3. `GET` if query string is provided in header. +
 4. `GET` if endpoint is configured with a query string. +
 5. `POST` if there is data to send (body is not `null`). +
 6. `GET` otherwise.

### How to get access to HttpServletRequest and HttpServletResponse

You can get access to these two using the Camel type converter system
using

[source,java]
----------------------------------------------------------------------------------
HttpServletRequest request = exchange.getIn().getBody(HttpServletRequest.class);
HttpServletRequest response = exchange.getIn().getBody(HttpServletResponse.class);
----------------------------------------------------------------------------------

### Using client timeout - SO_TIMEOUT

See the unit test in
http://svn.apache.org/viewvc?view=rev&revision=781775[this link]

### More Examples

### Configuring a Proxy

Java DSL

[source,java]
---------------------------------------------------------------
from("direct:start")
  .to("http://oldhost?proxyHost=www.myproxy.com&proxyPort=80");
---------------------------------------------------------------

There is also support for proxy authentication via the `proxyUsername`
and `proxyPassword` options.

#### Using proxy settings outside of URI

Java DSL

Spring DSL

[source,java]
---------------------------------------------------------------
 context.getProperties().put("http.proxyHost", "172.168.18.9");
 context.getProperties().put("http.proxyPort" "8080");
---------------------------------------------------------------

[source,java]
----------------------------------------------------------------
   <camelContext>
       <properties>
           <property key="http.proxyHost" value="172.168.18.9"/>
           <property key="http.proxyPort" value="8080"/>
      </properties>
   </camelContext>
----------------------------------------------------------------

Options on Endpoint will override options on the context.

### Configuring charset

If you are using `POST` to send data you can configure the `charset`

[source,java]
-------------------------------------------------
setProperty(Exchange.CHARSET_NAME, "iso-8859-1");
-------------------------------------------------

### Sample with scheduled poll

The sample polls the Google homepage every 10 seconds and write the page
to the file `message.html`:

[source,java]
----------------------------------------------------------------------------------------
from("timer://foo?fixedRate=true&delay=0&period=10000")
    .to("http://www.google.com")
    .setHeader(FileComponent.HEADER_FILE_NAME, "message.html").to("file:target/google");
----------------------------------------------------------------------------------------

### Getting the Response Code

You can get the HTTP response code from the HTTP component by getting
the value from the Out message header with
`Exchange.HTTP_RESPONSE_CODE`.

[source,java]
----------------------------------------------------------------------------------------------
   Exchange exchange = template.send("http://www.google.com/search", new Processor() {
            public void process(Exchange exchange) throws Exception {
                exchange.getIn().setHeader(Exchange.HTTP_QUERY, constant("hl=en&q=activemq"));
            }
   });
   Message out = exchange.getOut();
   int responseCode = out.getHeader(Exchange.HTTP_RESPONSE_CODE, Integer.class);
----------------------------------------------------------------------------------------------

### Using `throwExceptionOnFailure=false` to get any response back

In the route below we want to route a message that we
link:content-enricher.html[enrich] with data returned from a remote HTTP
call. As we want any response from the remote server, we set the
`throwExceptionOnFailure` option to `false` so we get any response in
the `AggregationStrategy`. As the code is based on a unit test that
simulates a HTTP status code 404, there is some assertion code etc.

### Disabling Cookies

To disable cookies you can set the HTTP Client to ignore cookies by
adding this URI option: +
 `httpClient.cookiePolicy=ignoreCookies`

### Advanced Usage

If you need more control over the HTTP producer you should use the
`HttpComponent` where you can set various classes to give you custom
behavior.

#### Setting MaxConnectionsPerHost

The link:http.html[HTTP] Component has a
`org.apache.commons.httpclient.HttpConnectionManager` where you can
configure various global configuration for the given component. +
 By global, we mean that any endpoint the component creates has the same
shared `HttpConnectionManager`. So, if we want to set a different value
for the max connection per host, we need to define it on the HTTP
component and *not* on the endpoint URI that we usually use. So here
comes:

First, we define the `http` component in Spring XML. Yes, we use the
same scheme name, `http`, because otherwise Camel will auto-discover and
create the component with default settings. What we need is to overrule
this so we can set our options. In the sample below we set the max
connection to 5 instead of the default of 2.

And then we can just use it as we normally do in our routes:

#### Using preemptive authentication

An end user reported that he had problem with authenticating with HTTPS.
The problem was eventually resolved when he discovered the HTTPS server
did not return a HTTP code 401 Authorization Required. The solution was
to set the following URI option:
`httpClient.authenticationPreemptive=true`

#### Accepting self signed certificates from remote server

See this
http://www.nabble.com/Using-HTTPS-in-camel-http-when-remote-side-has-self-signed-cert-td25916878.html[link]
from a mailing list discussion with some code to outline how to do this
with the Apache Commons HTTP API.

#### Setting up SSL for HTTP Client

[[HTTP-UsingtheJSSEConfigurationUtility]]
Using the JSSE Configuration Utility

As of Camel 2.8, the HTTP4 component supports SSL/TLS configuration
through the link:camel-configuration-utilities.html[Camel JSSE
Configuration Utility].  This utility greatly decreases the amount of
component specific code you need to write and is configurable at the
endpoint and component levels.  The following examples demonstrate how
to use the utility with the HTTP4 component.

The version of the Apache HTTP client used in this component resolves
SSL/TLS information from a global "protocol" registry.  This component
provides an implementation,
`org.apache.camel.component.http.SSLContextParametersSecureProtocolSocketFactory`,
of the HTTP client's protocol socket factory in order to support the use
of the Camel JSSE Configuration utility.  The following example
demonstrates how to configure the protocol registry and use the
registered protocol information in a route.

[source,java]
----------------------------------------------------------------
KeyStoreParameters ksp = new KeyStoreParameters();
ksp.setResource("/users/home/server/keystore.jks");
ksp.setPassword("keystorePassword");

KeyManagersParameters kmp = new KeyManagersParameters();
kmp.setKeyStore(ksp);
kmp.setKeyPassword("keyPassword");

SSLContextParameters scp = new SSLContextParameters();
scp.setKeyManagers(kmp);

ProtocolSocketFactory factory =
    new SSLContextParametersSecureProtocolSocketFactory(scp);

Protocol.registerProtocol("https",
        new Protocol(
        "https",
        factory,
        443));

from("direct:start")
        .to("https://mail.google.com/mail/").to("mock:results");
----------------------------------------------------------------

[[HTTP-ConfiguringApacheHTTPClientDirectly]]
Configuring Apache HTTP Client Directly

Basically camel-http component is built on the top of Apache HTTP
client, and you can implement a custom
`org.apache.camel.component.http.HttpClientConfigurer` to do some
configuration on the http client if you need full control of it.

However if you _just_ want to specify the keystore and truststore you
can do this with Apache HTTP `HttpClientConfigurer`, for example:

[source,java]
----------------------------------------------------------------------------
Protocol authhttps = new Protocol("https", new AuthSSLProtocolSocketFactory(
  new URL("file:my.keystore"), "mypassword",
  new URL("file:my.truststore"), "mypassword"), 443);

Protocol.registerProtocol("https", authhttps);
----------------------------------------------------------------------------

And then you need to create a class that implements
`HttpClientConfigurer`, and registers https protocol providing a
keystore or truststore per example above. Then, from your camel route
builder class you can hook it up like so:

[source,java]
-------------------------------------------------------------------------------------
HttpComponent httpComponent = getContext().getComponent("http", HttpComponent.class);
httpComponent.setHttpClientConfigurer(new MyHttpClientConfigurer());
-------------------------------------------------------------------------------------

If you are doing this using the Spring DSL, you can specify your
`HttpClientConfigurer` using the URI. For example:

[source,java]
-------------------------------------------------------------------------------------------
<bean id="myHttpClientConfigurer"
 class="my.https.HttpClientConfigurer">
</bean>

<to uri="https://myhostname.com:443/myURL?httpClientConfigurerRef=myHttpClientConfigurer"/>
-------------------------------------------------------------------------------------------

As long as you implement the HttpClientConfigurer and configure your
keystore and truststore as described above, it will work fine.

### See Also

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]

* link:jetty.html[Jetty]
