[[ref-component]]
= Ref Component
:docTitle: Ref
:artifactId: camel-ref
:description: Route messages to an endpoint looked up dynamically by name in the Camel Registry.
:since: 1.2
:supportLevel: Stable
:component-header: Both producer and consumer are supported
:core:
include::{cq-version}@camel-quarkus:ROOT:partial$reference/components/ref.adoc[opts=optional]

*Since Camel {since}*

*{component-header}*

The Ref component is used for lookup of existing endpoints bound in
the Registry.

== URI format

----
ref:someName[?options]
----

Where *someName* is the name of an endpoint in the
Registry (usually, but not always, the Spring
registry). If you are using the Spring registry, `someName` would be the
bean ID of an endpoint in the Spring registry.

// component options: START
// component options: END
// endpoint options: START
// endpoint options: END


== Runtime lookup

This component can be used when you need dynamic discovery of endpoints
in the Registry where you can compute the URI at
runtime. Then you can look up the endpoint using the following code:

[source,java]
----
// lookup the endpoint
String myEndpointRef = "bigspenderOrder";
Endpoint endpoint = context.getEndpoint("ref:" + myEndpointRef);

Producer producer = endpoint.createProducer();
Exchange exchange = producer.createExchange();
exchange.getIn().setBody(payloadToSend);
// send the exchange
producer.process(exchange);
----

And you could have a list of endpoints defined in the
Registry such as:

[source,xml]
----
<camelContext id="camel" xmlns="http://activemq.apache.org/camel/schema/spring">
    <endpoint id="normalOrder" uri="activemq:order.slow"/>
    <endpoint id="bigspenderOrder" uri="activemq:order.high"/>
</camelContext>
----

== Sample

In the sample below we use the `ref:` in the URI to reference the
endpoint with the spring ID, `endpoint2`:

You could, of course, have used the `ref` attribute instead:

[source,xml]
----
<to uri="ref:endpoint2"/>
----

Which is the more common way to write it.

include::{page-component-version}@camel-spring-boot::page$ref-starter.adoc[]
