= WhatsApp Component
:doctitle: WhatsApp
:shortname: whatsapp
:artifactid: camel-whatsapp
:description: Send messages to WhatsApp.
:since: 3.19
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported

*Since Camel {since}*

*{component-header}*

The WhatsApp component provides access to the https://developers.facebook.com/docs/whatsapp/cloud-api[WhatsApp Cloud API].
It allows a Camel-based application to send messages using a cloud-hosted version of the WhatsApp Business Platform.

Before using this component, you have to set up Developer Assets and Platform Access, following the instructions at the
https://developers.facebook.com/docs/whatsapp/cloud-api/get-started#set-up-developer-assets[Register WhatsApp Business Cloud API account].
Once the account is set up,
you can navigate to https://developers.facebook.com/apps/?show_reminder=true[Meta for Developers Apps],
to access to the WhatsApp dashboard.
There you can get the **authorization token**, **phone number id**,
and you can add **recipient phone numbers**, these parameters are mandatory to use the component.=

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-whatsapp</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

== URI format

----------------------------------------------------
whatsapp:type[?options]
----------------------------------------------------



// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END
// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

== Usage

The WhatsApp component supports only producer endpoints.

== Producer Example

The following is a basic example of how to send a message to a WhatsApp chat through the
Business Cloud API.

in Java DSL

[source,java]
---------------------------------------------------------
from("direct:start")
	.process(exchange -> {
		 TextMessageRequest request = new TextMessageRequest();
		 request.setTo(insertYourRecipientPhoneNumberHere);
		 request.setText(new TextMessage());
		 request.getText().setBody("This is an auto-generated message from Camel \uD83D\uDC2B");
        
		 exchange.getIn().setBody(request);
	})
	.to("whatsapp:123456789:insertYourPhoneNumberIdHere?authorizationToken=123456789:insertYourAuthorizationTokenHere");
---------------------------------------------------------
For more information you can refer to https://developers.facebook.com/docs/whatsapp/cloud-api/reference[Cloud API Reference], Supported API are: https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages[Messages] and https://developers.facebook.com/docs/whatsapp/cloud-api/reference/media[Media]

== Webhook Mode

The Whatsapp component supports usage in the *webhook mode* using the *camel-webhook* component.

To enable webhook mode, users need first to add a REST implementation to their application.
Maven users, for example, can add *netty-http* to their `pom.xml` file:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-netty-http</artifactId>
</dependency>
------------------------------------------------------------

Once done, you need to prepend the webhook URI to the whatsapp URI you want to use.

In Java DSL:

[source,java]
---------------------------------------------------------
fromF("webhook:whatsapp:%s?authorizationToken=%s&webhookVerifyToken=%s", "<phoneNumberId>", "<AuthorizationToken>", "<webhookVerifyToken>").log("${body}")
---------------------------------------------------------

You can follow the
https://developers.facebook.com/docs/whatsapp/cloud-api/guides/set-up-webhooks[set up webhooks guide]
to enable and configure the webhook.
The webhook component will expose an endpoint that can be used into the whatsapp administration console.

Refer to the xref:webhook-component.adoc[camel-webhook component] documentation for instructions on how to set it.
