== Hessian DataFormat (deprecated)

*Available as of Camel version 2.17*

Hessian is Data Format for marshalling and unmarshalling messages using Caucho's Hessian format.

If you want to use Hessian Data Format from Maven, add the following dependency to your `pom.xml`:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-hessian</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

### Options

// dataformat options: START
The Hessian dataformat supports 4 options which are listed below.



[width="100%",cols="2s,1m,1m,6",options="header"]
|===
| Name | Default | Java Type | Description
| whitelistEnabled | true | Boolean | Define if Whitelist feature is enabled or not
| allowedUnmarshallObjects |  | String | Define the allowed objects to be unmarshalled
| deniedUnmarshallObjects |  | String | Define the denied objects to be unmarshalled
| contentTypeHeader | false | Boolean | Whether the data format should set the Content-Type header with the type from the data format if the data format is capable of doing so. For example application/xml for data formats marshalling to XML or application/json for data formats marshalling to JSon etc.
|===
// dataformat options: END

### Using the Hessian data format in Java DSL

[source,java]
--------------------------------------------------------------------------------
    from("direct:in")
        .marshal().hessian();
--------------------------------------------------------------------------------

### Using the Hessian data format in Spring DSL

[source,xml]
--------------------------------------------------------------------------------
    <camelContext id="camel" xmlns="http://camel.apache.org/schema/spring">
        <route>
            <from uri="direct:in"/>
            <marshal ref="hessian"/>
        </route>
    </camelContext>
--------------------------------------------------------------------------------
