--
-- Licensed to the Apache Software Foundation (ASF) under one or more
-- contributor license agreements.  See the NOTICE file distributed with
-- this work for additional information regarding copyright ownership.
-- The ASF licenses this file to You under the Apache License, Version 2.0
-- (the "License"); you may not use this file except in compliance with
-- the License.  You may obtain a copy of the License at
--
--      http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-- A valid stored-procedure template. Referenced only so that, before the fix, a message body of
-- "classpath:sql/bodyTemplateResource.sql" would have been dereferenced, loaded and executed. After the fix the
-- body is used verbatim as the template text and never resolved as a resource.
SUBNUMBERS(INTEGER :#num1,INTEGER :#num2,OUT INTEGER resultofsum)
