[[BeanIntegration-BeanIntegration]]
= Bean Integration

Camel supports the integration of beans and POJOs in a number of ways.

[[BeanIntegration-Annotations]]
== Annotations

If a bean is defined in Spring XML or scanned using
the Spring component scanning mechanism and a *<camelContext>* is used
or a `CamelBeanPostProcessor` then we process a number of Camel
annotations to do various things such as injecting resources or
producing, consuming or routing messages.

The following annotations is supported and inject by Camel's
`CamelBeanPostProcessor`

[width="100%",cols="10%,90%",options="header",]
|=======================================================================
|Annotation |Description
|`@EndpointInject` |To inject an endpoint, see more details at xref:pojo-producing.adoc[POJO Producing].
|`@BeanInject` |To inject a bean obtained from the Registry. See xref:bean-injection.adoc[Bean Injection].
|`@BeanConfigInject` |To inject a configuration bean obtained from the Registry. The bean is a POJO that represents
a set of configuration options, which is automatic configured with values loaded via Camel xref:latest@manual::using-propertyplaceholder.adoc[Property Placeholders].
|`@PropertyInject` |To inject a value using property placeholder.
|`@Produce` |To inject a producer to send message to an endpoint. See xref:pojo-producing.adoc[POJO Producing].
|`@Consume` |To inject a consumer on a method. See xref:pojo-consuming.adoc[POJO Consuming].
|`@BindToRegistry` |Used for binding a bean to the registry.
  If no name is specified then the bean will have its name auto computed based on the class name,
 field name, or method name where the annotation is configured.
|`@DeferredContextBinding` | Used to indicate that if the target type is `CamelContextAware` then the `CamelContext` is deferred and injected later; after the bootstrap of Camel so the `CamelContext` is ready for use.
|=======================================================================

See more details at:

* xref:pojo-consuming.adoc[POJO Consuming] to consume and possibly route messages from Camel
* xref:pojo-producing.adoc[POJO Producing] to make it easy to produce camel messages from your POJOs
* `@DynamicRouter` Annotation for creating a xref:{eip-vc}:eips:dynamicRouter-eip.adoc[Dynamic Router] from a POJO method
* `@RecipientList` Annotation for creating a xref:{eip-vc}:eips:recipientList-eip.adoc[Recipient List] from a POJO method
* `@RoutingSlip` Annotation for creating a xref:{eip-vc}:eips:routingSlip-eip.adoc[Routing Slip] for a POJO method
* xref:bean-injection.adoc[Bean Injection] to inject Camel related resources into your POJOs
* xref:using-exchange-pattern-annotations.adoc[Using Exchange Pattern Annotations]
  describes how the pattern annotations can be used to change
  the behaviour of method invocations with Spring Remoting or POJO Producing

*Example*

See the https://github.com/apache/camel-examples/tree/master/examples/camel-example-pojo-messaging[POJO Messaging Example]
for how to use the annotations for routing and messaging.

[[BeanIntegration-BeanComponent]]
== Bean Component

The xref:components::bean-component.adoc[Bean] component allows one to invoke a particular
method. Alternately the xref:components::bean-component.adoc[Bean] component supports the
creation of a proxy via `ProxyHelper` to a Java interface; which allows hiding sending data
to the endpoint via an interface. See more at xref:hiding-middleware.adoc[Hiding Middleware].

