= Apache Camel 4.x Upgrade Guide

This document is for helping you upgrade your Apache Camel application
from Camel 4.x to 4.y. For example if you are upgrading Camel 4.0 to 4.2, then you should follow the guides
from both 4.0 to 4.1 and 4.1 to 4.2.

== Upgrading Camel 4.0 to 4.1

=== camel-aws2-step-functions

The following Message Headers of `camel-aws2-step-functions` component have been renamed to follow standard camel naming convention.

[cols="1,1"]
|===
|Old Name|New Name

|CamelAwsStateMachineOperation
|CamelAwsStepFunctionsOperation

|CamelAwsStateMachinesMaxResults
|CamelAwsStepFunctionsStateMachinesMaxResults

|CamelAwsStepFunctionsStateMachineActivityName
|CamelAwsStepFunctionsActivityName

|CamelAwsStepFunctionsStateMachineActivityArn
|CamelAwsStepFunctionsActivityArn

|CamelAwsStateMachineActivitiesMaxResults
|CamelAwsStepFunctionsActivitiesMaxResults

|CamelAwsStateMachineExecutionArn
|CamelAwsStepFunctionsExecutionArn

|CamelAwsStateMachineExecutionName
|CamelAwsStepFunctionsExecutionName

|CamelAwsStateMachineExecutionInput
|CamelAwsStepFunctionsExecutionInput

|CamelAwsStateMachineExecutionTraceHeader
|CamelAwsStepFunctionsExecutionTraceHeader

|CamelAwsStateMachineExecutionHistoryMaxResults
|CamelAwsStepFunctionsExecutionHistoryMaxResults

|CamelAwsStateMachineExecutionHistoryIncludeExecutionData
|CamelAwsStepFunctionsExecutionHistoryIncludeExecutionData

|CamelAwsStateMachineExecutionHistoryReverseOrder
|CamelAwsStepFunctionsExecutionHistoryReverseOrder

|CamelAwsStateMachineExecutionMaxResults
|CamelAwsStepFunctionsExecutionMaxResults
|===

This is applicable only if literal constant headers are used such as `CamelAwsStateMachinesMaxResults`. If the headers are used from StepFunctions2Constants Interface like StepFunctions2Constants.STATE_MACHINES_MAX_RESULTS , then there is no change;

For Example before

----
from("direct:listActivities")
  .setHeader("CamelAwsStepFunctionsActivitiesMaxResults",5)
   .to("aws2-step-functions://test?awsSfnClient=#awsSfnClient&operation=listActivities")
----

Should be changed to

----
from("direct:listActivities")
  .setHeader("CamelAwsStepFunctionsActivitiesMaxResults",5)
    .to("aws2-step-functions://test?awsSfnClient=#awsSfnClient&operation=listActivities")
----

