= Apache Camel 4.x Upgrade Guide

This document is for helping you upgrade your Apache Camel application
from Camel 4.x to 4.y. For example, if you are upgrading Camel 4.0 to 4.2, then you should follow the guides
from both 4.0 to 4.1 and 4.1 to 4.2.

[NOTE]
====
https://github.com/apache/camel-upgrade-recipes/[The Camel Upgrade Recipes project] provides automated assistance for some common migration tasks.
Note that manual migration is still required.
See the xref:camel-upgrade-recipes-tool.adoc[documentation] page for details.
====

== Upgrading Camel 4.19 to 4.20

=== camel-pulsar

The Apache Pulsar client library has been upgraded from 4.1.3 to 4.2.0.

Pulsar 4.2.0 removes support for V1 topic names via https://github.com/apache/pulsar/pull/25304[PIP-457].
Topic names must now use the V2 format (`persistent://tenant/namespace/topic`) with exactly three path
segments after the scheme. The V1 format (`persistent://tenant/cluster/namespace/topic`) with four path
segments is no longer accepted and will result in an `InvalidTopicNameException`.

If your Camel routes use topic URIs with extra `/` characters in the topic name portion
(e.g., `pulsar:persistent://public/default/my-topic/sub-path`), you must replace the extra `/` with
another separator such as `-` (e.g., `pulsar:persistent://public/default/my-topic-sub-path`).

=== camel-telemetry

The telemetry API has been enhanced to support proper span type classification through the introduction
of the `SpanKind` enum. This affects custom implementations of telemetry tracers and span decorators.

==== SpanKind API Changes

The `SpanLifecycleManager.create()` method signature has been updated to accept a `SpanKind` parameter:

Before:
[source,java]
----
Span create(Exchange exchange, String spanName);
----

After:
[source,java]
----
Span create(Exchange exchange, String spanName, SpanKind kind);
----

==== Impact on Custom Implementations

If you have implemented custom tracer or span decorator classes, you need to update them:

**Custom Tracer Implementations**

If you implemented the `org.apache.camel.telemetry.Tracer` interface, update your `createSpan()` method:

Before:
[source,java]
----
@Override
public Span createSpan(Exchange exchange, String spanName) {
    return spanLifecycleManager.create(exchange, spanName);
}
----

After:
[source,java]
----
@Override
public Span createSpan(Exchange exchange, String spanName, SpanKind kind) {
    return spanLifecycleManager.create(exchange, spanName, kind);
}
----

**Custom SpanDecorator Implementations**

If you implemented custom `SpanDecorator` classes, you must now provide span kind information by implementing
the new `getSpanKind()` method:

[source,java]
----
@Override
public SpanKind getSpanKind() {
    // Return appropriate span kind based on your component's behavior:
    // - CLIENT: for outbound calls to remote services
    // - SERVER: for handling incoming requests
    // - PRODUCER: for sending messages/data to remote systems
    // - CONSUMER: for receiving messages/data from remote systems
    // - INTERNAL: for internal operations with no remote interaction
    return SpanKind.PRODUCER;
}
----

==== MockTracer Test Utilities

If you use `MockTracer` in tests, update calls to `createSpan()`:

Before:
[source,java]
----
mockTracer.createSpan(exchange, "test-span");
----

After:
[source,java]
----
mockTracer.createSpan(exchange, "test-span", SpanKind.INTERNAL);
----
