= Apache Camel 3.x Upgrade Guide

This document is for helping you upgrade your Apache Camel application
from Camel 3.x to 3.y. For example if you are upgrading Camel 3.0 to 3.2, then you should follow the guides
from both 3.0 to 3.1 and 3.1 to 3.2.

== Upgrading Camel 3.6 to 3.7

=== AdviceWith

Advice routes moved the `adviceWith` method from `org.apache.camel.reifier.RouteReifier` to `org.apache.camel.builder.AdviceWith`.
Also `adviceWith` methods on `org.apache.camel.builder.AdviceWithRouteBuilder` is deprecated in favour
of using methods on `org.apache.camel.builder.AdviceWith`.

=== API changes

These internal classes has been moved to locations that better suit where other similar processors are located.

The class `org.apache.camel.impl.validator.ProcessorValidator` moved to `org.apache.camel.processor.validator.ProcessorValidator`.
The class `org.apache.camel.impl.transformer.ProcessorTransformer` moved to `org.apache.camel.processor.transformer.ProcessorTransformer`.
The class `org.apache.camel.impl.transformer.DataFormatTransformer` moved to `org.apache.camel.processor.transformer.DataFormatTransformer`.
The class `org.apache.camel.impl.validator.ValidatorKey` moved to `org.apache.camel.impl.engine.ValidatorKey`.
The class `org.apache.camel.impl.transformer.TransformerKey` moved to `org.apache.camel.impl.engine.TransformerKey`.

And the class `org.apache.camel.impl.DefaultExecutorServiceManager` is moved from `camel-core-engine` JAR to
`org.apache.camel.impl.engine.DefaultExecutorServiceManager` in the `camel-base` JAR.

=== toD EIP

Support for using multiple languages in the toD EIP has been removed as it was a rare feature in use, and is causing some
problems for maintenance. toD uses simple language by default, but an alternative language can still be specified.

=== camel-couchbase

The original URI path has been changed, now the bucket part is simply a required option and it's not part of the URI anymore.

=== camel-file-watch

The event type header is no more an enum, but it is now the explicit event as a `String` value.

=== camel-leveldb

Component uses different serialization mechanism, which is not backwards compatible with the original one.
For full compatibility use camel-leveldb-legacy component. (legacy component will be removed in the future)

