= Apache Camel 4.x Upgrade Guide

This document is for helping you upgrade your Apache Camel application
from Camel 4.x to 4.y. For example, if you are upgrading Camel 4.0 to 4.2, then you should follow the guides
from both 4.0 to 4.1 and 4.1 to 4.2.

== Upgrading Camel 4.9 to 4.10

=== camel-jgroups

The cluster lock has been removed as it has been removed in JGroups 5.4 onwards, and it was
not recommended to be used in older JGroups releases. You can use another Camel component such as
`camel-infinispan` that has cluster locking.

The `camel-jgroups-cluster-service-starter` in Camel Spring Boot has been removed.

=== camel-jbang

The camel-jbang commands for `camel-k` has been removed.

=== camel-mina

If using object codec, then you should configure the `objectCodecPattern` configuration to specify
which java classes (FQN) to allow for Object serialization. You can use `*` to accept all patterns.

=== camel-google-pubsub-lite

The component `camel-google-pubsub-lite` has been deprecated following the deprecation of the corresponding service by Google Cloud Platform.

Google recommends migrating your Pub/Sub Lite service to either Google Cloud Managed Service for Apache Kafka or Google Cloud Pub/Sub. Depending on your choice, you should use `camel-kafka` or `camel-google-pubsub component`, respectively.

== camel-spring-boot

The `camel-k-starter` has been removed.

=== camel-tracing

We have deprecated the setting of MDC `trace_id` and `span_id` in favour of implementation specific feature. You need to check the specific tracing/telemetry component configuration to learn how to switch from the deprecated configuration to the new one. Most of the time you will need to remove the `camel.main.use-mdc-logging` Camel property (or set it to `false`) and add dependencies and configuration settings to enable the specific component instrumentation.
