= Apache Camel 3.x Upgrade Guide

This document is for helping you upgrade your Apache Camel application
from Camel 3.x to 3.y. For example if you are upgrading Camel 3.0 to 3.2, then you should follow the guides
from both 3.0 to 3.1 and 3.1 to 3.2.

== Upgrading Camel 3.15 to 3.16

=== camel-core

Change the default from `Override` to `Ignore` in the `TypeConverterExists` option,
and the TypeConverterExistsLoggingLevel from `WARN` to `DEBUG`.

Previously when Camel detected a duplicate type converter during startup, Camel would
override the existing converter and log a WARN. A more correct behaviour would be
to keep the existing and ignore the duplicate.

==== Saga EIP

Removed the deprecated `timeoutInMilliseconds` option, use `timeout` instead.

In the `<option>` the `optionName` is renamed to `key`. When using XML DSL then this is affected as follows:

[source,xml]
----
<saga sagaServiceRef="mySagaService">
    <compensation uri="mock:compensation"/>
    <completion uri="mock:completion"/>
    <option optionName="myOptionKey">
        <constant>myOptionValue</constant>
    </option>
    <option optionName="myOptionKey2">
        <constant>myOptionValue2</constant>
    </option>
</saga>
----

To:

[source,xml]
----
<saga sagaServiceRef="mySagaService">
    <compensation uri="mock:compensation"/>
    <completion uri="mock:completion"/>
    <option key="myOptionKey">
        <constant>myOptionValue</constant>
    </option>
    <option key="myOptionKey2">
        <constant>myOptionValue2</constant>
    </option>
</saga>
----

==== WireTap EIP

Removed the _new message_ mode as this functionality is better done by using onPrepare processor in copy mode.

=== camel-health

The `HealthCheck` API has been simplified and removed the following configurations:

- interval
- success threshold
- failure threshold

These options would complicate health checks as they affect the outcome of health checks.
It is better the checks always execute and the responsibility of the monitoring systems
how to deal with interval between checks and thresholds.

Removed the option to disable context health check as it should always be enabled.

==== Disabling health checks

The configuration for disabling individual health-checks has changed

Before each health-check could be configured and set `enabled=false`. For example
to disable health-checks for route with id `netty` you would do:

[source,properties]
----
camel.health.config[netty].check = routes
camel.health.config[netty].enabled = false
----

With Camel 3.16 onwards you instead specify pattern(s) for health checks to be excluded
from being invoked, which is done in a single configuration:

[source,properties]
----
camel.health.exclude-pattern = netty
----

You can specify multiple patterns (and use wildcards) such as:

[source,properties]
----
camel.health.exclude-pattern = netty,foo,bar*
----

=== camel-main

The option `camel.main.packageScanRouteBuilders` has been renamed to `camel.main.basePackageScan`.

Using configuration classes must now implement the interface `org.apache.camel.main.CamelConfiguration`
and the `configure` method now takes a `CamelContext` as argument.

=== camel-any23

The option `baseURI` is renamed to `baseUri`.

=== camel-testcontainers

This component was deprecated and is removed on this version. Users should migrate to xref:test-infra.adoc[camel-test-infra].

=== camel-testcontainers-junit5

This component was deprecated and is removed on this version. Users should migrate to xref:test-infra.adoc[camel-test-infra].

=== camel-testcontainers-spring

This component was deprecated and is removed on this version. Users should migrate to xref:test-infra.adoc[camel-test-infra].

=== camel-testcontainers-spring-junit5

This component was deprecated and is removed on this version. Users should migrate to xref:test-infra.adoc[camel-test-infra].
