= Apache Camel 4.x Upgrade Guide

This document is for helping you upgrade your Apache Camel application
from Camel 4.x to 4.y. For example, if you are upgrading Camel 4.0 to 4.2, then you should follow the guides
from both 4.0 to 4.1 and 4.1 to 4.2.

== Upgrading Camel 4.3 to 4.4

=== camel-core

Removed the deprecated constructor from the internal class `org.apache.camel.util.StopWatch`. Users of this class are advised to
use the default constructor if necessary.

The method `getCreated` is now deprecated. Access to the time-related information from the exchange should be done via `getClock`.

The `lookup` method in `org.apache.camel.component.properties.PropertiesLookup` now has a 2nd parameter for the default value.

==== WireTap EIP

The copied exchange is no longer having exchange property CORRELATION_ID set that links to the original exchange.
The reason is that this link should only be for EIPs with sub exchanges such as Splitter and Multicast.

==== MDC logging

When using custom MDC keys (need to configure `MDCLoggingKeysPattern`) then these custom keys are cleared at the end of routing.
Also, custom keys is allowed to be changed during routing, using the `MDC.set(myKey, ...)` Java API.

=== camel-main

The route controller configuration has been moved from general main to its own group.
All keys started with `camel.main.routesController` should be renamed to `camel.routecontroller.`, for example
`camel.main.routeControllerBackOffDelay` should be renamed to `camel.routecontroller.backOffDelay`.
And the option `camel.main.routeControllerSuperviseEnabled` has been renamed to `camel.routecontroller.enabled`.

=== camel-azure-cosmosdb

The useDefaultIdentity parameter has been removed in favor of the credentialType parameter. Now user should select between SHARED_ACCOUNT_KEY and AZURE_IDENTITY.
This is part of the effort explained in CAMEL-18590.

=== camel-azure-eventhubs

The credentialType parameter has been introduced with three possible values: AZURE_IDENTITY, CONNECTION_STRING and TOKEN_CREDENTIAL.
With the CONNECTION_STRING mode the user could explicitly set the connectionString parameters or use the sharedAccessName and sharedAccessKey to automatically build the connection string.
With the TOKEN_CREDENTIAL mode the user could pass a TokenCredential instance.
With the AZURE_IDENTITY mode the user will be able to use the Default Azure Credentials Chain.
This is part of the effort explained in CAMEL-18590.

=== camel-azure-servicebus

The credentialType parameter has been introduced with three possible values: AZURE_IDENTITY, CONNECTION_STRING and TOKEN_CREDENTIAL.
With the CONNECTION_STRING mode the user could explicitly set the connectionString parameter.
With the TOKEN_CREDENTIAL mode the user could pass a TokenCredential instance.
With the AZURE_IDENTITY mode the user will be able to use the Default Azure Credentials Chain.
This is part of the effort explained in CAMEL-18590.

=== camel-azure-files

The credentialType parameter has been introduced with three possible values: AZURE_IDENTITY, SHARED_ACCOUNT_KEY and AZURE_SAS.
With the SHARED_ACCOUNT_KEY mode the user could explicitly set the sharedKey parameter.
With the AZURE_IDENTITY mode the user will be able to use the Default Azure Credentials Chain.
With the AZURE_SAS mode the user could explicitly set the token parameter.
This is part of the effort explained in CAMEL-18590.

=== camel-azure-storage-datalake

The useDefaultIdentity parameter has been removed in favor of the credentialType parameter. Now user should select between AZURE_IDENTITY, CLIENT_SECRET, SHARED_KEY_CREDENTIAL, AZURE_SAS and SERVICE_CLIENT_INSTANCE
With the SHARED_KEY_CREDENTIAL mode the user could explicitly set the sharedKey parameter or a SharedKeyCredential instance.
With the AZURE_IDENTITY mode the user will be able to use the Default Azure Credentials Chain.
With the AZURE_SAS mode the user could explicitly set the sasSignature or sasCredential parameter.
With the CLIENT_SECRET mode the user could explicitly set clientId, clientSecret and tenantId or specify a ClientSecretCredential instance.
With the SERVICE_CLIENT_INSTANCE the user could explicity set a serviceClient parameter by passing a DataLakeServiceClient instance.
This is part of the effort explained in CAMEL-18590.

=== camel-azure-storage-queue

The useDefaultIdentity parameter has been removed in favor of the credentialType parameter. Now user should select between AZURE_IDENTITY, SHARED_KEY_CREDENTIAL and SHARED_ACCOUNT_KEY
With the SHARED_KEY_CREDENTIAL mode the user could explicitly set the SharedKeyCredential instance.
With the AZURE_IDENTITY mode the user will be able to use the Default Azure Credentials Chain.
With the SHARED_ACCOUNT_KEY mode the user could explicitly set the accessKey parameter.
This is part of the effort explained in CAMEL-18590.

== Camel Spring Boot

=== Auto Configuration

The route controller configuration has been moved from general main to its own group.
All keys started with `camel.springboot.routesController` should be renamed to `camel.routecontroller.`, for example
`camel.springboot.routeControllerBackOffDelay` should be renamed to `camel.routecontroller.backOffDelay`.
And the option `camel.springboot.routeControllerSuperviseEnabled` has been renamed to `camel.routecontroller.enabled`.
