= Apache Camel 4.x Upgrade Guide

This document is for helping you upgrade your Apache Camel application
from Camel 4.x to 4.y. For example if you are upgrading Camel 4.0 to 4.2, then you should follow the guides
from both 4.0 to 4.1 and 4.1 to 4.2.

== Upgrading Camel 4.2 to 4.3

=== camel-kafka

The behavior for `breakOnFirstError` was altered as numerous issues were fixed. The behavior related to committing 
the offset is now determined by the `CommitManager` that is configured. 

When the default `CommitManager` is used (`NoopCommitManager`) then no commit is performed. The route implementation will
be responsible for managing the offset using `KafkaManualCommit` to manage the retrying of the payload.

When using the `SyncCommitManager` then the offset will be committed so that the payload is continually retried. This was
the behavior described in the documentation.

When using the `AsyncCommitManager` then the offset will be committed so that the payload is continually retried. This was
the behavior described in the documentation.

=== throttle

Throttle now uses the number of concurrent requests as the throttling measure instead of the number of requests
per period.

The `throttle` parameter now specifies the maximum number of concurrent requests,
and there is no longer support for the `timePeriodMillis` option.
