= Apache Camel 4.x Upgrade Guide

This document is for helping you upgrade your Apache Camel application
from Camel 4.x to 4.y. For example, if you are upgrading Camel 4.0 to 4.2, then you should follow the guides
from both 4.0 to 4.1 and 4.1 to 4.2.

[NOTE]
====
https://github.com/apache/camel-upgrade-recipes/[The Camel Upgrade Recipes project] provides automated assistance for some common migration tasks.
Note that manual migration is still required.
See the xref:camel-upgrade-recipes-tool.adoc[documentation] page for details.
====

== Upgrading Camel 4.18 to 4.19

=== camel-core

The WireTap EIP has removed the `pattern` option from its model (not in use) as wiretap always
uses `InOnly` pattern.

=== camel-yaml-io / camel-xml-io

When dumping routes in YAML or XML format via `camel-yaml-io` or `camel-xml-io` then the structure of routes
and all the EIP options now respect the intended order in the model.

For example `id` is always first, and the following attributes are ordered so the most
commonly used at in the top. EIPs such as `circuitBreaker` now has `onFallback` last.

This order is also the same order that UI builders like Camel Karavan and Kaoto do as well.
