= Apache Camel 3.x to 4.0 Migration Guide

This document is intended to help you migrate your Apache Camel applications
from version 3.20 or higher to 4.0. If you are upgrading from an older Camel 3.x release,
such as 3.14, then make sure to read the individual xref:camel-3x-upgrade-guide.adoc[Camel 3.x Upgrade Guide]
to upgrade to the 3.20 release, prior to upgrade to Camel 4.

IMPORTANT: If you are upgrading Camel 4.x to 4.y then use the
xref:camel-4x-upgrade-guide.adoc[Camel 4.x Upgrade Guide].

== Java versions

Camel 4 supports Java 17. Support for Java 11 is dropped.

== Removed Components

The following components has been removed:

[options="header"]
|===
| Component | Alternative component(s)
| camel-activemq                       | camel-jms, camel-sjms, camel-amqp
| camel-any23                          | none
| camel-atmos                          | none
| camel-caffeine-lrucache              | camel-cache, camel-ignite, camel-infinispan
| camel-cdi                            | camel-spring-boot, camel-quarkus
| camel-elasticsearch-rest             | camel-elasticsearch
| camel-gora                           | none
| camel-hbase                          | none
| camel-iota                           | none
| camel-ipfs                           | none
| camel-jbpm                           | none
| camel-jclouds                        | none
| camel-johnzon                        | camel-jackson, camel-fastjson, camel-gson
| camel-microprofile-metrics           | camel-micrometer, camel-opentelemtry
| camel-milo                           | none
| camel-opentracing                    | camel-micrometer, camel-opentelemtry
| camel-optaplanner                    | none
| camel-rabbitmq                       | spring-rabbitmq-component
| camel-rest-swagger                   | camel-openapi-rest
| camel-restdsl-swagger-plugin         | camel-restdsl-openapi-plugin
| camel-resteasy                       | camel-cxf, camel-rest
| camel-spark                          | none
| camel-spring-integration             | none
| camel-swift                          | none
| camel-swagger-java                   | camel-openapi-java
| camel-websocket                      | camel-vertx-websocket
| camel-websocket-jsr356               | camel-vertx-websocket
| camel-vertx-kafka                    | camel-kafka
| camel-xstream                        | camel-jacksonxml
| camel-zipkin                         | camel-micrometer, camel-opentelemtry
|===

== Logging

Camel 4 has upgraded logging facade API `slf4j-api` from 1.7 to 2.0.

== JUnit 4

All the `camel-test` modules that were JUnit 4.x based has been removed. All test modules now use JUnit 5.

== API Changes

We have removed deprecated APIs such as the following.

The `org.apache.camel.ExchangePattern` has removed `InOptionalOut`.
Removed `getEndpointMap()` method from `CamelContext`.

== YAML DSL

The backwards compatible mode Camel 3.14 or older, which allowed to have _steps_ as child to _route_ has been removed.

The old syntax:

[source,yaml]
----
- route:
    from:
      uri: "direct:info"
    steps:
    - log: "message"
----

should be changed to:

[source,yaml]
----
- route:
    from:
      uri: "direct:info"
      steps:
      - log: "message"
----

== Backlog Tracing

The option `backlogTracing=true` now automatic enabled the tracer on startup. The previous behavior
was _surprisingly_ that the tracer was only made available, and had to be manually enabled afterwards.
The old behavior can be archived by setting `backlogTracingStandby=true`.

Move the following class from `org.apache.camel.api.management.mbean.BacklogTracerEventMessage` in `camel-management-api` JAR
to `org.apache.camel.spi.BacklogTracerEventMessage` in `camel-api` JAR.

The `org.apache.camel.impl.debugger.DefaultBacklogTracerEventMessage` has been refactored into an interface `org.apache.camel.spi.BacklogTracerEventMessage`
with some additional details about traced messages. For example Camel now captures a _first_ and _last_ trace
that contains the input and outgoing (if `InOut`) messages.

== XML serialization

The default xml serialization using `ModelToXMLDumper` has been improved and now uses a generated xml
serializer located in the `camel-xml-io` module instead of the JAXB based one from `camel-jaxb`.

== Component changes

=== camel-caffeine

The `keyType` parameter has been removed. The Key for the cache will now be only `String` type. More information in CAMEL-18877.

=== camel-fhir

The underlying `hapi-fhir` library has been upgraded from 4.2.0 to 6.2.4. Only the `Delete` API method has changed and now returns `ca.uhn.fhir.rest.api.MethodOutcome` instead of `org.hl7.fhir.instance.model.api.IBaseOperationOutcome`. See https://hapifhir.io/hapi-fhir/blog/ for a more detailed list of underlying changes (only the hapi-fhir client is used in Camel).

