= Apache Camel 3.x Upgrade Guide

This document is for helping you upgrade your Apache Camel application
from Camel 3.x to 3.y. For example if you are upgrading Camel 3.0 to 3.2, then you should follow the guides
from both 3.0 to 3.1 and 3.1 to 3.2.

== Upgrading Camel 3.11 to 3.12

=== API changes

The method `getComponentNames` and `getLanguageNames` on `CamelContext` has changed to
return `Set<String>` instead of `List<String>`.

The `ThroughputLogger` has changed the return type from `int` to `long` in the `getReceivedCounter` method.

=== Data Formats

The `camel-asn1` data format has renamed the option `clazzName` to `unmarshalType`.
The `camel-avro` data format has renamed the option `collectionTypeName` to `collectionType`.
The `camel-avro` data format has renamed the option `jsonViewTypeName` to `jsonView`.
The `camel-avro` data format has renamed the option `unmarshalTypeName` to `unmarshalType`.
The `camel-cbor` data format has renamed the option `collectionTypeName` to `collectionType`.
The `camel-cbor` data format has renamed the option `unmarshalTypeName` to `unmarshalType`.
The `camel-jacksonxml` data format has renamed the option `collectionTypeName` to `collectionType`.
The `camel-jacksonxml` data format has renamed the option `jsonViewTypeName` to `jsonView`.
The `camel-jacksonxml` data format has renamed the option `unmarshalTypeName` to `unmarshalType`.
The `camel-json` data format has renamed the option `collectionTypeName` to `collectionType`.
The `camel-json` data format has renamed the option `jsonViewTypeName` to `jsonView`.
The `camel-json` data format has renamed the option `unmarshalTypeName` to `unmarshalType`.
The `camel-protobuf` data format has renamed the option `collectionTypeName` to `collectionType`.
The `camel-protobuf` data format has renamed the option `jsonViewTypeName` to `jsonView`.
The `camel-protobuf` data format has renamed the option `unmarshalTypeName` to `unmarshalType`.
The `camel-yaml` data format has renamed the option `unmarshalTypeName` to `unmarshalType`.

=== camel-spark

The `camel-spark` component has been upgraded from Spark 2.x to 3.x.