= Apache Camel 3.x to 4.0 Migration Guide

This document is intended to help you migrate your Apache Camel applications
from version 3.20 or higher to 4.0. If you are upgrading from an older Camel 3.x release,
such as 3.14, then make sure to read the individual xref:camel-3x-upgrade-guide.adoc[Camel 3.x Upgrade Guide]
to upgrade to the 3.20 release, prior to upgrade to Camel 4.

IMPORTANT: If you are upgrading Camel 4.x to 4.y then use the
xref:camel-4x-upgrade-guide.adoc[Camel 4.x Upgrade Guide].

== Java versions

Camel 4 supports Java 17. Support for Java 11 is dropped.

== Removed Components

The following components has been removed:

- camel-activemq
- camel-any23
- camel-atmos
- camel-caffeine-lrucache
- camel-cdi
- camel-elasticsearch-rest
- camel-gora
- camel-hbase
- camel-iota
- camel-ipfs
- camel-jbpm
- camel-jclouds
- camel-johnzon
- camel-microprofile-metrics
- camel-milo
- camel-opentracing
- camel-optaplanner
- camel-rabbitmq
- camel-rest-swagger
- camel-restdsl-swagger-plugin
- camel-resteasy
- camel-spark
- camel-spring-integration
- camel-swift
- camel-swagger-java
- camel-websocket
- camel-websocket-jsr356
- camel-xstream
- camel-zikin

== Logging

Camel 4 has upgraded logging facade API `slf4j-api` from 1.7 to 2.0.

== JUnit 4

All the `camel-test` modules that were JUnit 4.x based has been removed. All test modules now use JUnit 5.

== Backlog Tracing

The option `backlogTracing=true` now automatic enabled the tracer on startup. The previous behavior
was _surprisingly_ that the tracer was only made available, and had to be manually enabled afterwards.
The old behavior can be archived by setting `backlogTracingStandby=true`.

== XML serialization

The default xml serialization using `ModelToXMLDumper` has been improved and now uses a generated xml
serializer located in the `camel-xml-io` module instead of the JAXB based one from `camel-jaxb`.

== Component changes

=== camel-caffeine

The `keyType` parameter has been removed. The Key for the cache will now be only `String` type. More information in CAMEL-18877.

=== camel-fhir

The underlying `hapi-fhir` library has been upgraded from 4.2.0 to 6.2.4. Only the `Delete` API method has changed and now returns `ca.uhn.fhir.rest.api.MethodOutcome` instead of `org.hl7.fhir.instance.model.api.IBaseOperationOutcome`. See https://hapifhir.io/hapi-fhir/blog/ for a more detailed list of underlying changes (only the hapi-fhir client is used in Camel).
