= Apache Camel 3.x Upgrade Guide

This document is for helping you upgrade your Apache Camel application
from Camel 3.x to 3.y. For example if you are upgrading Camel 3.0 to 3.2, then you should follow the guides
from both 3.0 to 3.1 and 3.1 to 3.2.

== Upgrading Camel 3.14 to 3.15

IMPORTANT: Java 8 is no longer supported. Camel 3.15 onwards requires Java 11 or 17.

=== Removed components

The `camel-kamelet-reify` has been removed.

=== API changes

Added `getScheme` method to `org.apache.camel.spi.Resource`.

=== camel-core

Removed the deprecated `Classic` value from `startupSummaryLevel` enums.

=== camel-endpointdsl

The Endpoint DSL is now more type-safe, where previously an option would be declared as `Object` type,
is now declared using its actual type, such as `javax.sql.DataSource`.

Option that are enums is now using the real enum FQN class name, instead of a duplicate enum
class that was embedded inside the Endpoint DSL. For example when using `aws2sq` the
namingStrategy enum is changed from `org.apache.camel.builder.endpoint.dsl.AWS2S3EndpointBuilderFactory`
to `org.apache.camel.component.aws2.s3.stream.AWSS3NamingStrategyEnum` class name.

=== camel-management

The route controller MBeans are moved from `routecontrollers` to the existing `services`
node in the JMX MBean tree.

Removed deprecated operations on `CamelContextMBean` and `CamelRouteMBean`.

=== camel-yaml-dsl

Removed `steps` from `route` because steps should only be configured on `from` making
the DSL consistent and similar to Java DSL.

Before it was possible to do:

[source,yaml]
----
- route:
    id: demo-route
    from:
      uri: "timer:info"
    steps:
      - log: "message"
----

This should correctly be done with `steps` as child of `from`:

[source,yaml]
----
- route:
    id: demo-route
    from:
      uri: "timer:info"
      steps:
        - log: "message"
----

=== camel-karaf

The `camel-endpointdsl` and `camel-componentdsl` is no longer supported on Apache Karaf.
