[[DataFormat-DataFormat]]
= Data Format

Camel supports a pluggable `DataFormat` to allow messages to be marshalled
to and from binary or text formats to support a kind of
xref:{eip-vc}:eips:message-translator.adoc[Message Translator].

== Supported data formats

There are more than 40 different xref:latest@components:dataformats:index.adoc[Data Formats] that
supports formats such as XML, CSV, JSon, YAML, Avro, Protobuf, and many more.

== Unmarshalling

If you receive a message from one of the Camel
xref:component.adoc[Components] such as xref:components::file-component.adoc[File],
xref:components::http-component.adoc[HTTP] or xref:components::jms-component.adoc[JMS] you often want to unmarshal
the payload into some bean so that you can process it using some
xref:bean-integration.adoc[Bean Integration] or perform
xref:predicate.adoc[Predicate] evaluation and so forth. To do this use
the `unmarshal` word in the xref:dsl.adoc[DSL] in Java or the
xref:xml-configuration.adoc[XML DSL].

For example:

[source,java]
----
DataFormat jaxb = new JaxbDataFormat("com.acme.model");

from("activemq:My.Queue").
  unmarshal(jaxb).
  to("mqseries:Another.Queue");
----

The above uses a named DataFormat of `jaxb` which is configured with a
number of Java package names. You can if you prefer use a named
reference to a data format which can then be defined in your
xref:registry.adoc[Registry] such as via your xref:spring.adoc[Spring]
XML file.

== Marshalling

Marshalling is the opposite of unmarshalling, where a bean is marshalled
into some binary or textual format for transmission over some transport
via a Camel xref:component.adoc[Component]. Marshalling is used in the
same way as unmarshalling above; in the xref:dsl.adoc[DSL] you can use a
DataFormat instance, you can configure the DataFormat dynamically using
the DSL or you can refer to a named instance of the format in the
xref:registry.adoc[Registry].

The following example marshals using a
named JAXB data format to perform a kind of
xref:{eip-vc}:eips:message-translator.adoc[Message Translator]:

[source,java]
----
from("file://foo/bar").
  marshal("jaxb").
  to("activemq:Some.Queue");
----

== Example using Spring XML

This example shows how to configure the data type just once and reuse it
on multiple routes:

[source,xml]
----
<camelContext id="camel" xmlns="http://camel.apache.org/schema/spring">
  <dataFormats>
    <jaxb id="myJaxb" prettyPrint="true" contextPath="org.apache.camel.example"/>
  </dataFormats>

  <route>
    <from uri="direct:start"/>
    <marshal>
        <custom ref="myJaxb"/>
    </marshal>
    <to uri="direct:marshalled"/>
  </route>
  <route>
    <from uri="direct:marshalled"/>
    <unmarshal>
        <custom ref="myJaxb"/>
    </unmarshal>
    <to uri="mock:result"/>
  </route>

</camelContext>
----

You can also define reusable data formats as Spring beans:

[source,xml]
----
<bean id="myJaxb" class="org.apache.camel.model.dataformat.JaxbDataFormat">
  <property name="prettyPrint" value="true"/>
  <property name="contextPath" value="org.apache.camel.example"/>
</bean>  
----
