= Examples

Once you have read about xref:getting-started.adoc[Getting Started] and
looked at the xref:components:eips:enterprise-integration-patterns.adoc[Enterprise
Integration Patterns], you might want to try out some examples.


== Walk-throughs

* Walk through the code of a
xref:walk-through-an-example.adoc[beginner's example] so you can
understand how things fit together using the Java xref:dsl.adoc[DSL] to
set up some routes in a simple `main(...)` method.
* Walk through the xref:walk-through-another-example.adoc[Spring XML DSL
example] to look at XML-based routing.

[NOTE]
====
The examples listed below are hosted at Apache. We also offer the
link:/community/articles/[Articles] page as a collection of 3rd-party Camel
material - such as tutorials, blog posts, published articles, videos,
podcasts, presentations, and so forth.

If you have written a Camel-related article, then we are happy to
provide a link to it. You can contact the Camel link:/community/team/[Team] via
our link:/community/mailing-list/[Mailing Lists], or simply post a tweet with
the words "Apache Camel".
====

== Examples

Browse the https://github.com/apache/camel-examples/tree/main/examples#welcome-to-the-apache-camel-examples[camel-examples]
from github where each example is documented with instructions how to run, and are up-to-date.


