= Expressions

Expressions and xref:predicate.adoc[Predicates] can then be used to
create the various xref:components:eips:enterprise-integration-patterns.adoc[Enterprise
Integration Patterns] in the xref:dsl.adoc[DSL] like with the
xref:components:eips:choice-eip.adoc[Content Based Router] EIP, or
xref:components:eips:recipientList-eip.adoc[Recipient List] EIP.

To support dynamic rules Camel supports pluggable
https://www.javadoc.io/doc/org.apache.camel/camel-api/current/org/apache/camel/Expression.html[Expression]
strategies using a variety of different xref:components:languages:index.adoc[Languages].

NOTE: The xref:components:languages:simple-language.adoc[Simple] is often used as predicates and expressions
with the Camel EIPs.

If you are outside the DSL and want to create your own
expressions you can either implement the
https://www.javadoc.io/doc/org.apache.camel/camel-api/current/org/apache/camel/Expression.html[Expression
interface], reuse one of the other builders or try the
https://www.javadoc.io/doc/org.apache.camel/camel-support/current/org/apache/camel/support/builder/ExpressionBuilder.html[ExpressionBuilder
class].

== Expression API

The API for a Camel Expression is defined in the
`org.apache.camel.Expression` interface as shown:
[source,java]
----
public interface Expression {

    /**
     * Returns the value of the expression on the given exchange
     *
     * @param exchange the message exchange on which to evaluate the expression
     * @param type the expected type of the evaluation result
     * @return the value of the expression
     */
    <T> T evaluate(Exchange exchange, Class<T> type);
}
----

A `Expression` is being evaluated to an Object value. This makes expressions so
powerful as this can be used for functions, data mapping, templating, and for low-code users.
