[[GettingStarted-GettingStarted]]
= Getting Started

First you need to Download the Camel distribution;
or you could grab the Source and try
Building it yourself.

Then come back here and you might want to read the following
documentation before continuing:

* Longer xref:book-getting-started.adoc[Getting Started Guide]
* Find out about xref:{eip-vc}:eips:enterprise-integration-patterns.adoc[Enterprise Integration Patterns]
  and how to implement them with Camel
* Review the xref:architecture.adoc[Architecture guide] to see how to build Routes using the xref:java-dsl.adoc[Java DSL]
  or xref:xml-configuration.adoc[XML DSL]

[[GettingStarted-WorkingwithCamelContextsandRouteBuilders]]
== Working with CamelContexts and RouteBuilders

To get started with Camel:

1.  Create a xref:camelcontext.adoc[CamelContext].
2.  Optionally, xref:configuring-camel.adoc[configure components or endpoints].
3.  Add whatever routing rules you wish using the DSL and `RouteBuilder` or using XML DSL.
4.  Start the Camel context.

When your application is closing you may wish to stop the context

When you are ready, why not xref:walk-through-an-example.adoc[Walk through an Example]?
And then continue the walk xref:walk-through-another-example.adoc[Walk through another example].

[[GettingStarted-WorkingwithSpring]]
== Working with Spring

If you use Spring as a Dependency Injection container then please refer
to the Camel Spring documentation.

[[GettingStarted-OtherResources]]
== Other Resources

We strongly suggest that you brew a cup of coffee or tea and take the 30
minutes to read one or more of the following resources:

* http://manning.com/ibsen/chapter1sample.pdf[Camel in Action, Chapter 1
(direct link)] free chapter 1 of the http://www.manning.com/ibsen[Camel
in Action] book. Highly recommended to read to learn what Camel is and
the basic Camel concepts. This is a free chapter you can download
directly as a pdf (about 20 pages) and introduces you to Camel. We have
been told by experience Camel end users they wished this chapter was
available to them when they started learning Camel.

* http://java.dzone.com/articles/open-source-integration-apache[Open
Source Integration with Apache Camel and How Fuse IDE Can Help] by
Jonathan Anstey. Updated article of the
http://architects.dzone.com/articles/apache-camel-integration[Apache
Camel: Integration Nirvana]. Great article to learn what Camel is and
has a good use case example.

* Several of the vendors on the
Commercial Camel Offerings page
also offer various tutorials, webinars, examples, etc.... that may be
useful.

* Articles is a link collection with articles,
blogs, podcasts, presentations and the likes about Camel done by people
from the community.
