[[HTTP4-HTTP4Component]]
HTTP4 Component
~~~~~~~~~~~~~~~

*Available as of Camel 2.3*

The *http4:* component provides HTTP based link:endpoint.html[endpoints]
for calling external HTTP resources (as a client to call external
servers using HTTP).

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-http4</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------


*camel-http4 vs camel-http*

Camel-http4 uses http://hc.apache.org/httpcomponents-client-ga/[Apache
HttpClient 4.x] while camel-http uses
http://hc.apache.org/httpclient-3.x/[Apache HttpClient 3.x].

[[HTTP4-URIformat]]
URI format
^^^^^^^^^^

[source,java]
---------------------------------------------
http4:hostname[:port][/resourceUri][?options]
---------------------------------------------

Will by default use port 80 for HTTP and 443 for HTTPS.

You can append query options to the URI in the following format,
`?option=value&option=value&...`

*camel-http4 vs camel-jetty*

You can only produce to endpoints generated by the HTTP4 component.
Therefore it should never be used as input into your Camel Routes. To
bind/expose an HTTP endpoint via a HTTP server as input to a Camel
route, use the link:jetty.html[Jetty Component] instead.

[[HTTP4-HttpOptions]]
Http4 Component Options
^^^^^^^^^^^^^^^^^^^^^^^


// component options: START
The HTTP4 component supports 13 options which are listed below.



[width="100%",cols="2s,1m,8",options="header"]
|=======================================================================
| Name | Java Type | Description
| httpClientConfigurer | HttpClientConfigurer | To use the custom HttpClientConfigurer to perform configuration of the HttpClient that will be used.
| clientConnectionManager | HttpClientConnectionManager | To use a custom HttpClientConnectionManager to manage connections
| httpBinding | HttpBinding | To use a custom HttpBinding to control the mapping between Camel message and HttpClient.
| httpConfiguration | HttpConfiguration | To use the shared HttpConfiguration as base configuration.
| allowJavaSerializedObject | boolean | Whether to allow java serialization when a request uses context-type=application/x-java-serialized-object This is by default turned off. If you enable this then be aware that Java will deserialize the incoming data from the request to Java and that can be a potential security risk.
| httpContext | HttpContext | To use a custom org.apache.http.protocol.HttpContext when executing requests.
| sslContextParameters | SSLContextParameters | To configure security using SSLContextParameters. Important: Only one instance of org.apache.camel.util.jsse.SSLContextParameters is supported per HttpComponent. If you need to use 2 or more different instances you need to define a new HttpComponent per instance you need.
| x509HostnameVerifier | X509HostnameVerifier | To use a custom X509HostnameVerifier such as org.apache.http.conn.ssl.StrictHostnameVerifier or org.apache.http.conn.ssl.AllowAllHostnameVerifier.
| maxTotalConnections | int | The maximum number of connections.
| connectionsPerRoute | int | The maximum number of connections per route.
| connectionTimeToLive | long | The time for connection to live the time unit is millisecond the default value is always keep alive.
| cookieStore | CookieStore | To use a custom org.apache.http.client.CookieStore. By default the org.apache.http.impl.client.BasicCookieStore is used which is an in-memory only cookie store. Notice if bridgeEndpoint=true then the cookie store is forced to be a noop cookie store as cookie shouldn't be stored as we are just bridging (eg acting as a proxy).
| headerFilterStrategy | HeaderFilterStrategy | To use a custom HeaderFilterStrategy to filter header to and from Camel message.
|=======================================================================
// component options: END





// endpoint options: START
The HTTP4 component supports 30 endpoint options which are listed below:

[width="100%",cols="2s,1,1m,1m,5",options="header"]
|=======================================================================
| Name | Group | Default | Java Type | Description
| httpUri | producer |  | URI | *Required* The url of the HTTP endpoint to call.
| disableStreamCache | common | false | boolean | Determines whether or not the raw input stream from Servlet is cached or not (Camel will read the stream into a in memory/overflow to file Stream caching) cache. By default Camel will cache the Servlet input stream to support reading it multiple times to ensure it Camel can retrieve all data from the stream. However you can set this option to true when you for example need to access the raw stream such as streaming it directly to a file or other persistent store. DefaultHttpBinding will copy the request input stream into a stream cache and put it into message body if this option is false to support reading the stream multiple times. If you use Servlet to bridge/proxy an endpoint then consider enabling this option to improve performance in case you do not need to read the message payload multiple times. The http/http4 producer will by default cache the response body stream. If setting this option to true then the producers will not cache the response body stream but use the response stream as-is as the message body.
| authenticationPreemptive | producer | false | boolean | If this option is true camel-http4 sends preemptive basic authentication to the server.
| authMethodPriority | producer |  | String | Authentication method for proxy either as Basic Digest or NTLM.
| bridgeEndpoint | producer | false | boolean | If the option is true HttpProducer will ignore the Exchange.HTTP_URI header and use the endpoint's URI for request. You may also set the option throwExceptionOnFailure to be false to let the HttpProducer send all the fault response back.
| chunked | producer | true | boolean | If this option is false the Servlet will disable the HTTP streaming and set the content-length header on the response
| clearExpiredCookies | producer | true | boolean | Whether to clear expired cookies before sending the HTTP request. This ensures the cookies store does not keep growing by adding new cookies which is newer removed when they are expired.
| cookieStore | producer |  | CookieStore | To use a custom org.apache.http.client.CookieStore. By default the org.apache.http.impl.client.BasicCookieStore is used which is an in-memory only cookie store. Notice if bridgeEndpoint=true then the cookie store is forced to be a noop cookie store as cookie shouldn't be stored as we are just bridging (eg acting as a proxy).
| copyHeaders | producer | true | boolean | If this option is true then IN exchange headers will be copied to OUT exchange headers according to copy strategy. Setting this to false allows to only include the headers from the HTTP response (not propagating IN headers).
| headerFilterStrategy | producer |  | HeaderFilterStrategy | To use a custom HeaderFilterStrategy to filter header to and from Camel message.
| httpBinding | producer |  | HttpBinding | To use a custom HttpBinding to control the mapping between Camel message and HttpClient.
| ignoreResponseBody | producer | false | boolean | If this option is true The http producer won't read response body and cache the input stream
| okStatusCodeRange | producer | 200-299 | String | The status codes which is considered a success response. The values are inclusive. The range must be defined as from-to with the dash included.
| preserveHostHeader | producer | false | boolean | If the option is true HttpProducer will set the Host header to the value contained in the current exchange Host header useful in reverse proxy applications where you want the Host header received by the downstream server to reflect the URL called by the upstream client this allows applications which use the Host header to generate accurate URL's for a proxied service
| proxyHost | producer |  | String | The proxy host name
| proxyPort | producer |  | int | The proxy port number
| throwExceptionOnFailure | producer | true | boolean | Option to disable throwing the HttpOperationFailedException in case of failed responses from the remote server. This allows you to get all responses regardless of the HTTP status code.
| transferException | producer | false | boolean | If enabled and an Exchange failed processing on the consumer side and if the caused Exception was send back serialized in the response as a application/x-java-serialized-object content type. On the producer side the exception will be deserialized and thrown as is instead of the HttpOperationFailedException. The caused exception is required to be serialized. This is by default turned off. If you enable this then be aware that Java will deserialize the incoming data from the request to Java and that can be a potential security risk.
| urlRewrite | producer (advanced) |  | UrlRewrite | Refers to a custom org.apache.camel.component.http.UrlRewrite which allows you to rewrite urls when you bridge/proxy endpoints. See more details at http://camel.apache.org/urlrewrite.html
| clientBuilder | advanced |  | HttpClientBuilder | Provide access to the http client request parameters used on new RequestConfig instances used by producers or consumers of this endpoint.
| clientConnectionManager | advanced |  | HttpClientConnectionManager | To use a custom HttpClientConnectionManager to manage connections
| exchangePattern | advanced | InOnly | ExchangePattern | Sets the default exchange pattern when creating an exchange
| httpClient | advanced |  | HttpClient | Gets the HttpClient to be used by org.apache.camel.component.http4.HttpProducer
| httpClientConfigurer | advanced |  | HttpClientConfigurer | Register a custom configuration strategy for new HttpClient instances created by producers or consumers such as to configure authentication mechanisms etc
| httpClientOptions | advanced |  | Map | To configure the HttpClient using the key/values from the Map.
| httpContext | advanced |  | HttpContext | To use a custom HttpContext instance
| mapHttpMessageBody | advanced | true | boolean | If this option is true then IN exchange Body of the exchange will be mapped to HTTP body. Setting this to false will avoid the HTTP mapping.
| mapHttpMessageHeaders | advanced | true | boolean | If this option is true then IN exchange Headers of the exchange will be mapped to HTTP headers. Setting this to false will avoid the HTTP Headers mapping.
| synchronous | advanced | false | boolean | Sets whether synchronous processing should be strictly used or Camel is allowed to use asynchronous processing (if supported).
| useSystemProperties | advanced | false | boolean | To use System Properties as fallback for configuration
|=======================================================================
// endpoint options: END




[[HTTP4-MessageHeaders]]
Message Headers
^^^^^^^^^^^^^^^

[width="100%",cols="10%,20%,70%",options="header",]
|=======================================================================
|Name |Type |Description

|`Exchange.HTTP_URI` |`String` |URI to call. Will override existing URI set directly on the endpoint.
This uri is the uri of the http server to call. Its not the same as the
Camel endpoint uri, where you can configure endpoint options such as
security etc. This header does not support that, its only the uri of the
http server.

|`Exchange.HTTP_PATH` |`String` |Request URI's path, the header will be used to build the request URI
with the HTTP_URI.

|`Exchange.HTTP_QUERY` |`String` |URI parameters. Will override existing URI parameters set directly on
the endpoint.

|`Exchange.HTTP_RESPONSE_CODE` |`int` |The HTTP response code from the external server. Is 200 for OK.

|`Exchange.HTTP_RESPONSE_TEXT` | `String` |The HTTP response text from the external server.

|`Exchange.HTTP_CHARACTER_ENCODING` |`String` |Character encoding.

|`Exchange.CONTENT_TYPE` |`String` |The HTTP content type. Is set on both the IN and OUT message to provide
a content type, such as `text/html`.

|`Exchange.CONTENT_ENCODING` |`String` |The HTTP content encoding. Is set on both the IN and OUT message to
provide a content encoding, such as `gzip`.
|=======================================================================

[[HTTP4-MessageBody]]
Message Body
^^^^^^^^^^^^

Camel will store the HTTP response from the external server on the OUT
body. All headers from the IN message will be copied to the OUT message,
so headers are preserved during routing. Additionally Camel will add the
HTTP response headers as well to the OUT message headers.

 


[[HTTP4-UsingSystemProperties]]
Using System Properties
^^^^^^^^^^^^^^^^^^^^^^^

When setting useSystemProperties to true, the HTTP Client will look for
the following System Properties and it will use it:

* ssl.TrustManagerFactory.algorithm
* http://javax.net/[javax.net].ssl.trustStoreType
* http://javax.net/[javax.net].ssl.trustStore
* http://javax.net/[javax.net].ssl.trustStoreProvider
* http://javax.net/[javax.net].ssl.trustStorePassword
* java.home
* ssl.KeyManagerFactory.algorithm
* http://javax.net/[javax.net].ssl.keyStoreType
* http://javax.net/[javax.net].ssl.keyStore
* http://javax.net/[javax.net].ssl.keyStoreProvider
* http://javax.net/[javax.net].ssl.keyStorePassword
* http.proxyHost
* http.proxyPort
* http.nonProxyHosts
* http.keepAlive
* http.maxConnections

[[HTTP4-Responsecode]]
Response code
^^^^^^^^^^^^^

Camel will handle according to the HTTP response code:

* Response code is in the range 100..299, Camel regards it as a success
response.
* Response code is in the range 300..399, Camel regards it as a
redirection response and will throw a `HttpOperationFailedException`
with the information.
* Response code is 400+, Camel regards it as an external server failure
and will throw a `HttpOperationFailedException` with the information.

*throwExceptionOnFailure*
The option, `throwExceptionOnFailure`, can be set to `false` to prevent
the `HttpOperationFailedException` from being thrown for failed response
codes. This allows you to get any response from the remote server. +
There is a sample below demonstrating this.

[[HTTP4-HttpOperationFailedException]]
HttpOperationFailedException
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

This exception contains the following information:

* The HTTP status code
* The HTTP status line (text of the status code)
* Redirect location, if server returned a redirect
* Response body as a `java.lang.String`, if server provided a body as
response

[[HTTP4-CallingusingGETorPOST]]
Calling using GET or POST
^^^^^^^^^^^^^^^^^^^^^^^^^

The following algorithm is used to determine whether the `GET` or `POST`
HTTP method should be used: +
 1. Use method provided in header. +
 2. `GET` if query string is provided in header. +
 3. `GET` if endpoint is configured with a query string. +
 4. `POST` if there is data to send (body is not null). +
 5. `GET` otherwise.

[[HTTP4-HowtogetaccesstoHttpServletRequestandHttpServletResponse]]
How to get access to HttpServletRequest and HttpServletResponse
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

You can get access to these two using the Camel type converter system
using +
 *NOTE* You can get the request and response not just from the processor
after the camel-jetty or camel-cxf endpoint.

[source,java]
----------------------------------------------------------------------------------
HttpServletRequest request = exchange.getIn().getBody(HttpServletRequest.class);
HttpServletRequest response = exchange.getIn().getBody(HttpServletResponse.class);
----------------------------------------------------------------------------------

[[HTTP4-ConfiguringURItocall]]
Configuring URI to call
^^^^^^^^^^^^^^^^^^^^^^^

You can set the HTTP producer's URI directly form the endpoint URI. In
the route below, Camel will call out to the external server, `oldhost`,
using HTTP.

[source,java]
-------------------------------
from("direct:start")
        .to("http4://oldhost");
-------------------------------

And the equivalent Spring sample:

[source,xml]
---------------------------------------------------------------------
<camelContext xmlns="http://activemq.apache.org/camel/schema/spring">
  <route>
    <from uri="direct:start"/>
    <to uri="http4://oldhost"/>
  </route>
</camelContext>
---------------------------------------------------------------------

You can override the HTTP endpoint URI by adding a header with the key,
`Exchange.HTTP_URI`, on the message.

[source,java]
-----------------------------------------------------------
from("direct:start")
  .setHeader(Exchange.HTTP_URI, constant("http://newhost"))
  .to("http4://oldhost");
-----------------------------------------------------------

In the sample above Camel will call the http://newhost despite the
endpoint is configured with http4://oldhost. +
If the http4 endpoint is working in bridge mode, it will ignore the
message header of `Exchange.HTTP_URI`.

[[HTTP4-ConfiguringURIParameters]]
Configuring URI Parameters
^^^^^^^^^^^^^^^^^^^^^^^^^^

The *http* producer supports URI parameters to be sent to the HTTP
server. The URI parameters can either be set directly on the endpoint
URI or as a header with the key `Exchange.HTTP_QUERY` on the message.

[source,java]
------------------------------------------------
from("direct:start")
  .to("http4://oldhost?order=123&detail=short");
------------------------------------------------

Or options provided in a header:

[source,java]
---------------------------------------------------------------------
from("direct:start")
  .setHeader(Exchange.HTTP_QUERY, constant("order=123&detail=short"))
  .to("http4://oldhost");
---------------------------------------------------------------------

[[HTTP4-HowtosetthehttpmethodtotheHTTPproducer]]
How to set the http method (GET/PATCH/POST/PUT/DELETE/HEAD/OPTIONS/TRACE) to the HTTP producer
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

*Using the http PATCH method*

The http PATCH method is supported starting with Camel 2.11.3 / 2.12.1.

The HTTP4 component provides a way to set the HTTP request method by
setting the message header. Here is an example:

[source,java]
-----------------------------------------------------------------------------------------------
from("direct:start")
  .setHeader(Exchange.HTTP_METHOD, constant(org.apache.camel.component.http4.HttpMethods.POST))
  .to("http4://www.google.com")
  .to("mock:results");
-----------------------------------------------------------------------------------------------

The method can be written a bit shorter using the string constants:

[source,java]
-----------------------------------------------
.setHeader("CamelHttpMethod", constant("POST"))
-----------------------------------------------

And the equivalent Spring sample:

[source,xml]
---------------------------------------------------------------------
<camelContext xmlns="http://activemq.apache.org/camel/schema/spring">
  <route>
    <from uri="direct:start"/>
    <setHeader headerName="CamelHttpMethod">
        <constant>POST</constant>
    </setHeader>
    <to uri="http4://www.google.com"/>
    <to uri="mock:results"/>
  </route>
</camelContext>
---------------------------------------------------------------------

[[HTTP4-Usingclienttimeout-SO_TIMEOUT]]
Using client timeout - SO_TIMEOUT
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

See the
https://svn.apache.org/repos/asf/camel/trunk/components/camel-http4/src/test/java/org/apache/camel/component/http4/HttpSOTimeoutTest.java[HttpSOTimeoutTest]
unit test.

*Since Camel 2.13.0*: See the updated
https://github.com/apache/camel/blob/master/components/camel-http4/src/test/java/org/apache/camel/component/http4/HttpSOTimeoutTest.java[HttpSOTimeoutTest]
unit test.

[[HTTP4-ConfiguringaProxy]]
Configuring a Proxy
^^^^^^^^^^^^^^^^^^^

The HTTP4 component provides a way to configure a proxy.

[source,java]
------------------------------------------------------------------------
from("direct:start")
  .to("http4://oldhost?proxyAuthHost=www.myproxy.com&proxyAuthPort=80");
------------------------------------------------------------------------

There is also support for proxy authentication via the
`proxyAuthUsername` and `proxyAuthPassword` options.

[[HTTP4-UsingproxysettingsoutsideofURI]]
Using proxy settings outside of URI
+++++++++++++++++++++++++++++++++++

To avoid System properties conflicts, you can set proxy configuration
only from the CamelContext or URI. +
 Java DSL :

[source,java]
---------------------------------------------------------------
 context.getProperties().put("http.proxyHost", "172.168.18.9");
 context.getProperties().put("http.proxyPort" "8080");
---------------------------------------------------------------

Spring XML

[source,xml]
----------------------------------------------------------------
   <camelContext>
       <properties>
           <property key="http.proxyHost" value="172.168.18.9"/>
           <property key="http.proxyPort" value="8080"/>
      </properties>
   </camelContext>
----------------------------------------------------------------

Camel will first set the settings from Java System or CamelContext
Properties and then the endpoint proxy options if provided. +
 So you can override the system properties with the endpoint options.

Notice in *Camel 2.8* there is also a `http.proxyScheme` property you
can set to explicit configure the scheme to use.

[[HTTP4-Configuringcharset]]
Configuring charset
^^^^^^^^^^^^^^^^^^^

If you are using `POST` to send data you can configure the `charset`
using the `Exchange` property:

[source,java]
----------------------------------------------------------
exchange.setProperty(Exchange.CHARSET_NAME, "ISO-8859-1");
----------------------------------------------------------

[[HTTP4-Samplewithscheduledpoll]]
Sample with scheduled poll
++++++++++++++++++++++++++

This sample polls the Google homepage every 10 seconds and write the
page to the file `message.html`:

[source,java]
------------------------------------------------------------
from("timer://foo?fixedRate=true&delay=0&period=10000")
  .to("http4://www.google.com")
  .setHeader(FileComponent.HEADER_FILE_NAME, "message.html")
  .to("file:target/google");
------------------------------------------------------------

[[HTTP4-URIParametersfromtheendpointURI]]
URI Parameters from the endpoint URI
++++++++++++++++++++++++++++++++++++

In this sample we have the complete URI endpoint that is just what you
would have typed in a web browser. Multiple URI parameters can of course
be set using the `&` character as separator, just as you would in the
web browser. Camel does no tricks here.

[source,java]
-----------------------------------------------------------------
// we query for Camel at the Google page
template.sendBody("http4://www.google.com/search?q=Camel", null);
-----------------------------------------------------------------

[[HTTP4-URIParametersfromtheMessage]]
URI Parameters from the Message
+++++++++++++++++++++++++++++++

[source,java]
------------------------------------------------------------------
Map headers = new HashMap();
headers.put(Exchange.HTTP_QUERY, "q=Camel&lr=lang_en");
// we query for Camel and English language at Google
template.sendBody("http4://www.google.com/search", null, headers);
------------------------------------------------------------------

In the header value above notice that it should *not* be prefixed with
`?` and you can separate parameters as usual with the `&` char.

[[HTTP4-GettingtheResponseCode]]
Getting the Response Code
+++++++++++++++++++++++++

You can get the HTTP response code from the HTTP4 component by getting
the value from the Out message header with
`Exchange.HTTP_RESPONSE_CODE`.

[source,java]
------------------------------------------------------------------------------------
Exchange exchange = template.send("http4://www.google.com/search", new Processor() {
  public void process(Exchange exchange) throws Exception {
    exchange.getIn().setHeader(Exchange.HTTP_QUERY, constant("hl=en&q=activemq"));
  }
});
Message out = exchange.getOut();
int responseCode = out.getHeader(Exchange.HTTP_RESPONSE_CODE, Integer.class);
------------------------------------------------------------------------------------

[[HTTP4-DisablingCookies]]
Disabling Cookies
^^^^^^^^^^^^^^^^^

To disable cookies you can set the HTTP Client to ignore cookies by
adding this URI option: +
 `httpClient.cookiePolicy=ignoreCookies`

[[HTTP4-AdvancedUsage]]
Advanced Usage
^^^^^^^^^^^^^^

If you need more control over the HTTP producer you should use the
`HttpComponent` where you can set various classes to give you custom
behavior.

[[HTTP4-SettingupSSLforHTTPClient]]
Setting up SSL for HTTP Client
++++++++++++++++++++++++++++++

[[HTTP4-UsingtheJSSEConfigurationUtility]]
Using the JSSE Configuration Utility

As of Camel 2.8, the HTTP4 component supports SSL/TLS configuration
through the link:camel-configuration-utilities.html[Camel JSSE
Configuration Utility].  This utility greatly decreases the amount of
component specific code you need to write and is configurable at the
endpoint and component levels.  The following examples demonstrate how
to use the utility with the HTTP4 component.

[[HTTP4-Programmaticconfigurationofthecomponent]]
Programmatic configuration of the component

[source,java]
---------------------------------------------------------------------------------------
KeyStoreParameters ksp = new KeyStoreParameters();
ksp.setResource("/users/home/server/keystore.jks");
ksp.setPassword("keystorePassword");

KeyManagersParameters kmp = new KeyManagersParameters();
kmp.setKeyStore(ksp);
kmp.setKeyPassword("keyPassword");

SSLContextParameters scp = new SSLContextParameters();
scp.setKeyManagers(kmp);

HttpComponent httpComponent = getContext().getComponent("https4", HttpComponent.class);
httpComponent.setSslContextParameters(scp);
---------------------------------------------------------------------------------------

[[HTTP4-SpringDSLbasedconfigurationofendpoint]]
Spring DSL based configuration of endpoint

[source,xml]
--------------------------------------------------------------------------------------
...
  <camel:sslContextParameters
      id="sslContextParameters">
    <camel:keyManagers
        keyPassword="keyPassword">
      <camel:keyStore
          resource="/users/home/server/keystore.jks"
          password="keystorePassword"/>
    </camel:keyManagers>
  </camel:sslContextParameters>...
...
  <to uri="https4://127.0.0.1/mail/?sslContextParametersRef=sslContextParameters"/>...
--------------------------------------------------------------------------------------

[[HTTP4-ConfiguringApacheHTTPClientDirectly]]
Configuring Apache HTTP Client Directly

Basically camel-http4 component is built on the top of
http://hc.apache.org/httpcomponents-client-ga/[Apache HttpClient].
Please refer to
http://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html#d4e537[SSL/TLS
customization] for details or have a look into the
`org.apache.camel.component.http4.HttpsServerTestSupport` unit test base
class. +
 You can also implement a custom
`org.apache.camel.component.http4.HttpClientConfigurer` to do some
configuration on the http client if you need full control of it.

However if you _just_ want to specify the keystore and truststore you
can do this with Apache HTTP `HttpClientConfigurer`, for example:

[source,java]
------------------------------------------------------------------------------------------------------
KeyStore keystore = ...;
KeyStore truststore = ...;

SchemeRegistry registry = new SchemeRegistry();
registry.register(new Scheme("https", 443, new SSLSocketFactory(keystore, "mypassword", truststore)));
------------------------------------------------------------------------------------------------------

And then you need to create a class that implements
`HttpClientConfigurer`, and registers https protocol providing a
keystore or truststore per example above. Then, from your camel route
builder class you can hook it up like so:

[source,java]
--------------------------------------------------------------------------------------
HttpComponent httpComponent = getContext().getComponent("http4", HttpComponent.class);
httpComponent.setHttpClientConfigurer(new MyHttpClientConfigurer());
--------------------------------------------------------------------------------------

If you are doing this using the Spring DSL, you can specify your
`HttpClientConfigurer` using the URI. For example:

[source,xml]
-----------------------------------------------------------------------------------------
<bean id="myHttpClientConfigurer"
 class="my.https.HttpClientConfigurer">
</bean>

<to uri="https4://myhostname.com:443/myURL?httpClientConfigurer=myHttpClientConfigurer"/>
-----------------------------------------------------------------------------------------

As long as you implement the HttpClientConfigurer and configure your
keystore and truststore as described above, it will work fine.

[[HTTP4-UsingHTTPStoauthenticategotchas]]
Using HTTPS to authenticate gotchas

An end user reported that he had problem with authenticating with HTTPS.
The problem was eventually resolved by providing a custom configured
`org.apache.http.protocol.HttpContext`:

* 1. Create a (Spring) factory for HttpContexts:

[source,java]
------------------------------------------------------------------
public class HttpContextFactory {

  private String httpHost = "localhost";
  private String httpPort = 9001;

  private BasicHttpContext httpContext = new BasicHttpContext();
  private BasicAuthCache authCache = new BasicAuthCache();
  private BasicScheme basicAuth = new BasicScheme();

  public HttpContext getObject() {
    authCache.put(new HttpHost(httpHost, httpPort), basicAuth);

    httpContext.setAttribute(ClientContext.AUTH_CACHE, authCache);

    return httpContext;
  }

  // getter and setter
}
------------------------------------------------------------------

* 2. Declare an HttpContext in the Spring application context file:

[source,xml]
---------------------------------------------------------------------------------------
<bean id="myHttpContext" factory-bean="httpContextFactory" factory-method="getObject"/>
---------------------------------------------------------------------------------------

* 3. Reference the context in the http4 URL:

[source,xml]
-----------------------------------------------------------------------
<to uri="https4://myhostname.com:443/myURL?httpContext=myHttpContext"/>
-----------------------------------------------------------------------

[[HTTP4-UsingdifferentSSLContextParameters]]
Using different SSLContextParameters

The link:http4.html[HTTP4] component only support one instance of
`org.apache.camel.util.jsse.SSLContextParameters` per component. If you
need to use 2 or more different instances, then you need to setup
multiple link:http4.html[HTTP4] components as shown below. Where we have
2 components, each using their own instance of `sslContextParameters`
property.

[source,xml]
----------------------------------------------------------------------------
<bean id="http4-foo" class="org.apache.camel.component.http4.HttpComponent">
   <property name="sslContextParameters" ref="sslContextParams1"/>
   <property name="x509HostnameVerifier" ref="hostnameVerifier"/>
</bean>

<bean id="http4-bar" class="org.apache.camel.component.http4.HttpComponent">
   <property name="sslContextParameters" ref="sslContextParams2"/>
   <property name="x509HostnameVerifier" ref="hostnameVerifier"/>
</bean>
----------------------------------------------------------------------------
