[[AsteriskComponent-AsteriskComponent]]
Asterisk Component
~~~~~~~~~~~~~~~~~~~

*Available as of Camel 2.18*

The *asterisk:* component allows you to work easily with an Asterisk PBX Server http://www.asterisk.org/ using https://asterisk-java.org/[asterisk-java]

This component help to interface with http://www.voip-info.org/wiki-Asterisk+manager+API[Asterisk Manager Interface]

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-asterisk</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

[[AsteriskComponent-URIformat]]
URI format
^^^^^^^^^^

[source,java]
-------------------------------------------------------------------------------------------------------------------------
asterisk:name[?options]
-------------------------------------------------------------------------------------------------------------------------

[[AsteriskComponent-Options]]
Options
^^^^^^^

// component options: START
The Asterisk component supports 4 endpoint options which are listed below:

{% raw %}
[width="100%",cols="1,1m,1m,5",options="header"]
|=======================================================================
| Name | Group | Java Type | Description
| hostname | common | String | *Required* This is hostname / ip of Asterisk Server.
| username | common | String | username
| password | common | String | password
| action | producer | AsteriskActionEnum | *Required* Operation to send via AMI
|=======================================================================
{% endraw %}
// endpoint options: END

[[Asterisk-Actions]]
Action
^^^^^^
Supported actions are:

* QUEUE_STATUS, Queue Status
* SIP_PEERS, List SIP Peers
* EXTENSION_STATE, Check Extension Status
