[[Mail-MailComponent]]
Mail Component
~~~~~~~~~~~~~~

The mail component provides access to Email via Spring's Mail support
and the underlying JavaMail system.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-mail</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

WARNING: *Geronimo mail .jar*

We have discovered that the geronimo mail `.jar` (v1.6) has a bug when
polling mails with attachments. It cannot correctly identify the
`Content-Type`. So, if you attach a `.jpeg` file to a mail and you poll
it, the `Content-Type` is resolved as `text/plain` and not as
`image/jpeg`. For that reason, we have added an
`org.apache.camel.component.ContentTypeResolver` SPI interface which
enables you to provide your own implementation and fix this bug by
returning the correct Mime type based on the file name. So if the file
name ends with `jpeg/jpg`, you can return `image/jpeg`.

You can set your custom resolver on the `MailComponent` instance or on
the `MailEndpoint` instance.


TIP: *POP3 or IMAP*
POP3 has some limitations and end users are encouraged to use IMAP if
possible.

INFO: *Using mock-mail for testing*
You can use a mock framework for unit testing, which allows you to test
without the need for a real mail server. However you should remember to
not include the mock-mail when you go into production or other
environments where you need to send mails to a real mail server. Just
the presence of the mock-javamail.jar on the classpath means that it
will kick in and avoid sending the mails.

[[Mail-URIformat]]
URI format
^^^^^^^^^^

Mail endpoints can have one of the following URI formats (for the
protocols, SMTP, POP3, or IMAP, respectively):

[source,java]
---------------------------------------
smtp://[username@]host[:port][?options]
pop3://[username@]host[:port][?options]
imap://[username@]host[:port][?options]
---------------------------------------

The mail component also supports secure variants of these protocols
(layered over SSL). You can enable the secure protocols by adding `s` to
the scheme:

[source,java]
----------------------------------------
smtps://[username@]host[:port][?options]
pop3s://[username@]host[:port][?options]
imaps://[username@]host[:port][?options]
----------------------------------------

You can append query options to the URI in the following format,
`?option=value&option=value&...`

[[Mail-Sampleendpoints]]
Sample endpoints
++++++++++++++++

Typically, you specify a URI with login credentials as follows (taking
SMTP as an example):

[source,java]
------------------------------------------------
smtp://[username@]host[:port][?password=somepwd]
------------------------------------------------

Alternatively, it is possible to specify both the user name and the
password as query options:

[source,java]
-----------------------------------------------------
smtp://host[:port]?password=somepwd&username=someuser
-----------------------------------------------------

For example:

[source,java]
------------------------------------------------------------
smtp://mycompany.mailserver:30?password=tiger&username=scott
------------------------------------------------------------

[[Mail-Components]]
Components
^^^^^^^^^^

- link:imap.html[IMAP]
- link:imaps.html[IMAPs]
- link:pop3.html[POP3s]
- link:pop3s.html[POP3s]
- link:smtp.html[STMP]
- link:smtps.html[SMTPs]

[[Mail-DefaultPortsDefaultports]]
Default ports
+++++++++++++

Default port numbers are supported. If the port number is omitted, Camel
determines the port number to use based on the protocol.

[width="100%",cols="10%,90%",options="header",]
|=======================================================================
|Protocol |Default Port Number

|`SMTP` |`25`

|`SMTPS` |`465`

|`POP3` |`110`

|`POP3S` |`995`

|`IMAP` |`143`

|`IMAPS` |`993`
|=======================================================================

[[Mail-SSLsupport]]
SSL support
^^^^^^^^^^^

The underlying mail framework is responsible for providing SSL support.
 You may either configure SSL/TLS support by completely specifying the
necessary Java Mail API configuration options, or you may provide a
configured SSLContextParameters through the component or endpoint
configuration.

[[Mail-UsingtheJSSEConfigurationUtility]]
Using the JSSE Configuration Utility
++++++++++++++++++++++++++++++++++++

As of *Camel 2.10*, the mail component supports SSL/TLS configuration
through the link:camel-configuration-utilities.html[Camel JSSE
Configuration Utility].  This utility greatly decreases the amount of
component specific code you need to write and is configurable at the
endpoint and component levels.  The following examples demonstrate how
to use the utility with the mail component.

[[Mail-Programmaticconfigurationoftheendpoint]]
Programmatic configuration of the endpoint

[source,java]
----------------------------------------------------------------------------------------------------------------------------------
KeyStoreParameters ksp = new KeyStoreParameters();
ksp.setResource("/users/home/server/truststore.jks");
ksp.setPassword("keystorePassword");
TrustManagersParameters tmp = new TrustManagersParameters();
tmp.setKeyStore(ksp);
SSLContextParameters scp = new SSLContextParameters();
scp.setTrustManagers(tmp);
Registry registry = ...
registry.bind("sslContextParameters", scp);
...
from(...)
&nbsp; &nbsp; .to("smtps://smtp.google.com?username=user@gmail.com&password=password&sslContextParameters=#sslContextParameters");
----------------------------------------------------------------------------------------------------------------------------------

[[Mail-SpringDSLbasedconfigurationofendpoint]]
Spring DSL based configuration of endpoint

[source,xml]
---------------------------------------------------------------------------------------------------------------------------
...
<camel:sslContextParameters id="sslContextParameters">
  <camel:trustManagers>
    <camel:keyStore resource="/users/home/server/truststore.jks" password="keystorePassword"/>
  </camel:trustManagers>
</camel:sslContextParameters>...
...
<to uri="smtps://smtp.google.com?username=user@gmail.com&password=password&sslContextParameters=#sslContextParameters"/>...
---------------------------------------------------------------------------------------------------------------------------

[[Mail-ConfiguringJavaMailDirectly]]
Configuring JavaMail Directly
+++++++++++++++++++++++++++++

Camel uses SUN JavaMail, which only trusts certificates issued by well
known Certificate Authorities (the default JVM trust configuration). If
you issue your own certificates, you have to import the CA certificates
into the JVM's Java trust/key store files, override the default JVM
trust/key store files (see `SSLNOTES.txt` in JavaMail for details).

[[Mail-MailMessageContent]]
Mail Message Content
^^^^^^^^^^^^^^^^^^^^

Camel uses the message exchange's IN body as the
http://java.sun.com/javaee/5/docs/api/javax/mail/internet/MimeMessage.html[MimeMessage]
text content. The body is converted to `String.class`.

Camel copies all of the exchange's IN headers to the
http://java.sun.com/javaee/5/docs/api/javax/mail/internet/MimeMessage.html[MimeMessage]
headers.

The subject of the
http://java.sun.com/javaee/5/docs/api/javax/mail/internet/MimeMessage.html[MimeMessage]
can be configured using a header property on the IN message. The code
below demonstrates this:

The same applies for other MimeMessage headers such as recipients, so
you can use a header property as `To`:

*Since Camel 2.11* When using the MailProducer the send the mail to
server, you should be able to get the message id of the
http://java.sun.com/javaee/5/docs/api/javax/mail/internet/MimeMessage.html[MimeMessage]
with the key `CamelMailMessageId` from the Camel message header.

[[Mail-Headerstakeprecedenceoverpre-configuredrecipients]]
Headers take precedence over pre-configured recipients
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The recipients specified in the message headers always take precedence
over recipients pre-configured in the endpoint URI. The idea is that if
you provide any recipients in the message headers, that is what you get.
The recipients pre-configured in the endpoint URI are treated as a
fallback.

In the sample code below, the email message is sent to
`davsclaus@apache.org`, because it takes precedence over the
pre-configured recipient, `info@mycompany.com`. Any `CC` and `BCC`
settings in the endpoint URI are also ignored and those recipients will
not receive any mail. The choice between headers and pre-configured
settings is all or nothing: the mail component _either_ takes the
recipients exclusively from the headers or exclusively from the
pre-configured settings. It is not possible to mix and match headers and
pre-configured settings.

[source,java]
------------------------------------------------------------------------------------------------------------
        Map<String, Object> headers = new HashMap<String, Object>();
        headers.put("to", "davsclaus@apache.org");

        template.sendBodyAndHeaders("smtp://admin@localhost?to=info@mycompany.com", "Hello World", headers);
------------------------------------------------------------------------------------------------------------

[[Mail-Multiplerecipientsforeasierconfiguration]]
Multiple recipients for easier configuration
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

It is possible to set multiple recipients using a comma-separated or a
semicolon-separated list. This applies both to header settings and to
settings in an endpoint URI. For example:

[source,java]
------------------------------------------------------------------------------------------------
        Map<String, Object> headers = new HashMap<String, Object>();
        headers.put("to", "davsclaus@apache.org ; jstrachan@apache.org ; ningjiang@apache.org");
------------------------------------------------------------------------------------------------

The preceding example uses a semicolon, `;`, as the separator character.

[[Mail-Settingsendernameandemail]]
Setting sender name and email
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

You can specify recipients in the format, `name <email>`, to include
both the name and the email address of the recipient.

For example, you define the following headers on the a
link:message.html[Message]:

[source,java]
---------------------------------------------------------
Map headers = new HashMap();
map.put("To", "Claus Ibsen <davsclaus@apache.org>");
map.put("From", "James Strachan <jstrachan@apache.org>");
map.put("Subject", "Camel is cool");
---------------------------------------------------------

[[Mail-JavaMailAPI(exSUNJavaMail)]]
JavaMail API (ex SUN JavaMail)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

https://java.net/projects/javamail/pages/Home[JavaMail API] is used
under the hood for consuming and producing mails. +
 We encourage end-users to consult these references when using either
POP3 or IMAP protocol. Note particularly that POP3 has a much more
limited set of features than IMAP.

* https://javamail.java.net/nonav/docs/api/com/sun/mail/pop3/package-summary.html[JavaMail
POP3 API]
* https://javamail.java.net/nonav/docs/api/com/sun/mail/imap/package-summary.html[JavaMail
IMAP API]
* And generally about the
https://javamail.java.net/nonav/docs/api/javax/mail/Flags.html[MAIL
Flags]

[[Mail-Samples]]
Samples
^^^^^^^

We start with a simple route that sends the messages received from a JMS
queue as emails. The email account is the `admin` account on
`mymailserver.com`.

[source,java]
-------------------------------------------------------------------------------------
from("jms://queue:subscription").to("smtp://admin@mymailserver.com?password=secret");
-------------------------------------------------------------------------------------

In the next sample, we poll a mailbox for new emails once every minute.
Notice that we use the special `consumer` option for setting the poll
interval, `consumer.delay`, as 60000 milliseconds = 60 seconds.

[source,java]
-------------------------------------------------------
from("imap://admin@mymailserver.com
     password=secret&unseen=true&consumer.delay=60000")
    .to("seda://mails");
-------------------------------------------------------

In this sample we want to send a mail to multiple recipients:

[[Mail-Sendingmailwithattachmentsample]]
Sending mail with attachment sample
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


WARNING: *Attachments are not support by all Camel components*
The _Attachments API_ is based on the Java Activation Framework and is
generally only used by the Mail API. Since many of the other Camel
components do not support attachments, the attachments could potentially
be lost as they propagate along the route. The rule of thumb, therefore,
is to add attachments just before sending a message to the mail
endpoint.


The mail component supports attachments. In the sample below, we send a
mail message containing a plain text message with a logo file
attachment.

[[Mail-SSLsample]]
SSL sample
^^^^^^^^^^

In this sample, we want to poll our Google mail inbox for mails. To
download mail onto a local mail client, Google mail requires you to
enable and configure SSL. This is done by logging into your Google mail
account and changing your settings to allow IMAP access. Google have
extensive documentation on how to do this.

[source,java]
-------------------------------------------------------------------------------------
from("imaps://imap.gmail.com?username=YOUR_USERNAME@gmail.com&password=YOUR_PASSWORD"
    + "&delete=false&unseen=true&consumer.delay=60000").to("log:newmail");
-------------------------------------------------------------------------------------

The preceding route polls the Google mail inbox for new mails once every
minute and logs the received messages to the `newmail` logger
category. +
 Running the sample with `DEBUG` logging enabled, we can monitor the
progress in the logs:

[source,java]
------------------------------------------------------------------------------------------------------------------------------------------------------------------
2008-05-08 06:32:09,640 DEBUG MailConsumer - Connecting to MailStore imaps//imap.gmail.com:993 (SSL enabled), folder=INBOX
2008-05-08 06:32:11,203 DEBUG MailConsumer - Polling mailfolder: imaps//imap.gmail.com:993 (SSL enabled), folder=INBOX
2008-05-08 06:32:11,640 DEBUG MailConsumer - Fetching 1 messages. Total 1 messages.
2008-05-08 06:32:12,171 DEBUG MailConsumer - Processing message: messageNumber=[332], from=[James Bond <007@mi5.co.uk>], to=YOUR_USERNAME@gmail.com], subject=[...
2008-05-08 06:32:12,187 INFO  newmail - Exchange[MailMessage: messageNumber=[332], from=[James Bond <007@mi5.co.uk>], to=YOUR_USERNAME@gmail.com], subject=[...
------------------------------------------------------------------------------------------------------------------------------------------------------------------

[[Mail-Consumingmailswithattachmentsample]]
Consuming mails with attachment sample
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In this sample we poll a mailbox and store all attachments from the
mails as files. First, we define a route to poll the mailbox. As this
sample is based on google mail, it uses the same route as shown in the
SSL sample:

[source,java]
---------------------------------------------------------------------------------------
from("imaps://imap.gmail.com?username=YOUR_USERNAME@gmail.com&password=YOUR_PASSWORD"
    + "&delete=false&unseen=true&consumer.delay=60000").process(new MyMailProcessor());
---------------------------------------------------------------------------------------

Instead of logging the mail we use a processor where we can process the
mail from java code:

[source,java]
---------------------------------------------------------------------------------
    public void process(Exchange exchange) throws Exception {
        // the API is a bit clunky so we need to loop
        Map<String, DataHandler> attachments = exchange.getIn().getAttachments();
        if (attachments.size() > 0) {
            for (String name : attachments.keySet()) {
                DataHandler dh = attachments.get(name);
                // get the file name
                String filename = dh.getName();

                // get the content and convert it to byte[]
                byte[] data = exchange.getContext().getTypeConverter()
                                  .convertTo(byte[].class, dh.getInputStream());

                // write the data to a file
                FileOutputStream out = new FileOutputStream(filename);
                out.write(data);
                out.flush();
                out.close();
            }
        }
   }
---------------------------------------------------------------------------------

As you can see the API to handle attachments is a bit clunky but it's
there so you can get the `javax.activation.DataHandler` so you can
handle the attachments using standard API.

[[Mail-Howtosplitamailmessagewithattachments]]
How to split a mail message with attachments
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In this example we consume mail messages which may have a number of
attachments. What we want to do is to use the
link:splitter.html[Splitter] EIP per individual attachment, to process
the attachments separately. For example if the mail message has 5
attachments, we want the link:splitter.html[Splitter] to process five
messages, each having a single attachment. To do this we need to provide
a custom link:expression.html[Expression] to the
link:splitter.html[Splitter] where we provide a List<Message> that
contains the five messages with the single attachment.

The code is provided out of the box in Camel 2.10 onwards in the
`camel-mail` component. The code is in the class:
`org.apache.camel.component.mail.SplitAttachmentsExpression`, which you
can find the source code
https://svn.apache.org/repos/asf/camel/trunk/components/camel-mail/src/main/java/org/apache/camel/component/mail/SplitAttachmentsExpression.java[here]

In the Camel route you then need to use this
link:expression.html[Expression] in the route as shown below:

If you use XML DSL then you need to declare a method call expression in
the link:splitter.html[Splitter] as shown below

[source,xml]
---------------------------------------------------------------------------------
<split>
  <method beanType="org.apache.camel.component.mail.SplitAttachmentsExpression"/>
  <to uri="mock:split"/>
</split>
---------------------------------------------------------------------------------

 

From Camel 2.16 onwards you can also split the attachments as byte[] to
be stored as the message body. This is done by creating the expression
with boolean true

[source,java]
--------------------------------------------------------------------
SplitAttachmentsExpression split = SplitAttachmentsExpression(true);
--------------------------------------------------------------------

And then use the expression with the splitter eip.

[[Mail-UsingcustomSearchTerm]]
Using custom SearchTerm
^^^^^^^^^^^^^^^^^^^^^^^

*Available as of Camel 2.11*

You can configure a `searchTerm` on the `MailEndpoint` which allows you
to filter out unwanted mails.

For example to filter mails to contain Camel in either Subject or Text
you can do as follows:

[source,xml]
-------------------------------------------------------------------------------------------------
<route>
  <from uri="imaps://mymailseerver?username=foo&password=secret&searchTerm.subjectOrBody=Camel"/>
  <to uri="bean:myBean"/>
</route>
-------------------------------------------------------------------------------------------------

Notice we use the `"searchTerm.subjectOrBody"` as parameter key to
indicate that we want to search on mail subject or body, to contain the
word "Camel". +
 The class `org.apache.camel.component.mail.SimpleSearchTerm` has a
number of options you can configure:

Or to get the new unseen emails going 24 hours back in time you can do.
Notice the "now-24h" syntax. See the table below for more details.

[source,xml]
--------------------------------------------------------------------------------------------------
<route>
  <from uri="imaps://mymailseerver?username=foo&password=secret&searchTerm.fromSentDate=now-24h"/>
  <to uri="bean:myBean"/>
</route>
--------------------------------------------------------------------------------------------------

You can have multiple searchTerm in the endpoint uri configuration. They
would then be combined together using AND operator, eg so both
conditions must match. For example to get the last unseen emails going
back 24 hours which has Camel in the mail subject you can do:

[source,xml]
---------------------------------------------------------------------------------------------------------------------------
<route>
  <from uri="imaps://mymailseerver?username=foo&password=secret&searchTerm.subject=Camel&searchTerm.fromSentDate=now-24h"/>
  <to uri="bean:myBean"/>
</route>
---------------------------------------------------------------------------------------------------------------------------

The `SimpleSearchTerm` is designed to be easily configurable from a
POJO, so you can also configure it using a <bean> style in XML

[source,java]
---------------------------------------------------------------------------------
<bean id="mySearchTerm" class="org.apache.camel.component.mail.SimpleSearchTerm">
  <property name="subject" value="Order"/>
  <property name="to" value="acme-order@acme.com"/>
  <property name="fromSentDate" value="now"/>
 </bean>
---------------------------------------------------------------------------------

You can then refer to this bean, using #beanId in your Camel route as
shown:

[source,xml]
-------------------------------------------------------------------------------------------
<route>
  <from uri="imaps://mymailseerver?username=foo&password=secret&searchTerm=#mySearchTerm"/>
  <to uri="bean:myBean"/>
</route>
-------------------------------------------------------------------------------------------

In Java there is a builder class to build compound
`SearchTerms` using the `org.apache.camel.component.mail.SearchTermBuilder`
class. This allows you to build complex terms such as:

[source,java]
--------------------------------------------------------------
// we just want the unseen mails which is not spam
SearchTermBuilder builder = new SearchTermBuilder();

builder.unseen().body(Op.not, "Spam").subject(Op.not, "Spam")
  // which was sent from either foo or bar
  .from("foo@somewhere.com").from(Op.or, "bar@somewhere.com");
  // .. and we could continue building the terms

SearchTerm term = builder.build();
--------------------------------------------------------------

[[Mail-SeeAlso]]
See Also
^^^^^^^^

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]

