= Milvus Component
:doctitle: Milvus
:shortname: milvus
:artifactid: camel-milvus
:description: Perform operations on the Milvus Vector Database.
:since: 4.5
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported
//Manually maintained attributes
:group: AI
:camel-spring-boot-name: milvus

*Since Camel {since}*

*{component-header}*

The Milvus Component provides support for interacting with the https://https://milvus.io/[Milvus Vector Database].

== URI format

----
milvus:collection[?options]
----

Where *collection* represents a named set of points (vectors with a payload) defined in your database.


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END

// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

== Examples

=== Collection Examples

In the route below, we use the milvus component to create a collection named _test_ with the given parameters:

[tabs]
====
Java::
+
[source,java]
----
FieldType fieldType1 = FieldType.newBuilder()
                .withName("userID")
                .withDescription("user identification")
                .withDataType(DataType.Int64)
                .withPrimaryKey(true)
                .withAutoID(true)
                .build();

FieldType fieldType2 = FieldType.newBuilder()
                .withName("userFace")
                .withDescription("face embedding")
                .withDataType(DataType.FloatVector)
                .withDimension(64)
                .build();

FieldType fieldType3 = FieldType.newBuilder()
                .withName("userAge")
                .withDescription("user age")
                .withDataType(DataType.Int8)
                .build();

from("direct:in")
    .setHeader(Milvus.Headers.ACTION)
        .constant(MilvusAction.CREATE_COLLECTION)
    .setBody()
        .constant(
                CreateCollectionParam.newBuilder()
                    .withCollectionName("test")
                    .withDescription("customer info")
                    .withShardsNum(2)
                    .withEnableDynamicField(false)
                    .addFieldType(fieldType1)
                    .addFieldType(fieldType2)
                    .addFieldType(fieldType3)
                    .build())
    .to("milvus:test");
----
====

=== Points Examples

==== Upsert

In the route below we use the milvus component to perform insert on points in the collection named _test_:

[tabs]
====
Java::
+
[source,java]
----
private List<List<Float>> generateFloatVectors(int count) {
        Random ran = new Random();
        List<List<Float>> vectors = new ArrayList<>();
        for (int n = 0; n < count; ++n) {
            List<Float> vector = new ArrayList<>();
            for (int i = 0; i < 64; ++i) {
                vector.add(ran.nextFloat());
            }
            vectors.add(vector);
        }

        return vectors;
}


Random ran = new Random();
List<Integer> ages = new ArrayList<>();
for (long i = 0L; i < 2; ++i) {
    ages.add(ran.nextInt(99));
}
List<InsertParam.Field> fields = new ArrayList<>();
fields.add(new InsertParam.Field("userAge", ages));
fields.add(new InsertParam.Field("userFace", generateFloatVectors(2)));

from("direct:in")
    .setHeader(Milvus.Headers.ACTION)
        .constant(MilvusAction.INSERT)
    .setBody()
        .constant(
            InsertParam.newBuilder()
                .withCollectionName("test")
                .withFields(fields)
                .build())
    .to("qdrant:test");
----
====


=== Search

In the route below, we use the milvus component to retrieve information by query from the collection named _test_:

[tabs]
====
Java::
+
[source,java]
----
private List<Float> generateFloatVector() {
        Random ran = new Random();
        List<Float> vector = new ArrayList<>();
        for (int i = 0; i < 64; ++i) {
            vector.add(ran.nextFloat());
        }
        return vector;
}

from("direct:in")
    .setHeader(Milvus.Headers.ACTION)
        .constant(MilvusAction.SEARCH)
    .setBody()
        .constant(SearchSimpleParam.newBuilder()
                .withCollectionName("test")
                .withVectors(generateFloatVector())
                .withFilter("userAge>0")
                .withLimit(100L)
                .withOffset(0L)
                .withOutputFields(Lists.newArrayList("userAge"))
                .withConsistencyLevel(ConsistencyLevelEnum.STRONG)
                .build())
    .to("qdrant:myCollection");
----
====


include::spring-boot:partial$starter.adoc[]
