= JSON Fastjson DataFormat
:doctitle: JSON Fastjson
:shortname: fastjson
:artifactid: camel-fastjson
:description: Marshal POJOs to JSON and back using Fastjson
:since: 2.20
:supportlevel: Stable
:tabs-sync-option:

*Since Camel {since}*

Fastjson is a Data Format that uses the
https://github.com/alibaba/fastjson[Fastjson Library]

[tabs]
====
Java::
+
[source,java]
----
from("activemq:My.Queue")
    .marshal().json(JsonLibrary.Fastjson)
    .to("mqseries:Another.Queue");
----

XML::
+
[source,xml]
----
<route>
  <from uri="activemq:My.Queue"/>
  <marshal><json library="Fastjson"/></marshal>
  <to uri="mqseries:Another.Queue"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: activemq:My.Queue
      steps:
        - marshal:
            json:
              library: Fastjson
        - to:
            uri: mqseries:Another.Queue
----
====

== Fastjson Options


// dataformat options: START
include::partial$dataformat-options.adoc[]
// dataformat options: END


== A body that is already JSON

A body that already is the JSON text is written as it is, not serialized as a Java object: a file, an `InputStream`,
a `byte[]`, and a `String` whose text is a JSON object or array (it starts with `{` and ends with `}`, or `[` and
`]`). So `marshal: json` after reading a JSON file, or after building the JSON with a template or a Simple
expression, sends that JSON unchanged. Any other `String` is written as a JSON string, and POJOs, maps and lists are
marshalled as usual. All the JSON data formats of Camel do the same.

== Dependencies

To use Fastjson in your camel routes, you need to add the dependency
on *camel-fastjson* which implements this data format.

If you use maven, you could add the following to your `pom.xml`,
substituting the version number for the latest & greatest release.

[source,xml]
----------------------------------------------------------
<dependency>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-fastjson</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel core version -->
</dependency>
----------------------------------------------------------
