= JFR Component
:doctitle: JFR
:shortname: jfr
:artifactid: camel-jfr
:description: Diagnose Camel applications with Java Flight Recorder
:since: 3.8
:supportlevel: Stable
:tabs-sync-option:
//Manually maintained attributes
:camel-spring-boot-name: jfr

*Since Camel {since}*

The Camel Java Flight Recorder (JFR) component is used for integrating Camel with Java Flight Recorder (JFR).

This allows to monitor and troubleshoot your Camel applications with JFR.

The camel-jfr component emits lifecycle events for startup to JFR.
This can for example be used to pin-point which Camel routes may be slow to startup.

See the __startupRecorder__ options from xref:components:others:main.adoc[Camel Main]

== Example

To enable you just need to add `camel-jfr` to the classpath, and enable JFR recording.

JFR recordings can be started either at:

- When running the JVM using JVM arguments
- When starting Camel by setting `camel.main.startup-recorder-recording=true`.

See the `flight-recorder` from the Camel Examples.

include::spring-boot:partial$starter.adoc[]
