= Kamelet EIP
:doctitle: Kamelet
:shortname: kamelet
:description: To call Kamelets
:since: 
:supportlevel: Stable

Kamelets (Kamel route snippets) allow users to connect to external systems via a simplified interface,
hiding all the low level details about how those connections are implemented.

The Kamelet EIP allows calling Kamelets (i.e. xref:manual::route-template.adoc[Route Template]).
When calling a Kamelet you may just refer to the name (template id) of the Kamelet in the EIP as shown below:

== Options
// eip options: START
include::partial$eip-options.adoc[]
// eip options: END

== Using Kamelet EIP

[source,java]
----
from("direct:start")
    .kamelet("foo")
    .to("mock:result");
----

And in XML

[source,xml]
----
<route>
    <from uri="direct:start"/>
    <kamelet name="foo"/>
    <to uri="mock:result"/>
</route>
----

Camel will then, when starting:

* Lookup the xref:manual::route-template.adoc[Route Template] with the given id (in the example above its foo) from the `CamelContext`
* Create a new route based on the xref:manual::route-template.adoc[Route Template]

== Dependency

The implementation of the Kamelet EIP is located in the `camel-kamelet` JAR, so you should add the following dependency:

[source,xml]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-kamelet</artifactId>
    <!-- use the same version as your Camel core version -->
    <version>x.y.z</version>
</dependency>
----

== See Also

See the example https://github.com/apache/camel-examples/tree/master/examples/kamelet[camel-example-kamelet].
