= Multicast EIP
:doctitle: Multicast
:shortname: multicast
:description: Routes the same message to multiple paths either sequentially or in parallel.
:since: 
:supportlevel: Stable

The Multicast EIP allows to route the same message to a number of endpoints
and process them in a different way. The main difference between the
Multicast and Splitter is that Splitter will split the message into
several pieces but the Multicast will not modify the request message.

== Options

// eip options: START
include::partial$eip-options.adoc[]
// eip options: END

== Multicast example

The following example shows how to take a request from the *direct:a*
endpoint , then multicast these request to *direct:x*, *direct:y*,
*direct:z*.

== Using the fluent builder

By default Multicast invokes each endpoint sequentially. If parallel
processing is desired, simply use

[source,java]
----
from("direct:a").multicast().parallelProcessing().to("direct:x", "direct:y", "direct:z");
----

In case of using InOut MEP, an AggregationStrategy is used for
aggregating all reply messages. The default is to only use the latest
reply message and discard any earlier replies. The aggregation strategy
is configurable:

[source,java]
----
from("direct:start")
  .multicast(new MyAggregationStrategy())
  .parallelProcessing().timeout(500).to("direct:a", "direct:b", "direct:c")
  .end()
  .to("mock:result");
----

[NOTE]
====
The Multicast, Recipient List, and Splitter EIPs have special support for using `AggregationStrategy` with
access to the original input exchange. You may want to use this when you aggregate messages and
there has been a failure in one of the messages, which you then want to enrich on the original
input message and return as response; its the aggregate method with 3 exchange parameters.
====

== Stop processing in case of exception

The mutlicast EIP will by default continue to process
the entire exchange even in case one of the
multicasted messages will throw an exception during routing. 
For example if you want to multicast to 3 destinations and the 2nd
destination fails by an exception. What Camel does by default is to
process the remainder destinations. You have the chance to remedy or
handle this in the `AggregationStrategy`.

But sometimes you just want Camel to stop and let the exception be
propagated back, and let the Camel error handler handle it. You can do
this by specifying that it should stop in case of an
exception occurred. This is done by the `stopOnException` option as
shown below:

[source,java]
----
    from("direct:start")
        .multicast()
            .stopOnException().to("direct:foo", "direct:bar", "direct:baz")
        .end()
        .to("mock:result");

        from("direct:foo").to("mock:foo");

        from("direct:bar").process(new MyProcessor()).to("mock:bar");

        from("direct:baz").to("mock:baz");
----

And using XML DSL you specify it as follows:

[source,xml]
----
        <route>
            <from uri="direct:start"/>
            <multicast stopOnException="true">
                <to uri="direct:foo"/>
                <to uri="direct:bar"/>
                <to uri="direct:baz"/>
            </multicast>
            <to uri="mock:result"/>
        </route>

        <route>
            <from uri="direct:foo"/>
            <to uri="mock:foo"/>
        </route>

        <route>
            <from uri="direct:bar"/>
            <process ref="myProcessor"/>
            <to uri="mock:bar"/>
        </route>

        <route>
            <from uri="direct:baz"/>
            <to uri="mock:baz"/>
        </route>
----

== Using onPrepare to execute custom logic when preparing messages

The multicast EIP will copy the source
exchange and multicast each copy. However the copy
is a shallow copy, so in case you have mutateable message bodies, then
any changes will be visible by the other copied messages. If you want to
use a deep clone copy then you need to use a custom `onPrepare` which
allows you to do this using the processor
interface.

Notice the `onPrepare` can be used for any kind of custom logic which
you would like to execute before the xref:latest@manual:ROOT:exchange.adoc[Exchange] is
being multicasted.
