= On Fallback EIP
:doctitle: On Fallback
:shortname: onFallback
:description: Route to be executed when Circuit Breaker EIP executes fallback
:since: 
:supportlevel: Stable
:tabs-sync-option:

If you are using *onFallback* then that is intended to be local processing only where you can do a message transformation or call a bean or something as the fallback.

If you need to call an external service over the network then you should use *onFallbackViaNetwork* that runs in another independent *HystrixCommand* that uses its own thread pool to not exhaust the first command.

== Options

// eip options: START
include::partial$eip-options.adoc[]
// eip options: END

== Using fallback

The *onFallback* is used by xref:circuitBreaker-eip.adoc[Circuit Breaker] EIPs to execute a fallback route.
For examples how to use this see the various Circuit Breaker implementations:

- xref:fault-tolerance-eip.adoc[FaultTolerance EIP] - MicroProfile Fault Tolerance Circuit Breaker
- xref:resilience4j-eip.adoc[Resilience4j EIP] - Resilience4j Circuit Breaker
