= Remove Headers EIP
:doctitle: Remove Headers
:shortname: removeHeaders
:description: Removes message headers whose name matches a specified pattern
:since: 
:supportlevel: Stable
:tabs-sync-option:

The Remove Headers EIP allows you to remove one or more headers from the xref:message.adoc[Message],
based on pattern syntax.

== Options

// eip options: START
include::partial$eip-options.adoc[]
// eip options: END

== Exchange properties

// eip exchangeProperties: START
include::partial$eip-exchangeProperties.adoc[]
// eip exchangeProperties: END

== Remove Headers by pattern

The Remove Headers EIP supports pattern
matching by the following rules in the given order:

* match by exact name
* match by wildcard
* match by regular expression

== Remove all headers

To remove all headers you can use `*` as the pattern:

[tabs]
====
Java::
+
[source,java]
----
from("seda:b")
  .removeHeaders("*")
  .to("mock:result");
----

XML::
+
[source,xml]
----
<route>
  <from uri="seda:b"/>
  <removeHeaders pattern="*"/>
  <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- from:
    uri: seda:b
    steps:
      - removeHeaders:
          pattern: "*"
      - to:
          uri: mock:result
----
====

== Remove all Camel headers

To remove all headers that start with `Camel` then use `Camel*` as shown:

[tabs]
====
Java::
+
[source,java]
----
from("seda:b")
  .removeHeaders("Camel*")
  .to("mock:result");
----

XML::
+
[source,xml]
----
<route>
  <from uri="seda:b"/>
  <removeHeaders pattern="Camel*"/>
  <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- from:
    uri: seda:b
    steps:
      - removeHeaders: "Camel*"
      - to:
          uri: mock:result
----
====

== Leaking Camel headers when sending to an endpoint

When I send a message to a Camel endpoint such as the
xref:components::mail-component.adoc[Mail] component, then the mail include some message
headers I do not want. How can I avoid this?

This is a gotcha more people encounter. However, it's very easy to solve.
To remove all headers (see above) use a `*` expression:

Most components will automatically remove all Camel specific headers (the header key starts with `Camel`) using
the `DefaultHeaderFilterStrategy` which automatic removes these headers. However if you use a component that does
not do this, such as a custom component, or a Camel component which has not been improved to do that, then you can
remove all these Camel specific headers using `Camel*` with the `removeHeaders` EIP as shown previously on this page.

== See Also

Camel provides the following EIPs for removing headers or exchange properties:

- xref:removeHeader-eip.adoc[Remove Header]: To remove a single header
- xref:removeHeaders-eip.adoc[Remove Headers]: To remove one or more message headers
- xref:removeProperty-eip.adoc[Remove Property]: To remove a single exchange property
- xref:removeProperties-eip.adoc[Remove Properties]: To remove one or more exchange properties
