= Set Header EIP
:doctitle: Set Header
:shortname: setHeader
:description: Sets the value of a message header
:since: 
:supportlevel: Stable
:tabs-sync-option:

The SetHeader EIP is used for setting a xref:message.adoc[message] header.

== Options

// eip options: START
include::partial$eip-options.adoc[]
// eip options: END

== Using Set Header

The following example shows how to set a header in a Camel route:

[tabs]
====
Java::
+
[source,java]
----
from("direct:a")
    .setHeader("myHeader", constant("test"))
    .to("direct:b");
----

XML::
+
[source,xml]
----
<route>
    <from uri="direct:a"/>
    <setHeader name="myHeader">
        <constant>test</constant>
    </setHeader>
    <to uri="direct:b"/>
</route>
----
====

In the example the header value is a xref:components:languages:constant-language.adoc[constant].

Any of the Camel languages can be used, such as xref:components:languages:simple-language.adoc[Simple].

[tabs]
====
Java::
+
[source,java]
----
from("direct:a")
    .setHeader("randomNumber", simple("${random(1,100)}"))
    .to("direct:b");
----
+
Header can be set using fluent syntax.
+
[source,java]
----
from("direct:a")
    .setHeader("randomNumber").simple("${random(1,100)}")
    .to("direct:b");
----

XML::
+
[source,xml]
----
<route>
    <from uri="direct:a"/>
    <setHeader name="randomNumber">
        <simple>${random(1,100)}</simple>
    </setHeader>
    <to uri="direct:b"/>
</route>
----
====

See xref:components:languages:jsonpath-language.adoc#_using_header_as_input[JSONPath] for another example.

=== Setting a header from another header

You can also set a header with the value from another header.

In the example we set the header foo with the value from an existing header named bar.

[tabs]
====
Java::
+
[source,java]
----
from("direct:a")
    .setHeader("foo", header("bar"))
    .to("direct:b");
----

XML::
+
[source,xml]
----
<route>
    <from uri="direct:a"/>
    <setHeader name="foo">
        <header>bar</header>
    </setHeader>
    <to uri="direct:b"/>
</route>
----
====
