= Stub Component
:doctitle: Stub
:shortname: stub
:artifactid: camel-stub
:description: Stub out any physical endpoints while in development or testing.
:since: 2.10
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
:core:
//Manually maintained attributes
:camel-spring-boot-name: stub

*Since Camel {since}*

*{component-header}*

The Stub component provides a simple way to stub out any physical
endpoints while in development or testing, allowing you, for example, to
run a route without needing to actually connect to a specific
xref:mail-component.adoc[SMTP] or xref:http-component.adoc[Http] endpoint.
Add *stub:*
in front of any endpoint URI to stub out the endpoint.

Internally, the Stub component creates xref:seda-component.adoc[Seda] endpoints.
The main difference between xref:stub-component.adoc[Stub] and xref:seda-component.adoc[Seda] is
that xref:seda-component.adoc[Seda] will validate the URI and parameters you give it,
so putting seda: in front of a typical URI with query arguments will
usually fail.
Stub won't, though, as it basically ignores all query
parameters to let you quickly stub out one or more endpoints in your
route temporarily.

== URI format

----
stub:someUri
----

Where *`someUri`* can be any URI with any query parameters.



// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END


== Examples

Here are a few samples of stubbing endpoint uris

----
stub:smtp://somehost.foo.com?user=whatnot&something=else
stub:http://somehost.bar.com/something
----


include::spring-boot:partial$starter.adoc[]
