= AWS Secrets Manager Component
:doctitle: AWS Secrets Manager
:shortname: aws-secrets-manager
:artifactid: camel-aws-secrets-manager
:description: Manage AWS Secrets Manager services using AWS SDK version 2.x.
:since: 3.9
:supportlevel: Stable
:component-header: Only producer is supported
//Manually maintained attributes
:group: AWS
:camel-spring-boot-name: aws-secrets-manager

*Since Camel {since}*

*{component-header}*

The AWS Secrets Manager component supports list secret
https://aws.amazon.com/secrets-manager/[AWS Secrets Manager] service.

Prerequisites

You must have a valid Amazon Web Services developer account, and be
signed up to use Amazon Secrets Manager. More information is available at
https://aws.amazon.com/secrets-manager/[AWS Secrets Manager].


== URI Format

-------------------------
aws-secrets-manager://label[?options]
-------------------------

You can append query options to the URI in the following format,
?options=value&option2=value&...


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END

=== Secrets Manager Producer operations

Camel-AWS-Secrets-manager component provides the following operation on the producer side:

- listSecrets
- createSecret
- deleteSecret
- describeSecret
- rotateSecret
- getSecret
- updateSecret
- replicateSecretToRegions

== Dependencies

Maven users will need to add the following dependency to their pom.xml.

*pom.xml*

[source,xml]
---------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-aws-secrets-manager</artifactId>
    <version>${camel-version}</version>
</dependency>
---------------------------------------

where `$\{camel-version}` must be replaced by the actual version of Camel.


include::spring-boot:partial$starter.adoc[]
