= Stomp Component
:doctitle: Stomp
:shortname: stomp
:artifactid: camel-stomp
:description: Send and receive messages to/from STOMP (Simple Text Oriented Messaging Protocol) compliant message brokers.
:since: 2.12
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:camel-spring-boot-name: stomp

*Since Camel {since}*

*{component-header}*

The Stomp component is used for communicating with
http://stomp.github.io/[Stomp] compliant message brokers, like
http://activemq.apache.org[Apache ActiveMQ] or
http://activemq.apache.org/apollo/[ActiveMQ Apollo]

NOTE: Since STOMP specification is not actively maintained,
please note https://github.com/fusesource/stompjms/tree/master/stompjms-client[STOMP JMS client]
is not as well actively maintained.
However, we hope for the community to step up to help in maintaining the STOMP JMS project in the near future.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-stomp</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

== URI format

---------------------------------
stomp:queue:destination[?options]
---------------------------------

Where *destination* is the name of the queue.



// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END



== Samples

Sending messages:

[source,java]
------------------------------------------
from("direct:foo").to("stomp:queue:test");
------------------------------------------

Consuming messages:

[source,java]
------------------------------------------------------------------------------
from("stomp:queue:test").transform(body().convertToString()).to("mock:result")
------------------------------------------------------------------------------

== Endpoints

Camel supports the Message Endpoint pattern
using the
https://www.javadoc.io/doc/org.apache.camel/camel-api/current/org/apache/camel/Endpoint.html[Endpoint]
interface. Endpoints are usually created by a
Component, and Endpoints are usually referred to in
the DSL via their URIs.

From an Endpoint you can use the following methods

* https://www.javadoc.io/doc/org.apache.camel/camel-api/current/org/apache/camel/Endpoint.html#createProducer--[createProducer()]
will create a
https://www.javadoc.io/doc/org.apache.camel/camel-api/current/org/apache/camel/Producer.html[Producer]
for sending message exchanges to the endpoint
* https://www.javadoc.io/doc/org.apache.camel/camel-api/current/org/apache/camel/Endpoint.html#createConsumer-org.apache.camel.Processor-[createConsumer()]
implements the Event Driven Consumer
pattern for consuming message exchanges from the endpoint via a
https://www.javadoc.io/doc/org.apache.camel/camel-api/current/org/apache/camel/Processor.html[Processor]
when creating a
https://www.javadoc.io/doc/org.apache.camel/camel-api/current/org/apache/camel/Consumer.html[Consumer]
* https://www.javadoc.io/doc/org.apache.camel/camel-api/current/org/apache/camel/Endpoint.html#createPollingConsumer--[createPollingConsumer()]
implements the Polling Consumer pattern for
consuming message exchanges from the endpoint via a
https://www.javadoc.io/doc/org.apache.camel/camel-api/current/org/apache/camel/PollingConsumer.html[PollingConsumer]



include::spring-boot:partial$starter.adoc[]
