= JQ Language
:doctitle: JQ
:shortname: jq
:artifactid: camel-jq
:description: Evaluates a JQ expression against a JSON message body.
:since: 3.18
:supportlevel: Stable
:tabs-sync-option:
//Manually maintained attributes
:camel-spring-boot-name: jq

*Since Camel {since}*

Camel supports https://jqlang.github.io/jq/[JQ] to allow using xref:manual::expression.adoc[Expression] or xref:manual::predicate.adoc[Predicate] on JSON messages.

== JQ Options

// language options: START
include::partial$language-options.adoc[]
// language options: END


== Examples

For example, you can use JQ in a xref:manual::predicate.adoc[Predicate] with the xref:eips:choice-eip.adoc[Content-Based Router] EIP.

[source,java]
----
from("queue:books.new")
  .choice()
    .when().jq(".store.book.price < 10)")
      .to("jms:queue:book.cheap")
    .when().jq(".store.book.price < 30)")
      .to("jms:queue:book.average")
    .otherwise()
      .to("jms:queue:book.expensive");
----

== Message body types

Camel JQ leverages `camel-jackson` for type conversion.
To enable camel-jackson POJO type conversion, refer to the Camel Jackson documentation.

== Using header as input

By default, JQ uses the message body as the input source. However, you can also use a header as input by specifying the `headerName` option.

For example, to count the number of books from a JSON document that was stored in a header named `books` you can do:

[source,java]
----
from("direct:start")
    .setHeader("numberOfBooks")
        .jq(".store.books | length", int.class, "books")
    .to("mock:result");
----

== Camel supplied JQ Functions

NOTE: JQ comes with about a hundred built-in functions, and you can see many examples from https://jqlang.github.io/jq/[JQ] documentation.

The camel-jq adds the following functions:

* `header`: allow accessing the Message header in a JQ expression.
* `property`: allow accessing the Exchange property in a JQ expression.
* `constant`: allow using a constant value as-is in a JQ expression.

For example, to set the property foo with the value from the Message header `MyHeader':

[source, java]
----
from("direct:start")
    .transform()
        .jq(".foo = header(\"MyHeader\")")
    .to("mock:result");
----

Or from the exchange property:

[source, java]
----
from("direct:start")
    .transform()
        .jq(".foo = property(\"MyProperty\")")
    .to("mock:result");
----

And using a constant value

[source, java]
----
from("direct:start")
    .transform()
        .jq(".foo = constant(\"Hello World\")")
    .to("mock:result");
----

== Transforming a JSon message

For basic JSon transformation where you have a fixed structure, you can represent with a combination of using
Camel simple and JQ language as:

[source]
----
{
  "company": "${jq(.customer.name)}",
  "location": "${jq(.customer.address.country)}",
  "gold": ${jq(.customer.orders[] | length > 5)}
}
----

Here we use the simple language to define the structure and use JQ as inlined functions via the `${jq(exp)}` syntax.

This makes it possible to use simple as a template language to define a basic structure and then JQ to grab the data
from an incoming JSon message. The output of the transformation is also JSon, but with simple you could
also make it XML or plain text based:

[source,xml]
----
<customer gold="${jq(.customer.orders[] | length > 5)}">
    <company>${jq(.customer.name)}</company>
    <location>${jq(.customer.address.country)}</location>
</customer>
----

== Dependencies

If you use Maven you could just add the following to your `pom.xml`, substituting the version number for the latest and greatest release (see the download page for the latest versions).

[source,xml]
---------------------------------------
<dependency>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-jq</artifactId>
  <version>x.x.x</version>
</dependency>
---------------------------------------

include::spring-boot:partial$starter.adoc[]
