= Minio Component
:doctitle: Minio
:shortname: minio
:artifactid: camel-minio
:description: Store and retrieve objects from Minio Storage Service using Minio SDK.
:since: 3.5
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
//Manually maintained attributes

*Since Camel {since}*

*{component-header}*

The Minio component supports storing and retrieving objects from/to
https://min.io/[Minio] service.

== Prerequisites

You must have valid credentials for authorized access to the buckets/folders. More information is available at
https://min.io/[Minio].

== URI Format

----
minio://bucketName[?options]
----

The bucket will be created if it doesn't already exist. +
You can append query options to the URI in the following format: `?options=value&option2=value&...`

For example, to read file `hello.txt` from the bucket `helloBucket`, use the following snippet:

[tabs]
====
Java::
+
[source,java]
----
from("minio://helloBucket?accessKey=yourAccessKey&secretKey=yourSecretKey&objectName=hello.txt")
  .to("file:/var/downloaded");
----

XML::
+
[source,xml]
----
<route>
  <from uri="minio://helloBucket?accessKey=yourAccessKey&amp;secretKey=yourSecretKey&amp;objectName=hello.txt"/>
  <to uri="file:/var/downloaded"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: minio://helloBucket
      parameters:
        accessKey: yourAccessKey
        secretKey: yourSecretKey
        objectName: hello.txt
      steps:
        - to:
            uri: file:/var/downloaded
----
====

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
include::partial$component-endpoint-headers.adoc[]
// component options: END


NOTE: You have to provide the minioClient in the Registry or your `accessKey` and `secretKey` to access
the https://min.io/[Minio].

== Usage

=== Batch Consumer

This component implements the Batch Consumer.

This allows you, for instance, to know how many messages exist in this
batch and for instance, let the Aggregator
aggregate this number of messages.

=== Minio Producer operations

Camel-Minio component provides the following operation on the producer side:

- `copyObject`
- `deleteObject`
- `deleteObjects`
- `listBuckets`
- `deleteBucket`
- `listObjects`
- `getObject` (this will return a `MinioObject instance)
- `getObjectRange` (this will return a `MinioObject instance)
- `createDownloadLink` (this will return a Presigned download Url)
- `createUploadLink` (this will return a Presigned upload url)

=== Advanced Minio configuration

If your Camel Application is running behind a firewall or if you need to
have more control over the `MinioClient` instance configuration, you can
create your own instance and refer to it in your Camel minio component configuration:

[tabs]
====
Java::
+
[source,java]
----
from("minio://MyBucket?minioClient=#client&delay=5000&maxMessagesPerPoll=5")
  .to("mock:result");
----

XML::
+
[source,xml]
----
<route>
  <from uri="minio://MyBucket?minioClient=#client&amp;delay=5000&amp;maxMessagesPerPoll=5"/>
  <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: minio://MyBucket
      parameters:
        minioClient: "#client"
        delay: 5000
        maxMessagesPerPoll: 5
      steps:
        - to:
            uri: mock:result
----
====

=== Minio Producer Operation examples

- `CopyObject`: this operation copies an object from one bucket to a different one

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .setHeader("CamelMinioDestinationBucketName").constant("camelDestinationBucket")
    .setHeader("CamelMinioObjectName").constant("camelKey")
    .setHeader("CamelMinioDestinationObjectName").constant("camelDestinationKey")
    .to("minio://mycamelbucket?minioClient=#minioClient&operation=copyObject")
    .to("mock:result");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:start"/>
  <setHeader name="CamelMinioDestinationBucketName">
    <constant>camelDestinationBucket</constant>
  </setHeader>
  <setHeader name="CamelMinioObjectName">
    <constant>camelKey</constant>
  </setHeader>
  <setHeader name="CamelMinioDestinationObjectName">
    <constant>camelDestinationKey</constant>
  </setHeader>
  <to uri="minio://mycamelbucket?minioClient=#minioClient&amp;operation=copyObject"/>
  <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
      steps:
        - setHeader:
            name: CamelMinioDestinationBucketName
            constant: camelDestinationBucket
        - setHeader:
            name: CamelMinioObjectName
            constant: camelKey
        - setHeader:
            name: CamelMinioDestinationObjectName
            constant: camelDestinationKey
        - to:
            uri: minio://mycamelbucket
            parameters:
              minioClient: "#minioClient"
              operation: copyObject
        - to:
            uri: mock:result
----
====

This operation will copy the object with the name expressed in the header camelDestinationKey to the camelDestinationBucket bucket, from the bucket mycamelbucket.

- `DeleteObject`: this operation deletes an object from a bucket

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .setHeader("CamelMinioObjectName").constant("camelKey")
    .to("minio://mycamelbucket?minioClient=#minioClient&operation=deleteObject")
    .to("mock:result");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:start"/>
  <setHeader name="CamelMinioObjectName">
    <constant>camelKey</constant>
  </setHeader>
  <to uri="minio://mycamelbucket?minioClient=#minioClient&amp;operation=deleteObject"/>
  <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
      steps:
        - setHeader:
            name: CamelMinioObjectName
            constant: camelKey
        - to:
            uri: minio://mycamelbucket
            parameters:
              minioClient: "#minioClient"
              operation: deleteObject
        - to:
            uri: mock:result
----
====

This operation will delete the object camelKey from the bucket mycamelbucket.

- `ListBuckets`: this operation lists the buckets for this account in this region

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .to("minio://mycamelbucket?minioClient=#minioClient&operation=listBuckets")
    .to("mock:result");
----

XML::
+
[source,xml]
----
<route>
    <from uri="direct:start"/>
    <to uri="minio://mycamelbucket?minioClient=#minioClient&amp;operation=listBuckets"/>
    <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
    steps:
      - to:
          uri: minio://mycamelbucket
          parameters:
            minioClient: "#minioClient"
            operation: listBuckets
      - to:
          uri: mock:result
----
====

This operation will list the buckets for this account

- `DeleteBucket`: this operation deletes the bucket specified as URI parameter or header

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .to("minio://mycamelbucket?minioClient=#minioClient&operation=deleteBucket")
    .to("mock:result");
----

XML::
+
[source,xml]
----
<route>
    <from uri="direct:start"/>
    <to uri="minio://mycamelbucket?minioClient=#minioClient&amp;operation=deleteBucket"/>
    <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
    steps:
      - to:
          uri: minio://mycamelbucket
          parameters:
            minioClient: "#minioClient"
            operation: deleteBucket
      - to:
          uri: mock:result
----
====

This operation will delete the bucket mycamelbucket

- `ListObjects`: this operation list object in a specific bucket

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .to("minio://mycamelbucket?minioClient=#minioClient&operation=listObjects")
    .to("mock:result");
----

XML::
+
[source,xml]
----
<route>
    <from uri="direct:start"/>
    <to uri="minio://mycamelbucket?minioClient=#minioClient&amp;operation=listObjects"/>
    <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
    steps:
      - to:
          uri: minio://mycamelbucket
          parameters:
            minioClient: "#minioClient"
            operation: listObjects
      - to:
          uri: mock:result
----
====

This operation will list the objects in the mycamelbucket bucket

- `GetObject`: this operation gets a single object in a specific bucket

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .setHeader("CamelMinioObjectName").constant("camelKey")
    .to("minio://mycamelbucket?minioClient=#minioClient&operation=getObject")
    .to("mock:result");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:start"/>
  <setHeader name="CamelMinioObjectName">
    <constant>camelKey</constant>
  </setHeader>
  <to uri="minio://mycamelbucket?minioClient=#minioClient&amp;operation=getObject"/>
  <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
      steps:
        - setHeader:
            name: CamelMinioObjectName
            constant: camelKey
        - to:
            uri: minio://mycamelbucket
            parameters:
              minioClient: "#minioClient"
              operation: getObject
        - to:
            uri: mock:result
----
====

This operation will return a MinioObject instance related to the camelKey object in `mycamelbucket` bucket.

- `GetObjectRange`: this operation gets a single object range in a specific bucket

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .setHeader("CamelMinioObjectName").constant("camelKey")
    .setHeader("CamelMinioOffset").constant("0")
    .setHeader("CamelMinioLength").constant("9")
    .to("minio://mycamelbucket?minioClient=#minioClient&operation=getObjectRange")
    .to("mock:result");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:start"/>
  <setHeader name="CamelMinioObjectName">
    <constant>camelKey</constant>
  </setHeader>
  <setHeader name="CamelMinioOffset">
    <constant>0</constant>
  </setHeader>
  <setHeader name="CamelMinioLength">
    <constant>9</constant>
  </setHeader>
  <to uri="minio://mycamelbucket?minioClient=#minioClient&amp;operation=getObjectRange"/>
  <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
      steps:
        - setHeader:
            name: CamelMinioObjectName
            constant: camelKey
        - setHeader:
            name: CamelMinioOffset
            constant: "0"
        - setHeader:
            name: CamelMinioLength
            constant: "9"
        - to:
            uri: minio://mycamelbucket
            parameters:
              minioClient: "#minioClient"
              operation: getObjectRange
        - to:
            uri: mock:result
----
====
This operation will return a MinioObject instance related to the camelKey object in `mycamelbucket` bucket, containing bytes from 0 to 9.

- `createDownloadLink`: this operation will return a presigned url through which a file can be downloaded using GET method

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .setHeader("CamelMinioObjectName").constant("camelKey")
    .setHeader("CamelMinioPresignedURLExpirationTime").constant(3600)
    .to("minio://mycamelbucket?minioClient=#minioClient&operation=createDownloadLink")
    .to("mock:result");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:start"/>
  <setHeader name="CamelMinioObjectName">
    <constant>camelKey</constant>
  </setHeader>
  <setHeader name="CamelMinioPresignedURLExpirationTime">
    <constant resultType="java.lang.Integer">3600</constant>
  </setHeader>
  <to uri="minio://mycamelbucket?minioClient=#minioClient&amp;operation=createDownloadLink"/>
  <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
      steps:
        - setHeader:
            name: CamelMinioObjectName
            constant: camelKey
        - setHeader:
            name: CamelMinioPresignedURLExpirationTime
            constant: 3600
        - to:
            uri: minio://mycamelbucket
            parameters:
              minioClient: "#minioClient"
              operation: createDownloadLink
        - to:
            uri: mock:result
----
====

- `createUploadLink`: this operation will return a presigned url through which a file can be uploaded using PUT method

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .setHeader("CamelMinioObjectName").constant("camelKey")
    .setHeader("CamelMinioPresignedURLExpirationTime").constant(3600)
    .to("minio://mycamelbucket?minioClient=#minioClient&operation=createUploadLink")
    .to("mock:result");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:start"/>
  <setHeader name="CamelMinioObjectName">
    <constant>camelKey</constant>
  </setHeader>
  <setHeader name="CamelMinioPresignedURLExpirationTime">
    <constant resultType="java.lang.Integer">3600</constant>
  </setHeader>
  <to uri="minio://mycamelbucket?minioClient=#minioClient&amp;operation=createUploadLink"/>
  <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
      steps:
        - setHeader:
            name: CamelMinioObjectName
            constant: camelKey
        - setHeader:
            name: CamelMinioPresignedURLExpirationTime
            constant: 3600
        - to:
            uri: minio://mycamelbucket
            parameters:
              minioClient: "#minioClient"
              operation: createUploadLink
        - to:
            uri: mock:result
----
====

`createDownLink` and `createUploadLink` have a default expiry of 3600s which can be overridden by setting the header `CamelMinioPresignedURLExpirationTime` (value in seconds)

=== Bucket Auto-creation

With the option `autoCreateBucket` users are able to avoid the auto-creation of a Minio Bucket in case it doesn't exist. The default for this option is `true`.
If set to false, any operation on a not-existent bucket in Minio won't be successful, and an error will be returned.

=== Automatic detection of a Minio client in registry

The component is capable of detecting the presence of a Minio bean into the registry.
If it's the only instance of that type, it will be used as the client, and you won't have to define it as uri parameter, like the example above.
This may be really useful for smarter configuration of the endpoint.

=== Moving stuff between a bucket and another bucket

Some users like to consume stuff from a bucket and move the content in a different one without using the `copyObject` feature of this component.
If this is the case for you, remember to remove the `bucketName` header from the incoming exchange of the consumer.
Otherwise, the file will always be overwritten on the same original bucket.

=== MoveAfterRead consumer option

In addition to `deleteAfterRead`, it has been added another option, `moveAfterRead`.
With this option enabled, the consumed object will be moved to a target `destinationBucket` instead of being only deleted.
This will require specifying the destinationBucket option. As example:

[tabs]
====
Java::
+
[source,java]
----
from("minio://mycamelbucket?minioClient=#minioClient&moveAfterRead=true&destinationBucketName=myothercamelbucket")
  .to("mock:result");
----

XML::
+
[source,xml]
----
<route>
  <from uri="minio://mycamelbucket?minioClient=#minioClient&amp;moveAfterRead=true&amp;destinationBucketName=myothercamelbucket"/>
  <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: minio://mycamelbucket
      parameters:
        minioClient: "#minioClient"
        moveAfterRead: true
        destinationBucketName: myothercamelbucket
      steps:
        - to:
            uri: mock:result
----
====

In this case, the objects consumed will be moved to `myothercamelbucket` bucket and deleted from the original one (because of `deleteAfterRead` set to true as default).

=== Using a POJO as body

Sometimes build a Minio Request can be complex because of multiple options.
We introduce the possibility to use a POJO as the body.
In Minio, there are multiple operations you can submit, as an example for List brokers request, you can do something like:

._Java-only: uses Minio Java SDK builder API for POJO request body_
[source,java]
----
from("direct:minio")
     .setBody(ListObjectsArgs.builder()
                    .bucket(bucketName)
                    .recursive(getConfiguration().isRecursive()))
     .to("minio://test?minioClient=#minioClient&operation=listObjects&pojoRequest=true");
----

In this way, you'll pass the request directly without the need of passing headers and options specifically related to this operation.

== Dependencies

Maven users will need to add the following dependency to their `pom.xml`.

*pom.xml*

[source,xml]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-minio</artifactId>
    <version>${camel-version}</version>
</dependency>
----

where `$\{camel-version}` must be replaced by the actual version of Camel.


