= Scheduler Component
:doctitle: Scheduler
:shortname: scheduler
:artifactid: camel-scheduler
:description: Generate messages in specified intervals using java.util.concurrent.ScheduledExecutorService.
:since: 2.15
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only consumer is supported
:core:
//Manually maintained attributes
:camel-spring-boot-name: scheduler

*Since Camel {since}*

*{component-header}*

The Scheduler component is used to generate message exchanges when a
scheduler fires. This component is similar to the
 xref:timer-component.adoc[Timer] component, but it offers more functionality in
terms of scheduling. Also, this component uses
JDK `ScheduledExecutorService`, whereas the timer uses a JDK `Timer`.

You can only consume events from this endpoint.

== URI format

----
scheduler:name[?options]
----

Where `name` is the name of the scheduler, which is created and shared
across endpoints. So if you use the same name for all your scheduler
endpoints, only one scheduler thread pool and thread will be used - but
you can configure the thread pool to allow more concurrent threads.

*Note:* The IN body of the generated exchange is `null`. So
`exchange.getIn().getBody()` returns `null`.



// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END
// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

== More information

This component is a scheduler
http://camel.apache.org/polling-consumer.html[Polling Consumer] where
you can find more information about the options above, and examples at
the http://camel.apache.org/polling-consumer.html[Polling
Consumer] page.

== Exchange Properties

When the timer is fired, it adds the following information as properties
to the `Exchange`:

[width="100%",cols="10%,10%,80%",options="header",]
|===
|Name |Type |Description

|`Exchange.TIMER_NAME` |`String` |The value of the `name` option.

|`Exchange.TIMER_FIRED_TIME` |`Date` |The time when the consumer fired.
|===

== Sample

To set up a route that generates an event every 60 seconds:

[source,java]
----
from("scheduler://foo?delay=60000").to("bean:myBean?method=someMethodName");
----

The above route will generate an event and then invoke the
`someMethodName` method on the bean called `myBean` in the
Registry such as JNDI or Spring.

And the route in Spring DSL:

[source,xml]
----
<route>
  <from uri="scheduler://foo?delay=60000"/>
  <to uri="bean:myBean?method=someMethodName"/>
</route>
----

== Forcing the scheduler to trigger immediately when completed

To let the scheduler trigger as soon as the previous task is complete,
you can set the option `greedy=true`. But beware then the scheduler will
keep firing all the time. So use this with caution.

== Forcing the scheduler to be idle

There can be use cases where you want the scheduler to trigger and be
greedy. But sometimes you want "tell the scheduler" that there was no
task to poll, so the scheduler can change into idle mode using the
backoff options. To do this you would need to set a property on the
exchange with the key `Exchange.SCHEDULER_POLLED_MESSAGES` to a boolean
value of false. This will cause the consumer to indicate that there was
no messages polled. 

The consumer will otherwise as by default return 1 message polled to the
scheduler, every time the consumer has completed processing the
exchange.



include::spring-boot:partial$starter.adoc[]
