= PDF Component
:doctitle: PDF
:shortname: pdf
:artifactid: camel-pdf
:description: Create, modify or extract content from PDF documents.
:since: 2.16
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported
//Manually maintained attributes
:camel-spring-boot-name: pdf

*Since Camel {since}*

*{component-header}*

The PDF component provides the ability to create, modify or extract
content from PDF documents. This component uses
https://pdfbox.apache.org/[Apache PDFBox] as the underlying library to work
with PDF documents.

To use the PDF component, Maven users will need to add the
following dependency to their `pom.xml`:

*pom.xml*

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-pdf</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

== URI format

The PDF component only supports producer endpoints.

-----------------------
pdf:operation[?options]
-----------------------

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

== Usage

=== Type converter

Since Camel 4.8, the component is capable of doing simple document conversions. For instance,
suppose you are receiving a PDF byte as a byte array:


[source,java]
----
from("direct:start")
    .to("pdf:extractText")
    .to("mock:result");
----


It is now possible to get the body as a PD Document by using `PDDocument doc = exchange.getIn().getBody(PDDocument.class);`,
which saves the trouble of converting the byte-array to a document.

NOTE: this only works for unprotected PDF files. For password-protected, the files still need to be converted
manually.

include::spring-boot:partial$starter.adoc[]
