= Nagios Component
:doctitle: Nagios
:shortname: nagios
:artifactid: camel-nagios
:description: Send passive checks to Nagios using JSendNSCA.
:since: 2.3
:supportlevel: Stable
:component-header: Only producer is supported
include::{cq-version}@camel-quarkus:ROOT:partial$reference/components/nagios.adoc[opts=optional]
//Manually maintained attributes
:camel-spring-boot-name: nagios

*Since Camel {since}*

*{component-header}*

The xref:nagios-component.adoc[Nagios] component allows you to send passive checks to http://nagios.org[Nagios].

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-nagios</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

== URI format

------------------------------
nagios://host[:port][?Options]
------------------------------

Camel provides two abilities with the xref:nagios-component.adoc[Nagios]
component.
You can send passive check messages by sending a message to its endpoint. +
Camel also provides a EventNotifer which allows you to send notifications to Nagios.


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END


== Sending message examples

You can send a message to Nagios where the message payload contains the message.
By default it will be `OK` level and use the CamelContext name as the service name.
You can overrule these values using headers as shown above.

For example we send the `Hello Nagios` message to Nagios as follows:

[source,java]
---------------------------------------------------------------------------------------
    template.sendBody("direct:start", "Hello Nagios");

    from("direct:start").to("nagios:127.0.0.1:5667?password=secret").to("mock:result");
---------------------------------------------------------------------------------------

To send a `CRITICAL` message you can send the headers such as:

[source,java]
-----------------------------------------------------------------------------
        Map headers = new HashMap();
        headers.put(NagiosConstants.LEVEL, "CRITICAL");
        headers.put(NagiosConstants.HOST_NAME, "myHost");
        headers.put(NagiosConstants.SERVICE_NAME, "myService");
        template.sendBodyAndHeaders("direct:start", "Hello Nagios", headers);
-----------------------------------------------------------------------------

== Using NagiosEventNotifer

The xref:nagios-component.adoc[Nagios] component also provides an
`EventNotifer` which you can use to send events to Nagios.
For example we can enable this from Java as follows:

[source,java]
-------------------------------------------------------------------
        NagiosEventNotifier notifier = new NagiosEventNotifier();
        notifier.getConfiguration().setHost("localhost");
        notifier.getConfiguration().setPort(5667);
        notifier.getConfiguration().setPassword("password");

        CamelContext context = ... 
        context.getManagementStrategy().addEventNotifier(notifier);
        return context;
-------------------------------------------------------------------

In Camel on Spring XML you can declare a `<bean>` which Camel will automatic pickup and use.

[source,xml]
----
<beans>
  <!-- setup to use nagios event notifier -->
  <bean id="nagiosEventNotifier" class="org.apache.camel.component.nagios.NagiosEventNotifier"/>

  <camelContext>
     ...
  </camelContext>
</beans>
----


include::spring-boot:partial$starter.adoc[]
