= Thrift Component
:doctitle: Thrift
:shortname: thrift
:artifactid: camel-thrift
:description: Call and expose remote procedures (RPC) with Apache Thrift data format and serialization mechanism.
:since: 2.20
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:camel-spring-boot-name: thrift

*Since Camel {since}*

*{component-header}*

The Thrift component allows you to call or expose Remote Procedure Call (RPC) services
using https://thrift.apache.org/[Apache Thrift] binary communication protocol and serialization mechanism.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-thrift</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

== URI format

-------------------------------------
thrift://service[?options]
-------------------------------------



// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END

// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

== Thrift method parameters mapping

Parameters in the called procedure must be passed as a list of objects inside the message body. The primitives are converted from the objects on the fly.
In order to correctly find the corresponding method, all types must be transmitted regardless of the values. Please see an exmaple below, how to pass
different parameters to the method with the Camel body
[source,java]
-------------------------------------------------------------------------------
List requestBody = new ArrayList();

requestBody.add((boolean)true);
requestBody.add((byte)THRIFT_TEST_NUM1);
requestBody.add((short)THRIFT_TEST_NUM1);
requestBody.add((int)THRIFT_TEST_NUM1);
requestBody.add((long)THRIFT_TEST_NUM1);
requestBody.add((double)THRIFT_TEST_NUM1);
requestBody.add("empty"); // String parameter
requestBody.add(ByteBuffer.allocate(10)); // binary parameter
requestBody.add(new Work(THRIFT_TEST_NUM1, THRIFT_TEST_NUM2, Operation.MULTIPLY)); // Struct parameter
requestBody.add(new ArrayList<Integer>()); // list paramater 
requestBody.add(new HashSet<String>()); // set parameter
requestBody.add(new HashMap<String, Long>()); // map parameter 

Object responseBody = template.requestBody("direct:thrift-alltypes", requestBody);
-------------------------------------------------------------------------------

Incoming parameters in the service consumer will also be passed to the message body as a list of objects.

== Examples

Below is a simple synchronous method invoke with host and port parameters

[source,java]
-------------------------------------------------------------------------------
from("direct:thrift-calculate")
.to("thrift://localhost:1101/org.apache.camel.component.thrift.generated.Calculator?method=calculate&synchronous=true");
-------------------------------------------------------------------------------

Below is a simple synchronous method invoke for the XML DSL configuration

[source,xml]
---------------------------------------------------------------------------------------
<route>
    <from uri="direct:thrift-add" />
    <to uri="thrift://localhost:1101/org.apache.camel.component.thrift.generated.Calculator?method=add&synchronous=true"/>
</route>
---------------------------------------------------------------------------------------

Thrift service consumer with asynchronous communication

[source,java]
-------------------------------------------------------------------------------
from("thrift://localhost:1101/org.apache.camel.component.thrift.generated.Calculator")
.to("direct:thrift-service");
-------------------------------------------------------------------------------

It's possible to automate Java code generation for .thrift files using *thrift-maven-plugin*, but before start the thrift compiler binary distribution for your operating system must be present on the running host.

== For more information, see these resources

https://github.com/apache/thrift/[Thrift project GitHub]
https://thrift.apache.org/tutorial/java [Apache Thrift Java tutorial]



include::spring-boot:partial$starter.adoc[]
