= SEDA Component
:doctitle: SEDA
:shortname: seda
:artifactid: camel-seda
:description: Asynchronously call another endpoint from any Camel Context in the same JVM.
:since: 1.1
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
:core:
//Manually maintained attributes
:camel-spring-boot-name: seda

*Since Camel {since}*

*{component-header}*

The SEDA component provides asynchronous
https://en.wikipedia.org/wiki/Staged_event-driven_architecture[SEDA] behavior, so that
messages are exchanged on a
http://java.sun.com/j2se/1.5.0/docs/api/java/util/concurrent/BlockingQueue.html[BlockingQueue]
and consumers are invoked in a separate thread from the producer.

Note that queues are only visible within the same CamelContext.

[NOTE]
====
This component does not implement any kind of persistence or recovery
if the JVM terminates while messages are yet to be processed.
If you need persistence, reliability or distributed SEDA, try using xref:jms-component.adoc[JMS].
====

[TIP]
====
*Synchronous*

The xref:direct-component.adoc[Direct] component provides synchronous invocation (uses no threading; it directly invokes the
consumer when sending) of any consumers when a producer sends a message exchange.
====

== URI format

----
seda:someId[?options]
----

Where _someId_ can be any string that uniquely identifies the endpoint
within the current CamelContext.


// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
include::partial$component-endpoint-headers.adoc[]
// component options: END

== Usage

=== Choosing BlockingQueue implementation

By default, the SEDA component always instantiates a `LinkedBlockingQueue`,
but you can use different implementation, you can reference your own
`BlockingQueue` implementation, in this case the size option is not used:

[source,xml]
----
<bean id="arrayQueue" class="java.util.ArrayBlockingQueue">
  <constructor-arg index="0" value="10" /><!-- size -->
  <constructor-arg index="1" value="true" /><!-- fairness -->
</bean>

<!-- ... and later -->
<from>seda:array?queue=#arrayQueue</from>
----

You can also reference a `BlockingQueueFactory` implementation.
Three implementations are provided:

* `LinkedBlockingQueueFactory`
* `ArrayBlockingQueueFactory`
* `PriorityBlockingQueueFactory`

[source,xml]
----
<bean id="priorityQueueFactory" class="org.apache.camel.component.seda.PriorityBlockingQueueFactory">
  <property name="comparator">
    <bean class="org.apache.camel.demo.MyExchangeComparator" />
  </property>
</bean>

<!-- ... and later -->
<from>seda:priority?queueFactory=#priorityQueueFactory&size=100</from>
----

=== Use of Request Reply

The xref:seda-component.adoc[SEDA] component supports using
Request Reply, where the caller will wait for
the Async route to complete. For instance:

[tabs]
====
Java::
+
[source,java]
----
from("mina:tcp://0.0.0.0:9876?textline=true&sync=true").to("seda:input");

from("seda:input").to("bean:processInput").to("bean:createResponse");
----

XML::
+
[source,xml]
----
<route>
  <from uri="mina:tcp://0.0.0.0:9876?textline=true&amp;sync=true"/>
  <to uri="seda:input"/>
</route>
<route>
  <from uri="seda:input"/>
  <to uri="bean:processInput"/>
  <to uri="bean:createResponse"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: mina:tcp://0.0.0.0:9876
      parameters:
        textline: true
        sync: true
      steps:
        - to:
            uri: seda:input
- route:
    from:
      uri: seda:input
      steps:
        - to:
            uri: bean:processInput
        - to:
            uri: bean:createResponse
----
====

In the route above, we have a TCP listener on port 9876 that accepts
incoming requests. The request is routed to the `seda:input` queue. As
it is a Request Reply message, we wait for the
response. When the consumer on the `seda:input` queue is complete, it
copies the response to the original message response.

=== Concurrent consumers

By default, the SEDA endpoint uses a single consumer thread, but you can
configure it to use concurrent consumer threads. So instead of thread
 pools, you can use:

[tabs]
====
Java::
+
[source,java]
----
from("seda:stageName?concurrentConsumers=5").process(...)
----

XML::
+
[source,xml]
----
<from uri="seda:stageName?concurrentConsumers=5"/>
----

YAML::
+
[source,yaml]
----
from:
  uri: seda:stageName
  parameters:
    concurrentConsumers: 5
----
====

As for the difference between the two, note a _thread pool_ can
increase/shrink dynamically at runtime depending on load, whereas the
number of concurrent consumers is always fixed.

=== Thread pools

Be aware that adding a thread pool to a SEDA endpoint by doing something
like:

._Java-only: thread pool added to SEDA endpoint_
[source,java]
----
from("seda:stageName").thread(5).process(...)
----

Can wind up with two `BlockQueues`: one from the SEDA endpoint, and one
from the work queue of the thread pool, which may not be what you want.
Instead, you might wish to configure a xref:direct-component.adoc[Direct] endpoint
with a thread pool, which can process messages both synchronously and
asynchronously. For example:

._Java-only: thread pool on a Direct endpoint_
[source,java]
----
from("direct:stageName").thread(5).process(...)
----

You can also directly configure number of threads that process messages
on a SEDA endpoint using the `concurrentConsumers` option.

== Examples

In the route below, we use the SEDA queue to send the request to this
async queue.
As such, it is able to send a _fire-and-forget_ message for further
processing in another thread, and return a constant reply in this thread
to the original caller.

We send a _Hello World_ message and expect the reply to be _OK_.

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .to("seda:next")
    .transform(constant("OK"));

from("seda:next").to("mock:result");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:start"/>
  <to uri="seda:next"/>
  <transform>
    <constant>OK</constant>
  </transform>
</route>
<route>
  <from uri="seda:next"/>
  <to uri="mock:result"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
      steps:
        - to:
            uri: seda:next
        - transform:
            constant: "OK"
- route:
    from:
      uri: seda:next
      steps:
        - to:
            uri: mock:result
----
====

The _Hello World_ message will be consumed from the SEDA queue from
another thread for further processing. Since this is from a unit test,
it will be sent to a `mock` endpoint where we can do assertions in the
unit test.

=== Using multipleConsumers

In this example, we have defined two consumers.

[tabs]
====
Java::
+
[source,java]
----
from("seda:foo?multipleConsumers=true").routeId("foo").to("mock:foo");
from("seda:foo?multipleConsumers=true").routeId("bar").to("mock:bar");
----

XML::
+
[source,xml]
----
<route id="foo">
  <from uri="seda:foo?multipleConsumers=true"/>
  <to uri="mock:foo"/>
</route>
<route id="bar">
  <from uri="seda:foo?multipleConsumers=true"/>
  <to uri="mock:bar"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    id: foo
    from:
      uri: seda:foo
      parameters:
        multipleConsumers: true
      steps:
        - to:
            uri: mock:foo
- route:
    id: bar
    from:
      uri: seda:foo
      parameters:
        multipleConsumers: true
      steps:
        - to:
            uri: mock:bar
----
====

Since we have specified `multipleConsumers=true` on the seda `foo`
endpoint we can have those two consumers receive their own copy of the
message as a kind of _publish/subscribe_ style messaging.

=== Extracting queue information.

If needed, information such as queue size, etc. can be obtained without
using JMX in this fashion:

._Java-only: programmatic access to `SedaEndpoint` internals_
[source,java]
----
SedaEndpoint seda = context.getEndpoint("seda:xxxx");
int size = seda.getExchanges().size();
----



include::spring-boot:partial$starter.adoc[]
