= AWS Elastic Container Service (ECS) Component
:doctitle: AWS Elastic Container Service (ECS)
:shortname: aws2-ecs
:artifactid: camel-aws2-ecs
:description: Manage AWS ECS cluster instances.
:since: 3.1
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported
//Manually maintained attributes
:group: AWS
:camel-spring-boot-name: aws2-ecs

*Since Camel {since}*

*{component-header}*

The AWS2 ECS component supports create, delete, describe and list clusters
https://aws.amazon.com/ecs/[AWS ECS] clusters instances.

Prerequisites

You must have a valid Amazon Web Services developer account, and be
signed up to use Amazon ECS. More information is available at
https://aws.amazon.com/ecs/[Amazon ECS].

== URI Format

-------------------------
aws2-ecs://label[?options]
-------------------------

You can append query options to the URI in the following format,
?options=value&option2=value&...


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END

Required ECS component options

You have to provide the amazonECSClient in the
Registry or your accessKey and secretKey to access
the https://aws.amazon.com/ecs/[Amazon ECS] service.

== Usage

=== Static credentials, Default Credential Provider and Profile Credentials Provider

You have the possibility of avoiding the usage of explicit static credentials, by specifying the useDefaultCredentialsProvider option and set it to true.

The order of evaluation for Default Credentials Provider is the following:

 - Java system properties - aws.accessKeyId and aws.secretKey
 - Environment variables - AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY.
 - Web Identity Token from AWS STS.
 - The shared credentials and config files.
 - Amazon ECS container credentials - loaded from the Amazon ECS if the environment variable AWS_CONTAINER_CREDENTIALS_RELATIVE_URI is set.
 - Amazon EC2 Instance profile credentials. 

You have also the possibility of using Profile Credentials Provider, by specifying the useProfileCredentialsProvider option to true and profileCredentialsName to the profile name.

Only one of static, default and profile credentials could be used at the same time.

For more information about this you can look at https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials.html[AWS credentials documentation]

// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

=== ECS Producer operations

Camel-AWS ECS component provides the following operation on the producer side:

- listClusters
- createCluster
- describeCluster
- deleteCluster

== Producer Examples

- listClusters: this operation will list the available clusters in ECS

[source,java]
--------------------------------------------------------------------------------
from("direct:listClusters")
    .to("aws2-ecs://test?ecsClient=#amazonEcsClient&operation=listClusters")
--------------------------------------------------------------------------------

== Using a POJO as body

Sometimes build an AWS Request can be complex, because of multiple options. We introduce the possibility to use a POJO as body.
In AWS ECS there are multiple operations you can submit, as an example for List cluster request, you can do something like:

[source,java]
------------------------------------------------------------------------------------------------------
from("direct:start")
  .setBody(ListClustersRequest.builder().maxResults(10).build())
  .to("aws2-ecs://test?ecsClient=#amazonEcsClient&operation=listClusters&pojoRequest=true")
------------------------------------------------------------------------------------------------------

In this way you'll pass the request directly without the need of passing headers and options specifically related to this operation.

== Dependencies

Maven users will need to add the following dependency to their pom.xml.

*pom.xml*

[source,xml]
---------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-aws2-ecs</artifactId>
    <version>${camel-version}</version>
</dependency>
---------------------------------------

where `$\{camel-version}` must be replaced by the actual version of Camel.


include::spring-boot:partial$starter.adoc[]
