= How can I become a committer

First of all you need to get involved and
link:/community/contributing/[Contribute] via the mail list, forums, edit the
documentation, work on the issue tracker and submit patches.

Once you're contributing and your work is good, one of our
link:/community/team/[Team] may invite you to be a committer (after we've
called a vote). When that happens, if you accept, the following process
kicks into place...

Note that becoming a committer is not just about submitting some
patches; its also about helping out on the development and user
link:/community/mailing-list/[Discussion Forums],
helping with documentation and the issue tracker.

When you have done that for a while, then someone from the Camel PMC team
will invite you via email.

== Becoming a committer steps

You will be invited, and the email have instructions how to proceed.

== Getting started at Apache

Firstly add yourself to the link:/community/team/[Team] page

Now go read the instructions on the
http://www.apache.org/dev/new-committers-guide.html[new committers guide].
Its also worth viewing http://www.apache.org/dev.

== More information

You can find more information about being a
http://www.apache.org/dev/committers.html[committer at Apache here].

== Getting Karma in JIRA and GitHub

Mail the dev list and ask for karma for JIRA / GitHub giving them
details of your username you used to register with them both. We can
then grant the necessary karma so you can start grabbing JIRA issues.

