= JSLT Component
:doctitle: JSLT
:shortname: jslt
:artifactid: camel-jslt
:description: Query or transform JSON payloads using JSLT.
:since: 3.1
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported

*Since Camel {since}*

*{component-header}*

The JSLT component allows you to process JSON messages using an
https://github.com/schibsted/jslt[JSLT] expression. This can be
ideal when doing JSON to JSON transformation or querying data.

Maven users will need to add the following dependency to
their `pom.xml` for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-jslt</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------


== URI format

-----------------------
jslt:specName[?options]
-----------------------

Where *specName* is the classpath-local URI of the specification to
invoke; or the complete URL of the remote specification
(e.g.: `\file://folder/myfile.vm`).


// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
include::partial$component-endpoint-headers.adoc[]
// component options: END


== Usage

=== Passing values to JSLT

Camel can supply exchange information as variables when applying a JSLT expression on the body. The available variables from the *Exchange* are:

[width="100%",cols="2,5",options="header"]
|===
| name | value
| headers | The headers of the In message as a json object
| variables |The variables
| exchange.properties | The *Exchange* properties as a json object. `exchange` is the name of the variable and `properties` is the path to the exchange properties. Available if `allowContextMapAll` option is true.
|===

All the values that cannot be converted to json with Jackson are denied and will not be available in the jslt expression.

For example, the header named `type` and the exchange property `instance` can be accessed like

[source,json]
--------------------------------------
{
  "type": $headers.type,
  "instance": $exchange.properties.instance
}
--------------------------------------

== Examples

For example, you could use something like:

[tabs]
====
Java::
+
[source,java]
----
from("activemq:My.Queue")
    .to("jslt:com/acme/MyResponse.json");
----

XML::
+
[source,xml]
----
<route>
  <from uri="activemq:My.Queue"/>
  <to uri="jslt:com/acme/MyResponse.json"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: activemq:My.Queue
      steps:
        - to:
            uri: jslt:com/acme/MyResponse.json
----
====

And a file-based resource:

[tabs]
====
Java::
+
[source,java]
----
from("activemq:My.Queue")
    .to("jslt:file://myfolder/MyResponse.json?contentCache=true")
    .to("activemq:Another.Queue");
----

XML::
+
[source,xml]
----
<route>
  <from uri="activemq:My.Queue"/>
  <to uri="jslt:file://myfolder/MyResponse.json?contentCache=true"/>
  <to uri="activemq:Another.Queue"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: activemq:My.Queue
      steps:
        - to:
            uri: jslt:file://myfolder/MyResponse.json
            parameters:
              contentCache: true
        - to:
            uri: activemq:Another.Queue
----
====

You can also specify which JSLT expression the component should use
dynamically via a header, so, for example:

[tabs]
====
Java::
+
[source,java]
----
from("direct:in")
    .setHeader("CamelJsltResourceUri").constant("path/to/my/spec.json")
    .to("jslt:dummy?allowTemplateFromHeader=true");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:in"/>
  <setHeader name="CamelJsltResourceUri">
    <constant>path/to/my/spec.json</constant>
  </setHeader>
  <to uri="jslt:dummy?allowTemplateFromHeader=true"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:in
      steps:
        - setHeader:
            name: CamelJsltResourceUri
            expression:
              constant:
                expression: path/to/my/spec.json
        - to:
            uri: jslt:dummy
            parameters:
              allowTemplateFromHeader: true
----
====

Or send whole jslt expression via header: (suitable for querying)

[tabs]
====
Java::
+
[source,java]
----
from("direct:in")
    .setHeader("CamelJsltString").constant(".published")
    .to("jslt:dummy?allowTemplateFromHeader=true");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:in"/>
  <setHeader name="CamelJsltString">
    <constant>.published</constant>
  </setHeader>
  <to uri="jslt:dummy?allowTemplateFromHeader=true"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:in
      steps:
        - setHeader:
            name: CamelJsltString
            expression:
              constant:
                expression: ".published"
        - to:
            uri: jslt:dummy
            parameters:
              allowTemplateFromHeader: true
----
====

Passing exchange properties to the jslt expression can be done like this

[tabs]
====
Java::
+
[source,java]
----
from("direct:in")
    .to("jslt:com/acme/MyResponse.json?allowContextMapAll=true");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:in"/>
  <to uri="jslt:com/acme/MyResponse.json?allowContextMapAll=true"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:in
      steps:
        - to:
            uri: jslt:com/acme/MyResponse.json
            parameters:
              allowContextMapAll: true
----
====
