= Language Component
:doctitle: Language
:shortname: language
:artifactid: camel-language
:description: Execute scripts in any of the languages supported by Camel.
:since: 2.5
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported
:core:
//Manually maintained attributes
:camel-spring-boot-name: language

*Since Camel {since}*

*{component-header}*

The Language component allows you to send Exchange
to an endpoint which executes a script by any of the supported
Languages in Camel. +
 By having a component to execute language scripts, it allows more
dynamic routing capabilities. For example by using the
Routing Slip or xref:eips:dynamicRouter-eip.adoc[Dynamic
Router] EIPs you can send messages to `language` endpoints where the
script is dynamic defined as well.

This component is provided out of the box in `camel-core` and hence no
additional JARs is needed. You only have to include additional Camel
components if the language of choice mandates it, such as using
xref:languages:groovy-language.adoc[Groovy] or xref:languages:groovy-language.adoc[JavaScript] languages.

== URI format

----
language://languageName[:script][?options]
----

You can refer to an external resource for
the script using same notation as supported by the other
xref:language-component.adoc[Language]s in Camel

----
language://languageName:resource:scheme:location][?options]
----

// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END

// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

== Examples

For example, you can use the xref:languages:simple-language.adoc[Simple] language to
Message Translator a message:

In case you want to convert the message body type you can do this as
well:

You can also use the xref:languages:groovy-language.adoc[Groovy] language, such as this
example where the input message will by multiplied with 2:

You can also provide the script as a header as shown below. Here we use
xref:languages:xpath-language.adoc[XPath] language to extract the text from the `<foo>`
tag.

[source,java]
----
Object out = producer.requestBodyAndHeader("language:xpath", "<foo>Hello World</foo>", Exchange.LANGUAGE_SCRIPT, "/foo/text()");
assertEquals("Hello World", out);
----

== Loading scripts from resources

You can specify a resource uri for a script to load in either the
endpoint uri, or in the `Exchange.LANGUAGE_SCRIPT` header.
The uri must start with one of the following schemes: file:, classpath:, or http:

By default, the script is loaded once and cached. However, you can disable
the `contentCache` option and have the script loaded on each
evaluation. For example if the file myscript.txt is changed on disk, then the
updated script is used:

You can refer to the resource similar to the
other xref:language-component.adoc[Language]s in Camel by prefixing with
`"resource:"` as shown below:


include::spring-boot:partial$starter.adoc[]
