= Log Component
:doctitle: Log
:shortname: log
:artifactid: camel-log
:description: Log messages to the underlying logging mechanism.
:since: 1.1
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported
:core:
//Manually maintained attributes
:camel-spring-boot-name: log

*Since Camel {since}*

*{component-header}*

The Log component logs message exchanges to the underlying logging
mechanism.

Camel uses http://www.slf4j.org/[SLF4J], which allows you to configure
logging via, among others:

* Log4j
* Logback
* Java Util Logging

== URI format

----
log:loggingCategory[?options]
----

Where *loggingCategory* is the name of the logging category to use. You
can append query options to the URI in the following format,
`?option=value&option=value&...`

[NOTE]
====
*Using Logger instance from the Registry*

If there's single instance
of `org.slf4j.Logger` found in the Registry, the *loggingCategory* is no
longer used to create logger instance. The registered instance is used
instead. Also, it is possible to reference particular `Logger` instance
using `?logger=#myLogger` URI parameter. Eventually, if there's no
registered and URI `logger` parameter, the logger instance is created
using *loggingCategory*.
====

For example, a log endpoint typically specifies the logging level using
the `level` option, as follows:

----
log:org.apache.camel.example?level=DEBUG
----

The default logger logs every exchange (_regular logging_). But Camel
also ships with the `Throughput` logger, which is used whenever the
`groupSize` option is specified.

[TIP]
====
There is also a `log` directly in the DSL, but it has a different
purpose. It's meant for lightweight and human logs. See more details at
xref:eips:log-eip.adoc[LogEIP].
====


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END


== Regular logger sample

In the route below we log the incoming orders at `DEBUG` level before
the order is processed:

[source,java]
----
from("activemq:orders").to("log:com.mycompany.order?level=DEBUG").to("bean:processOrder");
----

Or using Spring XML to define the route:

[source,xml]
----
<route>
  <from uri="activemq:orders"/>
  <to uri="log:com.mycompany.order?level=DEBUG"/>
  <to uri="bean:processOrder"/>
</route>
----

== Regular logger with formatter sample

In the route below we log the incoming orders at `INFO` level before the
order is processed.

[source,java]
----
from("activemq:orders").
    to("log:com.mycompany.order?showAll=true&multiline=true").to("bean:processOrder");
----

== Throughput logger with groupSize sample

In the route below we log the throughput of the incoming orders at
`DEBUG` level grouped by 10 messages.

[source,java]
----
from("activemq:orders").
    to("log:com.mycompany.order?level=DEBUG&groupSize=10").to("bean:processOrder");
----

== Throughput logger with groupInterval sample

This route will result in message stats logged every 10s, with an
initial 60s delay, and stats should be displayed even if there isn't any
message traffic.

[source,java]
----
from("activemq:orders").
    to("log:com.mycompany.order?level=DEBUG&groupInterval=10000&groupDelay=60000&groupActiveOnly=false").to("bean:processOrder");
----

The following will be logged:

----
"Received: 1000 new messages, with total 2000 so far. Last group took: 10000 millis which is: 100 messages per second. average: 100"
----

== Masking sensitive information like password

You can enable security masking for logging by setting `logMask` flag to `true`.
Note that this option also affects Log EIP.

To enable mask in Java DSL at CamelContext level:
[source,java]
----
camelContext.setLogMask(true);
----

And in XML:
[source,xml]
----
<camelContext logMask="true">
----

You can also turn it on|off at endpoint level. To enable mask in Java DSL at endpoint level,
add logMask=true option in the URI for the log endpoint:

[source,java]
----
from("direct:start").to("log:foo?logMask=true");
----

And in XML:

[source,xml]
----
<route>
  <from uri="direct:foo"/>
  <to uri="log:foo?logMask=true"/>
</route>
----

`org.apache.camel.support.processor.DefaultMaskingFormatter` is used for the masking by default.
If you want to use a custom masking formatter, put it into registry with the name `CamelCustomLogMask`.
Note that the masking formatter must implement `org.apache.camel.spi.MaskingFormatter`.

== Full customization of the logging output

With the options outlined in the xref:log-component.adoc[#Formatting] section, you
can control much of the output of the logger. However, log lines will
always follow this structure:

----
Exchange[Id:ID-machine-local-50656-1234567901234-1-2, ExchangePattern:InOut, 
Properties:{CamelToEndpoint=log://org.apache.camel.component.log.TEST?showAll=true, 
CamelCreatedTimestamp=Thu Mar 28 00:00:00 WET 2013}, 
Headers:{breadcrumbId=ID-machine-local-50656-1234567901234-1-1}, BodyType:String, Body:Hello World, Out: null]
----

This format is unsuitable in some cases, perhaps because you need to...

* ... filter the headers and properties that are printed, to strike a
balance between insight and verbosity.
* ... adjust the log message to whatever you deem most readable.
* ... tailor log messages for digestion by log mining systems, e.g.
Splunk.
* ... print specific body types differently.
* ... etc.

Whenever you require absolute customization, you can create a class that
implements the
https://www.javadoc.io/doc/org.apache.camel/camel-api/current/org/apache/camel/spi/ExchangeFormatter.html[`ExchangeFormatter`]
interface. Within the `format(Exchange)` method you have access to the
full Exchange, so you can select and extract the precise information you
need, format it in a custom manner and return it. The return value will
become the final log message.

You can have the Log component pick up your custom `ExchangeFormatter`
in either of two ways:

*Explicitly instantiating the LogComponent in your Registry:*

[source,xml]
----
<bean name="log" class="org.apache.camel.component.log.LogComponent">
   <property name="exchangeFormatter" ref="myCustomFormatter" />
</bean>
----

=== Convention over configuration:*

Simply by registering a bean with the name `logFormatter`; the Log
Component is intelligent enough to pick it up automatically.

[source,xml]
-----
<bean name="logFormatter" class="com.xyz.MyCustomExchangeFormatter" />
-----

[NOTE]
====
The `ExchangeFormatter` gets applied to *all Log endpoints within
that Camel Context*. If you need different ExchangeFormatters for
different endpoints, instantiate the LogComponent as many times as
needed, and use the relevant bean name as the endpoint prefix.
====


When using a custom log formatter, you
can specify parameters in the log uri, which gets configured on the
custom log formatter. Though when you do that, you should define the
"logFormatter" as prototype scoped, so it's not shared if you have
different parameters, e.g.:

[source,xml]
----
<bean name="logFormatter" class="com.xyz.MyCustomExchangeFormatter" scope="prototype"/>
----

And then we can have Camel routes using the log uri with different
options:

[source,xml]
---------------------------------------------
<to uri="log:foo?param1=foo&amp;param2=100"/>

<to uri="log:bar?param1=bar&amp;param2=200"/>
---------------------------------------------



include::spring-boot:partial$starter.adoc[]
