== Drill Component

*Available as of Camel version 2.19*

The *drill:* component gives you the ability to querying to https://drill.apache.org/[Apache Drill Cluster]

Drill is an Apache open-source SQL query engine for Big Data exploration. Drill is designed from the ground up to support high-performance analysis on the semi-structured and rapidly evolving data coming from modern Big Data applications, while still providing the familiarity and ecosystem of ANSI SQL, the industry-standard query language

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-drill</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

### URI format

[source,java]
--------------------------------
drill://host[?options]
--------------------------------

You can append query options to the URI in the following format,
`?option=value&option=value&...`

### Drill Producer 

The producer execute query using *CamelDrillQuery* header and put results into body.

### Options

// component options: START
The Drill component has no options.
// component options: END



// endpoint options: START
The Drill endpoint is configured using URI syntax:

----
drill:host
----

with the following path and query parameters:

==== Path Parameters (1 parameters):

[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *host* | *Required* ZooKeeper host name or IP address. Use local instead of a host name or IP address to connect to the local Drillbit |  | String
|===

==== Query Parameters (5 parameters):

[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *clusterId* (producer) | Cluster ID https://drill.apache.org/docs/using-the-jdbc-driver/determining-the-cluster-id |  | String
| *directory* (producer) | Drill directory in ZooKeeper |  | String
| *mode* (producer) | Connection mode: zk: Zookeeper drillbit: Drillbit direct connection https://drill.apache.org/docs/using-the-jdbc-driver/ | ZK | DrillConnectionMode
| *port* (producer) | ZooKeeper port number |  | Integer
| *synchronous* (advanced) | Sets whether synchronous processing should be strictly used or Camel is allowed to use asynchronous processing (if supported). | false | boolean
|===
// endpoint options: END

### See Also

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]
