= XQuery Component
:doctitle: XQuery
:shortname: xquery
:artifactid: camel-saxon
:description: Query and/or transform XML payloads using XQuery and Saxon.
:since: 1.0
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:camel-spring-boot-name: saxon

*Since Camel {since}*

*{component-header}*

Camel supports http://www.w3.org/TR/xquery/[XQuery] component for message transformation

// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END


== Examples

[source,java]
---------------------------
from("queue:foo")
  .filter().xquery("//foo")
    .to("queue:bar")
---------------------------

You can also use functions inside your query, in which case you need an
explicit type conversion (or you will get a org.w3c.dom.DOMException:
HIERARCHY_REQUEST_ERR) by passing the Class as a second argument to the
*xquery()* method.

[source,java]
-----------------------------------------------------------------------------
from("direct:start")
  .recipientList().xquery("concat('mock:foo.', /person/@city)", String.class);
-----------------------------------------------------------------------------

== Variables

The IN message body will be set as the `contextItem`. Besides this these
Variables is also added as parameters:

[width="100%",cols="10%,10%,80%",options="header",]
|=======================================================================
|Variable |Type |Description

|exchange |Exchange |The current Exchange

|in.body |Object |The In message's body

|out.body |Object |The OUT message's body (if any)

|in.headers.* |Object |You can access the value of exchange.in.headers with key *foo* by using
the variable which name is in.headers.foo

|out.headers.* |Object |You can access the value of exchange.out.headers with key *foo* by using
the variable which name is out.headers.foo variable

|*key name* |Object |Any exchange.properties and exchange.in.headers and any additional
parameters set using `setParameters(Map)`. These parameters is added
with they own key name, for instance if there is an IN header with the
key name *foo* then its added as *foo*.
|=======================================================================

== Using XML configuration

If you prefer to configure your routes in your Spring
XML file then you can use XPath expressions as follows

[source,xml]
---------------------------------------------------------------------------------------------------------------
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:foo="http://example.com/person"
       xsi:schemaLocation="
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd">

  <camelContext id="camel" xmlns="http://activemq.apache.org/camel/schema/spring">
    <route>
      <from uri="activemq:MyQueue"/>
      <filter>
        <xquery>/foo:person[@name='James']</xquery>
        <to uri="mqseries:SomeOtherQueue"/>
      </filter>
    </route>
  </camelContext>
</beans>
---------------------------------------------------------------------------------------------------------------

Notice how we can reuse the namespace prefixes, *foo* in this case, in
the XPath expression for easier namespace based XQuery expressions!

When you use functions in your XQuery expression you need an explicit
type conversion which is done in the xml configuration via the *@type*
attribute:

[source,xml]
-------------------------------------------------------------------------------
<xquery type="java.lang.String">concat('mock:foo.', /person/@city)</xquery>
-------------------------------------------------------------------------------


== Using XQuery as an endpoint

Sometimes an XQuery expression can be quite large; it can essentally be
used for Templating. So you may want to use an
XQuery Endpoint so you can route using XQuery
templates.

The following example shows how to take a message of an ActiveMQ queue
(MyQueue) and transform it using XQuery and send it to MQSeries.

[source,xml]
-------------------------------------------------------------------------
  <camelContext id="camel" xmlns="http://camel.apache.org/schema/spring">
    <route>
      <from uri="activemq:MyQueue"/>
      <to uri="xquery:com/acme/someTransform.xquery"/>
      <to uri="mqseries:SomeOtherQueue"/>
    </route>
  </camelContext>
-------------------------------------------------------------------------

== Loading script from external resource

You can externalize the script and have Camel load it from a resource
such as `"classpath:"`, `"file:"`, or `"http:"`.
This is done using the following syntax: `"resource:scheme:location"`,
e.g. to refer to a file on the classpath you can do:

[source,java]
------------------------------------------------------------------------------
.setHeader("myHeader").xquery("resource:classpath:myxquery.txt", String.class)
------------------------------------------------------------------------------

== Learning XQuery

XQuery is a very powerful language for querying, searching, sorting and
returning XML. For help learning XQuery try these tutorials

* Mike Kay's http://www.stylusstudio.com/xquery_primer.html[XQuery Primer]
* The W3Schools https://www.w3schools.com/xml/xquery_intro.asp[XQuery Tutorial]

== Dependencies

To use XQuery in your camel routes you need to add the dependency on
*camel-saxon* which implements the XQuery language.

If you use maven you could just add the following to your pom.xml,
substituting the version number for the latest & greatest release.

[source,xml]
--------------------------------------
<dependency>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-saxon</artifactId>
  <version>x.x.x</version>
</dependency>
--------------------------------------


include::spring-boot:partial$starter.adoc[]
