[[fhir-component]]
= FHIR Component
//THIS FILE IS COPIED: EDIT THE SOURCE FILE:
:page-source: components/camel-fhir/camel-fhir-component/src/main/docs/fhir-component.adoc
:docTitle: FHIR
:artifactId: camel-fhir
:description: Exchange information in the healthcare domain using the FHIR (Fast Healthcare Interoperability Resources) standard.
:since: 2.23
:supportLevel: Stable
:component-header: Both producer and consumer are supported
include::{cq-version}@camel-quarkus:ROOT:partial$reference/components/fhir.adoc[opts=optional]

*Since Camel {since}*

*{component-header}*

The FHIR component integrates with the
http://hapifhir.io/[HAPI-FHIR] library which is an open-source implementation of the
http://hl7.org/implement/standards/fhir/[FHIR] (Fast Healthcare Interoperability Resources) specification in Java.

Maven users will need to add the following dependency to their pom.xml
for this component:


[source,xml]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-fhir</artifactId>
    <version>${camel-version}</version>
</dependency>
----

== URI Format

The FHIR Component uses the following URI format:

[source,text]
----
fhir://endpoint-prefix/endpoint?[options]
----

Endpoint prefix can be one of:

* capabilities
* create
* delete
* history
* load-page
* meta
* operation
* patch
* read
* search
* transaction
* update
* validate


// component options: START
The FHIR component supports 27 options, which are listed below.



[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *encoding* (common) | Encoding to use for all request. There are 2 enums and the value can be one of: JSON, XML |  | String
| *fhirVersion* (common) | The FHIR Version to use. There are 6 enums and the value can be one of: DSTU2, DSTU2_HL7ORG, DSTU2_1, DSTU3, R4, R5 | R4 | String
| *log* (common) | Will log every requests and responses | false | boolean
| *prettyPrint* (common) | Pretty print all request | false | boolean
| *serverUrl* (common) | The FHIR server base URL |  | String
| *bridgeErrorHandler* (consumer) | Allows for bridging the consumer to the Camel routing Error Handler, which mean any exceptions occurred while the consumer is trying to pickup incoming messages, or the likes, will now be processed as a message and handled by the routing Error Handler. By default the consumer will use the org.apache.camel.spi.ExceptionHandler to deal with exceptions, that will be logged at WARN or ERROR level and ignored. | false | boolean
| *lazyStartProducer* (producer) | Whether the producer should be started lazy (on the first message). By starting lazy you can use this to allow CamelContext and routes to startup in situations where a producer may otherwise fail during starting and cause the route to fail being started. By deferring this startup to be lazy then the startup failure can be handled during routing messages via Camel's routing error handlers. Beware that when the first message is processed then creating and starting the producer may take a little time and prolong the total processing time of the processing. | false | boolean
| *autowiredEnabled* (advanced) | Whether autowiring is enabled. This is used for automatic autowiring options (the option must be marked as autowired) by looking up in the registry to find if there is a single instance of matching type, which then gets configured on the component. This can be used for automatic configuring JDBC data sources, JMS connection factories, AWS Clients, etc. | true | boolean
| *client* (advanced) | To use the custom client |  | IGenericClient
| *clientFactory* (advanced) | To use the custom client factory |  | IRestfulClientFactory
| *compress* (advanced) | Compresses outgoing (POST/PUT) contents to the GZIP format | false | boolean
| *configuration* (advanced) | To use the shared configuration |  | FhirConfiguration
| *connectionTimeout* (advanced) | How long to try and establish the initial TCP connection (in ms) | 10000 | Integer
| *deferModelScanning* (advanced) | When this option is set, model classes will not be scanned for children until the child list for the given type is actually accessed. | false | boolean
| *fhirContext* (advanced) | FhirContext is an expensive object to create. To avoid creating multiple instances, it can be set directly. |  | FhirContext
| *forceConformanceCheck* (advanced) | Force conformance check | false | boolean
| *sessionCookie* (advanced) | HTTP session cookie to add to every request |  | String
| *socketTimeout* (advanced) | How long to block for individual read/write operations (in ms) | 10000 | Integer
| *summary* (advanced) | Request that the server modify the response using the _summary param. There are 5 enums and the value can be one of: COUNT, TEXT, DATA, TRUE, FALSE |  | String
| *validationMode* (advanced) | When should Camel validate the FHIR Server's conformance statement. There are 2 enums and the value can be one of: NEVER, ONCE | ONCE | String
| *proxyHost* (proxy) | The proxy host |  | String
| *proxyPassword* (proxy) | The proxy password |  | String
| *proxyPort* (proxy) | The proxy port |  | Integer
| *proxyUser* (proxy) | The proxy username |  | String
| *accessToken* (security) | OAuth access token |  | String
| *password* (security) | Username to use for basic authentication |  | String
| *username* (security) | Username to use for basic authentication |  | String
|===
// component options: END


// endpoint options: START
The FHIR endpoint is configured using URI syntax:

----
fhir:apiName/methodName
----

with the following path and query parameters:

=== Path Parameters (2 parameters):


[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *apiName* | *Required* What kind of operation to perform. There are 13 enums and the value can be one of: CAPABILITIES, CREATE, DELETE, HISTORY, LOAD_PAGE, META, OPERATION, PATCH, READ, SEARCH, TRANSACTION, UPDATE, VALIDATE |  | FhirApiName
| *methodName* | *Required* What sub operation to use for the selected operation |  | String
|===


=== Query Parameters (45 parameters):


[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *encoding* (common) | Encoding to use for all request. There are 2 enums and the value can be one of: JSON, XML |  | String
| *fhirVersion* (common) | The FHIR Version to use. There are 6 enums and the value can be one of: DSTU2, DSTU2_HL7ORG, DSTU2_1, DSTU3, R4, R5 | R4 | String
| *inBody* (common) | Sets the name of a parameter to be passed in the exchange In Body |  | String
| *log* (common) | Will log every requests and responses | false | boolean
| *prettyPrint* (common) | Pretty print all request | false | boolean
| *serverUrl* (common) | The FHIR server base URL |  | String
| *bridgeErrorHandler* (consumer) | Allows for bridging the consumer to the Camel routing Error Handler, which mean any exceptions occurred while the consumer is trying to pickup incoming messages, or the likes, will now be processed as a message and handled by the routing Error Handler. By default the consumer will use the org.apache.camel.spi.ExceptionHandler to deal with exceptions, that will be logged at WARN or ERROR level and ignored. | false | boolean
| *sendEmptyMessageWhenIdle* (consumer) | If the polling consumer did not poll any files, you can enable this option to send an empty message (no body) instead. | false | boolean
| *exceptionHandler* (consumer) | To let the consumer use a custom ExceptionHandler. Notice if the option bridgeErrorHandler is enabled then this option is not in use. By default the consumer will deal with exceptions, that will be logged at WARN or ERROR level and ignored. |  | ExceptionHandler
| *exchangePattern* (consumer) | Sets the exchange pattern when the consumer creates an exchange. There are 3 enums and the value can be one of: InOnly, InOut, InOptionalOut |  | ExchangePattern
| *pollStrategy* (consumer) | A pluggable org.apache.camel.PollingConsumerPollingStrategy allowing you to provide your custom implementation to control error handling usually occurred during the poll operation before an Exchange have been created and being routed in Camel. |  | PollingConsumerPollStrategy
| *lazyStartProducer* (producer) | Whether the producer should be started lazy (on the first message). By starting lazy you can use this to allow CamelContext and routes to startup in situations where a producer may otherwise fail during starting and cause the route to fail being started. By deferring this startup to be lazy then the startup failure can be handled during routing messages via Camel's routing error handlers. Beware that when the first message is processed then creating and starting the producer may take a little time and prolong the total processing time of the processing. | false | boolean
| *client* (advanced) | To use the custom client |  | IGenericClient
| *clientFactory* (advanced) | To use the custom client factory |  | IRestfulClientFactory
| *compress* (advanced) | Compresses outgoing (POST/PUT) contents to the GZIP format | false | boolean
| *connectionTimeout* (advanced) | How long to try and establish the initial TCP connection (in ms) | 10000 | Integer
| *deferModelScanning* (advanced) | When this option is set, model classes will not be scanned for children until the child list for the given type is actually accessed. | false | boolean
| *fhirContext* (advanced) | FhirContext is an expensive object to create. To avoid creating multiple instances, it can be set directly. |  | FhirContext
| *forceConformanceCheck* (advanced) | Force conformance check | false | boolean
| *sessionCookie* (advanced) | HTTP session cookie to add to every request |  | String
| *socketTimeout* (advanced) | How long to block for individual read/write operations (in ms) | 10000 | Integer
| *summary* (advanced) | Request that the server modify the response using the _summary param. There are 5 enums and the value can be one of: COUNT, TEXT, DATA, TRUE, FALSE |  | String
| *synchronous* (advanced) | Sets whether synchronous processing should be strictly used, or Camel is allowed to use asynchronous processing (if supported). | false | boolean
| *validationMode* (advanced) | When should Camel validate the FHIR Server's conformance statement. There are 2 enums and the value can be one of: NEVER, ONCE | ONCE | String
| *proxyHost* (proxy) | The proxy host |  | String
| *proxyPassword* (proxy) | The proxy password |  | String
| *proxyPort* (proxy) | The proxy port |  | Integer
| *proxyUser* (proxy) | The proxy username |  | String
| *backoffErrorThreshold* (scheduler) | The number of subsequent error polls (failed due some error) that should happen before the backoffMultipler should kick-in. |  | int
| *backoffIdleThreshold* (scheduler) | The number of subsequent idle polls that should happen before the backoffMultipler should kick-in. |  | int
| *backoffMultiplier* (scheduler) | To let the scheduled polling consumer backoff if there has been a number of subsequent idles/errors in a row. The multiplier is then the number of polls that will be skipped before the next actual attempt is happening again. When this option is in use then backoffIdleThreshold and/or backoffErrorThreshold must also be configured. |  | int
| *delay* (scheduler) | Milliseconds before the next poll. | 500 | long
| *greedy* (scheduler) | If greedy is enabled, then the ScheduledPollConsumer will run immediately again, if the previous run polled 1 or more messages. | false | boolean
| *initialDelay* (scheduler) | Milliseconds before the first poll starts. | 1000 | long
| *repeatCount* (scheduler) | Specifies a maximum limit of number of fires. So if you set it to 1, the scheduler will only fire once. If you set it to 5, it will only fire five times. A value of zero or negative means fire forever. | 0 | long
| *runLoggingLevel* (scheduler) | The consumer logs a start/complete log line when it polls. This option allows you to configure the logging level for that. There are 6 enums and the value can be one of: TRACE, DEBUG, INFO, WARN, ERROR, OFF | TRACE | LoggingLevel
| *scheduledExecutorService* (scheduler) | Allows for configuring a custom/shared thread pool to use for the consumer. By default each consumer has its own single threaded thread pool. |  | ScheduledExecutorService
| *scheduler* (scheduler) | To use a cron scheduler from either camel-spring or camel-quartz component. Use value spring or quartz for built in scheduler | none | Object
| *schedulerProperties* (scheduler) | To configure additional properties when using a custom scheduler or any of the Quartz, Spring based scheduler. |  | Map
| *startScheduler* (scheduler) | Whether the scheduler should be auto started. | true | boolean
| *timeUnit* (scheduler) | Time unit for initialDelay and delay options. There are 7 enums and the value can be one of: NANOSECONDS, MICROSECONDS, MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS | MILLISECONDS | TimeUnit
| *useFixedDelay* (scheduler) | Controls if fixed delay or fixed rate is used. See ScheduledExecutorService in JDK for details. | true | boolean
| *accessToken* (security) | OAuth access token |  | String
| *password* (security) | Username to use for basic authentication |  | String
| *username* (security) | Username to use for basic authentication |  | String
|===




=== API Parameters (13 APIs):

The FHIR endpoint is an API based component and has additional parameters based on which API name and API method is used.
The API name and API method is located in the endpoint URI as the apiName/methodName path parameters:

----
fhir:apiName/methodName
----

There are 13 API names as listed in the table below:

[width="100%",cols="2,2,6",options="header"]
|===
| API Name | Type | Description
| *capabilities* | Both | API to Fetch the capability statement for the server
| *create* | Both | API for the create operation, which creates a new resource instance on the server
| *delete* | Both | API for the delete operation, which performs a logical delete on a server resource
| *history* | Both | API for the history method
| *load-page* | Both | API that Loads the previous/next bundle of resources from a paged set, using the link specified in the link type=next tag within the atom bundle
| *meta* | Both | API for the meta operations, which can be used to get, add and remove tags and other Meta elements from a resource or across the server
| *operation* | Both | API for extended FHIR operations https://www
| *patch* | Both | API for the patch operation, which performs a logical patch on a server resource
| *read* | Both | API method for read operations
| *search* | Both | API to search for resources matching a given set of criteria
| *transaction* | Both | API for sending a transaction (collection of resources) to the server to be executed as a single unit
| *update* | Both | API for the update operation, which performs a logical delete on a server resource
| *validate* | Both | API for validating resources
|===

Each API is documented in the following sections to come.


==== API: capabilities

*Both producer and consumer are supported*




The capabilities API has 1 method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

[source,java]
----

org.hl7.fhir.instance.model.api.IBaseConformance ofType(Class<org.hl7.fhir.instance.model.api.IBaseConformance> type, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

----

The capabilities API is defined in the syntax as follows:

----
fhir:capabilities/methodName?[parameters]
----

The 1 method(s) is listed in the table below.
(API methods can have a shorthand alias name which can be used in the syntax instead of the name)

[width="100%",cols="2,2,6",options="header"]
|===
| Method | Alias | Description
| *ofType* |  | Retrieve the conformance statement using the given model type
|===

The capabilities API method(s) has the following set of parameters listed in the table below:
[width="100%",cols="2,2,4,2",options="header"]
|===
| Method | Parameter | Description | Type
| ofType | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| ofType | *type* |  The model type | Class
|===

In addition to the parameters above, the capabilities API can also use from the 45 endpoint query option
which is listed in the _Query Parameters_ section.

Any of the parameters can be provided in either the endpoint URI, or dynamically in a message header.
The message header name must be of the format `CamelFhir.parameter`.
The `inBody` parameter overrides message header, i.e. the endpoint parameter `inBody=myParameterNameHere`
would override a `CamelFhir.myParameterNameHere` header.



==== API: create

*Both producer and consumer are supported*




The create API has 1 method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

[source,java]
----

ca.uhn.fhir.rest.api.MethodOutcome resource(String resourceAsString, String url, ca.uhn.fhir.rest.api.PreferReturnEnum preferReturn, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

ca.uhn.fhir.rest.api.MethodOutcome resource(org.hl7.fhir.instance.model.api.IBaseResource resource, String url, ca.uhn.fhir.rest.api.PreferReturnEnum preferReturn, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

----

The create API is defined in the syntax as follows:

----
fhir:create/methodName?[parameters]
----

The 1 method(s) is listed in the table below.
(API methods can have a shorthand alias name which can be used in the syntax instead of the name)

[width="100%",cols="2,2,6",options="header"]
|===
| Method | Alias | Description
| *resource* |  | Creates a IBaseResource on the server
|===

The create API method(s) has the following set of parameters listed in the table below:
[width="100%",cols="2,2,4,2",options="header"]
|===
| Method | Parameter | Description | Type
| resource | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| resource | *preferReturn* | *Optional*  Add a Prefer header to the request, which requests that the server include or suppress the resource body as a part of the result. If a resource is returned by the server it will be parsed an accessible to the client via MethodOutcome#getResource() , may be null | PreferReturnEnum
| resource | *resource* |  The resource to create | IBaseResource
| resource | *resourceAsString* |  The resource to create | String
| resource | *url* | *Optional*  The search URL to use. The format of this URL should be of the form ResourceTypeParameters, for example: Patientname=Smith&amp;identifier=13.2.4.11.4%7C847366, may be null | String
|===

In addition to the parameters above, the create API can also use from the 45 endpoint query option
which is listed in the _Query Parameters_ section.

Any of the parameters can be provided in either the endpoint URI, or dynamically in a message header.
The message header name must be of the format `CamelFhir.parameter`.
The `inBody` parameter overrides message header, i.e. the endpoint parameter `inBody=myParameterNameHere`
would override a `CamelFhir.myParameterNameHere` header.



==== API: delete

*Both producer and consumer are supported*




The delete API has 3 method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

[source,java]
----

org.hl7.fhir.instance.model.api.IBaseOperationOutcome resource(org.hl7.fhir.instance.model.api.IBaseResource resource, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseOperationOutcome resourceById(String type, String stringId, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseOperationOutcome resourceById(org.hl7.fhir.instance.model.api.IIdType id, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseOperationOutcome resourceConditionalByUrl(String url, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

----

The delete API is defined in the syntax as follows:

----
fhir:delete/methodName?[parameters]
----

The 3 method(s) is listed in the table below.
(API methods can have a shorthand alias name which can be used in the syntax instead of the name)

[width="100%",cols="2,2,6",options="header"]
|===
| Method | Alias | Description
| *resource* |  | Deletes the given resource
| *resourceById* |  | Deletes the resource by resource type e
| *resourceConditionalByUrl* |  | Specifies that the delete should be performed as a conditional delete against a given search URL
|===

The delete API method(s) has the following set of parameters listed in the table below:
[width="100%",cols="2,2,4,2",options="header"]
|===
| Method | Parameter | Description | Type
| resource | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| resource | *resource* |  The IBaseResource to delete | IBaseResource
| resourceById | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| resourceById | *id* |  The IIdType referencing the resource | IIdType
| resourceById | *stringId* |  It's id | String
| resourceById | *type* |  The resource type e.g Patient | String
| resourceConditionalByUrl | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| resourceConditionalByUrl | *url* |  The search URL to use. The format of this URL should be of the form ResourceTypeParameters, for example: Patientname=Smith&amp;identifier=13.2.4.11.4%7C847366 | String
|===

In addition to the parameters above, the delete API can also use from the 45 endpoint query option
which is listed in the _Query Parameters_ section.

Any of the parameters can be provided in either the endpoint URI, or dynamically in a message header.
The message header name must be of the format `CamelFhir.parameter`.
The `inBody` parameter overrides message header, i.e. the endpoint parameter `inBody=myParameterNameHere`
would override a `CamelFhir.myParameterNameHere` header.



==== API: history

*Both producer and consumer are supported*




The history API has 3 method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

[source,java]
----

org.hl7.fhir.instance.model.api.IBaseBundle onInstance(org.hl7.fhir.instance.model.api.IIdType id, Class<org.hl7.fhir.instance.model.api.IBaseBundle> returnType, Integer count, java.util.Date cutoff, org.hl7.fhir.instance.model.api.IPrimitiveType<java.util.Date> iCutoff, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseBundle onServer(Class<org.hl7.fhir.instance.model.api.IBaseBundle> returnType, Integer count, java.util.Date cutoff, org.hl7.fhir.instance.model.api.IPrimitiveType<java.util.Date> iCutoff, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseBundle onType(Class<org.hl7.fhir.instance.model.api.IBaseResource> resourceType, Class<org.hl7.fhir.instance.model.api.IBaseBundle> returnType, Integer count, java.util.Date cutoff, org.hl7.fhir.instance.model.api.IPrimitiveType<java.util.Date> iCutoff, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

----

The history API is defined in the syntax as follows:

----
fhir:history/methodName?[parameters]
----

The 3 method(s) is listed in the table below.
(API methods can have a shorthand alias name which can be used in the syntax instead of the name)

[width="100%",cols="2,2,6",options="header"]
|===
| Method | Alias | Description
| *onInstance* |  | Perform the operation across all versions of a specific resource (by ID and type) on the server
| *onServer* |  | Perform the operation across all versions of all resources of all types on the server
| *onType* |  | Perform the operation across all versions of all resources of the given type on the server
|===

The history API method(s) has the following set of parameters listed in the table below:
[width="100%",cols="2,2,4,2",options="header"]
|===
| Method | Parameter | Description | Type
| onInstance | *count* | *Optional*  Request that the server return only up to theCount number of resources, may be NULL | Integer
| onInstance | *cutoff* | *Optional*  Request that the server return only resource versions that were created at or after the given time (inclusive), may be NULL | Date
| onInstance | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| onInstance | *iCutoff* | *Optional*  Request that the server return only resource versions that were created at or after the given time (inclusive), may be NULL | IPrimitiveType
| onInstance | *id* |  The IIdType which must be populated with both a resource type and a resource ID at | IIdType
| onInstance | *returnType* |  Request that the method return a Bundle resource (such as ca.uhn.fhir.model.dstu2.resource.Bundle). Use this method if you are accessing a DSTU2 server. | Class
| onServer | *count* | *Optional*  Request that the server return only up to theCount number of resources, may be NULL | Integer
| onServer | *cutoff* | *Optional*  Request that the server return only resource versions that were created at or after the given time (inclusive), may be NULL | Date
| onServer | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| onServer | *iCutoff* | *Optional*  Request that the server return only resource versions that were created at or after the given time (inclusive), may be NULL | IPrimitiveType
| onServer | *returnType* |  Request that the method return a Bundle resource (such as ca.uhn.fhir.model.dstu2.resource.Bundle). Use this method if you are accessing a DSTU2 server. | Class
| onType | *count* | *Optional*  Request that the server return only up to theCount number of resources, may be NULL | Integer
| onType | *cutoff* | *Optional*  Request that the server return only resource versions that were created at or after the given time (inclusive), may be NULL | Date
| onType | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| onType | *iCutoff* | *Optional*  Request that the server return only resource versions that were created at or after the given time (inclusive), may be NULL | IPrimitiveType
| onType | *resourceType* |  The resource type to search for | Class
| onType | *returnType* |  Request that the method return a Bundle resource (such as ca.uhn.fhir.model.dstu2.resource.Bundle). Use this method if you are accessing a DSTU2 server. | Class
|===

In addition to the parameters above, the history API can also use from the 45 endpoint query option
which is listed in the _Query Parameters_ section.

Any of the parameters can be provided in either the endpoint URI, or dynamically in a message header.
The message header name must be of the format `CamelFhir.parameter`.
The `inBody` parameter overrides message header, i.e. the endpoint parameter `inBody=myParameterNameHere`
would override a `CamelFhir.myParameterNameHere` header.



==== API: load-page

*Both producer and consumer are supported*




The load-page API has 3 method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

[source,java]
----

org.hl7.fhir.instance.model.api.IBaseBundle byUrl(String url, Class<org.hl7.fhir.instance.model.api.IBaseBundle> returnType, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseBundle next(org.hl7.fhir.instance.model.api.IBaseBundle bundle, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseBundle previous(org.hl7.fhir.instance.model.api.IBaseBundle bundle, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

----

The load-page API is defined in the syntax as follows:

----
fhir:load-page/methodName?[parameters]
----

The 3 method(s) is listed in the table below.
(API methods can have a shorthand alias name which can be used in the syntax instead of the name)

[width="100%",cols="2,2,6",options="header"]
|===
| Method | Alias | Description
| *byUrl* |  | Load a page of results using the given URL and bundle type and return a DSTU1 Atom bundle
| *next* |  | Load the next page of results using the link with relation next in the bundle
| *previous* |  | Load the previous page of results using the link with relation prev in the bundle
|===

The load-page API method(s) has the following set of parameters listed in the table below:
[width="100%",cols="2,2,4,2",options="header"]
|===
| Method | Parameter | Description | Type
| byUrl | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| byUrl | *returnType* |  The return type | Class
| byUrl | *url* |  The search url | String
| next | *bundle* |  The IBaseBundle | IBaseBundle
| next | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| previous | *bundle* |  The IBaseBundle | IBaseBundle
| previous | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
|===

In addition to the parameters above, the load-page API can also use from the 45 endpoint query option
which is listed in the _Query Parameters_ section.

Any of the parameters can be provided in either the endpoint URI, or dynamically in a message header.
The message header name must be of the format `CamelFhir.parameter`.
The `inBody` parameter overrides message header, i.e. the endpoint parameter `inBody=myParameterNameHere`
would override a `CamelFhir.myParameterNameHere` header.



==== API: meta

*Both producer and consumer are supported*




The meta API has 5 method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

[source,java]
----

org.hl7.fhir.instance.model.api.IBaseMetaType add(org.hl7.fhir.instance.model.api.IBaseMetaType meta, org.hl7.fhir.instance.model.api.IIdType id, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseMetaType delete(org.hl7.fhir.instance.model.api.IBaseMetaType meta, org.hl7.fhir.instance.model.api.IIdType id, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseMetaType getFromResource(Class<org.hl7.fhir.instance.model.api.IBaseMetaType> metaType, org.hl7.fhir.instance.model.api.IIdType id, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseMetaType getFromServer(Class<org.hl7.fhir.instance.model.api.IBaseMetaType> metaType, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseMetaType getFromType(Class<org.hl7.fhir.instance.model.api.IBaseMetaType> metaType, String resourceType, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

----

The meta API is defined in the syntax as follows:

----
fhir:meta/methodName?[parameters]
----

The 5 method(s) is listed in the table below.
(API methods can have a shorthand alias name which can be used in the syntax instead of the name)

[width="100%",cols="2,2,6",options="header"]
|===
| Method | Alias | Description
| *add* |  | Add the elements in the given metadata to the already existing set (do not remove any)
| *delete* |  | Delete the elements in the given metadata from the given id
| *getFromResource* |  | Fetch the current metadata from a specific resource
| *getFromServer* |  | Fetch the current metadata from the whole Server
| *getFromType* |  | Fetch the current metadata from a specific type
|===

The meta API method(s) has the following set of parameters listed in the table below:
[width="100%",cols="2,2,4,2",options="header"]
|===
| Method | Parameter | Description | Type
| add | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| add | *id* |  The id | IIdType
| add | *meta* |  The IBaseMetaType class | IBaseMetaType
| delete | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| delete | *id* |  The id | IIdType
| delete | *meta* |  The IBaseMetaType class | IBaseMetaType
| getFromResource | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| getFromResource | *id* |  The id | IIdType
| getFromResource | *metaType* |  The IBaseMetaType class | Class
| getFromServer | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| getFromServer | *metaType* |  The type of the meta datatype for the given FHIR model version (should be MetaDt.class or MetaType.class) | Class
| getFromType | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| getFromType | *metaType* |  The IBaseMetaType class | Class
| getFromType | *resourceType* |  The resource type e.g Patient | String
|===

In addition to the parameters above, the meta API can also use from the 45 endpoint query option
which is listed in the _Query Parameters_ section.

Any of the parameters can be provided in either the endpoint URI, or dynamically in a message header.
The message header name must be of the format `CamelFhir.parameter`.
The `inBody` parameter overrides message header, i.e. the endpoint parameter `inBody=myParameterNameHere`
would override a `CamelFhir.myParameterNameHere` header.



==== API: operation

*Both producer and consumer are supported*




The operation API has 5 method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

[source,java]
----

org.hl7.fhir.instance.model.api.IBaseResource onInstance(org.hl7.fhir.instance.model.api.IIdType id, String name, org.hl7.fhir.instance.model.api.IBaseParameters parameters, Class<org.hl7.fhir.instance.model.api.IBaseParameters> outputParameterType, boolean useHttpGet, Class<org.hl7.fhir.instance.model.api.IBaseResource> returnType, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseResource onInstanceVersion(org.hl7.fhir.instance.model.api.IIdType id, String name, org.hl7.fhir.instance.model.api.IBaseParameters parameters, Class<org.hl7.fhir.instance.model.api.IBaseParameters> outputParameterType, boolean useHttpGet, Class<org.hl7.fhir.instance.model.api.IBaseResource> returnType, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseResource onServer(String name, org.hl7.fhir.instance.model.api.IBaseParameters parameters, Class<org.hl7.fhir.instance.model.api.IBaseParameters> outputParameterType, boolean useHttpGet, Class<org.hl7.fhir.instance.model.api.IBaseResource> returnType, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseResource onType(Class<org.hl7.fhir.instance.model.api.IBaseResource> resourceType, String name, org.hl7.fhir.instance.model.api.IBaseParameters parameters, Class<org.hl7.fhir.instance.model.api.IBaseParameters> outputParameterType, boolean useHttpGet, Class<org.hl7.fhir.instance.model.api.IBaseResource> returnType, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseBundle processMessage(String respondToUri, org.hl7.fhir.instance.model.api.IBaseBundle msgBundle, boolean asynchronous, Class<org.hl7.fhir.instance.model.api.IBaseBundle> responseClass, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

----

The operation API is defined in the syntax as follows:

----
fhir:operation/methodName?[parameters]
----

The 5 method(s) is listed in the table below.
(API methods can have a shorthand alias name which can be used in the syntax instead of the name)

[width="100%",cols="2,2,6",options="header"]
|===
| Method | Alias | Description
| *onInstance* |  | Perform the operation across all versions of a specific resource (by ID and type) on the server
| *onInstanceVersion* |  | This operation operates on a specific version of a resource
| *onServer* |  | Perform the operation across all versions of all resources of all types on the server
| *onType* |  | Perform the operation across all versions of all resources of the given type on the server
| *processMessage* |  | This operation is called $process-message as defined by the FHIR specification
|===

The operation API method(s) has the following set of parameters listed in the table below:
[width="100%",cols="2,2,4,2",options="header"]
|===
| Method | Parameter | Description | Type
| onInstance | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| onInstance | *id* |  Resource (version will be stripped) | IIdType
| onInstance | *name* |  Operation name | String
| onInstance | *outputParameterType* | *Optional*  The type to use for the output parameters (this should be set to Parameters.class drawn from the version of the FHIR structures you are using), may be NULL | Class
| onInstance | *parameters* | *Optional*  The parameters to use as input. May also be null if the operation does not require any input parameters. | IBaseParameters
| onInstance | *returnType* | *Optional*  If this operation returns a single resource body as its return type instead of a Parameters resource, use this method to specify that resource type. This is useful for certain operations (e.g. Patient/NNN/$everything) which return a bundle instead of a Parameters resource, may be NULL | Class
| onInstance | *useHttpGet* |  Use HTTP GET verb | Boolean
| onInstanceVersion | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| onInstanceVersion | *id* |  Resource version | IIdType
| onInstanceVersion | *name* |  Operation name | String
| onInstanceVersion | *outputParameterType* | *Optional*  The type to use for the output parameters (this should be set to Parameters.class drawn from the version of the FHIR structures you are using), may be NULL | Class
| onInstanceVersion | *parameters* | *Optional*  The parameters to use as input. May also be null if the operation does not require any input parameters. | IBaseParameters
| onInstanceVersion | *returnType* | *Optional*  If this operation returns a single resource body as its return type instead of a Parameters resource, use this method to specify that resource type. This is useful for certain operations (e.g. Patient/NNN/$everything) which return a bundle instead of a Parameters resource, may be NULL | Class
| onInstanceVersion | *useHttpGet* |  Use HTTP GET verb | Boolean
| onServer | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| onServer | *name* |  Operation name | String
| onServer | *outputParameterType* | *Optional*  The type to use for the output parameters (this should be set to Parameters.class drawn from the version of the FHIR structures you are using), may be NULL | Class
| onServer | *parameters* | *Optional*  The parameters to use as input. May also be null if the operation does not require any input parameters. | IBaseParameters
| onServer | *returnType* | *Optional*  If this operation returns a single resource body as its return type instead of a Parameters resource, use this method to specify that resource type. This is useful for certain operations (e.g. Patient/NNN/$everything) which return a bundle instead of a Parameters resource, may be NULL | Class
| onServer | *useHttpGet* |  Use HTTP GET verb | Boolean
| onType | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| onType | *name* |  Operation name | String
| onType | *outputParameterType* | *Optional*  The type to use for the output parameters (this should be set to Parameters.class drawn from the version of the FHIR structures you are using), may be NULL | Class
| onType | *parameters* | *Optional*  The parameters to use as input. May also be null if the operation does not require any input parameters. | IBaseParameters
| onType | *resourceType* |  The resource type to operate on | Class
| onType | *returnType* | *Optional*  If this operation returns a single resource body as its return type instead of a Parameters resource, use this method to specify that resource type. This is useful for certain operations (e.g. Patient/NNN/$everything) which return a bundle instead of a Parameters resource, may be NULL | Class
| onType | *useHttpGet* |  Use HTTP GET verb | Boolean
| processMessage | *asynchronous* |  Whether to process the message asynchronously or synchronously, defaults to synchronous. | Boolean
| processMessage | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| processMessage | *msgBundle* |  Set the Message Bundle to POST to the messaging server | IBaseBundle
| processMessage | *respondToUri* | *Optional*  An optional query parameter indicating that responses from the receiving server should be sent to this URI, may be NULL | String
| processMessage | *responseClass* |  The response class | Class
|===

In addition to the parameters above, the operation API can also use from the 45 endpoint query option
which is listed in the _Query Parameters_ section.

Any of the parameters can be provided in either the endpoint URI, or dynamically in a message header.
The message header name must be of the format `CamelFhir.parameter`.
The `inBody` parameter overrides message header, i.e. the endpoint parameter `inBody=myParameterNameHere`
would override a `CamelFhir.myParameterNameHere` header.



==== API: patch

*Both producer and consumer are supported*




The patch API has 2 method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

[source,java]
----

ca.uhn.fhir.rest.api.MethodOutcome patchById(String patchBody, String stringId, ca.uhn.fhir.rest.api.PreferReturnEnum preferReturn, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

ca.uhn.fhir.rest.api.MethodOutcome patchById(String patchBody, org.hl7.fhir.instance.model.api.IIdType id, ca.uhn.fhir.rest.api.PreferReturnEnum preferReturn, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

ca.uhn.fhir.rest.api.MethodOutcome patchByUrl(String patchBody, String url, ca.uhn.fhir.rest.api.PreferReturnEnum preferReturn, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

----

The patch API is defined in the syntax as follows:

----
fhir:patch/methodName?[parameters]
----

The 2 method(s) is listed in the table below.
(API methods can have a shorthand alias name which can be used in the syntax instead of the name)

[width="100%",cols="2,2,6",options="header"]
|===
| Method | Alias | Description
| *patchById* |  | Applies the patch to the given resource ID
| *patchByUrl* |  | Specifies that the update should be performed as a conditional create against a given search URL
|===

The patch API method(s) has the following set of parameters listed in the table below:
[width="100%",cols="2,2,4,2",options="header"]
|===
| Method | Parameter | Description | Type
| patchById | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| patchById | *id* |  The resource ID to patch | IIdType
| patchById | *patchBody* |  The body of the patch document serialized in either XML or JSON which conforms to \http://jsonpatch.com/ or \http://tools.ietf.org/html/rfc5261 | String
| patchById | *preferReturn* | *Optional*  Add a Prefer header to the request, which requests that the server include or suppress the resource body as a part of the result. If a resource is returned by the server it will be parsed an accessible to the client via MethodOutcome#getResource() | PreferReturnEnum
| patchById | *stringId* |  The resource ID to patch | String
| patchByUrl | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| patchByUrl | *patchBody* |  The body of the patch document serialized in either XML or JSON which conforms to \http://jsonpatch.com/ or \http://tools.ietf.org/html/rfc5261 | String
| patchByUrl | *preferReturn* | *Optional*  Add a Prefer header to the request, which requests that the server include or suppress the resource body as a part of the result. If a resource is returned by the server it will be parsed an accessible to the client via MethodOutcome#getResource() | PreferReturnEnum
| patchByUrl | *url* |  The search URL to use. The format of this URL should be of the form ResourceTypeParameters, for example: Patientname=Smith&amp;identifier=13.2.4.11.4%7C847366 | String
|===

In addition to the parameters above, the patch API can also use from the 45 endpoint query option
which is listed in the _Query Parameters_ section.

Any of the parameters can be provided in either the endpoint URI, or dynamically in a message header.
The message header name must be of the format `CamelFhir.parameter`.
The `inBody` parameter overrides message header, i.e. the endpoint parameter `inBody=myParameterNameHere`
would override a `CamelFhir.myParameterNameHere` header.



==== API: read

*Both producer and consumer are supported*




The read API has 2 method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

[source,java]
----

org.hl7.fhir.instance.model.api.IBaseResource resourceById(Class<org.hl7.fhir.instance.model.api.IBaseResource> resource, Long longId, String ifVersionMatches, Boolean returnNull, org.hl7.fhir.instance.model.api.IBaseResource returnResource, Boolean throwError, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseResource resourceById(Class<org.hl7.fhir.instance.model.api.IBaseResource> resource, String stringId, String version, String ifVersionMatches, Boolean returnNull, org.hl7.fhir.instance.model.api.IBaseResource returnResource, Boolean throwError, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseResource resourceById(Class<org.hl7.fhir.instance.model.api.IBaseResource> resource, org.hl7.fhir.instance.model.api.IIdType id, String ifVersionMatches, Boolean returnNull, org.hl7.fhir.instance.model.api.IBaseResource returnResource, Boolean throwError, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseResource resourceById(String resourceClass, Long longId, String ifVersionMatches, Boolean returnNull, org.hl7.fhir.instance.model.api.IBaseResource returnResource, Boolean throwError, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseResource resourceById(String resourceClass, String stringId, String ifVersionMatches, String version, Boolean returnNull, org.hl7.fhir.instance.model.api.IBaseResource returnResource, Boolean throwError, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseResource resourceById(String resourceClass, org.hl7.fhir.instance.model.api.IIdType id, String ifVersionMatches, Boolean returnNull, org.hl7.fhir.instance.model.api.IBaseResource returnResource, Boolean throwError, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseResource resourceByUrl(Class<org.hl7.fhir.instance.model.api.IBaseResource> resource, String url, String ifVersionMatches, Boolean returnNull, org.hl7.fhir.instance.model.api.IBaseResource returnResource, Boolean throwError, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseResource resourceByUrl(Class<org.hl7.fhir.instance.model.api.IBaseResource> resource, org.hl7.fhir.instance.model.api.IIdType iUrl, String ifVersionMatches, Boolean returnNull, org.hl7.fhir.instance.model.api.IBaseResource returnResource, Boolean throwError, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseResource resourceByUrl(String resourceClass, String url, String ifVersionMatches, Boolean returnNull, org.hl7.fhir.instance.model.api.IBaseResource returnResource, Boolean throwError, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseResource resourceByUrl(String resourceClass, org.hl7.fhir.instance.model.api.IIdType iUrl, String ifVersionMatches, Boolean returnNull, org.hl7.fhir.instance.model.api.IBaseResource returnResource, Boolean throwError, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

----

The read API is defined in the syntax as follows:

----
fhir:read/methodName?[parameters]
----

The 2 method(s) is listed in the table below.
(API methods can have a shorthand alias name which can be used in the syntax instead of the name)

[width="100%",cols="2,2,6",options="header"]
|===
| Method | Alias | Description
| *resourceById* |  | 
| *resourceByUrl* |  | 
|===

The read API method(s) has the following set of parameters listed in the table below:
[width="100%",cols="2,2,4,2",options="header"]
|===
| Method | Parameter | Description | Type
| resourceById | *extraParameters* | *Optional*   | Map
| resourceById | *id* |   | IIdType
| resourceById | *ifVersionMatches* | *Optional*   | String
| resourceById | *longId* |   | Long
| resourceById | *resource* |   | Class
| resourceById | *resourceClass* |   | String
| resourceById | *returnNull* | *Optional*   | Boolean
| resourceById | *returnResource* | *Optional*   | IBaseResource
| resourceById | *stringId* |   | String
| resourceById | *throwError* | *Optional*   | Boolean
| resourceById | *version* | *Optional*   | String
| resourceByUrl | *extraParameters* | *Optional*   | Map
| resourceByUrl | *iUrl* |   | IIdType
| resourceByUrl | *ifVersionMatches* | *Optional*   | String
| resourceByUrl | *resource* |   | Class
| resourceByUrl | *resourceClass* |   | String
| resourceByUrl | *returnNull* | *Optional*   | Boolean
| resourceByUrl | *returnResource* | *Optional*   | IBaseResource
| resourceByUrl | *throwError* | *Optional*   | Boolean
| resourceByUrl | *url* |   | String
|===

In addition to the parameters above, the read API can also use from the 45 endpoint query option
which is listed in the _Query Parameters_ section.

Any of the parameters can be provided in either the endpoint URI, or dynamically in a message header.
The message header name must be of the format `CamelFhir.parameter`.
The `inBody` parameter overrides message header, i.e. the endpoint parameter `inBody=myParameterNameHere`
would override a `CamelFhir.myParameterNameHere` header.



==== API: search

*Both producer and consumer are supported*




The search API has 1 method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

[source,java]
----

org.hl7.fhir.instance.model.api.IBaseBundle searchByUrl(String url, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

----

The search API is defined in the syntax as follows:

----
fhir:search/methodName?[parameters]
----

The 1 method(s) is listed in the table below.
(API methods can have a shorthand alias name which can be used in the syntax instead of the name)

[width="100%",cols="2,2,6",options="header"]
|===
| Method | Alias | Description
| *searchByUrl* |  | Perform a search directly by URL
|===

The search API method(s) has the following set of parameters listed in the table below:
[width="100%",cols="2,2,4,2",options="header"]
|===
| Method | Parameter | Description | Type
| searchByUrl | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| searchByUrl | *url* |  The URL to search for. Note that this URL may be complete (e.g. \http://example.com/base/Patientname=foo) in which case the client's base URL will be ignored. Or it can be relative (e.g. Patientname=foo) in which case the client's base URL will be used. | String
|===

In addition to the parameters above, the search API can also use from the 45 endpoint query option
which is listed in the _Query Parameters_ section.

Any of the parameters can be provided in either the endpoint URI, or dynamically in a message header.
The message header name must be of the format `CamelFhir.parameter`.
The `inBody` parameter overrides message header, i.e. the endpoint parameter `inBody=myParameterNameHere`
would override a `CamelFhir.myParameterNameHere` header.



==== API: transaction

*Both producer and consumer are supported*




The transaction API has 2 method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

[source,java]
----

String withBundle(String stringBundle, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

org.hl7.fhir.instance.model.api.IBaseBundle withBundle(org.hl7.fhir.instance.model.api.IBaseBundle bundle, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

java.util.List<org.hl7.fhir.instance.model.api.IBaseResource> withResources(java.util.List<org.hl7.fhir.instance.model.api.IBaseResource> resources, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

----

The transaction API is defined in the syntax as follows:

----
fhir:transaction/methodName?[parameters]
----

The 2 method(s) is listed in the table below.
(API methods can have a shorthand alias name which can be used in the syntax instead of the name)

[width="100%",cols="2,2,6",options="header"]
|===
| Method | Alias | Description
| *withBundle* |  | Use the given raw text (should be a Bundle resource) as the transaction input
| *withResources* |  | Use a list of resources as the transaction input
|===

The transaction API method(s) has the following set of parameters listed in the table below:
[width="100%",cols="2,2,4,2",options="header"]
|===
| Method | Parameter | Description | Type
| withBundle | *bundle* |  Bundle to use in the transaction | IBaseBundle
| withBundle | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| withBundle | *stringBundle* |  Bundle to use in the transaction | String
| withResources | *extraParameters* | *Optional*  See ExtraParameters for a full list of parameters that can be passed, may be NULL | Map
| withResources | *resources* |  Resources to use in the transaction | List
|===

In addition to the parameters above, the transaction API can also use from the 45 endpoint query option
which is listed in the _Query Parameters_ section.

Any of the parameters can be provided in either the endpoint URI, or dynamically in a message header.
The message header name must be of the format `CamelFhir.parameter`.
The `inBody` parameter overrides message header, i.e. the endpoint parameter `inBody=myParameterNameHere`
would override a `CamelFhir.myParameterNameHere` header.



==== API: update

*Both producer and consumer are supported*




The update API has 2 method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

[source,java]
----

ca.uhn.fhir.rest.api.MethodOutcome resource(String resourceAsString, String stringId, ca.uhn.fhir.rest.api.PreferReturnEnum preferReturn, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

ca.uhn.fhir.rest.api.MethodOutcome resource(String resourceAsString, org.hl7.fhir.instance.model.api.IIdType id, ca.uhn.fhir.rest.api.PreferReturnEnum preferReturn, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

ca.uhn.fhir.rest.api.MethodOutcome resource(org.hl7.fhir.instance.model.api.IBaseResource resource, String stringId, ca.uhn.fhir.rest.api.PreferReturnEnum preferReturn, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

ca.uhn.fhir.rest.api.MethodOutcome resource(org.hl7.fhir.instance.model.api.IBaseResource resource, org.hl7.fhir.instance.model.api.IIdType id, ca.uhn.fhir.rest.api.PreferReturnEnum preferReturn, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

ca.uhn.fhir.rest.api.MethodOutcome resourceBySearchUrl(String resourceAsString, String url, ca.uhn.fhir.rest.api.PreferReturnEnum preferReturn, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

ca.uhn.fhir.rest.api.MethodOutcome resourceBySearchUrl(org.hl7.fhir.instance.model.api.IBaseResource resource, String url, ca.uhn.fhir.rest.api.PreferReturnEnum preferReturn, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

----

The update API is defined in the syntax as follows:

----
fhir:update/methodName?[parameters]
----

The 2 method(s) is listed in the table below.
(API methods can have a shorthand alias name which can be used in the syntax instead of the name)

[width="100%",cols="2,2,6",options="header"]
|===
| Method | Alias | Description
| *resource* |  | 
| *resourceBySearchUrl* |  | 
|===

The update API method(s) has the following set of parameters listed in the table below:
[width="100%",cols="2,2,4,2",options="header"]
|===
| Method | Parameter | Description | Type
| resource | *extraParameters* | *Optional*   | Map
| resource | *id* | *Optional*   | IIdType
| resource | *preferReturn* | *Optional*   | PreferReturnEnum
| resource | *resource* |   | IBaseResource
| resource | *resourceAsString* |   | String
| resource | *stringId* | *Optional*   | String
| resourceBySearchUrl | *extraParameters* | *Optional*   | Map
| resourceBySearchUrl | *preferReturn* | *Optional*   | PreferReturnEnum
| resourceBySearchUrl | *resource* |   | IBaseResource
| resourceBySearchUrl | *resourceAsString* |   | String
| resourceBySearchUrl | *url* |   | String
|===

In addition to the parameters above, the update API can also use from the 45 endpoint query option
which is listed in the _Query Parameters_ section.

Any of the parameters can be provided in either the endpoint URI, or dynamically in a message header.
The message header name must be of the format `CamelFhir.parameter`.
The `inBody` parameter overrides message header, i.e. the endpoint parameter `inBody=myParameterNameHere`
would override a `CamelFhir.myParameterNameHere` header.



==== API: validate

*Both producer and consumer are supported*




The validate API has 1 method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

[source,java]
----

ca.uhn.fhir.rest.api.MethodOutcome resource(String resourceAsString, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

ca.uhn.fhir.rest.api.MethodOutcome resource(org.hl7.fhir.instance.model.api.IBaseResource resource, java.util.Map<org.apache.camel.component.fhir.api.ExtraParameters, Object> extraParameters);

----

The validate API is defined in the syntax as follows:

----
fhir:validate/methodName?[parameters]
----

The 1 method(s) is listed in the table below.
(API methods can have a shorthand alias name which can be used in the syntax instead of the name)

[width="100%",cols="2,2,6",options="header"]
|===
| Method | Alias | Description
| *resource* |  | 
|===

The validate API method(s) has the following set of parameters listed in the table below:
[width="100%",cols="2,2,4,2",options="header"]
|===
| Method | Parameter | Description | Type
| resource | *extraParameters* | *Optional*   | Map
| resource | *resource* |   | IBaseResource
| resource | *resourceAsString* |   | String
|===

In addition to the parameters above, the validate API can also use from the 45 endpoint query option
which is listed in the _Query Parameters_ section.

Any of the parameters can be provided in either the endpoint URI, or dynamically in a message header.
The message header name must be of the format `CamelFhir.parameter`.
The `inBody` parameter overrides message header, i.e. the endpoint parameter `inBody=myParameterNameHere`
would override a `CamelFhir.myParameterNameHere` header.
// endpoint options: END

include::camel-spring-boot::page$fhir-starter.adoc[]
