[list-of-camel-components]
= Components

Component references are references used to place a component in an assembly. Apache Component references
provides various references that offers services for messaging, sending data, notifications and various other 
services that can not only resolve easy messaging and transferring data but also provide securing of data.

== Core Components

Below is the list of core components that are provided by Apache Camel.

Number of Core Components: indexCount:[attributes=core] in indexUniqueCount:[attributes=core,format=artifactid] JAR artifacts (indexCount:[attributes="core,deprecated"] deprecated)

[{index-table-format}]
|===
| Component | Artifact | Support Level | Since | Description
|===
indexTable::[attributes=core,cellformats="$xref|artifactid|supportlevel|since|description"]

== Components

Below is the list of non-core components that are provided by Apache Camel.

Number of Non-Core Components: indexCount:[attributes=!core] in indexUniqueCount:[attributes=!core,format=artifactid] JAR artifacts (indexCount:[attributes="!core,deprecated"] deprecated)

[{index-table-format}]
|===
| Component | Artifact | Support Level | Since | Description
|===
//'relative=!nav.adoc' is a workaround for https://gitlab.com/antora/xref-validator/-/issues/9
indexTable::[relative=!nav.adoc,attributes=!core,cellformats="$xref|artifactid|supportlevel|since|description"]

