[[undertow-spring-security-component]]
= Undertow Spring Security Security Provider
//THIS FILE IS COPIED: EDIT THE SOURCE FILE:
:page-source: components/camel-undertow-spring-security/src/main/docs/undertow-spring-security-component.adoc
//by hand
:since: 3.2

*Since Camel {since}*

*OSGi is not supported*

The Spring Security Provider provides Spring Security (5+) token bearer security over camel-undertow component.
To force camel-undertow to use spring security provider:
- Add spring security provider library on classpath.
- Provide instance of SpringSecurityConfiguration as `securityConfiguration`
parameter into camel-undertow component or provide both  `securityConfiguration` and `securityProvider`
into camel-undertow component.
- Configure spring-security.

Configuration has to provide all 3 security attributes:
[width="100%"]
|===
| Name | Description | Type
| *securityFiler* | Provides security filter gained from configured spring security (5+). Filter could be obtained
for example from DelegatingFilterProxyRegistrationBean. | Filter
| *clieantRegistration* | Provides configuration of external security provider which would be used by spring security |
ClientRegistration
|===

Each exchange created by Undertow endpoint with spring security contains header 'SpringSecurityProvider_principal' (
name of header is provided as constant `SpringSecurityProvider.PRINCIPAL_NAME_HEADER`) with current authorized identity
as value  or is not present (for not authorized requests)


