[[zendesk-component]]
= Zendesk Component
//THIS FILE IS COPIED: EDIT THE SOURCE FILE:
:page-source: components/camel-zendesk/src/main/docs/zendesk-component.adoc
:docTitle: Zendesk
:artifactId: camel-zendesk
:description: Manage Zendesk tickets, users, organizations, etc.
:since: 2.19
:supportLevel: Stable
:component-header: Both producer and consumer are supported
include::{cq-version}@camel-quarkus:ROOT:partial$reference/components/zendesk.adoc[opts=optional]

*Since Camel {since}*

*{component-header}*

The Zendesk component provides access to all of the zendesk.com APIs accessible
using https://github.com/cloudbees/zendesk-java-client[zendesk-java-client]. It
allows producing messages to manage Zendesk ticket, user, organization, etc.

Maven users will need to add the following dependency to their pom.xml
for this component:

[source,xml]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-zendesk</artifactId>
    <version>${camel-version}</version>
</dependency>
----

== Zendesk Options

// component options: START
The Zendesk component supports 10 options, which are listed below.



[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *serverUrl* (common) | The server URL to connect. |  | String
| *bridgeErrorHandler* (consumer) | Allows for bridging the consumer to the Camel routing Error Handler, which mean any exceptions occurred while the consumer is trying to pickup incoming messages, or the likes, will now be processed as a message and handled by the routing Error Handler. By default the consumer will use the org.apache.camel.spi.ExceptionHandler to deal with exceptions, that will be logged at WARN or ERROR level and ignored. | false | boolean
| *lazyStartProducer* (producer) | Whether the producer should be started lazy (on the first message). By starting lazy you can use this to allow CamelContext and routes to startup in situations where a producer may otherwise fail during starting and cause the route to fail being started. By deferring this startup to be lazy then the startup failure can be handled during routing messages via Camel's routing error handlers. Beware that when the first message is processed then creating and starting the producer may take a little time and prolong the total processing time of the processing. | false | boolean
| *autowiredEnabled* (advanced) | Whether autowiring is enabled. This is used for automatic autowiring options (the option must be marked as autowired) by looking up in the registry to find if there is a single instance of matching type, which then gets configured on the component. This can be used for automatic configuring JDBC data sources, JMS connection factories, AWS Clients, etc. | true | boolean
| *configuration* (advanced) | Component configuration |  | ZendeskConfiguration
| *zendesk* (advanced) | To use a shared Zendesk instance. |  | Zendesk
| *oauthToken* (security) | The OAuth token. |  | String
| *password* (security) | The password. |  | String
| *token* (security) | The security token. |  | String
| *username* (security) | The user name. |  | String
|===
// component options: END

// endpoint options: START
The Zendesk endpoint is configured using URI syntax:

----
zendesk:methodName
----

with the following path and query parameters:

=== Path Parameters (1 parameters):


[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *methodName* | *Required* What operation to use. There are 342 enums and the value can be one of: ADD_TAG_TO_ORGANISATIONS, ADD_TAG_TO_TICKET, ADD_TAG_TO_TOPICS, ASSOCIATE_ATTACHMENTS_TO_ARTICLE, CHANGE_USER_PASSWORD, CREATE_ARTICLE, CREATE_ARTICLE_1, CREATE_ARTICLE_TRANSLATION, CREATE_AUTOMATION, CREATE_CATEGORY, CREATE_CATEGORY_TRANSLATION, CREATE_COMMENT, CREATE_DYNAMIC_CONTENT_ITEM, CREATE_DYNAMIC_CONTENT_ITEM_VARIANT, CREATE_FORUM, CREATE_GROUP, CREATE_GROUP_MEMBERSHIP, CREATE_GROUP_MEMBERSHIP_1, CREATE_MACRO, CREATE_OR_UPDATE_USER, CREATE_OR_UPDATE_USERS, CREATE_OR_UPDATE_USERS_1, CREATE_OR_UPDATE_USERS_ASYNC, CREATE_ORGANIZATION, CREATE_ORGANIZATION_MEMBERSHIP, CREATE_ORGANIZATION_MEMBERSHIP_1, CREATE_ORGANIZATION_MEMBERSHIPS, CREATE_ORGANIZATION_MEMBERSHIPS_1, CREATE_ORGANIZATION_MEMBERSHIPS_ASYNC, CREATE_ORGANIZATIONS, CREATE_ORGANIZATIONS_1, CREATE_ORGANIZATIONS_ASYNC, CREATE_PERMISSION_GROUP, CREATE_REQUEST, CREATE_SATISFACTION_RATING, CREATE_SATISFACTION_RATING_1, CREATE_SECTION, CREATE_SECTION_TRANSLATION, CREATE_TARGET, CREATE_TICKET, CREATE_TICKET_ASYNC, CREATE_TICKET_FIELD, CREATE_TICKET_FORM, CREATE_TICKET_FROM_TWEET, CREATE_TICKETS, CREATE_TICKETS_1, CREATE_TICKETS_ASYNC, CREATE_TOPIC, CREATE_TRIGGER, CREATE_UPLOAD, CREATE_UPLOAD_1, CREATE_UPLOAD_2, CREATE_UPLOAD_ARTICLE, CREATE_UPLOAD_ARTICLE_1, CREATE_USER, CREATE_USER_IDENTITY, CREATE_USER_IDENTITY_1, CREATE_USER_SEGMENT, CREATE_USERS, CREATE_USERS_1, CREATE_USERS_ASYNC, DELETE_ARTICLE, DELETE_ARTICLE_ATTACHMENT, DELETE_ARTICLE_ATTACHMENT_1, DELETE_ATTACHMENT, DELETE_ATTACHMENT_1, DELETE_AUTOMATION, DELETE_CATEGORY, DELETE_DYNAMIC_CONTENT_ITEM, DELETE_DYNAMIC_CONTENT_ITEM_VARIANT, DELETE_FORUM, DELETE_GROUP, DELETE_GROUP_1, DELETE_GROUP_MEMBERSHIP, DELETE_GROUP_MEMBERSHIP_1, DELETE_GROUP_MEMBERSHIP_2, DELETE_GROUP_MEMBERSHIP_3, DELETE_ORGANIZATION, DELETE_ORGANIZATION_1, DELETE_ORGANIZATION_MEMBERSHIP, DELETE_ORGANIZATION_MEMBERSHIP_1, DELETE_ORGANIZATION_MEMBERSHIP_2, DELETE_ORGANIZATION_MEMBERSHIPS, DELETE_PERMISSION_GROUP, DELETE_PERMISSION_GROUP_1, DELETE_SECTION, DELETE_SUSPENDED_TICKET, DELETE_SUSPENDED_TICKET_1, DELETE_TARGET, DELETE_TICKET, DELETE_TICKET_1, DELETE_TICKET_FIELD, DELETE_TICKET_FIELD_1, DELETE_TICKETS, DELETE_TOPIC, DELETE_TRANSLATION, DELETE_TRANSLATION_1, DELETE_TRIGGER, DELETE_UPLOAD, DELETE_UPLOAD_1, DELETE_USER, DELETE_USER_1, DELETE_USER_IDENTITY, DELETE_USER_IDENTITY_1, DELETE_USER_IDENTITY_2, DELETE_USER_SEGMENT, DELETE_USER_SEGMENT_1, GET_ARTICLE, GET_ARTICLE_FROM_SEARCH, GET_ARTICLE_FROM_SEARCH_1, GET_ARTICLE_SUBSCRIPTIONS, GET_ARTICLE_SUBSCRIPTIONS_1, GET_ARTICLE_TRANSLATIONS, GET_ARTICLES, GET_ARTICLES_1, GET_ARTICLES_2, GET_ARTICLES_3, GET_ARTICLES_FROM_ALL_LABELS, GET_ARTICLES_FROM_ANY_LABELS, GET_ARTICLES_FROM_PAGE, GET_ARTICLES_INCREMENTALLY, GET_ASSIGNABLE_GROUP_MEMBERSHIPS, GET_ASSIGNABLE_GROUP_MEMBERSHIPS_1, GET_ASSIGNABLE_GROUPS, GET_ATTACHMENT, GET_ATTACHMENT_1, GET_ATTACHMENTS_FROM_ARTICLE, GET_AUTHENTICATED_USER, GET_AUTO_COMPLETE_ORGANIZATIONS, GET_AUTOMATION, GET_AUTOMATIONS, GET_BRANDS, GET_CC_REQUESTS, GET_CATEGORIES, GET_CATEGORY, GET_CATEGORY_TRANSLATIONS, GET_COMPLIANCE_DELETION_STATUSES, GET_CURRENT_USER, GET_CUSTOM_AGENT_ROLES, GET_DELETED_TICKETS, GET_DELETED_TICKETS_1, GET_DYNAMIC_CONTENT_ITEM, GET_DYNAMIC_CONTENT_ITEM_VARIANT, GET_DYNAMIC_CONTENT_ITEM_VARIANTS, GET_DYNAMIC_CONTENT_ITEMS, GET_FORUM, GET_FORUMS, GET_FORUMS_1, GET_GROUP, GET_GROUP_MEMBERSHIP, GET_GROUP_MEMBERSHIP_1, GET_GROUP_MEMBERSHIP_BY_USER, GET_GROUP_MEMBERSHIPS, GET_GROUP_MEMBERSHIPS_1, GET_GROUP_ORGANIZATION, GET_GROUP_USERS, GET_GROUPS, GET_HELP_CENTER_LOCALES, GET_HOLIDAYS_FOR_SCHEDULE, GET_HOLIDAYS_FOR_SCHEDULE_1, GET_INCREMENTAL_TICKETS_RESULT, GET_JOB_STATUS, GET_JOB_STATUS_ASYNC, GET_JOB_STATUSES, GET_JOB_STATUSES_ASYNC, GET_MACRO, GET_MACROS, GET_OPEN_REQUESTS, GET_ORGANIZATION, GET_ORGANIZATION_FIELDS, GET_ORGANIZATION_MEMBERSHIP, GET_ORGANIZATION_MEMBERSHIP_BY_USER, GET_ORGANIZATION_MEMBERSHIP_FOR_USER, GET_ORGANIZATION_MEMBERSHIPS, GET_ORGANIZATION_MEMBERSHIPS_FOR_ORG, GET_ORGANIZATION_MEMBERSHIPS_FOR_USER, GET_ORGANIZATION_TICKETS, GET_ORGANIZATION_USERS, GET_ORGANIZATIONS, GET_ORGANIZATIONS_INCREMENTALLY, GET_PERMISSION_GROUP, GET_PERMISSION_GROUPS, GET_RECENT_TICKETS, GET_REQUEST, GET_REQUEST_COMMENT, GET_REQUEST_COMMENT_1, GET_REQUEST_COMMENT_2, GET_REQUEST_COMMENTS, GET_REQUEST_COMMENTS_1, GET_REQUESTS, GET_SATISFACTION_RATING, GET_SATISFACTION_RATINGS, GET_SCHEDULE, GET_SCHEDULE_1, GET_SCHEDULES, GET_SEARCH_RESULTS, GET_SEARCH_RESULTS_1, GET_SEARCH_RESULTS_2, GET_SEARCH_RESULTS_3, GET_SEARCH_RESULTS_4, GET_SECTION, GET_SECTION_SUBSCRIPTIONS, GET_SECTION_SUBSCRIPTIONS_1, GET_SECTION_TRANSLATIONS, GET_SECTIONS, GET_SECTIONS_1, GET_SECTIONS_2, GET_SOLVED_REQUESTS, GET_SUSPENDED_TICKETS, GET_TARGET, GET_TARGETS, GET_TICKET, GET_TICKET_AUDIT, GET_TICKET_AUDIT_1, GET_TICKET_AUDIT_2, GET_TICKET_AUDITS, GET_TICKET_AUDITS_1, GET_TICKET_COLLABORATORS, GET_TICKET_COMMENTS, GET_TICKET_COMMENTS_1, GET_TICKET_FIELD, GET_TICKET_FIELDS, GET_TICKET_FORM, GET_TICKET_FORMS, GET_TICKET_INCIDENTS, GET_TICKET_METRIC, GET_TICKET_METRIC_BY_TICKET, GET_TICKET_METRICS, GET_TICKETS, GET_TICKETS_1, GET_TICKETS_BY_EXTERNAL_ID, GET_TICKETS_BY_EXTERNAL_ID_1, GET_TICKETS_FROM_SEARCH, GET_TICKETS_INCREMENTALLY, GET_TICKETS_INCREMENTALLY_1, GET_TOPIC, GET_TOPICS, GET_TOPICS_1, GET_TOPICS_2, GET_TOPICS_3, GET_TOPICS_BY_USER, GET_TRIGGER, GET_TRIGGERS, GET_TWITTER_MONITORS, GET_USER, GET_USER_CCD_TICKETS, GET_USER_FIELDS, GET_USER_IDENTITIES, GET_USER_IDENTITIES_1, GET_USER_IDENTITY, GET_USER_IDENTITY_1, GET_USER_IDENTITY_2, GET_USER_RELATED_INFO, GET_USER_REQUESTED_TICKETS, GET_USER_REQUESTS, GET_USER_REQUESTS_1, GET_USER_SEGMENT, GET_USER_SEGMENTS, GET_USER_SEGMENTS_1, GET_USER_SEGMENTS_APPLICABLE, GET_USER_SUBSCRIPTIONS, GET_USER_SUBSCRIPTIONS_1, GET_USERS, GET_USERS_BY_ROLE, GET_USERS_INCREMENTALLY, IMPORT_TICKET, IMPORT_TOPIC, LOOKUP_ORGANIZATIONS_BY_EXTERNAL_ID, LOOKUP_USER_BY_EMAIL, LOOKUP_USER_BY_EXTERNAL_ID, MACROS_SHOW_CHANGES_TO_TICKET, MACROS_SHOW_TICKET_AFTER_CHANGES, MAKE_PRIVATE_TICKET_AUDIT, MAKE_PRIVATE_TICKET_AUDIT_1, MAKE_PRIVATE_TICKET_AUDIT_2, MARK_TICKET_AS_SPAM, MARK_TICKET_AS_SPAM_1, MERGE_USERS, NOTIFY_APP, PERMANENTLY_DELETE_TICKET, PERMANENTLY_DELETE_TICKET_1, PERMANENTLY_DELETE_TICKETS, PERMANENTLY_DELETE_USER, PERMANENTLY_DELETE_USER_1, QUEUE_CREATE_TICKET_ASYNC, REMOVE_TAG_FROM_ORGANISATIONS, REMOVE_TAG_FROM_TICKET, REMOVE_TAG_FROM_TOPICS, REQUEST_VERIFY_USER_IDENTITY, REQUEST_VERIFY_USER_IDENTITY_1, REQUEST_VERIFY_USER_IDENTITY_2, RESET_USER_PASSWORD, RESET_USER_PASSWORD_1, SET_GROUP_MEMBERSHIP_AS_DEFAULT, SET_ORGANIZATION_MEMBERSHIP_AS_DEFAULT, SET_TAG_ON_ORGANISATIONS, SET_TAG_ON_TICKET, SET_TAG_ON_TOPICS, SET_USER_PRIMARY_IDENTITY, SET_USER_PRIMARY_IDENTITY_1, SET_USER_PRIMARY_IDENTITY_2, SUSPEND_USER, TRUST_TICKET_AUDIT, TRUST_TICKET_AUDIT_1, TRUST_TICKET_AUDIT_2, UNSUSPEND_USER, UPDATE_ARTICLE, UPDATE_ARTICLE_TRANSLATION, UPDATE_AUTOMATION, UPDATE_CATEGORY, UPDATE_CATEGORY_TRANSLATION, UPDATE_DYNAMIC_CONTENT_ITEM, UPDATE_DYNAMIC_CONTENT_ITEM_VARIANT, UPDATE_FORUM, UPDATE_GROUP, UPDATE_INSTALLATION, UPDATE_MACRO, UPDATE_ORGANIZATION, UPDATE_ORGANIZATIONS, UPDATE_ORGANIZATIONS_1, UPDATE_ORGANIZATIONS_ASYNC, UPDATE_PERMISSION_GROUP, UPDATE_REQUEST, UPDATE_SECTION, UPDATE_SECTION_TRANSLATION, UPDATE_TICKET, UPDATE_TICKET_FIELD, UPDATE_TICKETS, UPDATE_TICKETS_1, UPDATE_TICKETS_ASYNC, UPDATE_TOPIC, UPDATE_TRIGGER, UPDATE_USER, UPDATE_USER_IDENTITY, UPDATE_USER_IDENTITY_1, UPDATE_USER_SEGMENT, UPDATE_USERS, UPDATE_USERS_1, UPDATE_USERS_ASYNC, VERIFY_USER_IDENTITY, VERIFY_USER_IDENTITY_1, VERIFY_USER_IDENTITY_2 |  | ZendeskApiMethod
|===


=== Query Parameters (27 parameters):


[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *inBody* (common) | Sets the name of a parameter to be passed in the exchange In Body |  | String
| *serverUrl* (common) | The server URL to connect. |  | String
| *bridgeErrorHandler* (consumer) | Allows for bridging the consumer to the Camel routing Error Handler, which mean any exceptions occurred while the consumer is trying to pickup incoming messages, or the likes, will now be processed as a message and handled by the routing Error Handler. By default the consumer will use the org.apache.camel.spi.ExceptionHandler to deal with exceptions, that will be logged at WARN or ERROR level and ignored. | false | boolean
| *sendEmptyMessageWhenIdle* (consumer) | If the polling consumer did not poll any files, you can enable this option to send an empty message (no body) instead. | false | boolean
| *exceptionHandler* (consumer) | To let the consumer use a custom ExceptionHandler. Notice if the option bridgeErrorHandler is enabled then this option is not in use. By default the consumer will deal with exceptions, that will be logged at WARN or ERROR level and ignored. |  | ExceptionHandler
| *exchangePattern* (consumer) | Sets the exchange pattern when the consumer creates an exchange. There are 3 enums and the value can be one of: InOnly, InOut, InOptionalOut |  | ExchangePattern
| *pollStrategy* (consumer) | A pluggable org.apache.camel.PollingConsumerPollingStrategy allowing you to provide your custom implementation to control error handling usually occurred during the poll operation before an Exchange have been created and being routed in Camel. |  | PollingConsumerPollStrategy
| *lazyStartProducer* (producer) | Whether the producer should be started lazy (on the first message). By starting lazy you can use this to allow CamelContext and routes to startup in situations where a producer may otherwise fail during starting and cause the route to fail being started. By deferring this startup to be lazy then the startup failure can be handled during routing messages via Camel's routing error handlers. Beware that when the first message is processed then creating and starting the producer may take a little time and prolong the total processing time of the processing. | false | boolean
| *synchronous* (advanced) | Sets whether synchronous processing should be strictly used, or Camel is allowed to use asynchronous processing (if supported). | false | boolean
| *backoffErrorThreshold* (scheduler) | The number of subsequent error polls (failed due some error) that should happen before the backoffMultipler should kick-in. |  | int
| *backoffIdleThreshold* (scheduler) | The number of subsequent idle polls that should happen before the backoffMultipler should kick-in. |  | int
| *backoffMultiplier* (scheduler) | To let the scheduled polling consumer backoff if there has been a number of subsequent idles/errors in a row. The multiplier is then the number of polls that will be skipped before the next actual attempt is happening again. When this option is in use then backoffIdleThreshold and/or backoffErrorThreshold must also be configured. |  | int
| *delay* (scheduler) | Milliseconds before the next poll. | 500 | long
| *greedy* (scheduler) | If greedy is enabled, then the ScheduledPollConsumer will run immediately again, if the previous run polled 1 or more messages. | false | boolean
| *initialDelay* (scheduler) | Milliseconds before the first poll starts. | 1000 | long
| *repeatCount* (scheduler) | Specifies a maximum limit of number of fires. So if you set it to 1, the scheduler will only fire once. If you set it to 5, it will only fire five times. A value of zero or negative means fire forever. | 0 | long
| *runLoggingLevel* (scheduler) | The consumer logs a start/complete log line when it polls. This option allows you to configure the logging level for that. There are 6 enums and the value can be one of: TRACE, DEBUG, INFO, WARN, ERROR, OFF | TRACE | LoggingLevel
| *scheduledExecutorService* (scheduler) | Allows for configuring a custom/shared thread pool to use for the consumer. By default each consumer has its own single threaded thread pool. |  | ScheduledExecutorService
| *scheduler* (scheduler) | To use a cron scheduler from either camel-spring or camel-quartz component. Use value spring or quartz for built in scheduler | none | Object
| *schedulerProperties* (scheduler) | To configure additional properties when using a custom scheduler or any of the Quartz, Spring based scheduler. |  | Map
| *startScheduler* (scheduler) | Whether the scheduler should be auto started. | true | boolean
| *timeUnit* (scheduler) | Time unit for initialDelay and delay options. There are 7 enums and the value can be one of: NANOSECONDS, MICROSECONDS, MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS | MILLISECONDS | TimeUnit
| *useFixedDelay* (scheduler) | Controls if fixed delay or fixed rate is used. See ScheduledExecutorService in JDK for details. | true | boolean
| *oauthToken* (security) | The OAuth token. |  | String
| *password* (security) | The password. |  | String
| *token* (security) | The security token. |  | String
| *username* (security) | The user name. |  | String
|===




=== API Parameters (1 APIs):

The Zendesk endpoint is an API based component and has additional parameters based on which API name and API method is used.
The API name and API method is located in the endpoint URI as the methodName path parameters:

----
zendesk:methodName
----

There are 1 API names as listed in the table below:

[width="100%",cols="2,2,6",options="header"]
|===
| API Name | Type | Description
| *DEFAULT* | Both | 
|===

Each API is documented in the following sections to come.


==== API: DEFAULT

*Both producer and consumer are supported*




The DEFAULT API has 221 method(s) which is represented by the following method signatures
(an API method may have multiple signatures due to overloading):

[source,java]
----

java.util.List<String> addTagToOrganisations(long id, String[] tags);

java.util.List<String> addTagToTicket(long id, String[] tags);

java.util.List<String> addTagToTopics(long id, String[] tags);

void associateAttachmentsToArticle(String idArticle, java.util.List<org.zendesk.client.v2.model.Attachment> attachments);

void changeUserPassword(org.zendesk.client.v2.model.User user, String oldPassword, String newPassword);

org.zendesk.client.v2.model.hc.Article createArticle(org.zendesk.client.v2.model.hc.Article article);

org.zendesk.client.v2.model.hc.Article createArticle(org.zendesk.client.v2.model.hc.Article article, boolean notifySubscribers);

org.zendesk.client.v2.model.hc.Translation createArticleTranslation(Long articleId, org.zendesk.client.v2.model.hc.Translation translation);

org.zendesk.client.v2.model.Automation createAutomation(org.zendesk.client.v2.model.Automation automation);

org.zendesk.client.v2.model.hc.Category createCategory(org.zendesk.client.v2.model.hc.Category category);

org.zendesk.client.v2.model.hc.Translation createCategoryTranslation(Long categoryId, org.zendesk.client.v2.model.hc.Translation translation);

org.zendesk.client.v2.model.Ticket createComment(long ticketId, org.zendesk.client.v2.model.Comment comment);

org.zendesk.client.v2.model.dynamic.DynamicContentItem createDynamicContentItem(org.zendesk.client.v2.model.dynamic.DynamicContentItem item);

org.zendesk.client.v2.model.dynamic.DynamicContentItemVariant createDynamicContentItemVariant(Long itemId, org.zendesk.client.v2.model.dynamic.DynamicContentItemVariant variant);

org.zendesk.client.v2.model.Forum createForum(org.zendesk.client.v2.model.Forum forum);

org.zendesk.client.v2.model.Group createGroup(org.zendesk.client.v2.model.Group group);

org.zendesk.client.v2.model.GroupMembership createGroupMembership(long user_id, org.zendesk.client.v2.model.GroupMembership groupMembership);

org.zendesk.client.v2.model.GroupMembership createGroupMembership(org.zendesk.client.v2.model.GroupMembership groupMembership);

org.zendesk.client.v2.model.Macro createMacro(org.zendesk.client.v2.model.Macro macro);

org.zendesk.client.v2.model.Organization createOrganization(org.zendesk.client.v2.model.Organization organization);

org.zendesk.client.v2.model.OrganizationMembership createOrganizationMembership(long user_id, org.zendesk.client.v2.model.OrganizationMembership organizationMembership);

org.zendesk.client.v2.model.OrganizationMembership createOrganizationMembership(org.zendesk.client.v2.model.OrganizationMembership organizationMembership);

org.zendesk.client.v2.model.JobStatus createOrganizationMemberships(java.util.List<org.zendesk.client.v2.model.OrganizationMembership> organizationMemberships);

org.zendesk.client.v2.model.JobStatus createOrganizationMemberships(org.zendesk.client.v2.model.OrganizationMembership[] organizationMemberships);

org.asynchttpclient.ListenableFuture<org.zendesk.client.v2.model.JobStatus> createOrganizationMembershipsAsync(java.util.List<org.zendesk.client.v2.model.OrganizationMembership> organizationMemberships);

org.zendesk.client.v2.model.JobStatus createOrganizations(java.util.List<org.zendesk.client.v2.model.Organization> organizations);

org.zendesk.client.v2.model.JobStatus createOrganizations(org.zendesk.client.v2.model.Organization[] organizations);

org.asynchttpclient.ListenableFuture<org.zendesk.client.v2.model.JobStatus> createOrganizationsAsync(java.util.List<org.zendesk.client.v2.model.Organization> organizations);

org.zendesk.client.v2.model.User createOrUpdateUser(org.zendesk.client.v2.model.User user);

org.zendesk.client.v2.model.JobStatus createOrUpdateUsers(java.util.List<org.zendesk.client.v2.model.User> users);

org.zendesk.client.v2.model.JobStatus createOrUpdateUsers(org.zendesk.client.v2.model.User[] users);

org.asynchttpclient.ListenableFuture<org.zendesk.client.v2.model.JobStatus> createOrUpdateUsersAsync(java.util.List<org.zendesk.client.v2.model.User> users);

org.zendesk.client.v2.model.hc.PermissionGroup createPermissionGroup(org.zendesk.client.v2.model.hc.PermissionGroup permissionGroup);

org.zendesk.client.v2.model.Request createRequest(org.zendesk.client.v2.model.Request request);

org.zendesk.client.v2.model.SatisfactionRating createSatisfactionRating(long ticketId, org.zendesk.client.v2.model.SatisfactionRating satisfactionRating);

org.zendesk.client.v2.model.SatisfactionRating createSatisfactionRating(org.zendesk.client.v2.model.Ticket ticket, org.zendesk.client.v2.model.SatisfactionRating satisfactionRating);

org.zendesk.client.v2.model.hc.Section createSection(org.zendesk.client.v2.model.hc.Section section);

org.zendesk.client.v2.model.hc.Translation createSectionTranslation(Long sectionId, org.zendesk.client.v2.model.hc.Translation translation);

org.zendesk.client.v2.model.targets.Target createTarget(org.zendesk.client.v2.model.targets.Target target);

org.zendesk.client.v2.model.Ticket createTicket(org.zendesk.client.v2.model.Ticket ticket);

org.asynchttpclient.ListenableFuture<org.zendesk.client.v2.model.Ticket> createTicketAsync(org.zendesk.client.v2.model.Ticket ticket);

org.zendesk.client.v2.model.Field createTicketField(org.zendesk.client.v2.model.Field field);

org.zendesk.client.v2.model.TicketForm createTicketForm(org.zendesk.client.v2.model.TicketForm ticketForm);

org.zendesk.client.v2.model.Ticket createTicketFromTweet(long tweetId, long monitorId);

org.zendesk.client.v2.model.JobStatus createTickets(java.util.List<org.zendesk.client.v2.model.Ticket> tickets);

org.zendesk.client.v2.model.JobStatus createTickets(org.zendesk.client.v2.model.Ticket[] tickets);

org.asynchttpclient.ListenableFuture<org.zendesk.client.v2.model.JobStatus> createTicketsAsync(java.util.List<org.zendesk.client.v2.model.Ticket> tickets);

org.zendesk.client.v2.model.Topic createTopic(org.zendesk.client.v2.model.Topic topic);

org.zendesk.client.v2.model.Trigger createTrigger(org.zendesk.client.v2.model.Trigger trigger);

org.zendesk.client.v2.model.Attachment.Upload createUpload(String fileName, String contentType, byte[] content);

org.zendesk.client.v2.model.Attachment.Upload createUpload(String fileName, byte[] content);

org.zendesk.client.v2.model.Attachment.Upload createUpload(String token, String fileName, String contentType, byte[] content);

org.zendesk.client.v2.model.hc.ArticleAttachments createUploadArticle(long articleId, java.io.File file);

org.zendesk.client.v2.model.hc.ArticleAttachments createUploadArticle(long articleId, java.io.File file, boolean inline);

org.zendesk.client.v2.model.User createUser(org.zendesk.client.v2.model.User user);

org.zendesk.client.v2.model.Identity createUserIdentity(long userId, org.zendesk.client.v2.model.Identity identity);

org.zendesk.client.v2.model.Identity createUserIdentity(org.zendesk.client.v2.model.User user, org.zendesk.client.v2.model.Identity identity);

org.zendesk.client.v2.model.JobStatus createUsers(java.util.List<org.zendesk.client.v2.model.User> users);

org.zendesk.client.v2.model.JobStatus createUsers(org.zendesk.client.v2.model.User[] users);

org.asynchttpclient.ListenableFuture<org.zendesk.client.v2.model.JobStatus> createUsersAsync(java.util.List<org.zendesk.client.v2.model.User> users);

org.zendesk.client.v2.model.hc.UserSegment createUserSegment(org.zendesk.client.v2.model.hc.UserSegment userSegment);

void deleteArticle(org.zendesk.client.v2.model.hc.Article article);

void deleteArticleAttachment(long id);

void deleteArticleAttachment(org.zendesk.client.v2.model.hc.ArticleAttachments attachment);

void deleteAttachment(long id);

void deleteAttachment(org.zendesk.client.v2.model.Attachment attachment);

void deleteAutomation(long automationId);

void deleteCategory(org.zendesk.client.v2.model.hc.Category category);

void deleteDynamicContentItem(org.zendesk.client.v2.model.dynamic.DynamicContentItem item);

void deleteDynamicContentItemVariant(Long itemId, org.zendesk.client.v2.model.dynamic.DynamicContentItemVariant variant);

void deleteForum(org.zendesk.client.v2.model.Forum forum);

void deleteGroup(long id);

void deleteGroup(org.zendesk.client.v2.model.Group group);

void deleteGroupMembership(long id);

void deleteGroupMembership(long user_id, long group_membership_id);

void deleteGroupMembership(long user_id, org.zendesk.client.v2.model.GroupMembership groupMembership);

void deleteGroupMembership(org.zendesk.client.v2.model.GroupMembership groupMembership);

void deleteOrganization(long id);

void deleteOrganization(org.zendesk.client.v2.model.Organization organization);

void deleteOrganizationMembership(long id);

void deleteOrganizationMembership(long user_id, long organization_membership_id);

void deleteOrganizationMembership(long user_id, org.zendesk.client.v2.model.OrganizationMembership organizationMembership);

void deleteOrganizationMemberships(long id, long[] ids);

void deletePermissionGroup(long id);

void deletePermissionGroup(org.zendesk.client.v2.model.hc.PermissionGroup permissionGroup);

void deleteSection(org.zendesk.client.v2.model.hc.Section section);

void deleteSuspendedTicket(long id);

void deleteSuspendedTicket(org.zendesk.client.v2.model.SuspendedTicket ticket);

void deleteTarget(long targetId);

void deleteTicket(long id);

void deleteTicket(org.zendesk.client.v2.model.Ticket ticket);

void deleteTicketField(long id);

void deleteTicketField(org.zendesk.client.v2.model.Field field);

void deleteTickets(long id, long[] ids);

void deleteTopic(org.zendesk.client.v2.model.Topic topic);

void deleteTranslation(Long translationId);

void deleteTranslation(org.zendesk.client.v2.model.hc.Translation translation);

void deleteTrigger(long triggerId);

void deleteUpload(String token);

void deleteUpload(org.zendesk.client.v2.model.Attachment.Upload upload);

void deleteUser(long id);

void deleteUser(org.zendesk.client.v2.model.User user);

void deleteUserIdentity(long userId, long identityId);

void deleteUserIdentity(org.zendesk.client.v2.model.User user, long identityId);

void deleteUserIdentity(org.zendesk.client.v2.model.User user, org.zendesk.client.v2.model.Identity identity);

void deleteUserSegment(long id);

void deleteUserSegment(org.zendesk.client.v2.model.hc.UserSegment userSegment);

org.zendesk.client.v2.model.hc.Article getArticle(long id);

Iterable<org.zendesk.client.v2.model.hc.Article> getArticleFromSearch(String searchTerm);

Iterable<org.zendesk.client.v2.model.hc.Article> getArticleFromSearch(String searchTerm, Long sectionId);

Iterable<org.zendesk.client.v2.model.hc.Article> getArticles();

Iterable<org.zendesk.client.v2.model.hc.Article> getArticles(String locale);

Iterable<org.zendesk.client.v2.model.hc.Article> getArticles(org.zendesk.client.v2.model.hc.Category category);

Iterable<org.zendesk.client.v2.model.hc.Article> getArticles(org.zendesk.client.v2.model.hc.Section section);

Iterable<org.zendesk.client.v2.model.hc.Article> getArticlesFromAllLabels(java.util.List<String> labels);

Iterable<org.zendesk.client.v2.model.hc.Article> getArticlesFromAnyLabels(java.util.List<String> labels);

java.util.List<org.zendesk.client.v2.model.hc.Article> getArticlesFromPage(int page);

Iterable<org.zendesk.client.v2.model.hc.Article> getArticlesIncrementally(java.util.Date startTime);

Iterable<org.zendesk.client.v2.model.hc.Subscription> getArticleSubscriptions(Long articleId);

Iterable<org.zendesk.client.v2.model.hc.Subscription> getArticleSubscriptions(Long articleId, String locale);

Iterable<org.zendesk.client.v2.model.hc.Translation> getArticleTranslations(Long articleId);

Iterable<org.zendesk.client.v2.model.GroupMembership> getAssignableGroupMemberships();

java.util.List<org.zendesk.client.v2.model.GroupMembership> getAssignableGroupMemberships(long group_id);

org.zendesk.client.v2.model.Attachment getAttachment(long id);

org.zendesk.client.v2.model.Attachment getAttachment(org.zendesk.client.v2.model.Attachment attachment);

java.util.List<org.zendesk.client.v2.model.hc.ArticleAttachments> getAttachmentsFromArticle(Long articleID);

Iterable<org.zendesk.client.v2.model.Organization> getAutoCompleteOrganizations(String name);

org.zendesk.client.v2.model.Automation getAutomation(long id);

org.zendesk.client.v2.model.hc.Category getCategory(long id);

Iterable<org.zendesk.client.v2.model.hc.Translation> getCategoryTranslations(Long categoryId);

Iterable<org.zendesk.client.v2.model.ComplianceDeletionStatus> getComplianceDeletionStatuses(long userId);

Iterable<org.zendesk.client.v2.model.DeletedTicket> getDeletedTickets();

Iterable<org.zendesk.client.v2.model.DeletedTicket> getDeletedTickets(String sortBy, org.zendesk.client.v2.model.SortOrder sortOrder);

org.zendesk.client.v2.model.dynamic.DynamicContentItem getDynamicContentItem(long id);

org.zendesk.client.v2.model.dynamic.DynamicContentItemVariant getDynamicContentItemVariant(Long itemId, long id);

Iterable<org.zendesk.client.v2.model.dynamic.DynamicContentItemVariant> getDynamicContentItemVariants(org.zendesk.client.v2.model.dynamic.DynamicContentItem item);

org.zendesk.client.v2.model.Forum getForum(long id);

Iterable<org.zendesk.client.v2.model.Forum> getForums();

java.util.List<org.zendesk.client.v2.model.Forum> getForums(long category_id);

org.zendesk.client.v2.model.Group getGroup(long id);

org.zendesk.client.v2.model.GroupMembership getGroupMembership(long id);

org.zendesk.client.v2.model.GroupMembership getGroupMembership(long user_id, long group_membership_id);

java.util.List<org.zendesk.client.v2.model.GroupMembership> getGroupMembershipByUser(long user_id);

Iterable<org.zendesk.client.v2.model.GroupMembership> getGroupMemberships();

java.util.List<org.zendesk.client.v2.model.GroupMembership> getGroupMemberships(long group_id);

org.zendesk.client.v2.model.OrganizationMembership getGroupOrganization(long user_id, long organization_membership_id);

Iterable<org.zendesk.client.v2.model.User> getGroupUsers(long id);

Iterable<org.zendesk.client.v2.model.schedules.Holiday> getHolidaysForSchedule(Long scheduleId);

Iterable<org.zendesk.client.v2.model.schedules.Holiday> getHolidaysForSchedule(org.zendesk.client.v2.model.schedules.Schedule schedule);

java.util.Map getIncrementalTicketsResult(long unixEpochTime);

org.zendesk.client.v2.model.JobStatus getJobStatus(org.zendesk.client.v2.model.JobStatus status);

org.asynchttpclient.ListenableFuture<org.zendesk.client.v2.model.JobStatus> getJobStatusAsync(org.zendesk.client.v2.model.JobStatus status);

java.util.List<org.zendesk.client.v2.model.JobStatus> getJobStatuses(java.util.List<org.zendesk.client.v2.model.JobStatus> statuses);

org.asynchttpclient.ListenableFuture<java.util.List<org.zendesk.client.v2.model.JobStatus>> getJobStatusesAsync(java.util.List<org.zendesk.client.v2.model.JobStatus> statuses);

org.zendesk.client.v2.model.Macro getMacro(long macroId);

org.zendesk.client.v2.model.Organization getOrganization(long id);

org.zendesk.client.v2.model.OrganizationMembership getOrganizationMembership(long id);

java.util.List<org.zendesk.client.v2.model.OrganizationMembership> getOrganizationMembershipByUser(long user_id);

org.zendesk.client.v2.model.OrganizationMembership getOrganizationMembershipForUser(long user_id, long id);

Iterable<org.zendesk.client.v2.model.OrganizationMembership> getOrganizationMembershipsForOrg(long organization_id);

Iterable<org.zendesk.client.v2.model.OrganizationMembership> getOrganizationMembershipsForUser(long user_id);

Iterable<org.zendesk.client.v2.model.Organization> getOrganizationsIncrementally(java.util.Date startTime);

Iterable<org.zendesk.client.v2.model.Ticket> getOrganizationTickets(long organizationId);

Iterable<org.zendesk.client.v2.model.User> getOrganizationUsers(long id);

org.zendesk.client.v2.model.hc.PermissionGroup getPermissionGroup(long id);

org.zendesk.client.v2.model.Request getRequest(long id);

org.zendesk.client.v2.model.Comment getRequestComment(long requestId, long commentId);

org.zendesk.client.v2.model.Comment getRequestComment(org.zendesk.client.v2.model.Request request, long commentId);

org.zendesk.client.v2.model.Comment getRequestComment(org.zendesk.client.v2.model.Request request, org.zendesk.client.v2.model.Comment comment);

Iterable<org.zendesk.client.v2.model.Comment> getRequestComments(long id);

Iterable<org.zendesk.client.v2.model.Comment> getRequestComments(org.zendesk.client.v2.model.Request request);

org.zendesk.client.v2.model.SatisfactionRating getSatisfactionRating(long id);

org.zendesk.client.v2.model.schedules.Schedule getSchedule(Long scheduleId);

org.zendesk.client.v2.model.schedules.Schedule getSchedule(org.zendesk.client.v2.model.schedules.Schedule schedule);

Iterable<org.zendesk.client.v2.model.SearchResultEntity> getSearchResults(Class<org.zendesk.client.v2.model.SearchResultEntity> type, String query);

Iterable<org.zendesk.client.v2.model.SearchResultEntity> getSearchResults(Class<org.zendesk.client.v2.model.SearchResultEntity> type, String query, String params);

Iterable<org.zendesk.client.v2.model.SearchResultEntity> getSearchResults(Class<org.zendesk.client.v2.model.SearchResultEntity> type, String query, String sortBy, org.zendesk.client.v2.model.SortOrder sortOrder);

Iterable<org.zendesk.client.v2.model.SearchResultEntity> getSearchResults(Class<org.zendesk.client.v2.model.SearchResultEntity> type, String query, java.util.Map<String, Object> params);

Iterable<org.zendesk.client.v2.model.SearchResultEntity> getSearchResults(String query);

org.zendesk.client.v2.model.hc.Section getSection(long id);

Iterable<org.zendesk.client.v2.model.hc.Section> getSections();

Iterable<org.zendesk.client.v2.model.hc.Section> getSections(org.zendesk.client.v2.model.hc.Category category);

Iterable<org.zendesk.client.v2.model.hc.Section> getSections(org.zendesk.client.v2.model.hc.UserSegment userSegment);

Iterable<org.zendesk.client.v2.model.hc.Subscription> getSectionSubscriptions(Long sectionId);

Iterable<org.zendesk.client.v2.model.hc.Subscription> getSectionSubscriptions(Long sectionId, String locale);

Iterable<org.zendesk.client.v2.model.hc.Translation> getSectionTranslations(Long sectionId);

org.zendesk.client.v2.model.targets.Target getTarget(long id);

org.zendesk.client.v2.model.Ticket getTicket(long id);

org.zendesk.client.v2.model.Audit getTicketAudit(long ticketId, long auditId);

org.zendesk.client.v2.model.Audit getTicketAudit(org.zendesk.client.v2.model.Ticket ticket, long id);

org.zendesk.client.v2.model.Audit getTicketAudit(org.zendesk.client.v2.model.Ticket ticket, org.zendesk.client.v2.model.Audit audit);

Iterable<org.zendesk.client.v2.model.Audit> getTicketAudits(Long id);

Iterable<org.zendesk.client.v2.model.Audit> getTicketAudits(org.zendesk.client.v2.model.Ticket ticket);

java.util.List<org.zendesk.client.v2.model.User> getTicketCollaborators(long id);

Iterable<org.zendesk.client.v2.model.Comment> getTicketComments(long id);

Iterable<org.zendesk.client.v2.model.Comment> getTicketComments(long id, org.zendesk.client.v2.model.SortOrder order);

org.zendesk.client.v2.model.Field getTicketField(long id);

org.zendesk.client.v2.model.TicketForm getTicketForm(long id);

java.util.List<org.zendesk.client.v2.model.Ticket> getTicketIncidents(long id);

org.zendesk.client.v2.model.Metric getTicketMetric(long id);

org.zendesk.client.v2.model.Metric getTicketMetricByTicket(long id);

Iterable<org.zendesk.client.v2.model.Ticket> getTickets();

java.util.List<org.zendesk.client.v2.model.Ticket> getTickets(long id, long[] ids);

Iterable<org.zendesk.client.v2.model.Ticket> getTicketsByExternalId(String externalId);

Iterable<org.zendesk.client.v2.model.Ticket> getTicketsByExternalId(String externalId, boolean includeArchived);

Iterable<org.zendesk.client.v2.model.Ticket> getTicketsFromSearch(String searchTerm);

Iterable<org.zendesk.client.v2.model.Ticket> getTicketsIncrementally(java.util.Date startTime);

Iterable<org.zendesk.client.v2.model.Ticket> getTicketsIncrementally(java.util.Date startTime, java.util.Date endTime);

org.zendesk.client.v2.model.Topic getTopic(long id);

Iterable<org.zendesk.client.v2.model.Topic> getTopics();

Iterable<org.zendesk.client.v2.model.Topic> getTopics(org.zendesk.client.v2.model.hc.UserSegment userSegment);

java.util.List<org.zendesk.client.v2.model.Topic> getTopics(long forum_id);

java.util.List<org.zendesk.client.v2.model.Topic> getTopics(long id, long[] ids);

java.util.List<org.zendesk.client.v2.model.Topic> getTopicsByUser(long user_id);

org.zendesk.client.v2.model.Trigger getTrigger(long id);

org.zendesk.client.v2.model.User getUser(long id);

Iterable<org.zendesk.client.v2.model.Ticket> getUserCCDTickets(long userId);

java.util.List<org.zendesk.client.v2.model.Identity> getUserIdentities(long userId);

java.util.List<org.zendesk.client.v2.model.Identity> getUserIdentities(org.zendesk.client.v2.model.User user);

org.zendesk.client.v2.model.Identity getUserIdentity(long userId, long identityId);

org.zendesk.client.v2.model.Identity getUserIdentity(org.zendesk.client.v2.model.User user, long identityId);

org.zendesk.client.v2.model.Identity getUserIdentity(org.zendesk.client.v2.model.User user, org.zendesk.client.v2.model.Identity identity);

org.zendesk.client.v2.model.UserRelatedInfo getUserRelatedInfo(long userId);

Iterable<org.zendesk.client.v2.model.Ticket> getUserRequestedTickets(long userId);

Iterable<org.zendesk.client.v2.model.Request> getUserRequests(long id);

Iterable<org.zendesk.client.v2.model.Request> getUserRequests(org.zendesk.client.v2.model.User user);

Iterable<org.zendesk.client.v2.model.User> getUsersByRole(String role, String[] roles);

org.zendesk.client.v2.model.hc.UserSegment getUserSegment(long id);

Iterable<org.zendesk.client.v2.model.hc.UserSegment> getUserSegments();

Iterable<org.zendesk.client.v2.model.hc.UserSegment> getUserSegments(long id);

Iterable<org.zendesk.client.v2.model.User> getUsersIncrementally(java.util.Date startTime);

Iterable<org.zendesk.client.v2.model.hc.Subscription> getUserSubscriptions(Long userId);

Iterable<org.zendesk.client.v2.model.hc.Subscription> getUserSubscriptions(org.zendesk.client.v2.model.User user);

org.zendesk.client.v2.model.Ticket importTicket(org.zendesk.client.v2.model.TicketImport ticketImport);

org.zendesk.client.v2.model.Topic importTopic(org.zendesk.client.v2.model.Topic topic);

Iterable<org.zendesk.client.v2.model.Organization> lookupOrganizationsByExternalId(String externalId);

Iterable<org.zendesk.client.v2.model.User> lookupUserByEmail(String email);

Iterable<org.zendesk.client.v2.model.User> lookupUserByExternalId(String externalId);

org.zendesk.client.v2.model.Ticket macrosShowChangesToTicket(long macroId);

org.zendesk.client.v2.model.Ticket macrosShowTicketAfterChanges(long ticketId, long macroId);

void makePrivateTicketAudit(long ticketId, long auditId);

void makePrivateTicketAudit(org.zendesk.client.v2.model.Ticket ticket, long id);

void makePrivateTicketAudit(org.zendesk.client.v2.model.Ticket ticket, org.zendesk.client.v2.model.Audit audit);

void markTicketAsSpam(long id);

void markTicketAsSpam(org.zendesk.client.v2.model.Ticket ticket);

org.zendesk.client.v2.model.User mergeUsers(long userIdThatWillRemain, long userIdThatWillBeMerged);

void notifyApp(String json);

org.zendesk.client.v2.model.JobStatus permanentlyDeleteTicket(long id);

org.zendesk.client.v2.model.JobStatus permanentlyDeleteTicket(org.zendesk.client.v2.model.Ticket ticket);

org.zendesk.client.v2.model.JobStatus permanentlyDeleteTickets(long id, long[] ids);

org.zendesk.client.v2.model.User permanentlyDeleteUser(long id);

org.zendesk.client.v2.model.User permanentlyDeleteUser(org.zendesk.client.v2.model.User user);

org.asynchttpclient.ListenableFuture<org.zendesk.client.v2.model.JobStatus> queueCreateTicketAsync(org.zendesk.client.v2.model.Ticket ticket);

java.util.List<String> removeTagFromOrganisations(long id, String[] tags);

java.util.List<String> removeTagFromTicket(long id, String[] tags);

java.util.List<String> removeTagFromTopics(long id, String[] tags);

org.zendesk.client.v2.model.Identity requestVerifyUserIdentity(long userId, long identityId);

org.zendesk.client.v2.model.Identity requestVerifyUserIdentity(org.zendesk.client.v2.model.User user, long identityId);

org.zendesk.client.v2.model.Identity requestVerifyUserIdentity(org.zendesk.client.v2.model.User user, org.zendesk.client.v2.model.Identity identity);

void resetUserPassword(long id, String password);

void resetUserPassword(org.zendesk.client.v2.model.User user, String password);

java.util.List<org.zendesk.client.v2.model.GroupMembership> setGroupMembershipAsDefault(long user_id, org.zendesk.client.v2.model.GroupMembership groupMembership);

java.util.List<org.zendesk.client.v2.model.OrganizationMembership> setOrganizationMembershipAsDefault(long user_id, org.zendesk.client.v2.model.OrganizationMembership organizationMembership);

java.util.List<String> setTagOnOrganisations(long id, String[] tags);

java.util.List<String> setTagOnTicket(long id, String[] tags);

java.util.List<String> setTagOnTopics(long id, String[] tags);

java.util.List<org.zendesk.client.v2.model.Identity> setUserPrimaryIdentity(long userId, long identityId);

java.util.List<org.zendesk.client.v2.model.Identity> setUserPrimaryIdentity(org.zendesk.client.v2.model.User user, long identityId);

java.util.List<org.zendesk.client.v2.model.Identity> setUserPrimaryIdentity(org.zendesk.client.v2.model.User user, org.zendesk.client.v2.model.Identity identity);

org.zendesk.client.v2.model.User suspendUser(long id);

void trustTicketAudit(long ticketId, long auditId);

void trustTicketAudit(org.zendesk.client.v2.model.Ticket ticket, long id);

void trustTicketAudit(org.zendesk.client.v2.model.Ticket ticket, org.zendesk.client.v2.model.Audit audit);

org.zendesk.client.v2.model.User unsuspendUser(long id);

org.zendesk.client.v2.model.hc.Article updateArticle(org.zendesk.client.v2.model.hc.Article article);

org.zendesk.client.v2.model.hc.Translation updateArticleTranslation(Long articleId, String locale, org.zendesk.client.v2.model.hc.Translation translation);

org.zendesk.client.v2.model.Automation updateAutomation(Long automationId, org.zendesk.client.v2.model.Automation automation);

org.zendesk.client.v2.model.hc.Category updateCategory(org.zendesk.client.v2.model.hc.Category category);

org.zendesk.client.v2.model.hc.Translation updateCategoryTranslation(Long categoryId, String locale, org.zendesk.client.v2.model.hc.Translation translation);

org.zendesk.client.v2.model.dynamic.DynamicContentItem updateDynamicContentItem(org.zendesk.client.v2.model.dynamic.DynamicContentItem item);

org.zendesk.client.v2.model.dynamic.DynamicContentItemVariant updateDynamicContentItemVariant(Long itemId, org.zendesk.client.v2.model.dynamic.DynamicContentItemVariant variant);

org.zendesk.client.v2.model.Forum updateForum(org.zendesk.client.v2.model.Forum forum);

org.zendesk.client.v2.model.Group updateGroup(org.zendesk.client.v2.model.Group group);

void updateInstallation(int id, String json);

org.zendesk.client.v2.model.Macro updateMacro(Long macroId, org.zendesk.client.v2.model.Macro macro);

org.zendesk.client.v2.model.Organization updateOrganization(org.zendesk.client.v2.model.Organization organization);

org.zendesk.client.v2.model.JobStatus updateOrganizations(java.util.List<org.zendesk.client.v2.model.Organization> organizations);

org.zendesk.client.v2.model.JobStatus updateOrganizations(org.zendesk.client.v2.model.Organization[] organizations);

org.asynchttpclient.ListenableFuture<org.zendesk.client.v2.model.JobStatus> updateOrganizationsAsync(java.util.List<org.zendesk.client.v2.model.Organization> organizations);

org.zendesk.client.v2.model.hc.PermissionGroup updatePermissionGroup(org.zendesk.client.v2.model.hc.PermissionGroup permissionGroup);

org.zendesk.client.v2.model.Request updateRequest(org.zendesk.client.v2.model.Request request);

org.zendesk.client.v2.model.hc.Section updateSection(org.zendesk.client.v2.model.hc.Section section);

org.zendesk.client.v2.model.hc.Translation updateSectionTranslation(Long sectionId, String locale, org.zendesk.client.v2.model.hc.Translation translation);

org.zendesk.client.v2.model.Ticket updateTicket(org.zendesk.client.v2.model.Ticket ticket);

org.zendesk.client.v2.model.Field updateTicketField(org.zendesk.client.v2.model.Field field);

org.zendesk.client.v2.model.JobStatus updateTickets(java.util.List<org.zendesk.client.v2.model.Ticket> tickets);

org.zendesk.client.v2.model.JobStatus updateTickets(org.zendesk.client.v2.model.Ticket[] tickets);

org.asynchttpclient.ListenableFuture<org.zendesk.client.v2.model.JobStatus> updateTicketsAsync(java.util.List<org.zendesk.client.v2.model.Ticket> tickets);

org.zendesk.client.v2.model.Topic updateTopic(org.zendesk.client.v2.model.Topic topic);

org.zendesk.client.v2.model.Trigger updateTrigger(Long triggerId, org.zendesk.client.v2.model.Trigger trigger);

org.zendesk.client.v2.model.User updateUser(org.zendesk.client.v2.model.User user);

org.zendesk.client.v2.model.Identity updateUserIdentity(long userId, org.zendesk.client.v2.model.Identity identity);

org.zendesk.client.v2.model.Identity updateUserIdentity(org.zendesk.client.v2.model.User user, org.zendesk.client.v2.model.Identity identity);

org.zendesk.client.v2.model.JobStatus updateUsers(java.util.List<org.zendesk.client.v2.model.User> users);

org.zendesk.client.v2.model.JobStatus updateUsers(org.zendesk.client.v2.model.User[] users);

org.asynchttpclient.ListenableFuture<org.zendesk.client.v2.model.JobStatus> updateUsersAsync(java.util.List<org.zendesk.client.v2.model.User> users);

org.zendesk.client.v2.model.hc.UserSegment updateUserSegment(org.zendesk.client.v2.model.hc.UserSegment userSegment);

org.zendesk.client.v2.model.Identity verifyUserIdentity(long userId, long identityId);

org.zendesk.client.v2.model.Identity verifyUserIdentity(org.zendesk.client.v2.model.User user, long identityId);

org.zendesk.client.v2.model.Identity verifyUserIdentity(org.zendesk.client.v2.model.User user, org.zendesk.client.v2.model.Identity identity);

----

The DEFAULT API is defined in the syntax as follows:

----
zendesk:DEFAULT/methodName?[parameters]
----

The 221 method(s) is listed in the table below.
(API methods can have a shorthand alias name which can be used in the syntax instead of the name)

[width="100%",cols="2,2,6",options="header"]
|===
| Method | Alias | Description
| *addTagToOrganisations* |  | 
| *addTagToTicket* |  | 
| *addTagToTopics* |  | 
| *associateAttachmentsToArticle* |  | 
| *changeUserPassword* |  | 
| *createArticle* |  | 
| *createArticleTranslation* |  | 
| *createAutomation* |  | 
| *createCategory* |  | 
| *createCategoryTranslation* |  | 
| *createComment* |  | 
| *createDynamicContentItem* |  | 
| *createDynamicContentItemVariant* |  | 
| *createForum* |  | 
| *createGroup* |  | 
| *createGroupMembership* |  | 
| *createMacro* |  | 
| *createOrganization* |  | 
| *createOrganizationMembership* |  | 
| *createOrganizationMemberships* |  | 
| *createOrganizationMembershipsAsync* |  | 
| *createOrganizations* |  | 
| *createOrganizationsAsync* |  | 
| *createOrUpdateUser* |  | 
| *createOrUpdateUsers* |  | 
| *createOrUpdateUsersAsync* |  | 
| *createPermissionGroup* |  | Create permission group
| *createRequest* |  | 
| *createSatisfactionRating* |  | 
| *createSection* |  | 
| *createSectionTranslation* |  | 
| *createTarget* |  | 
| *createTicket* |  | 
| *createTicketAsync* |  | 
| *createTicketField* |  | 
| *createTicketForm* |  | 
| *createTicketFromTweet* |  | 
| *createTickets* |  | 
| *createTicketsAsync* |  | 
| *createTopic* |  | 
| *createTrigger* |  | 
| *createUpload* |  | 
| *createUploadArticle* |  | Create upload article with inline false
| *createUser* |  | 
| *createUserIdentity* |  | 
| *createUsers* |  | 
| *createUsersAsync* |  | 
| *createUserSegment* |  | Create User Segment
| *deleteArticle* |  | 
| *deleteArticleAttachment* |  | Delete attachment from article
| *deleteAttachment* |  | 
| *deleteAutomation* |  | 
| *deleteCategory* |  | 
| *deleteDynamicContentItem* |  | 
| *deleteDynamicContentItemVariant* |  | 
| *deleteForum* |  | 
| *deleteGroup* |  | 
| *deleteGroupMembership* |  | 
| *deleteOrganization* |  | 
| *deleteOrganizationMembership* |  | 
| *deleteOrganizationMemberships* |  | 
| *deletePermissionGroup* |  | Delete permission group
| *deleteSection* |  | 
| *deleteSuspendedTicket* |  | 
| *deleteTarget* |  | 
| *deleteTicket* |  | 
| *deleteTicketField* |  | 
| *deleteTickets* |  | 
| *deleteTopic* |  | 
| *deleteTranslation* |  | Delete translation
| *deleteTrigger* |  | 
| *deleteUpload* |  | 
| *deleteUser* |  | 
| *deleteUserIdentity* |  | 
| *deleteUserSegment* |  | Delete User Segment
| *getArticle* |  | 
| *getArticleFromSearch* |  | 
| *getArticles* |  | Get all articles from help center
| *getArticlesFromAllLabels* |  | 
| *getArticlesFromAnyLabels* |  | 
| *getArticlesFromPage* |  | 
| *getArticlesIncrementally* |  | 
| *getArticleSubscriptions* |  | 
| *getArticleTranslations* |  | 
| *getAssignableGroupMemberships* |  | 
| *getAttachment* |  | 
| *getAttachmentsFromArticle* |  | 
| *getAutoCompleteOrganizations* |  | 
| *getAutomation* |  | 
| *getCategory* |  | 
| *getCategoryTranslations* |  | 
| *getComplianceDeletionStatuses* |  | 
| *getDeletedTickets* |  | 
| *getDynamicContentItem* |  | 
| *getDynamicContentItemVariant* |  | 
| *getDynamicContentItemVariants* |  | 
| *getForum* |  | 
| *getForums* |  | 
| *getGroup* |  | 
| *getGroupMembership* |  | 
| *getGroupMembershipByUser* |  | 
| *getGroupMemberships* |  | 
| *getGroupOrganization* |  | 
| *getGroupUsers* |  | 
| *getHolidaysForSchedule* |  | 
| *getIncrementalTicketsResult* |  | 
| *getJobStatus* |  | 
| *getJobStatusAsync* |  | 
| *getJobStatuses* |  | 
| *getJobStatusesAsync* |  | 
| *getMacro* |  | 
| *getOrganization* |  | 
| *getOrganizationMembership* |  | 
| *getOrganizationMembershipByUser* |  | 
| *getOrganizationMembershipForUser* |  | 
| *getOrganizationMembershipsForOrg* |  | 
| *getOrganizationMembershipsForUser* |  | 
| *getOrganizationsIncrementally* |  | 
| *getOrganizationTickets* |  | 
| *getOrganizationUsers* |  | 
| *getPermissionGroup* |  | Get permission group by id
| *getRequest* |  | 
| *getRequestComment* |  | 
| *getRequestComments* |  | 
| *getSatisfactionRating* |  | 
| *getSchedule* |  | 
| *getSearchResults* |  | 
| *getSection* |  | 
| *getSections* |  | List Sections using a User Segment
| *getSectionSubscriptions* |  | 
| *getSectionTranslations* |  | 
| *getTarget* |  | 
| *getTicket* |  | 
| *getTicketAudit* |  | 
| *getTicketAudits* |  | 
| *getTicketCollaborators* |  | 
| *getTicketComments* |  | 
| *getTicketField* |  | 
| *getTicketForm* |  | 
| *getTicketIncidents* |  | 
| *getTicketMetric* |  | 
| *getTicketMetricByTicket* |  | 
| *getTickets* |  | 
| *getTicketsByExternalId* |  | 
| *getTicketsFromSearch* |  | 
| *getTicketsIncrementally* |  | 
| *getTopic* |  | 
| *getTopics* |  | List Topics using a User Segment
| *getTopicsByUser* |  | 
| *getTrigger* |  | 
| *getUser* |  | 
| *getUserCCDTickets* |  | 
| *getUserIdentities* |  | 
| *getUserIdentity* |  | 
| *getUserRelatedInfo* |  | 
| *getUserRequestedTickets* |  | 
| *getUserRequests* |  | 
| *getUsersByRole* |  | 
| *getUserSegment* |  | Get user segment by id
| *getUserSegments* |  | Returns the list of user segments that a particular user belongs to
| *getUsersIncrementally* |  | 
| *getUserSubscriptions* |  | 
| *importTicket* |  | 
| *importTopic* |  | 
| *lookupOrganizationsByExternalId* |  | 
| *lookupUserByEmail* |  | 
| *lookupUserByExternalId* |  | 
| *macrosShowChangesToTicket* |  | 
| *macrosShowTicketAfterChanges* |  | 
| *makePrivateTicketAudit* |  | 
| *markTicketAsSpam* |  | 
| *mergeUsers* |  | 
| *notifyApp* |  | 
| *permanentlyDeleteTicket* |  | 
| *permanentlyDeleteTickets* |  | 
| *permanentlyDeleteUser* |  | 
| *queueCreateTicketAsync* |  | 
| *removeTagFromOrganisations* |  | 
| *removeTagFromTicket* |  | 
| *removeTagFromTopics* |  | 
| *requestVerifyUserIdentity* |  | 
| *resetUserPassword* |  | 
| *setGroupMembershipAsDefault* |  | 
| *setOrganizationMembershipAsDefault* |  | 
| *setTagOnOrganisations* |  | 
| *setTagOnTicket* |  | 
| *setTagOnTopics* |  | 
| *setUserPrimaryIdentity* |  | 
| *suspendUser* |  | 
| *trustTicketAudit* |  | 
| *unsuspendUser* |  | 
| *updateArticle* |  | 
| *updateArticleTranslation* |  | 
| *updateAutomation* |  | 
| *updateCategory* |  | 
| *updateCategoryTranslation* |  | 
| *updateDynamicContentItem* |  | 
| *updateDynamicContentItemVariant* |  | 
| *updateForum* |  | 
| *updateGroup* |  | 
| *updateInstallation* |  | 
| *updateMacro* |  | 
| *updateOrganization* |  | 
| *updateOrganizations* |  | 
| *updateOrganizationsAsync* |  | 
| *updatePermissionGroup* |  | Update permission group
| *updateRequest* |  | 
| *updateSection* |  | 
| *updateSectionTranslation* |  | 
| *updateTicket* |  | 
| *updateTicketField* |  | 
| *updateTickets* |  | 
| *updateTicketsAsync* |  | 
| *updateTopic* |  | 
| *updateTrigger* |  | 
| *updateUser* |  | 
| *updateUserIdentity* |  | 
| *updateUsers* |  | 
| *updateUsersAsync* |  | 
| *updateUserSegment* |  | Update User Segment
| *verifyUserIdentity* |  | 
|===

The DEFAULT API method(s) has the following set of parameters listed in the table below:
[width="100%",cols="2,2,4,2",options="header"]
|===
| Method | Parameter | Description | Type
| addTagToOrganisations | *id* |   | Long
| addTagToOrganisations | *tags* |   | String[]
| addTagToTicket | *id* |   | Long
| addTagToTicket | *tags* |   | String[]
| addTagToTopics | *id* |   | Long
| addTagToTopics | *tags* |   | String[]
| associateAttachmentsToArticle | *attachments* |   | List
| associateAttachmentsToArticle | *idArticle* |   | String
| changeUserPassword | *newPassword* |   | String
| changeUserPassword | *oldPassword* |   | String
| changeUserPassword | *user* |   | User
| createArticle | *article* |   | Article
| createArticle | *notifySubscribers* |   | Boolean
| createArticleTranslation | *articleId* |   | Long
| createArticleTranslation | *translation* |   | Translation
| createAutomation | *automation* |   | Automation
| createCategory | *category* |   | Category
| createCategoryTranslation | *categoryId* |   | Long
| createCategoryTranslation | *translation* |   | Translation
| createComment | *comment* |   | Comment
| createComment | *ticketId* |   | Long
| createDynamicContentItem | *item* |   | DynamicContentItem
| createDynamicContentItemVariant | *itemId* |   | Long
| createDynamicContentItemVariant | *variant* |   | DynamicContentItemVariant
| createForum | *forum* |   | Forum
| createGroup | *group* |   | Group
| createGroupMembership | *groupMembership* |   | GroupMembership
| createGroupMembership | *user_id* |   | Long
| createMacro | *macro* |   | Macro
| createOrganization | *organization* |   | Organization
| createOrganizationMembership | *organizationMembership* |   | OrganizationMembership
| createOrganizationMembership | *user_id* |   | Long
| createOrganizationMemberships | *organizationMembershipList* |   | List
| createOrganizationMemberships | *organizationMemberships* |   | OrganizationMembership[]
| createOrganizationMembershipsAsync | *organizationMembershipList* |   | List
| createOrganizations | *organizationList* |   | List
| createOrganizations | *organizations* |   | Organization[]
| createOrganizationsAsync | *organizationList* |   | List
| createOrUpdateUser | *user* |   | User
| createOrUpdateUsers | *users* |   | User[]
| createOrUpdateUsers | *usersList* |   | List
| createOrUpdateUsersAsync | *usersList* |   | List
| createPermissionGroup | *permissionGroup* |   | PermissionGroup
| createRequest | *request* |   | Request
| createSatisfactionRating | *satisfactionRating* |   | SatisfactionRating
| createSatisfactionRating | *ticket* |   | Ticket
| createSatisfactionRating | *ticketId* |   | Long
| createSection | *section* |   | Section
| createSectionTranslation | *sectionId* |   | Long
| createSectionTranslation | *translation* |   | Translation
| createTarget | *target* |   | Target
| createTicket | *ticket* |   | Ticket
| createTicketAsync | *ticket* |   | Ticket
| createTicketField | *field* |   | Field
| createTicketForm | *ticketForm* |   | TicketForm
| createTicketFromTweet | *monitorId* |   | Long
| createTicketFromTweet | *tweetId* |   | Long
| createTickets | *ticketList* |   | List
| createTickets | *tickets* |   | Ticket[]
| createTicketsAsync | *ticketList* |   | List
| createTopic | *topic* |   | Topic
| createTrigger | *trigger* |   | Trigger
| createUpload | *content* |   | byte[]
| createUpload | *contentType* |   | String
| createUpload | *fileName* |   | String
| createUpload | *token* |   | String
| createUploadArticle | *articleId0* |   | Long
| createUploadArticle | *file* |   | File
| createUploadArticle | *inline* |   | Boolean
| createUser | *user* |   | User
| createUserIdentity | *identity* |   | Identity
| createUserIdentity | *user* |   | User
| createUserIdentity | *userId* |   | Long
| createUsers | *userList* |   | List
| createUsers | *users* |   | User[]
| createUsersAsync | *userList* |   | List
| createUserSegment | *userSegment* |   | UserSegment
| deleteArticle | *article* |   | Article
| deleteArticleAttachment | *articleAttachments* |   | ArticleAttachments
| deleteArticleAttachment | *id* |  Attachment identifier | Long
| deleteAttachment | *attachment* |   | Attachment
| deleteAttachment | *id* |   | Long
| deleteAutomation | *automationId0* |   | Long
| deleteCategory | *category* |   | Category
| deleteDynamicContentItem | *item* |   | DynamicContentItem
| deleteDynamicContentItemVariant | *itemId* |   | Long
| deleteDynamicContentItemVariant | *variant* |   | DynamicContentItemVariant
| deleteForum | *forum* |   | Forum
| deleteGroup | *group* |   | Group
| deleteGroup | *id* |   | Long
| deleteGroupMembership | *groupMembership* |   | GroupMembership
| deleteGroupMembership | *group_membership_id* |   | Long
| deleteGroupMembership | *id* |   | Long
| deleteGroupMembership | *user_id* |   | Long
| deleteOrganization | *id* |   | Long
| deleteOrganization | *organization* |   | Organization
| deleteOrganizationMembership | *id* |   | Long
| deleteOrganizationMembership | *organizationMembership* |   | OrganizationMembership
| deleteOrganizationMembership | *organization_membership_id* |   | Long
| deleteOrganizationMembership | *user_id* |   | Long
| deleteOrganizationMemberships | *id* |   | Long
| deleteOrganizationMemberships | *ids* |   | long[]
| deletePermissionGroup | *id* |   | Long
| deletePermissionGroup | *permissionGroup* |   | PermissionGroup
| deleteSection | *section* |   | Section
| deleteSuspendedTicket | *id* |   | Long
| deleteSuspendedTicket | *suspendedTicket* |   | SuspendedTicket
| deleteTarget | *targetId* |   | Long
| deleteTicket | *id* |   | Long
| deleteTicket | *ticket* |   | Ticket
| deleteTicketField | *field* |   | Field
| deleteTicketField | *id* |   | Long
| deleteTickets | *id* |   | Long
| deleteTickets | *ids* |   | long[]
| deleteTopic | *topic* |   | Topic
| deleteTranslation | *translation* |   | Translation
| deleteTranslation | *translationId* |   | Long
| deleteTrigger | *triggerId* |   | Long
| deleteUpload | *token* |   | String
| deleteUpload | *upload* |   | Upload
| deleteUser | *id* |   | Long
| deleteUser | *user* |   | User
| deleteUserIdentity | *identity* |   | Identity
| deleteUserIdentity | *identityId* |   | Long
| deleteUserIdentity | *user* |   | User
| deleteUserIdentity | *userId* |   | Long
| deleteUserSegment | *id* |   | Long
| deleteUserSegment | *userSegment* |   | UserSegment
| getArticle | *id* |   | Long
| getArticleFromSearch | *searchTerm* |   | String
| getArticleFromSearch | *sectionId* |   | Long
| getArticles | *category* |   | Category
| getArticles | *locale* |   | String
| getArticles | *section* |   | Section
| getArticlesFromAllLabels | *labels* |   | List
| getArticlesFromAnyLabels | *labels* |   | List
| getArticlesFromPage | *page* |   | Integer
| getArticlesIncrementally | *startTime* |   | Date
| getArticleSubscriptions | *articleId* |   | Long
| getArticleSubscriptions | *locale* |   | String
| getArticleTranslations | *articleId* |   | Long
| getAssignableGroupMemberships | *group_id* |   | Long
| getAttachment | *attachment* |   | Attachment
| getAttachment | *id* |   | Long
| getAttachmentsFromArticle | *articleId* |   | Long
| getAutoCompleteOrganizations | *name* |   | String
| getAutomation | *id* |   | Long
| getCategory | *id* |   | Long
| getCategoryTranslations | *categoryId* |   | Long
| getComplianceDeletionStatuses | *userId* |   | Long
| getDeletedTickets | *sortBy* |   | String
| getDeletedTickets | *sortOrder* |   | SortOrder
| getDynamicContentItem | *id* |   | Long
| getDynamicContentItemVariant | *id* |   | Long
| getDynamicContentItemVariant | *itemId* |   | Long
| getDynamicContentItemVariants | *item* |   | DynamicContentItem
| getForum | *id* |   | Long
| getForums | *category_id* |   | Long
| getGroup | *id* |   | Long
| getGroupMembership | *group_membership_id* |   | Long
| getGroupMembership | *id* |   | Long
| getGroupMembership | *user_id* |   | Long
| getGroupMembershipByUser | *user_id* |   | Long
| getGroupMemberships | *group_id* |   | Long
| getGroupOrganization | *organization_membership_id* |   | Long
| getGroupOrganization | *user_id* |   | Long
| getGroupUsers | *id* |   | Long
| getHolidaysForSchedule | *schedule* |   | Schedule
| getHolidaysForSchedule | *scheduleId* |   | Long
| getIncrementalTicketsResult | *unixEpochTime* |   | Long
| getJobStatus | *status* |   | JobStatus
| getJobStatusAsync | *status* |   | JobStatus
| getJobStatuses | *statuses* |   | List
| getJobStatusesAsync | *statuses* |   | List
| getMacro | *macroId* |   | Long
| getOrganization | *id* |   | Long
| getOrganizationMembership | *id* |   | Long
| getOrganizationMembershipByUser | *user_id* |   | Long
| getOrganizationMembershipForUser | *id* |   | Long
| getOrganizationMembershipForUser | *user_id* |   | Long
| getOrganizationMembershipsForOrg | *organization_id* |   | Long
| getOrganizationMembershipsForUser | *user_id* |   | Long
| getOrganizationsIncrementally | *startTime* |   | Date
| getOrganizationTickets | *organizationId* |   | Long
| getOrganizationUsers | *id* |   | Long
| getPermissionGroup | *id* |   | Long
| getRequest | *id* |   | Long
| getRequestComment | *comment* |   | Comment
| getRequestComment | *commentId* |   | Long
| getRequestComment | *request* |   | Request
| getRequestComment | *requestId* |   | Long
| getRequestComments | *id* |   | Long
| getRequestComments | *request* |   | Request
| getSatisfactionRating | *id* |   | Long
| getSchedule | *schedule* |   | Schedule
| getSchedule | *scheduleId* |   | Long
| getSearchResults | *parameters* |   | String
| getSearchResults | *params* |   | Map
| getSearchResults | *query* |   | String
| getSearchResults | *sortBy* |   | String
| getSearchResults | *sortOrder* |   | SortOrder
| getSearchResults | *type* |   | Class
| getSection | *id* |   | Long
| getSections | *category* |   | Category
| getSections | *userSegment* |   | UserSegment
| getSectionSubscriptions | *locale* |   | String
| getSectionSubscriptions | *sectionId* |   | Long
| getSectionTranslations | *sectionId* |   | Long
| getTarget | *id* |   | Long
| getTicket | *id* |   | Long
| getTicketAudit | *audit* |   | Audit
| getTicketAudit | *auditId* |   | Long
| getTicketAudit | *id* |   | Long
| getTicketAudit | *ticket* |   | Ticket
| getTicketAudit | *ticketId* |   | Long
| getTicketAudits | *ticket* |   | Ticket
| getTicketAudits | *ticketId0* |   | Long
| getTicketCollaborators | *id* |   | Long
| getTicketComments | *id* |   | Long
| getTicketComments | *order* |   | SortOrder
| getTicketField | *id* |   | Long
| getTicketForm | *id* |   | Long
| getTicketIncidents | *id* |   | Long
| getTicketMetric | *id* |   | Long
| getTicketMetricByTicket | *id* |   | Long
| getTickets | *id* |   | Long
| getTickets | *ids* |   | long[]
| getTicketsByExternalId | *externalId* |   | String
| getTicketsByExternalId | *includeArchived* |   | Boolean
| getTicketsFromSearch | *searchTerm* |   | String
| getTicketsIncrementally | *endTime* |   | Date
| getTicketsIncrementally | *startTime* |   | Date
| getTopic | *id* |   | Long
| getTopics | *forum_id* |   | Long
| getTopics | *id* |   | Long
| getTopics | *ids* |   | long[]
| getTopics | *userSegment* |   | UserSegment
| getTopicsByUser | *user_id* |   | Long
| getTrigger | *id* |   | Long
| getUser | *id* |   | Long
| getUserCCDTickets | *userId* |   | Long
| getUserIdentities | *user* |   | User
| getUserIdentities | *userId* |   | Long
| getUserIdentity | *identity* |   | Identity
| getUserIdentity | *identityId* |   | Long
| getUserIdentity | *user* |   | User
| getUserIdentity | *userId* |   | Long
| getUserRelatedInfo | *userId* |   | Long
| getUserRequestedTickets | *userId* |   | Long
| getUserRequests | *id* |   | Long
| getUserRequests | *user* |   | User
| getUsersByRole | *role* |   | String
| getUsersByRole | *roles* |   | String[]
| getUserSegment | *id* |   | Long
| getUserSegments | *id* |   | Long
| getUsersIncrementally | *startTime* |   | Date
| getUserSubscriptions | *user* |   | User
| getUserSubscriptions | *userId0* |   | Long
| importTicket | *ticketImport* |   | TicketImport
| importTopic | *topic* |   | Topic
| lookupOrganizationsByExternalId | *externalId* |   | String
| lookupUserByEmail | *email* |   | String
| lookupUserByExternalId | *externalId* |   | String
| macrosShowChangesToTicket | *macroId* |   | Long
| macrosShowTicketAfterChanges | *macroId* |   | Long
| macrosShowTicketAfterChanges | *ticketId* |   | Long
| makePrivateTicketAudit | *audit* |   | Audit
| makePrivateTicketAudit | *auditId* |   | Long
| makePrivateTicketAudit | *id* |   | Long
| makePrivateTicketAudit | *ticket* |   | Ticket
| makePrivateTicketAudit | *ticketId* |   | Long
| markTicketAsSpam | *id* |   | Long
| markTicketAsSpam | *ticket* |   | Ticket
| mergeUsers | *userIdThatWillBeMerged* |   | Long
| mergeUsers | *userIdThatWillRemain* |   | Long
| notifyApp | *json* |   | String
| permanentlyDeleteTicket | *id* |   | Long
| permanentlyDeleteTicket | *ticket* |   | Ticket
| permanentlyDeleteTickets | *id* |   | Long
| permanentlyDeleteTickets | *ids* |   | long[]
| permanentlyDeleteUser | *id* |   | Long
| permanentlyDeleteUser | *user* |   | User
| queueCreateTicketAsync | *ticket* |   | Ticket
| removeTagFromOrganisations | *id* |   | Long
| removeTagFromOrganisations | *tags* |   | String[]
| removeTagFromTicket | *id* |   | Long
| removeTagFromTicket | *tags* |   | String[]
| removeTagFromTopics | *id* |   | Long
| removeTagFromTopics | *tags* |   | String[]
| requestVerifyUserIdentity | *identity* |   | Identity
| requestVerifyUserIdentity | *identityId* |   | Long
| requestVerifyUserIdentity | *user* |   | User
| requestVerifyUserIdentity | *userId* |   | Long
| resetUserPassword | *id* |   | Long
| resetUserPassword | *password* |   | String
| resetUserPassword | *user* |   | User
| setGroupMembershipAsDefault | *groupMembership* |   | GroupMembership
| setGroupMembershipAsDefault | *user_id* |   | Long
| setOrganizationMembershipAsDefault | *organizationMembership* |   | OrganizationMembership
| setOrganizationMembershipAsDefault | *user_id* |   | Long
| setTagOnOrganisations | *id* |   | Long
| setTagOnOrganisations | *tags* |   | String[]
| setTagOnTicket | *id* |   | Long
| setTagOnTicket | *tags* |   | String[]
| setTagOnTopics | *id* |   | Long
| setTagOnTopics | *tags* |   | String[]
| setUserPrimaryIdentity | *identity* |   | Identity
| setUserPrimaryIdentity | *identityId* |   | Long
| setUserPrimaryIdentity | *user* |   | User
| setUserPrimaryIdentity | *userId* |   | Long
| suspendUser | *id* |   | Long
| trustTicketAudit | *audit* |   | Audit
| trustTicketAudit | *auditId* |   | Long
| trustTicketAudit | *id* |   | Long
| trustTicketAudit | *ticket* |   | Ticket
| trustTicketAudit | *ticketId* |   | Long
| unsuspendUser | *id* |   | Long
| updateArticle | *article* |   | Article
| updateArticleTranslation | *articleId* |   | Long
| updateArticleTranslation | *locale* |   | String
| updateArticleTranslation | *translation* |   | Translation
| updateAutomation | *automation* |   | Automation
| updateAutomation | *automationId* |   | Long
| updateCategory | *category* |   | Category
| updateCategoryTranslation | *categoryId* |   | Long
| updateCategoryTranslation | *locale* |   | String
| updateCategoryTranslation | *translation* |   | Translation
| updateDynamicContentItem | *item* |   | DynamicContentItem
| updateDynamicContentItemVariant | *itemId* |   | Long
| updateDynamicContentItemVariant | *variant* |   | DynamicContentItemVariant
| updateForum | *forum* |   | Forum
| updateGroup | *group* |   | Group
| updateInstallation | *installationId* |   | Integer
| updateInstallation | *json* |   | String
| updateMacro | *macro* |   | Macro
| updateMacro | *macroId0* |   | Long
| updateOrganization | *organization* |   | Organization
| updateOrganizations | *organizationList* |   | List
| updateOrganizations | *organizations* |   | Organization[]
| updateOrganizationsAsync | *organizationList* |   | List
| updatePermissionGroup | *permissionGroup* |   | PermissionGroup
| updateRequest | *request* |   | Request
| updateSection | *section* |   | Section
| updateSectionTranslation | *locale* |   | String
| updateSectionTranslation | *sectionId* |   | Long
| updateSectionTranslation | *translation* |   | Translation
| updateTicket | *ticket* |   | Ticket
| updateTicketField | *field* |   | Field
| updateTickets | *ticketList* |   | List
| updateTickets | *tickets* |   | Ticket[]
| updateTicketsAsync | *ticketList* |   | List
| updateTopic | *topic* |   | Topic
| updateTrigger | *trigger* |   | Trigger
| updateTrigger | *triggerId0* |   | Long
| updateUser | *user* |   | User
| updateUserIdentity | *identity* |   | Identity
| updateUserIdentity | *user* |   | User
| updateUserIdentity | *userId* |   | Long
| updateUsers | *users* |   | User[]
| updateUsers | *usersList* |   | List
| updateUsersAsync | *usersList* |   | List
| updateUserSegment | *userSegment* |   | UserSegment
| verifyUserIdentity | *identity* |   | Identity
| verifyUserIdentity | *identityId* |   | Long
| verifyUserIdentity | *user* |   | User
| verifyUserIdentity | *userId* |   | Long
|===

In addition to the parameters above, the DEFAULT API can also use from the 27 endpoint query option
which is listed in the _Query Parameters_ section.

Any of the parameters can be provided in either the endpoint URI, or dynamically in a message header.
The message header name must be of the format `CamelZendesk.parameter`.
The `inBody` parameter overrides message header, i.e. the endpoint parameter `inBody=myParameterNameHere`
would override a `CamelZendesk.myParameterNameHere` header.
// endpoint options: END



include::camel-spring-boot::page$zendesk-starter.adoc[]
