= Validator Component
:doctitle: Validator
:shortname: validator
:artifactid: camel-validator
:description: Validate the payload using XML Schema and JAXP Validation.
:since: 1.1
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported
:core:
//Manually maintained attributes
:camel-spring-boot-name: validator

*Since Camel {since}*

*{component-header}*

The Validation component performs XML validation of the message body
using the JAXP Validation API and based on any of the supported XML
schema languages, which defaults to http://www.w3.org/XML/Schema[XML
Schema].

== URI format

----
validator:someLocalOrRemoteResource
----

Where *someLocalOrRemoteResource* is some URL to a local resource on the
classpath or a full URL to a remote resource or resource on the file
system which contains the XSD to validate against. For example:

* `validator:com/mypackage/myschema.xsd`

The Validation component is provided directly in the camel-core.


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END


== Example

The following
https://github.com/apache/camel/blob/main/components/camel-spring-xml/src/test/resources/org/apache/camel/component/validator/camelContext.xml[example]
shows how to configure a route from endpoint *direct:start* which then
goes to one of two endpoints, either *mock:valid* or *mock:invalid*
based on whether the XML matches the given schema (which is
supplied on the classpath).

== Advanced: JMX method `clearCachedSchema`

You can force that the cached schema in the
validator endpoint is cleared and reread with the next process call with
the JMX operation `clearCachedSchema`. You can also use this method to
programmatically clear the cache. This method is available on the
`ValidatorEndpoint` class.


include::spring-boot:partial$starter.adoc[]
