= YAML DSL Component
:doctitle: YAML DSL
:shortname: yaml-dsl
:artifactid: camel-yaml-dsl
:description: Camel DSL with YAML
:since: 3.9
:supportlevel: Stable
:tabs-sync-option:
//Manually maintained attributes
:group: DSL

*Since Camel {since}*

The YAML DSL provides the capability to define your Camel routes, route templates & REST DSL configuration in YAML.

== Defining a route

A route is collection of elements defined as follows:

[source,yaml]
----
- from: #<1>
    uri: "direct:start"
    steps: #<2>
      - filter:
          expression:
            simple: "${in.header.continue} == true"
          steps: #<2>
            - to:
                uri: "log:filtered"
      - to:
          uri: "log:original"
----

<1> route entry point, by default `from` and `rest` are supported
<2> processing steps

[NOTE]
====
Each step is represented by a YAML map that has a single entry where the field name is the EIP name
====

As a general rule, each step provides all the parameters the related definition declares, but there are some minor differences/enhancements:

- *Output Aware Steps*
+
Some steps such as `filter` and `split` have their own pipeline. When an exchange matches the filter expression or for the items generated by the split expression, such a pipeline can be defined by the `steps` field:
+
[source,yaml]
----
filter:
  expression:
    simple: "${in.header.continue} == true"
    steps:
      - to:
          uri: "log:filtered"
----
+

- *Expression Aware Steps*
+
Some EIPs such as `filter` and `split` support the definition of an expression through the `expression` field:
+
[source,yaml]
.Explicit Expression field
----
filter:
  expression:
    simple: "${in.header.continue} == true"
----
+
To make the DSL less verbose, the `expression` field can be omitted:
+
[source,yaml]
.Implicit Expression field
----
filter:
  simple: "${in.header.continue} == true"
----
+
In general, `expression` can be defined inline like in the examples above. But in case you need to provide more information, you can 'unroll' the expression definition and configure any single parameter the expression defines.
+
[source,yaml]
.Full Expression definition
----
filter:
  tokenize:
    token: "<"
    endToken: ">"
----

- *Data Format Aware Steps*
+
The EIP `marshal` and `unmarshal` supports the definition of data formats:
+
[source,yaml]
----
marshal:
  json:
    library: Gson
----
+
[NOTE]
====
In case you want to use the data-format's default settings, you need to place an empty block as data format parameters, like `json: {}`
====

== Defining endpoints

To define an endpoint with the YAML dsl you have two options:

. Using a classic Camel URI:
+
[source,yaml]
----
- from:
    uri: "timer:tick?period=1s"
    steps:
      - to:
          uri: "telegram:bots?authorizationToken=XXX"
----
. Using URI and parameters:
+
[source,yaml]
----
- from:
    uri: "timer://tick"
    parameters:
      period: "1s"
    steps:
      - to:
          uri: "telegram:bots"
          parameters:
            authorizationToken: "XXX"
----

== Defining beans

In addition to the general support for creating beans provided by xref:others:main.adoc#_specifying_custom_beans[Camel Main], the YAML DSL provides a convenient syntax to define and configure them:

[source,yaml]
----
- beans:
  - name: beanFromMap  # <1>
    type: com.acme.MyBean # <2>
    properties: # <3>
      foo: bar
----

<1> the name of the bean which will be used to bound the instance to the Camel Registry
<2> the full qualified class name of the bean
<3> the properties of the bean to be set

The properties of the bean can be defined using either a map or properties style, as shown in the example below:

[source,yaml]
----
- beans:
  # map style
  - name: beanFromMap
    type: com.acme.MyBean
    properties:
      field1: 'f1'
      field2: 'f2'
      nested:
        field1: 'nf1'
        field2: 'nf2'
  # properties style
  - name: beanFromProps
    type: com.acme.MyBean
    properties:
      field1: 'f1_p'
      field2: 'f2_p'
      nested.field1: 'nf1_p'
      nested.field2: 'nf2_p'
----

[NOTE]
====
The `beans` elements can only be used as the root element
====

== Configuring options on languages

Some xref:components:languages:index.adoc[Languages] have additional configurations
you may need to use.

For example, the xref:components:languages:jsonpath-language.adoc[JSONPath]
can be configured to ignore JSon parsing errors. This is intended when you use a
xref:components:eips:choice-eip.adoc[Content Based Router] and want to route the message
to different endpoints. But the JSon payload of the message can be in different forms;
meaning that the JSonPath expressions in some cases would fail with an exception,
and other times not. In this situation, you need to set `suppress-exception` to true,
as shown below:

[source,yaml]
----
- from:
    uri: "direct:start"
    steps:
      - choice:
          when:
          - jsonpath:
              expression: "person.middlename"
              suppressExceptions: true
            steps:
            - to: "mock:middle"
          - jsonpath:
              expression: "person.lastname"
              suppressExceptions: true
            steps:
            - to: "mock:last"
          otherwise:
            steps:
              - to: "mock:other"
----

In the route above, the following message

[source,json]
----
{
  "person": {
    "firstname": "John",
    "lastname": "Doe"
  }
}
----

Would have failed the JSonPath expression `person.middlename` because the JSon payload
does not have a `middlename` field. To remedy this we have suppressed the exception.

== External examples

You can find a set of examples using `main-yaml` in https://github.com/apache/camel-examples[Camel Examples]
which demonstrate creating Camel Routes with YAML.

Another way to find examples of YAML DSL is to look in https://github.com/apache/camel-kamelets[Camel Kamelets]
where each Kamelet is defined using YAML.

== Supported EIPs

The following set of high level EIPs are supported in the yaml DSL language. For full details on their expected configuration, please refer to the https://github.com/apache/camel/blob/main/dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json[Camel YAML DSL specification].

- Aggregate
- Bean
- Do Catch
- Do Try
- Do Finally
- Choice
- Circuit Breaker
- Claim Check
- Convert Body To
- Delay
- Dynamic Router
- Enrich
- Error Handler
- Filter
- From
- Idempotent Consumer
- Intercept
- Intercept From
- Intercept Send To Endpoint
- Load Balance
- Log
- Loop
- Marshal
- Multicast
- On Completion
- On Exception
- On Fallback
- Otherwise
- Pausable
- Pipeline
- Policy
- Poll Enrich
- Process
- Recipient List
- Remove Header
- Remove Headers
- Remove Property
- Remove Properties
- Resequence
- Resumable
- REST DSL
- Rollback
- Routing Slip
- Saga
- Sample
- Script
- Service Call
- Set Body
- Set Exchange Pattern
- Set Header
- Set Property
- Sort
- Split
- Step
- Stop
- Threads
- Throttle
- Throw Exception
- To
- To Dynamic
- Transacted
- Transform
- Unmarshal
- Validate
- When
- When Skip Send To Endpoint
- Wire Tap
