= ParquetAvro File DataFormat
:doctitle: ParquetAvro Format
:shortname: parquetAvro
:artifactid: camel-parquet-avro
:description: Unmarshal and marshal parquet format using avro (de)/serializers
:since: 4.0
:supportlevel: Unstable
:tabs-sync-option:
//Manually maintained attributes
:camel-spring-boot-name: parquet-avro

*Since Camel {since}*

The ParquetAvro Data Format Data Format is a Camel Frameworks's data format implementation based on parquet-avro library for (de)/serialization purposes. Messages can be unmarshalled (conversion to simple Java POJO(s)) to plain Java objects. By the help of Camel's routing engine and data transformations you can then play with POJO(s) and apply customised formatting and call other Camel Component's to convert and send messages to upstream systems.

== Parquet Data Format Options

// dataformat options: START
include::partial$dataformat-options.adoc[]
// dataformat options: END

== Unmarshal

There are ways to unmarshal parquet files/structures (Usually binary parquet files) where camel DSL allows

In this first example we unmarshal file payload to OutputStream and send it to mock endpoint, then we will be able to get Pojo (it could be a list if that is coming through)

[source,java]
-----------------------------------------------------------------------
from("direct:unmarshal").unmarshal(parquet).to("mock:unmarshal");
-----------------------------------------------------------------------

== Marshal

Marshalling is the reverse process of unmarshalling so when you have your Pojo and marshal it you will get the parquet formatted output stream on your producer endpoint.

[source,java]
-----------------------------------------------------------------------
from("direct:marshal").marshal(parquet).to("mock:marshal");
-----------------------------------------------------------------------

== Dependencies

To use parquet-avro data format in your camel routes you need to add a dependency on
*camel-parquet-avro* which implements this data format.

If you use Maven you can just add the following to your `pom.xml`,
substituting the version number for the latest & greatest release (see
the download page for the latest versions).

[source,xml]
----------------------------------------------------------
<dependency>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-parquet-avro</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel core version -->
</dependency>
----------------------------------------------------------


include::spring-boot:partial$starter.adoc[]