= CyberArk Vault Component
:doctitle: CyberArk Vault
:shortname: cyberark-vault
:artifactid: camel-cyberark-vault
:description: Retrieve secrets from CyberArk Conjur Vault.
:since: 4.17
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported
//Manually maintained attributes
:camel-spring-boot-name: cyberark-vault

*Since Camel {since}*

*{component-header}*

The CyberArk Vault component supports https://www.cyberark.com/products/conjur/[CyberArk Conjur] Vault service.

Prerequisites

You must have access to a CyberArk Conjur instance and have the necessary credentials
(username/password, API key, or auth token) to access it.

== URI Format

----
cyberark-vault:label[?options]
----

Where `label` is a logical name for the endpoint.

You can specify the secret ID either as a URI parameter or via a message header (`CamelCyberArkVaultSecretId`).

You can append query options to the URI in the following format:

`?options=value&option2=value&...`


// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
include::partial$component-endpoint-headers.adoc[]
// component options: END

=== Authentication Methods

The component supports multiple authentication methods with CyberArk Conjur:

1. **Username/Password Authentication**: Use username and password to authenticate
2. **API Key Authentication**: Use username and API key (recommended for programmatic access)
3. **Pre-authenticated Token**: Use a pre-obtained authentication token

=== Using CyberArk Conjur Vault Property Function

To use this function, you'll need to provide credentials to CyberArk Conjur Service as environment variables:

[source,bash]
----
export CAMEL_VAULT_CYBERARK_URL=https://conjur.example.com
export CAMEL_VAULT_CYBERARK_ACCOUNT=myaccount
export CAMEL_VAULT_CYBERARK_USERNAME=admin
export CAMEL_VAULT_CYBERARK_PASSWORD=secretpassword
----

You can also configure the credentials in the `application.properties` file such as:

[source,properties]
----
camel.vault.cyberark.url=https://conjur.example.com
camel.vault.cyberark.account=myaccount
camel.vault.cyberark.username=admin
camel.vault.cyberark.password=secretpassword
----

NOTE: If you're running the application on a Kubernetes based cloud platform, you can initialize the environment variables from a Secret or ConfigMap to enhance security.

For API key authentication:

[source,bash]
----
export CAMEL_VAULT_CYBERARK_URL=https://conjur.example.com
export CAMEL_VAULT_CYBERARK_ACCOUNT=myaccount
export CAMEL_VAULT_CYBERARK_USERNAME=host/myapp
export CAMEL_VAULT_CYBERARK_API_KEY=3ahx8dy3...
----

Or in `application.properties`:

[source,properties]
----
camel.vault.cyberark.url=https://conjur.example.com
camel.vault.cyberark.account=myaccount
camel.vault.cyberark.username=host/myapp
camel.vault.cyberark.apiKey=3ahx8dy3...
----

=== Operations

The component supports the following operations:

* **getSecret** (default) - Retrieve a secret value from CyberArk Conjur
* **createSecret** - Create or update a secret in CyberArk Conjur

You can specify the operation either as a URI parameter or via a message header (`CamelCyberArkVaultOperation`).

=== Examples

==== Property Placeholders

At this point, you can access secrets using property placeholders in your routes:

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .setHeader("DatabasePassword", simple("{{cyberark:db/password}}"))
    .to("direct:next");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:start"/>
  <setHeader name="DatabasePassword">
    <simple>{{cyberark:db/password}}</simple>
  </setHeader>
  <to uri="direct:next"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
      steps:
        - setHeader:
            name: DatabasePassword
            simple: "{{cyberark:db/password}}"
        - to:
            uri: direct:next
----
====

You can also specify a default value in case the secret doesn't exist:

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .setHeader("Password", simple("{{cyberark:db/password:defaultPassword}}"))
    .to("direct:next");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:start"/>
  <setHeader name="Password">
    <simple>{{cyberark:db/password:defaultPassword}}</simple>
  </setHeader>
  <to uri="direct:next"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
      steps:
        - setHeader:
            name: Password
            simple: "{{cyberark:db/password:defaultPassword}}"
        - to:
            uri: direct:next
----
====

==== Retrieve JSON Field from Secret

If your secret contains JSON data, you can extract specific fields:

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .setHeader("Username", simple("{{cyberark:database#username}}"))
    .setHeader("Password", simple("{{cyberark:database#password}}"))
    .to("direct:next");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:start"/>
  <setHeader name="Username">
    <simple>{{cyberark:database#username}}</simple>
  </setHeader>
  <setHeader name="Password">
    <simple>{{cyberark:database#password}}</simple>
  </setHeader>
  <to uri="direct:next"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
      steps:
        - setHeader:
            name: Username
            simple: "{{cyberark:database#username}}"
        - setHeader:
            name: Password
            simple: "{{cyberark:database#password}}"
        - to:
            uri: direct:next
----
====

==== Retrieve a Secret (getSecret)

You can retrieve a secret using the component endpoint:

Using URI parameter:

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .to("cyberark-vault:secret?operation=getSecret&secretId=db/password&url=https://conjur.example.com&account=myaccount&username=admin&password=secretpass")
    .log("Retrieved secret: ${body}");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:start"/>
  <to uri="cyberark-vault:secret?operation=getSecret&amp;secretId=db/password&amp;url=https://conjur.example.com&amp;account=myaccount&amp;username=admin&amp;password=secretpass"/>
  <log message="Retrieved secret: ${body}"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
      steps:
        - to:
            uri: cyberark-vault:secret
            parameters:
              operation: getSecret
              secretId: db/password
              url: "https://conjur.example.com"
              account: myaccount
              username: admin
              password: secretpass
        - log:
            message: "Retrieved secret: ${body}"
----
====

Using message header for dynamic secret retrieval:

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .setHeader("CamelCyberArkVaultSecretId", simple("${header.secretName}"))
    .to("cyberark-vault:secret?operation=getSecret&url=https://conjur.example.com&account=myaccount&username=admin&password=secretpass")
    .log("Retrieved secret: ${body}");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:start"/>
  <setHeader name="CamelCyberArkVaultSecretId">
    <simple>${header.secretName}</simple>
  </setHeader>
  <to uri="cyberark-vault:secret?operation=getSecret&amp;url=https://conjur.example.com&amp;account=myaccount&amp;username=admin&amp;password=secretpass"/>
  <log message="Retrieved secret: ${body}"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
      steps:
        - setHeader:
            name: CamelCyberArkVaultSecretId
            simple: "${header.secretName}"
        - to:
            uri: cyberark-vault:secret
            parameters:
              operation: getSecret
              url: "https://conjur.example.com"
              account: myaccount
              username: admin
              password: secretpass
        - log:
            message: "Retrieved secret: ${body}"
----
====

Retrieve a specific version of a secret:

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .setHeader("CamelCyberArkVaultSecretVersion", constant("3"))
    .to("cyberark-vault:secret?secretId=db/password&url=https://conjur.example.com&account=myaccount&username=admin&apiKey=3ahx8dy3...")
    .log("Retrieved secret version 3: ${body}");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:start"/>
  <setHeader name="CamelCyberArkVaultSecretVersion">
    <constant>3</constant>
  </setHeader>
  <to uri="cyberark-vault:secret?secretId=db/password&amp;url=https://conjur.example.com&amp;account=myaccount&amp;username=admin&amp;apiKey=3ahx8dy3..."/>
  <log message="Retrieved secret version 3: ${body}"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
      steps:
        - setHeader:
            name: CamelCyberArkVaultSecretVersion
            constant: "3"
        - to:
            uri: cyberark-vault:secret
            parameters:
              secretId: db/password
              url: "https://conjur.example.com"
              account: myaccount
              username: admin
              apiKey: "3ahx8dy3..."
        - log:
            message: "Retrieved secret version 3: ${body}"
----
====

==== Create or Update a Secret (createSecret)

To create or update a secret, use the createSecret operation with the secret value in the message body or header:

Using message body:

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .setBody(constant("mySecretValue123"))
    .to("cyberark-vault:secret?operation=createSecret&secretId=app/apikey&url=https://conjur.example.com&account=myaccount&username=admin&apiKey=3ahx8dy3...")
    .log("Secret created/updated");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:start"/>
  <setBody>
    <constant>mySecretValue123</constant>
  </setBody>
  <to uri="cyberark-vault:secret?operation=createSecret&amp;secretId=app/apikey&amp;url=https://conjur.example.com&amp;account=myaccount&amp;username=admin&amp;apiKey=3ahx8dy3..."/>
  <log message="Secret created/updated"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
      steps:
        - setBody:
            constant: mySecretValue123
        - to:
            uri: cyberark-vault:secret
            parameters:
              operation: createSecret
              secretId: app/apikey
              url: "https://conjur.example.com"
              account: myaccount
              username: admin
              apiKey: "3ahx8dy3..."
        - log:
            message: "Secret created/updated"
----
====

Using message header:

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .setHeader("CamelCyberArkVaultSecretValue", constant("myNewPassword"))
    .setHeader("CamelCyberArkVaultSecretId", constant("db/password"))
    .to("cyberark-vault:secret?operation=createSecret&url=https://conjur.example.com&account=myaccount&username=admin&apiKey=3ahx8dy3...")
    .log("Secret created/updated");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:start"/>
  <setHeader name="CamelCyberArkVaultSecretValue">
    <constant>myNewPassword</constant>
  </setHeader>
  <setHeader name="CamelCyberArkVaultSecretId">
    <constant>db/password</constant>
  </setHeader>
  <to uri="cyberark-vault:secret?operation=createSecret&amp;url=https://conjur.example.com&amp;account=myaccount&amp;username=admin&amp;apiKey=3ahx8dy3..."/>
  <log message="Secret created/updated"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
      steps:
        - setHeader:
            name: CamelCyberArkVaultSecretValue
            constant: myNewPassword
        - setHeader:
            name: CamelCyberArkVaultSecretId
            constant: db/password
        - to:
            uri: cyberark-vault:secret
            parameters:
              operation: createSecret
              url: "https://conjur.example.com"
              account: myaccount
              username: admin
              apiKey: "3ahx8dy3..."
        - log:
            message: "Secret created/updated"
----
====

Dynamic secret creation:

[tabs]
====
Java::
+
[source,java]
----
from("direct:start")
    .setBody(simple("${header.newSecretValue}"))
    .setHeader("CamelCyberArkVaultSecretId", simple("${header.secretPath}"))
    .to("cyberark-vault:secret?operation=createSecret&url=https://conjur.example.com&account=myaccount&username=admin&apiKey=3ahx8dy3...")
    .log("Secret ${header.secretPath} created/updated");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:start"/>
  <setBody>
    <simple>${header.newSecretValue}</simple>
  </setBody>
  <setHeader name="CamelCyberArkVaultSecretId">
    <simple>${header.secretPath}</simple>
  </setHeader>
  <to uri="cyberark-vault:secret?operation=createSecret&amp;url=https://conjur.example.com&amp;account=myaccount&amp;username=admin&amp;apiKey=3ahx8dy3..."/>
  <log message="Secret ${header.secretPath} created/updated"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:start
      steps:
        - setBody:
            simple: "${header.newSecretValue}"
        - setHeader:
            name: CamelCyberArkVaultSecretId
            simple: "${header.secretPath}"
        - to:
            uri: cyberark-vault:secret
            parameters:
              operation: createSecret
              url: "https://conjur.example.com"
              account: myaccount
              username: admin
              apiKey: "3ahx8dy3..."
        - log:
            message: "Secret ${header.secretPath} created/updated"
----
====

=== SSL Certificate Verification

By default, SSL certificate verification is enabled. You can disable it for testing purposes (not recommended for production):

[source,properties]
----
camel.vault.cyberark.verifySsl=false
----

Or provide a custom certificate path:

[source,properties]
----
camel.vault.cyberark.certificatePath=/path/to/cert.pem
----

=== Setting Up CyberArk Conjur for Testing

Before you can use the component or run integration tests, you need to set up a CyberArk Conjur instance and configure policies to define which secrets (variables) are available.

==== Step 1: Start Conjur with Docker

The easiest way to get started is using the official https://github.com/cyberark/conjur-quickstart[Conjur Quickstart]:

[source,bash]
----
# Clone the quickstart repository
git clone https://github.com/cyberark/conjur-quickstart.git
cd conjur-quickstart

# Start Conjur and database
docker-compose up -d

# Wait for services to be ready
sleep 15

# The admin API key will be displayed in the logs
docker-compose logs conjur_server | grep "admin API key"
----

Default connection details:
- **URL**: `http://localhost:8080`
- **Account**: `myConjurAccount`
- **Username**: `admin`
- **API Key**: Check the container logs (see command above)

==== Step 2: Load Conjur Policy

CyberArk Conjur requires you to define variables in a **policy file** before you can set their values. Here's how to create and load a policy:

**Automated Script:**

You can also use this automated script to load the policy:

[source,bash]
----
#!/bin/bash

# Replace with your actual API key from the Conjur logs
API_KEY="your-api-key-here"

# Create policy file
cat > test-secrets.yaml <<'EOF'
- !variable database
- !variable simple-secret
- !variable app/config
- !variable test/secret
- !variable production/database
- !variable api/credentials
- !variable db/primary
- !variable db/replica
- !variable cache/redis
EOF

# Copy to client container
echo "Copying policy to conjur_client..."
docker cp test-secrets.yaml conjur_client:/tmp/test-secrets.yaml

# Initialize Conjur CLI
echo "Initializing Conjur CLI..."
docker exec conjur_client conjur init -u http://conjur_server -a myConjurAccount --force

# Login
echo "Logging in..."
echo "$API_KEY" | docker exec -i conjur_client conjur login -i admin

# Load policy
echo "Loading policy..."
docker exec conjur_client conjur policy load -b root -f /tmp/test-secrets.yaml

if [ $? -eq 0 ]; then
    echo "✅ Policy loaded successfully!"
else
    echo "❌ Policy load failed"
    exit 1
fi

# Clean up
rm test-secrets.yaml
----

Save as `load-policy.sh`, make it executable (`chmod +x load-policy.sh`), update the API_KEY, and run it.

=== Running Integration Tests

The component includes integration tests that require a running CyberArk Conjur instance. The tests are **disabled by default** and only run when specific system properties are provided.

==== Prerequisites

1. A running CyberArk Conjur instance (see "Setting Up CyberArk Conjur for Testing" above)
2. Conjur policies loaded with the required variables (see Step 2 above)
3. Valid Conjur credentials (URL, account, username, API key)

==== Required System Properties

The integration tests require these system properties:

- `camel.cyberark.url` - CyberArk Conjur URL (e.g., `http://localhost:8080`)
- `camel.cyberark.account` - Conjur account name (e.g., `myConjurAccount`)
- `camel.cyberark.username` - Admin username (e.g., `admin`)
- `camel.cyberark.apiKey` - Admin API key

==== Running All Integration Tests

[source,bash]
----
cd components/camel-cyberark-vault

mvn clean verify \
  -Dcamel.cyberark.url=http://localhost:8080 \
  -Dcamel.cyberark.account=myConjurAccount \
  -Dcamel.cyberark.username=admin \
  -Dcamel.cyberark.apiKey=YOUR_API_KEY_HERE
----

Replace `YOUR_API_KEY_HERE` with the actual API key from your Conjur instance.

==== Running Specific Test Classes

[source,bash]
----
# Run properties function tests
mvn clean verify -Dit.test=CyberArkVaultPropertiesSourceIT \
  -Dcamel.cyberark.url=http://localhost:8080 \
  -Dcamel.cyberark.account=myConjurAccount \
  -Dcamel.cyberark.username=admin \
  -Dcamel.cyberark.apiKey=YOUR_API_KEY_HERE

# Run producer endpoint tests
mvn clean verify -Dit.test=CyberArkVaultProducerIT \
  -Dcamel.cyberark.url=http://localhost:8080 \
  -Dcamel.cyberark.account=myConjurAccount \
  -Dcamel.cyberark.username=admin \
  -Dcamel.cyberark.apiKey=YOUR_API_KEY_HERE
----
