= PubNub Component
:doctitle: PubNub
:shortname: pubnub
:artifactid: camel-pubnub
:description: Send and receive messages to/from PubNub data stream network for connected devices.
:since: 2.19
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:camel-spring-boot-name: pubnub

*Since Camel {since}*

*{component-header}*

Camel PubNub component can be used to communicate with the https://www.pubnub.com/[PubNub] data stream network for connected devices.
This component uses pubnub https://github.com/pubnub/java[java library].

Use cases include:

** Chat rooms: Sending and receiving messages
** Locations and Connected cars: dispatching taxi cabs
** Smart sensors: Receiving data from a sensor for data visualizations
** Health: Monitoring heart rate from a patient's wearable device
** Multiplayer games
** Interactive media: audience-participating voting system

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-pubnub</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

== URI format

------------------------
pubnub:channel[?options]
------------------------

Where *channel* is the PubNub channel to publish or subscribe to.

// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END
// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

== Message body

The message body can contain any JSON serializable data, including Objects, Arrays, Integers, and Strings.
Message data should not contain special Java V4 classes or functions as these will not serialize.
String content can include any single-byte or multibyte UTF-8.

Object serialization when sending is done automatically.
Pass the full object as the message payload.
PubNub will take care of object serialization.

When receiving the message body uses objects provided by the PubNub API.

== Examples

=== Publishing events

Default operation when producing.
The following snippet publishes the event generated by PojoBean to the channel iot.

[source,java]
----
from("timer:mytimer")
    // generate some data as POJO.
    .bean(PojoBean.class)
    .to("pubnub:iot?publishKey=mypublishKey");
----

=== Fire events aka BLOCKS Event Handlers

See https://www.pubnub.com/blocks-catalog/[blocks catalog] for all kinds of serverless functions that can be invoked.
Example of geolocation lookup 

[source,java]
----
from("timer:geotimer")
    .process(exchange -> exchange.getIn().setBody(new Foo("bar", "TEXT")))
    .to("pubnub:eon-maps-geolocation-input?operation=fire&publishKey=mypubkey&subscribeKey=mysubkey");

from("pubnub:eon-map-geolocation-output?subscribeKey=mysubkey)
    // geolocation output will be logged here
    .log("${body}");
----

=== Subscribing to events

The following snippet listens for events on the iot channel.
If you can add the option withPresence, you will also receive channel Join, Leave asf events.

[source,java]
----
from("pubnub:iot?subscribeKey=mySubscribeKey")
    .log("${body}")
    .to("mock:result");
----

=== Performing operations


- `herenow`: obtain information about the current state of a channel including a list of unique user-ids currently subscribed to the channel and the total occupancy count of the channel:

[source,java]
----
from("direct:control")
    .to("pubnub:myChannel?publishKey=mypublishKey&subscribeKey=mySubscribeKey&operation=herenow")
    .to("mock:result");
----

- `wherenow`: obtain information about the current list of channels to which a uuid is subscribed:

[source,java]
----
from("direct:control")
    .to("pubnub:myChannel?publishKey=mypublishKey&subscribeKey=mySubscribeKey&operation=wherenow&uuid=spyonme")
    .to("mock:result");
----

- `setstate`: used to set key/value pairs specific to a subscriber uuid:

[source,java]
----
from("direct:control")
    .bean(StateGenerator.class)
    .to("pubnub:myChannel?publishKey=mypublishKey&subscribeKey=mySubscribeKey&operation=setstate&uuid=myuuid");
----

- `gethistory`: Fetches historical messages of a channel:

[source,java]
----
from("direct:control")
    .to("pubnub:myChannel?publishKey=mypublishKey&subscribeKey=mySubscribeKey&operation=gethistory");
----

There are a couple of examples in the test directory that show some of the PubNub features.
They require a PubNub account, from where you can obtain a publish- and subscribe key.
 
The example PubNubSensorExample already contains a subscribe key provided by PubNub, so this is ready to run without an account.
The example illustrates the PubNub component subscribing to an infinite stream of sensor data.



include::spring-boot:partial$starter.adoc[]
