= OPC UA Client Component
:doctitle: OPC UA Client
:shortname: milo-client
:artifactid: camel-milo
:description: Connect to OPC UA servers using the binary protocol for acquiring telemetry data.
:since: 2.19
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:camel-spring-boot-name: milo

*Since Camel {since}*

*{component-header}*

The Milo Client component provides access to OPC UA servers using the
http://eclipse.org/milo[Eclipse Milo™] implementation.

*Java 11+*: This component requires Java 11+ at runtime.

NOTE: This component uses Eclipse Milo 1.0.5. When migrating from earlier versions,
be aware that the Milo API has undergone significant changes in the 1.0.x series.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-milo</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------


== URI format

The URI syntax of the endpoint is:

------------------------
milo-client:opc.tcp://[user:password@]host:port/path/to/service?node=RAW(nsu=urn:foo:bar;s=item-1)
------------------------

If the server does not use a path, then it is possible to simply omit it:

------------------------
milo-client:opc.tcp://[user:password@]host:port?node=RAW(nsu=urn:foo:bar;s=item-1)
------------------------

If no user credentials are provided the client will switch to anonymous mode.

All configuration options in the group +client+ are applicable to the shared client instance. Endpoints
will share client instances for each endpoint URI. So the first time a request for that endpoint URI is
made, the options of the +client+ group are applied. All further instances will be ignored.

If you need alternate options for the same endpoint URI it is possible though to set the +clientId+ option
which will by added internally to the endpoint URI in order to select a different shared connection instance.
In other words, shared connections located by the combination of endpoint URI and client id.


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END
// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

=== Discovery

If the server uses a dedicated discovery endpoint (e.g. `/discovery`), which may support different (less secure) security policies,
then you can make use of this via the parameter `discoveryEndpointSuffix`, which will be appended to the `endpointUri`. Or by using
an explicit `discoveryEndpointUri`.

=== Overriding the host name

The client uses the host information from the endpoint information, queried from the server. However in some situations this endpoint URI
might be different, and wrong from the point of view of the connecting client (e.g. an internal hostname).

In this case it is possible to set the parameter `overrideHost` to `true`, which will take the discovered endpoint information,
but override the host information with the value of the original URI.

[[nodeid]]
=== Node ID

In order to define a target node a namespace and node id is required. In previous versions this was possible by
specifying `nodeId` and either `namespaceUri` or `namespaceIndex`. However this only allowed for using
string based node IDs. And while this configuration is still possible, the newer one is preferred.

The new approach is to specify a full namespace+node ID in the format `ns=1;i=1` which also allows to use the other
node ID formats (like numeric, GUID/UUID or opaque). If the `node` parameter is used the older ones must not be used.
The syntax of this node format is a set of `key=value` pairs delimited by a semi-colon (`;`). 

Exactly one namespace and one node id key must be used. See the following table for possible keys:

[width="100%",cols="2,2,5",options="header"]
|===
| Key | Type | Description
| *ns*  | namespace | Numeric namespace index
| *nsu* | namespace | Namespace URI
| *s*   | node | String node ID
| *i*   | node | Numeric node ID
| *g*   | node | GUID/UUID node ID
| *b*   | node | Base64 encoded string for opaque node ID
|===

As the values generated by the syntax cannot be transparently encoded into a URI parameter value, it is necessary to escape them.
However Camel allows to wrap the actual value inside `RAW(…)`, which makes escaping unnecessary. For example:

------------------------
milo-client:opc.tcp://user:password@localhost:12345?node=RAW(nsu=http://foo.bar;s=foo/bar)
------------------------

=== Method ID

It is possible to perform methods calls on OPC UA nodes. If the parameter `method` is set to the Node ID of a method call (the node ID must be set to the parent object in this case),
then a method call will be performed instead of a write operation.

Input parameters are taken from the body:

* If the body is null, then an empty `Variant[]` will be used
* If the body is a `Variant[]`, then it will be used as is
* If the body is a `Variant`, then it will be wrapped in a `Variant[]` array
* Otherwise the body will be converted into a `Variant` and wrapped in an array of `Variant[]`

=== Read Values from Nodes

The component provide a producer to read values from multiple opc-ua nodes. The Node-IDs will be defined in the header `CamelMiloNodeIds` as list of strings. (see <<nodeid, Node-ID>> for the ID format).

Example:

[source,java]
----
from("direct:start")
    .setHeader("CamelMiloNodeIds", constant(Arrays.asList("nsu=urn:org:apache:camel;s=myitem1")))
    .setHeader("await", constant(true)) // await: parameter "defaultAwaitWrites"
        .enrich("milo-client:opc.tcp://localhost:4334", new AggregationStrategy() {

            @Override
            public Exchange aggregate(Exchange oldExchange, Exchange newExchange) {
                return newExchange;
            }
        }).to("mock:test1");
----

=== Security policies

When setting the allowing security policies is it possible to use the well known OPC UA URIs (e.g. `\http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15`)
or to use the Milo enum literals (e.g. `None`). Specifying an unknown security policy URI or enum is an error.

The known security policy URIs and enum literals are can be seen here: https://github.com/eclipse/milo/blob/master/opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/security/SecurityPolicy.java[SecurityPolicy.java]

NOTE: In any case security policies are considered case sensitive.

==== Milo 1.0.5 Migration Notes

With Milo 1.0.5, several security-related API changes were introduced:

* The `ServerCertificateValidator` class has been replaced with `CertificateValidator` in the core security package
* Certificate validation now uses `org.eclipse.milo.opcua.stack.core.security.CertificateValidator`
* When configuring custom certificate validators, ensure you're using the updated API


include::spring-boot:partial$starter.adoc[]
