AcceptAllHeaderFilterStrategy
CaffeineAggregationRepository
CaffeineIdempotentRepository
CaffeineKeyValueRepository
CassandraAggregationRepository
CassandraIdempotentRepository
CassandraKeyValueRepository
ConsulClusterService
CronScheduledRoutePolicy
DefaultHeaderFilterStrategy
DurationRoutePolicy
DurationRoutePolicyFactory
EhcacheAggregationRepository
EhcacheIdempotentRepository
EhcacheKeyValueRepository
ElasticsearchBulkRequestAggregationStrategy
FileIdempotentRepository
FileLockClusterService
GroupedBodyAggregationStrategy
GroupedExchangeAggregationStrategy
GroupedMessageAggregationStrategy
HazelcastAggregationRepository
HazelcastIdempotentRepository
HazelcastKeyValueRepository
InfinispanEmbeddedAggregationRepository
InfinispanEmbeddedClusterService
InfinispanEmbeddedIdempotentRepository
InfinispanRemoteAggregationRepository
InfinispanRemoteClusterService
InfinispanRemoteIdempotentRepository
InfinispanRemoteKeyValueRepository
JCacheAggregationRepository
JCacheIdempotentRepository
JCacheKeyValueRepository
JGroupsRaftClusterService
JdbcAggregationRepository
JdbcKeyValueRepository
JdbcMessageIdRepository
JpaKeyValueRepository
KafkaIdempotentRepository
KafkaKeyValueRepository
KeyValueAggregationRepository
KeyValueIdempotentRepository
KubernetesClusterService
LoggingHttpActivityListener
MemoryAggregationRepository
MemoryIdempotentRepository
MemoryKeyValueRepository
MongoDbIdempotentRepository
OpensearchBulkRequestAggregationStrategy
RedisAggregationRepository
RedisKeyValueRepository
SimpleScheduledRoutePolicy
SpringCacheIdempotentRepository
SpringRedisIdempotentRepository
StringAggregationStrategy
TarAggregationStrategy
ThrottlingExceptionRoutePolicy
ThrottlingInflightRoutePolicy
UseLatestAggregationStrategy
UseOriginalAggregationStrategy
XsltAggregationStrategy
XsltSaxonAggregationStrategy
ZipAggregationStrategy
ZooKeeperClusterService
