AcceptAllHeaderFilterStrategy
CaffeineAggregationRepository
CaffeineIdempotentRepository
CassandraAggregationRepository
CassandraIdempotentRepository
ConsulClusterService
CronScheduledRoutePolicy
DefaultHeaderFilterStrategy
DurationRoutePolicy
DurationRoutePolicyFactory
EhcacheAggregationRepository
EhcacheIdempotentRepository
ElasticsearchBulkRequestAggregationStrategy
FileIdempotentRepository
FileLockClusterService
GroupedBodyAggregationStrategy
GroupedExchangeAggregationStrategy
GroupedMessageAggregationStrategy
HazelcastAggregationRepository
HazelcastIdempotentRepository
InfinispanEmbeddedAggregationRepository
InfinispanEmbeddedClusterService
InfinispanEmbeddedIdempotentRepository
InfinispanRemoteAggregationRepository
InfinispanRemoteClusterService
InfinispanRemoteIdempotentRepository
JCacheAggregationRepository
JCacheIdempotentRepository
JGroupsRaftClusterService
JdbcAggregationRepository
JdbcMessageIdRepository
KafkaIdempotentRepository
KeyValueAggregationRepository
KeyValueIdempotentRepository
KubernetesClusterService
LoggingHttpActivityListener
MemoryAggregationRepository
MemoryIdempotentRepository
MemoryKeyValueRepository
MongoDbIdempotentRepository
OpensearchBulkRequestAggregationStrategy
RedisAggregationRepository
SimpleScheduledRoutePolicy
SpringCacheIdempotentRepository
SpringRedisIdempotentRepository
StringAggregationStrategy
TarAggregationStrategy
ThrottlingExceptionRoutePolicy
ThrottlingInflightRoutePolicy
UseLatestAggregationStrategy
UseOriginalAggregationStrategy
XsltAggregationStrategy
XsltSaxonAggregationStrategy
ZipAggregationStrategy
ZooKeeperClusterService
