= JCR Component
:doctitle: JCR
:shortname: jcr
:artifactid: camel-jcr
:description: Read and write nodes to/from a JCR compliant content repository.
:since: 1.3
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:camel-spring-boot-name: jcr

*Since Camel {since}*

*{component-header}*

The JCR component allows you to add/read nodes to/from a JCR
compliant content repository, for example,
http://jackrabbit.apache.org/[Apache Jackrabbit], with its producer, or
register an EventListener with the consumer.

You can use consumer as an EventListener in
JCR or a producer to read a node by identifier.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-jcr</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

== URI format

-------------------------------------------
jcr://user:password@repository/path/to/node
-------------------------------------------

The `repository` element of the URI is used to look up the JCR
`Repository` object in the Camel context registry.


// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
include::partial$component-endpoint-headers.adoc[]
// component options: END

== Example

The snippet below creates a node named `node` under the `/home/test`
node in the content repository. One additional property is added to the
node as well: `my.contents.property` which will contain the body of the
message being sent.

[tabs]
====
Java::
+
[source,java]
----
from("direct:a").setHeader("CamelJcrNodeName", constant("node"))
    .setHeader("my.contents.property", body())
    .to("jcr://user:pass@repository/home/test");
----

XML::
+
[source,xml]
----
<route>
    <from uri="direct:a"/>
    <setHeader name="CamelJcrNodeName">
        <constant>node</constant>
    </setHeader>
    <setHeader name="my.contents.property">
        <simple>${body}</simple>
    </setHeader>
    <to uri="jcr://user:pass@repository/home/test"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:a
      steps:
        - setHeader:
            name: CamelJcrNodeName
            expression:
              constant:
                expression: node
        - setHeader:
            name: my.contents.property
            expression:
              simple:
                expression: "${body}"
        - to:
            uri: jcr://user:pass@repository/home/test
----
====

The following code will register an EventListener under the path
import-application/inbox for `Event.NODE_ADDED` and `Event.NODE_REMOVED`
events (event types 1 and 2, both masked as 3) and listening deep for
all the children.

[tabs]
====
Java::
+
[source,java]
----
from("jcr://user:pass@repository/import-application/inbox?eventTypes=3&deep=true")
    .to("direct:execute-import-application");
----

XML::
+
[source,xml]
----
<route>
    <from uri="jcr://user:pass@repository/import-application/inbox?eventTypes=3&amp;deep=true"/>
    <to uri="direct:execute-import-application"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: jcr://user:pass@repository/import-application/inbox
      parameters:
        eventTypes: 3
        deep: true
      steps:
        - to:
            uri: direct:execute-import-application
----
====



include::spring-boot:partial$starter.adoc[]
