== Constant Language

*Available as of Camel version 1.5*

The Constant Expression Language is really just a way to specify
constant strings as a type of expression.

=== Constant Options


// language options: START
The Constant language supports 1 options which are listed below.



[width="100%",cols="2,1m,1m,6",options="header"]
|===
| Name | Default | Java Type | Description
| trim | true | Boolean | Whether to trim the value to remove leading and trailing whitespaces and line breaks
|===
// language options: END


=== Example usage

The setHeader element of the Spring DSL can utilize a constant
expression like:

[source,xml]
----
<route>
  <from uri="seda:a"/>
  <setHeader headerName="theHeader">
    <constant>the value</constant>        
  </setHeader>
  <to uri="mock:b"/>     
</route>
----

in this case, the link:message.html[Message] coming from the seda:a
link:endpoint.html[Endpoint] will have 'theHeader' header set to the
constant value 'the value'.

And the same example using Java DSL:

[source,java]
----
from("seda:a").setHeader("theHeader", constant("the value")).to("mock:b");
----

=== Dependencies

The Constant language is part of *camel-core*.
