## Log Component

*Available as of Camel version 1.1*

The *log:* component logs message exchanges to the underlying logging
mechanism.

Camel uses http://www.slf4j.org/[sfl4j] which allows you to configure
logging via, among others:

* http://logging.apache.org/log4j/[Log4j]
* http://logback.qos.ch/[Logback]
*
http://java.sun.com/j2se/1.4.2/docs/api/java/util/logging/package-summary.html[JDK
Util Logging logging]

### URI format

[source,java]
-----------------------------
log:loggingCategory[?options]
-----------------------------

Where *loggingCategory* is the name of the logging category to use. You
can append query options to the URI in the following format,
`?option=value&option=value&...`

INFO:*Using Logger instance from the the Registry*
As of *Camel 2.12.4/2.13.1*, if there's single instance
of `org.slf4j.Logger` found in the Registry, the *loggingCategory* is no
longer used to create logger instance. The registered instance is used
instead. Also it is possible to reference particular `Logger` instance
using `?logger=#myLogger` URI parameter. Eventually, if there's no
registered and URI `logger` parameter, the logger instance is created
using *loggingCategory*.

For example, a log endpoint typically specifies the logging level using
the `level` option, as follows:

[source,java]
----------------------------------------
log:org.apache.camel.example?level=DEBUG
----------------------------------------

The default logger logs every exchange (_regular logging_). But Camel
also ships with the `Throughput` logger, which is used whenever the
`groupSize` option is specified.

TIP:*Also a log in the DSL*
There is also a `log` directly in the DSL, but it has a different
purpose. Its meant for lightweight and human logs. See more details at
link:logeip.html[LogEIP].

### Options



// component options: START
The Log component supports 1 options which are listed below.



{% raw %}
[width="100%",cols="2,1,1m,1m,5",options="header"]
|=======================================================================
| Name | Group | Default | Java Type | Description
| exchangeFormatter | advanced |  | ExchangeFormatter | Sets a custom ExchangeFormatter to convert the Exchange to a String suitable for logging. If not specified we default to DefaultExchangeFormatter.
|=======================================================================
{% endraw %}
// component options: END




// endpoint options: START
The Log component supports 26 endpoint options which are listed below:

{% raw %}
[width="100%",cols="2,1,1m,1m,5",options="header"]
|=======================================================================
| Name | Group | Default | Java Type | Description
| loggerName | producer |  | String | *Required* The logger name to use
| groupActiveOnly | producer | true | Boolean | If true will hide stats when no new messages have been received for a time interval if false show stats regardless of message traffic.
| groupDelay | producer |  | Long | Set the initial delay for stats (in millis)
| groupInterval | producer |  | Long | If specified will group message stats by this time interval (in millis)
| groupSize | producer |  | Integer | An integer that specifies a group size for throughput logging.
| level | producer | INFO | String | Logging level to use. The default value is INFO.
| marker | producer |  | String | An optional Marker name to use.
| synchronous | advanced | false | boolean | Sets whether synchronous processing should be strictly used or Camel is allowed to use asynchronous processing (if supported).
| maxChars | formatting | 10000 | int | Limits the number of characters logged per line.
| multiline | formatting | false | boolean | If enabled then each information is outputted on a newline.
| showAll | formatting | false | boolean | Quick option for turning all options on. (multiline maxChars has to be manually set if to be used)
| showBody | formatting | true | boolean | Show the message body.
| showBodyType | formatting | true | boolean | Show the body Java type.
| showCaughtException | formatting | false | boolean | f the exchange has a caught exception show the exception message (no stack trace). A caught exception is stored as a property on the exchange (using the key link org.apache.camel.ExchangeEXCEPTION_CAUGHT and for instance a doCatch can catch exceptions.
| showException | formatting | false | boolean | If the exchange has an exception show the exception message (no stacktrace)
| showExchangeId | formatting | false | boolean | Show the unique exchange ID.
| showExchangePattern | formatting | true | boolean | Shows the Message Exchange Pattern (or MEP for short).
| showFiles | formatting | false | boolean | If enabled Camel will output files
| showFuture | formatting | false | boolean | If enabled Camel will on Future objects wait for it to complete to obtain the payload to be logged.
| showHeaders | formatting | false | boolean | Show the message headers.
| showOut | formatting | false | boolean | If the exchange has an out message show the out message.
| showProperties | formatting | false | boolean | Show the exchange properties.
| showStackTrace | formatting | false | boolean | Show the stack trace if an exchange has an exception. Only effective if one of showAll showException or showCaughtException are enabled.
| showStreams | formatting | false | boolean | Whether Camel should show stream bodies or not (eg such as java.io.InputStream). Beware if you enable this option then you may not be able later to access the message body as the stream have already been read by this logger. To remedy this you will have to use Stream Caching.
| skipBodyLineSeparator | formatting | true | boolean | Whether to skip line separators when logging the message body. This allows to log the message body in one line setting this option to false will preserve any line separators from the body which then will log the body as is.
| style | formatting | Default | OutputStyle | Sets the outputs style to use.
|=======================================================================
{% endraw %}
// endpoint options: END


### Regular logger sample

In the route below we log the incoming orders at `DEBUG` level before
the order is processed:

[source,java]
------------------------------------------------------------------------------------------
from("activemq:orders").to("log:com.mycompany.order?level=DEBUG").to("bean:processOrder");
------------------------------------------------------------------------------------------

Or using Spring XML to define the route:

[source,xml]
---------------------------------------------------
  <route>
    <from uri="activemq:orders"/>
    <to uri="log:com.mycompany.order?level=DEBUG"/>
    <to uri="bean:processOrder"/>
  </route> 
---------------------------------------------------

### Regular logger with formatter sample

In the route below we log the incoming orders at `INFO` level before the
order is processed.

[source,java]
--------------------------------------------------------------------------------------
from("activemq:orders").
    to("log:com.mycompany.order?showAll=true&multiline=true").to("bean:processOrder");
--------------------------------------------------------------------------------------

### Throughput logger with groupSize sample

In the route below we log the throughput of the incoming orders at
`DEBUG` level grouped by 10 messages.

[source,java]
-----------------------------------------------------------------------------------
from("activemq:orders").
    to("log:com.mycompany.order?level=DEBUG&groupSize=10").to("bean:processOrder");
-----------------------------------------------------------------------------------

### Throughput logger with groupInterval sample

This route will result in message stats logged every 10s, with an
initial 60s delay and stats should be displayed even if there isn't any
message traffic.

[source,java]
-----------------------------------------------------------------------------------------------------------------------------
from("activemq:orders").
to("log:com.mycompany.order?level=DEBUG&groupInterval=10000&groupDelay=60000&groupActiveOnly=false").to("bean:processOrder");
-----------------------------------------------------------------------------------------------------------------------------

The following will be logged:

[source,java]
------------------------------------------------------------------------------------------------------------------------------------
"Received: 1000 new messages, with total 2000 so far. Last group took: 10000 millis which is: 100 messages per second. average: 100"
------------------------------------------------------------------------------------------------------------------------------------

### Full customization of the logging output

*Available as of Camel 2.11*

With the options outlined in the link:log.html[#Formatting] section, you
can control much of the output of the logger. However, log lines will
always follow this structure:

[source,java]
--------------------------------------------------------------------------------------------------------------
Exchange[Id:ID-machine-local-50656-1234567901234-1-2, ExchangePattern:InOut, 
Properties:{CamelToEndpoint=log://org.apache.camel.component.log.TEST?showAll=true, 
CamelCreatedTimestamp=Thu Mar 28 00:00:00 WET 2013}, 
Headers:{breadcrumbId=ID-machine-local-50656-1234567901234-1-1}, BodyType:String, Body:Hello World, Out: null]
--------------------------------------------------------------------------------------------------------------

This format is unsuitable in some cases, perhaps because you need to...

* ... filter the headers and properties that are printed, to strike a
balance between insight and verbosity.
* ... adjust the log message to whatever you deem most readable.
* ... tailor log messages for digestion by log mining systems, e.g.
Splunk.
* ... print specific body types differently.
* ... etc.

Whenever you require absolute customization, you can create a class that
implements the
http://camel.apache.org/maven/current/camel-core/apidocs/org/apache/camel/spi/ExchangeFormatter.html[`ExchangeFormatter`]
interface. Within the `format(Exchange)` method you have access to the
full Exchange, so you can select and extract the precise information you
need, format it in a custom manner and return it. The return value will
become the final log message.

You can have the Log component pick up your custom `ExchangeFormatter`
in either of two ways:

*Explicitly instantiating the LogComponent in your Registry:*

[source,java]
---------------------------------------------------------------------
<bean name="log" class="org.apache.camel.component.log.LogComponent">
   <property name="exchangeFormatter" ref="myCustomFormatter" />
</bean>
---------------------------------------------------------------------

*Convention over configuration:*

Simply by registering a bean with the name `logFormatter`; the Log
Component is intelligent enough to pick it up automatically.

[source,java]
----------------------------------------------------------------------
<bean name="logFormatter" class="com.xyz.MyCustomExchangeFormatter" />
----------------------------------------------------------------------

NOTE: the `ExchangeFormatter` gets applied to *all Log endpoints within
that Camel Context*. If you need different ExchangeFormatters for
different endpoints, just instantiate the LogComponent as many times as
needed, and use the relevant bean name as the endpoint prefix.

From *Camel 2.11.2/2.12* onwards when using a custom log formatter, you
can specify parameters in the log uri, which gets configured on the
custom log formatter. Though when you do that you should define the
"logFormatter" as prototype scoped so its not shared if you have
different parameters, eg:

[source,java]
---------------------------------------------------------------------------------------
<bean name="logFormatter" class="com.xyz.MyCustomExchangeFormatter" scope="prototype"/>
---------------------------------------------------------------------------------------

And then we can have Camel routes using the log uri with different
options:

[source,java]
---------------------------------------------
<to uri="log:foo?param1=foo&amp;param2=100"/>
...
<to uri="log:bar?param1=bar&amp;param2=200"/>
---------------------------------------------

#### Using Log component in OSGi

*Improvement as of Camel 2.12.4/2.13.1*

When using Log component inside OSGi (e.g., in Karaf), the underlying
logging mechanisms are provided by PAX logging. It searches for a bundle
which invokes `org.slf4j.LoggerFactory.getLogger()` method and
associates the bundle with the logger instance. Without specifying
custom `org.sfl4j.Logger` instance, the logger created by Log component
is associated with `camel-core` bundle.

In some scenarios it is required that the bundle associated with logger
should be the bundle which contains route definition. To do this, either
register single instance of `org.slf4j.Logger` in the Registry or
reference it using `logger` URI parameter.

### See Also

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]

* link:tracer.html[Tracer]
* link:how-do-i-use-log4j.html[How do I use log4j]
* link:how-do-i-use-java-14-logging.html[How do I use Java 1.4 logging]
* link:logeip.html[LogEIP] for using `log` directly in the DSL for human
logs.