== Java Object Serialization DataFormat

*Available as of Camel version 2.12*

Serialization is a link:data-format.html[Data Format] which uses the
standard Java Serialization mechanism to unmarshal a binary payload into
Java objects or to marshal Java objects into a binary blob. +
 For example the following uses Java serialization to unmarshal a binary
file then send it as an ObjectMessage to link:activemq.html[ActiveMQ]

[source,java]
----
from("file://foo/bar").
  unmarshal().serialization().
  to("activemq:Some.Queue");
----

=== Options

// dataformat options: START
The Java Object Serialization dataformat supports 1 options which are listed below.



[width="100%",cols="2s,1m,1m,6",options="header"]
|===
| Name | Default | Java Type | Description
| contentTypeHeader | false | Boolean | Whether the data format should set the Content-Type header with the type from the data format if the data format is capable of doing so. For example application/xml for data formats marshalling to XML or application/json for data formats marshalling to JSon etc.
|===
// dataformat options: END

=== Dependencies

This data format is provided in *camel-core* so no additional
dependencies is needed.
