= Kamelet Main Component
:doctitle: Kamelet Main
:shortname: kamelet-main
:artifactid: camel-kamelet-main
:description: Main to run Kamelet standalone
:since: 3.11
:supportlevel: Preview
:tabs-sync-option:
//Manually maintained attributes
:group: DSL

*Since Camel {since}*

A `main` class that is opinionated to boostrap and run Camel standalone with Kamelets (or plain YAML routes)
for development and demo purposes.

== Initial configuration

The `KameletMain` is pre-configured with the following properties:

[source,properties]
----
camel.component.kamelet.location = classpath:/kamelets,github:apache:camel-kamelets/kamelets
camel.component.rest.consumerComponentName = platform-http
camel.component.rest.producerComponentName = vertx-http
----

These settings can be overridden by configuration in `application.properties`.

== Automatic dependencies downloading

The Kamelet Main can automatically download Kamelet YAML files from a remote location over http/https, and from github as well.

The official Kamelets from the Apache Camel Kamelet Catalog is stored on github and they can be used out of the box as-is.

For example a Camel route can be _coded_ in YAML which uses the Earthquake Kamelet from the catalog, as shown below:

[source,yaml]
----
- route:
    from: "kamelet:earthquake-source"
    steps:
      - unmarshal:
          json: {}
      - log: "Earthquake with magnitude ${body[properties][mag]} at ${body[properties][place]}"
----

In this use-case the earthquake kamelet will be downloaded from github, and as well its required dependencies.

You can find an example with this at
https://github.com/apache/camel-examples/tree/main/examples/kamelet-main[kamelet-main].
