= Hazelcast SEDA Component
:doctitle: Hazelcast SEDA
:shortname: hazelcast-seda
:artifactid: camel-hazelcast
:description: Asynchronously send/receive Exchanges between Camel routes running on potentially distinct JVMs/hosts backed by Hazelcast BlockingQueue.
:since: 2.7
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:group: Hazelcast
:camel-spring-boot-name: hazelcast

*Since Camel {since}*

*{component-header}*

The http://www.hazelcast.com/[Hazelcast] SEDA component is one of Camel Hazelcast Components which allows you to access Hazelcast BlockingQueue.
SEDA component differs from the rest components provided. It implements a work-queue in order to support asynchronous SEDA architectures, similar to the core "SEDA" component.


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END


== SEDA producer – to(“hazelcast-seda:foo”)

The SEDA producer provides no operations. You only send data to the
specified queue.

// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

Java DSL :

[source,java]
--------------------------
from("direct:foo")
.to("hazelcast-seda:foo");
--------------------------

Spring DSL :

[source,xml]
----------------------------------
<route>
   <from uri="direct:start" />
   <to uri="hazelcast-seda:foo" />
</route>
----------------------------------

== SEDA consumer – from(“hazelcast-seda:foo”)

The SEDA consumer provides no operations. You only retrieve data from
the specified queue.

Java DSL :

[source,java]
--------------------------
from("hazelcast-seda:foo")
.to("mock:result");
--------------------------

Spring DSL:

[source,xml]
-----------------------------------
<route>
  <from uri="hazelcast-seda:foo" />
  <to uri="mock:result" />
</route>
-----------------------------------


include::spring-boot:partial$starter.adoc[]
