[[sap-netweaver-component]]
= SAP NetWeaver Component
:docTitle: SAP NetWeaver
:artifactId: camel-sap-netweaver
:description: Send requests to SAP NetWeaver Gateway using HTTP.
:since: 2.12
:supportLevel: Stable
:component-header: Only producer is supported
include::{cq-version}@camel-quarkus:ROOT:partial$reference/components/sap-netweaver.adoc[opts=optional]

*Since Camel {since}*

*{component-header}*

The SAP Netweaver integrates with the
http://scn.sap.com/community/developer-center/netweaver-gateway[SAP
NetWeaver Gateway] using HTTP transports.

This camel component supports only producer endpoints.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-sap-netweaver</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

== URI format

The URI scheme for a sap netweaver gateway component is as follows

-----------------------------------------------------------------
sap-netweaver:https://host:8080/path?username=foo&password=secret
-----------------------------------------------------------------

== Prerequisites

You would need to have an account to the SAP NetWeaver system to be able
to leverage this component. SAP provides a
http://scn.sap.com/docs/DOC-31221#section6[demo setup] where you can
requires for an account.

This component uses the basic authentication scheme for logging into SAP
NetWeaver.

// component-configure options: START
== Configuring Options

Camel components are configured on two separate levels:

- component level
- endpoint level

=== Configuring Component Options

The component level is the highest level which holds general and common configurations that are inherited by the endpoints.
For example a component may have security settings, credentials for authentication, urls for network connection and so forth.

Some components only have a few options, and others may have many. Because components typically have pre configured defaults
that are commonly used, then you may often only need to configure a few options on a component; or none at all.

Configuring components can be done with the xref:latest@manual::component-dsl.adoc[Component DSL],
in a configuration file (application.properties|yaml), or directly with Java code.

=== Configuring Endpoint Options

Where you find yourself configuring the most is on endpoints, as endpoints often have many options, which allows you to
configure what you need the endpoint to do. The options are also categorized into whether the endpoint is used as consumer (from)
or as a producer (to), or used for both.

Configuring endpoints is most often done directly in the endpoint URI as path and query parameters. You can also use
the xref:latest@manual::Endpoint-dsl.adoc[Endpoint DSL] as a _type safe_ way of configuring endpoints.

A good practice when configuring options is to use xref:latest@manual::using-propertyplaceholder.adoc[Property Placeholders],
which allows to not hardcode urls, port numbers, sensitive information, and other settings.
In other words placeholders allows to externalize the configuration from your code, and gives more flexibility and reuse.

The following two sections lists all the options, firstly for the component followed by the endpoint.
// component-configure options: END
// component options: START
== Component Options


The SAP NetWeaver component supports 2 options, which are listed below.



[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *lazyStartProducer* (producer) | Whether the producer should be started lazy (on the first message). By starting lazy you can use this to allow CamelContext and routes to startup in situations where a producer may otherwise fail during starting and cause the route to fail being started. By deferring this startup to be lazy then the startup failure can be handled during routing messages via Camel's routing error handlers. Beware that when the first message is processed then creating and starting the producer may take a little time and prolong the total processing time of the processing. | false | boolean
| *autowiredEnabled* (advanced) | Whether autowiring is enabled. This is used for automatic autowiring options (the option must be marked as autowired) by looking up in the registry to find if there is a single instance of matching type, which then gets configured on the component. This can be used for automatic configuring JDBC data sources, JMS connection factories, AWS Clients, etc. | true | boolean
|===
// component options: END
// endpoint options: START
== Endpoint Options

The SAP NetWeaver endpoint is configured using URI syntax:

----
sap-netweaver:url
----

with the following path and query parameters:

=== Path Parameters (1 parameters):


[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *url* | *Required* Url to the SAP net-weaver gateway server. |  | String
|===


=== Query Parameters (6 parameters):


[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *flatternMap* (producer) | If the JSON Map contains only a single entry, then flattern by storing that single entry value as the message body. | true | boolean
| *json* (producer) | Whether to return data in JSON format. If this option is false, then XML is returned in Atom format. | true | boolean
| *jsonAsMap* (producer) | To transform the JSON from a String to a Map in the message body. | true | boolean
| *lazyStartProducer* (producer) | Whether the producer should be started lazy (on the first message). By starting lazy you can use this to allow CamelContext and routes to startup in situations where a producer may otherwise fail during starting and cause the route to fail being started. By deferring this startup to be lazy then the startup failure can be handled during routing messages via Camel's routing error handlers. Beware that when the first message is processed then creating and starting the producer may take a little time and prolong the total processing time of the processing. | false | boolean
| *password* (producer) | *Required* Password for account. |  | String
| *username* (producer) | *Required* Username for account. |  | String
|===
// endpoint options: END


== Message Headers

The following headers can be used by the producer.

[width="100%",cols="10%,10%,80%",options="header",]
|=======================================================================
|Name |Type |Description

|`CamelNetWeaverCommand` |`String` |*Mandatory*: The command to execute in
http://msdn.microsoft.com/en-us/library/cc956153.aspx[MS ADO.Net Data
Service] format.
|=======================================================================

== Examples

This example is using the flight demo example from SAP, which is
available online over the internet
http://scn.sap.com/docs/DOC-31221[here].

In the route below we request the SAP NetWeaver demo server using the
following url

----------------------------------------------------------------------
https://sapes1.sapdevcenter.com/sap/opu/odata/IWBEP/RMTSAMPLEFLIGHT_2/
----------------------------------------------------------------------

And we want to execute the following command

[source,java]
-------------------------------------------------------------------------------------------------------
FlightCollection(AirLineID='AA',FlightConnectionID='0017',FlightDate=datetime'2012-08-29T00%3A00%3A00')
-------------------------------------------------------------------------------------------------------

To get flight details for the given flight. The command syntax is in
http://msdn.microsoft.com/en-us/library/cc956153.aspx[MS ADO.Net Data
Service] format.

We have the following Camel route

[source,java]
-----------------------------------------------------------------------------
from("direct:start")
    .setHeader(NetWeaverConstants.COMMAND, constant(command))
    .toF("sap-netweaver:%s?username=%s&password=%s", url, username, password)
    .to("log:response")
    .to("velocity:flight-info.vm")
-----------------------------------------------------------------------------

Where url, username, password and command is defined as:

[source,java]
---------------------------------------------------------------------------------------------------------------------------------------
    private String username = "P1909969254";
    private String password = "TODO";
    private String url = "https://sapes1.sapdevcenter.com/sap/opu/odata/IWBEP/RMTSAMPLEFLIGHT_2/";
    private String command = "FlightCollection(AirLineID='AA',FlightConnectionID='0017',FlightDate=datetime'2012-08-29T00%3A00%3A00')";
---------------------------------------------------------------------------------------------------------------------------------------

The password is invalid. You would need to create an account at SAP
first to run the demo.

The velocity template is used for formatting the response to a basic
HTML page

[source,xml]
------------------------------------------------------------------------
<html>
  <body>
  Flight information:

  <p/>
  <br/>Airline ID: $body["AirLineID"]
  <br/>Aircraft Type: $body["AirCraftType"]
  <br/>Departure city: $body["FlightDetails"]["DepartureCity"]
  <br/>Departure airport: $body["FlightDetails"]["DepartureAirPort"]
  <br/>Destination city: $body["FlightDetails"]["DestinationCity"]
  <br/>Destination airport: $body["FlightDetails"]["DestinationAirPort"]

  </body>
</html>
------------------------------------------------------------------------

When running the application you get sample output:

-------------------------------
Flight information:
Airline ID: AA
Aircraft Type: 747-400
Departure city: new york
Departure airport: JFK
Destination city: SAN FRANCISCO
Destination airport: SFO
-------------------------------


include::{page-component-version}@camel-spring-boot::page$sap-netweaver-starter.adoc[]
