= Facebook Component
:doctitle: Facebook
:shortname: facebook
:artifactid: camel-facebook
:description: Send requests to Facebook APIs supported by Facebook4J.
:since: 2.14
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:camel-spring-boot-name: facebook

*Since Camel {since}*

*{component-header}*

The Facebook component provides access to all of the Facebook APIs
accessible using https://facebook4j.github.io/en/index.html[Facebook4J]. It
allows producing messages to retrieve, add, and delete posts, likes,
comments, photos, albums, videos, photos, checkins, locations, links,
etc. It also supports APIs that allow polling for posts, users,
checkins, groups, locations, etc.

Facebook requires the use of OAuth for all client application
authentication. In order to use camel-facebook with your account, you'll
need to create a new application within Facebook at
https://developers.facebook.com/apps[https://developers.facebook.com/apps]
and grant the application access to your account. The Facebook
application's id and secret will allow access to Facebook APIs which do
not require a current user. A user access token is required for APIs
that require a logged in user. More information on obtaining a user
access token can be found at
https://developers.facebook.com/docs/facebook-login/access-tokens/[https://developers.facebook.com/docs/facebook-login/access-tokens/].

Maven users will need to add the following dependency to their pom.xml
for this component:

[source,xml]
-----------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-facebook</artifactId>
    <version>${camel-version}</version>
</dependency>
-----------------------------------------------

== URI format

---------------------------------
facebook://[endpoint]?[options]
---------------------------------

The facebook component can be configured with the Facebook account
settings below, which are mandatory. The values can be provided to the
component using the bean property *configuration* of type
*org.apache.camel.component.facebook.config.FacebookConfiguration*. The
*oAuthAccessToken* option may be ommited but that will only allow access
to application APIs.


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END

// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

== Producer Endpoints:

Producer endpoints can use endpoint names and options from the table
below. Endpoints can also use the short name without the *get* or
*search* prefix, except *checkin* due to ambiguity between *getCheckin*
and *searchCheckin*. Endpoint options that are not mandatory are denoted
by [].

Producer endpoints can also use a special option **inBody** that in turn
should contain the name of the endpoint option whose value will be
contained in the Camel Exchange In message. For example, the facebook
endpoint in the following route retrieves activities for the user id
value in the incoming message body.

[source,java]
--------------------------------------------------------------------
from("direct:test").to("facebook://activities?inBody=userId")...
--------------------------------------------------------------------

Any of the endpoint options can be provided in either the endpoint URI,
or dynamically in a message header. The message header name must be of
the format `CamelFacebook.option`.
For example, the *userId* option value in the previous route could
alternately be provided in the message header *CamelFacebook.userId*.
Note that the inBody option overrides message header, e.g. the endpoint
option *inBody=user* would override a *CamelFacebook.userId* header.

Endpoints that return a String return an Id for the created or modified
entity, e.g. *addAlbumPhoto* returns the new album Id. Endpoints that
return a boolean, return true for success and false otherwise. In case
of Facebook API errors the endpoint will throw a RuntimeCamelException
with a facebook4j.FacebookException cause.

== Consumer Endpoints:

Any of the producer endpoints that take a
reading parameter can be used as a consumer endpoint. The polling consumer uses
the *since* and *until* fields to get responses within the polling
interval. In addition to other reading fields, an initial *since* value
can be provided in the endpoint for the first poll.

Rather than the endpoints returning a List (or
*facebook4j.ResponseList*) through a single route exchange,
camel-facebook creates one route exchange per returned object. As an
example, if *"facebook://home"* results in five posts, the route will be
executed five times (once for each Post).

== Reading Options

The *reading* option of type *facebook4j.Reading* adds support for
reading parameters, which allow selecting specific fields, limits the
number of results, etc. For more information see
https://developers.facebook.com/docs/reference/api/#reading[Graph API documentation].

It is also used by consumer endpoints to poll Facebook data to avoid
sending duplicate messages across polls.

The reading option can be a reference or value of type
*facebook4j.Reading*, or can be specified using the following reading
options in either the endpoint URI or exchange header with
*CamelFacebook.* prefix.

== Message header

Any of the URI options can be provided in a message header for producer
endpoints with `CamelFacebook.` prefix.

== Message body

All result message bodies utilize objects provided by the Facebook4J
API. Producer endpoints can specify the option name for incoming message
body in the *inBody* endpoint parameter.

For endpoints that return an array, or *facebook4j.ResponseList*, or
*java.util.List*, a consumer endpoint will map every elements in the
list to distinct messages.

== Use cases

To create a post within your Facebook profile, send this producer a
facebook4j.PostUpdate body.

[source,java]
----------------------------------------------------
from("direct:foo")
    .to("facebook://postFeed/inBody=postUpdate);
----------------------------------------------------

To poll, every 5 sec (You can set the xref:eips:polling-consumer.adoc[polling
consumer] options by adding a prefix of "consumer"), all statuses on
your home feed:

[source,java]
-----------------------------------------------
from("facebook://home?delay=5000")
    .to("bean:blah");
-----------------------------------------------

Searching using a producer with dynamic options from header.

In the bar header we have the Facebook search string we want to execute
in public posts, so we need to assign this value to the
CamelFacebook.query header.

[source,java]
--------------------------------------------------------
from("direct:foo")
    .setHeader("CamelFacebook.query", header("bar"))
    .to("facebook://posts");
--------------------------------------------------------


include::spring-boot:partial$starter.adoc[]
