= Servlet Component
:doctitle: Servlet
:shortname: servlet
:artifactid: camel-servlet
:description: Serve HTTP requests by a Servlet.
:since: 2.0
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only consumer is supported
//Manually maintained attributes
:camel-spring-boot-name: servlet

*Since Camel {since}*

*{component-header}*

The Servlet component provides HTTP-based
endpoints for consuming HTTP requests that arrive at
an HTTP endpoint that is bound to a published Servlet.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
---------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-servlet</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
---------------------------------------------------------------


[NOTE]
====
*Stream*

Servlet is stream-based, which means the input it receives is submitted
to Camel as a stream. That means you will only be able to read the
content of the stream *once*. If you find a situation where the message
body appears to be empty, or you need to access the data multiple times
(eg: doing multicasting, or redelivery error handling), you should use
Stream caching or convert the message body to
a `String` which is safe to be read multiple times.
====

== URI format

---------------------------------
servlet://relative_path[?options]
---------------------------------


// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END



== Message Headers

Camel will apply the same Message Headers as the xref:http-component.adoc[HTTP]
component.

Camel will also populate *all* `request.parameter` and
`request.headers`. For example, if a client request has the URL,
http://myserver/myserver?orderid=123, the exchange will contain a
header named `orderid` with the value `123`.

== Examples

You can consume only `from` endpoints generated by the Servlet component.
Therefore, it should be used only as input into your Camel routes. To
issue HTTP requests against other HTTP endpoints, use the
xref:http-component.adoc[HTTP Component].

=== Example `CamelHttpTransportServlet` configuration

==== Camel Spring Boot / Camel Quarkus

When running camel-servlet on the Spring Boot or Camel Quarkus runtimes, `CamelHttpTransportServlet` is configured for
you automatically and is driven by configuration properties. Refer to the camel-servlet configuration documentation for these runtimes.

==== Servlet container / application server

If you're running Camel standalone on a Servlet container or application server, you can use `web.xml` to configure `CamelHttpTransportServlet`.

For example, to define a route that exposes an HTTP service under the path `/services`.

[source,xml]
-------------------------------------------------------------------------
<web-app>
  <servlet>
    <servlet-name>CamelServlet</servlet-name>
    <servlet-class>org.apache.camel.component.servlet.CamelHttpTransportServlet</servlet-class>
  </servlet>

  <servlet-mapping>
    <servlet-name>CamelServlet</servlet-name>
    <url-pattern>/services/*</url-pattern>
  </servlet-mapping>
</web-app>
-------------------------------------------------------------------------

=== Example route

[source,java]
-------------------------------------------------------------------------
from("servlet:hello").process(new Processor() {
    public void process(Exchange exchange) throws Exception {
        // Access HTTP headers sent by the client
        Message message = exchange.getMessage();
        String contentType = message.getHeader(Exchange.CONTENT_TYPE, String.class);
        String httpUri = message.getHeader(Exchange.HTTP_URI, String.class);

        // Set the response body
        message.setBody("<b>Got Content-Type: " + contentType = ", URI: " + httpUri + "</b>");
    }
});
-------------------------------------------------------------------------

=== Camel Servlet HTTP endpoint path

The full path where the camel-servlet HTTP endpoint is published depends on:

* The Servlet application context path
* The configured Servlet mapping URL patterns
* The camel-servlet endpoint URI context path

For example, if the application context path is `/camel` and `CamelHttpTransportServlet` is configured with a URL mapping of `/services/*`.
Then a Camel route like `from("servlet:hello")` would be published to a path like http://localhost:8080/camel/services/hello.

=== Servlet asynchronous support

To enable Camel to benefit from Servlet asynchronous support, you must enable the `async` boolean init parameter by setting it to `true`.

By default, the servlet thread pool is used for exchange processing. However, to use a custom thread pool, you can configure an init parameter named `executorRef` with the String value set to the name of a bean bound to the Camel registry of type `Executor`.
If no bean was found in the Camel registry, the Servlet component will attempt to fall back on an executor policy or default executor service.

If you want to force exchange processing to wait in another container background thread, you can set the `forceAwait` boolean init parameter to `true`.

On the Camel Quarkus runtime, these init parameters can be set via configuration properties. Refer to the Camel Quarkus Servlet extension documentation for more information.

On other runtimes you can configure these parameters in `web.xml` as follows.

[source,xml]
-----------------------------------------------------------------------------------------------
<web-app>
    <servlet>
        <servlet-name>CamelServlet</servlet-name>
        <servlet-class>org.apache.camel.component.servlet.CamelHttpTransportServlet</servlet-class>
        <init-param>
            <param-name>async</param-name>
            <param-value>true</param-value>
        </init-param>
        <init-param>
            <param-name>executorRef</param-name>
            <param-value>my-custom-thread-pool</param-value>
        </init-param>
    </servlet>

    <servlet-mapping>
        <servlet-name>CamelServlet</servlet-name>
        <url-pattern>/services/*</url-pattern>
    </servlet-mapping>
</web-app>
-----------------------------------------------------------------------------------------------

=== Camel JARs on an application server boot classpath

If deploying into an application server / servlet container and you choose to have Camel JARs such as `camel-core`, `camel-servlet`, etc on the boot classpath.
Then the servlet mapping list will be shared between multiple deployed Camel application in the app server.

WARNING: Having Camel JARs on the boot classpath of the application server is not best practice.

In this scenario, you *must* define a custom and unique servlet name in each of your Camel applications. For example, in `web.xml`:

[source,xml]
---------------------------------------------------------------------------------------------
<web-app>
    <servlet>
      <servlet-name>MyServlet</servlet-name>
      <servlet-class>org.apache.camel.component.servlet.CamelHttpTransportServlet</servlet-class>
      <load-on-startup>1</load-on-startup>
    </servlet>

    <servlet-mapping>
      <servlet-name>MyServlet</servlet-name>
      <url-pattern>/*</url-pattern>
    </servlet-mapping>
</web-app>
---------------------------------------------------------------------------------------------

In your Camel servlet endpoints, include the servlet name:

[source,java]
---------------------------------------------------
from("servlet://foo?servletName=MyServlet")
---------------------------------------------------

Camel detects duplicate Servlet names and will fail to
start the application. You can control and ignore such duplicates by
setting the servlet init parameter `ignoreDuplicateServletName` to `true` as
follows:

[source,xml]
-----------------------------------------------------------------------------------------------
  <servlet>
    <servlet-name>CamelServlet</servlet-name>
    <display-name>Camel Http Transport Servlet</display-name>
    <servlet-class>org.apache.camel.component.servlet.CamelHttpTransportServlet</servlet-class>
    <init-param>
      <param-name>ignoreDuplicateServletName</param-name>
      <param-value>true</param-value>
    </init-param>
  </servlet>
-----------------------------------------------------------------------------------------------

But it is *strongly advised* to use unique `servlet-name` for each Camel
application to avoid this duplication clash, as well any unforeseen
side effects.

include::spring-boot:partial$starter.adoc[]
