[[hwcloud-dms-component]]
= Huawei Distributed Message Service (DMS) Component
:docTitle: Huawei Distributed Message Service (DMS)
:artifactId: camel-huaweicloud-dms
:description: To integrate with a fully managed, high-performance message queuing service on Huawei Cloud
:since: 3.12
:supportLevel: Preview
:component-header: Only producer is supported
include::{cq-version}@camel-quarkus:ROOT:partial$reference/components/hwcloud-dms.adoc[opts=optional]
//Manually maintained attributes
:group: Huawei Cloud

*Since Camel {since}*

*{component-header}*


Huawei Cloud Distributed Message Service (DMS) component allows you to integrate with https://www.huaweicloud.com/intl/en-us/product/dms.html[DMS] provided by Huawei Cloud.

Maven users will need to add the following dependency to their `pom.xml` for this component:

[source,xml]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-huaweicloud-dms</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
----

== URI Format

----
hwcloud-dms:operation[?options]
----

// component-configure options: START
== Configuring Options

Camel components are configured on two separate levels:

- component level
- endpoint level

=== Configuring Component Options

The component level is the highest level which holds general and common configurations that are inherited by the endpoints.
For example a component may have security settings, credentials for authentication, urls for network connection and so forth.

Some components only have a few options, and others may have many. Because components typically have pre configured defaults
that are commonly used, then you may often only need to configure a few options on a component; or none at all.

Configuring components can be done with the xref:latest@manual::component-dsl.adoc[Component DSL],
in a configuration file (application.properties|yaml), or directly with Java code.

=== Configuring Endpoint Options

Where you find yourself configuring the most is on endpoints, as endpoints often have many options, which allows you to
configure what you need the endpoint to do. The options are also categorized into whether the endpoint is used as consumer (from)
or as a producer (to), or used for both.

Configuring endpoints is most often done directly in the endpoint URI as path and query parameters. You can also use
the xref:latest@manual::Endpoint-dsl.adoc[Endpoint DSL] as a _type safe_ way of configuring endpoints.

A good practice when configuring options is to use xref:latest@manual::using-propertyplaceholder.adoc[Property Placeholders],
which allows to not hardcode urls, port numbers, sensitive information, and other settings.
In other words placeholders allows to externalize the configuration from your code, and gives more flexibility and reuse.

The following two sections lists all the options, firstly for the component followed by the endpoint.
// component-configure options: END

// component options: START
== Component Options


The Huawei Distributed Message Service (DMS) component supports 2 options, which are listed below.



[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *lazyStartProducer* (producer) | Whether the producer should be started lazy (on the first message). By starting lazy you can use this to allow CamelContext and routes to startup in situations where a producer may otherwise fail during starting and cause the route to fail being started. By deferring this startup to be lazy then the startup failure can be handled during routing messages via Camel's routing error handlers. Beware that when the first message is processed then creating and starting the producer may take a little time and prolong the total processing time of the processing. | false | boolean
| *autowiredEnabled* (advanced) | Whether autowiring is enabled. This is used for automatic autowiring options (the option must be marked as autowired) by looking up in the registry to find if there is a single instance of matching type, which then gets configured on the component. This can be used for automatic configuring JDBC data sources, JMS connection factories, AWS Clients, etc. | true | boolean
|===
// component options: END

// endpoint options: START
== Endpoint Options

The Huawei Distributed Message Service (DMS) endpoint is configured using URI syntax:

----
hwcloud-dms:operation
----

with the following path and query parameters:

=== Path Parameters (1 parameters):


[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *operation* | *Required* Operation to be performed |  | String
|===


=== Query Parameters (14 parameters):


[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *authenticationKey* (producer) | *Required* Authentication key for the cloud user |  | String
| *endpoint* (producer) | DMS url. Carries higher precedence than region parameter based client initialization |  | String
| *engine* (producer) | The message engine. Either kafka or rabbitmq. If the parameter is not specified, all instances will be queried. There are 2 enums and the value can be one of: kafka, rabbitmq |  | String
| *ignoreSslVerification* (producer) | Ignore SSL verification | false | boolean
| *instanceId* (producer) | The id of the instance. This option is mandatory when deleting or querying an instance |  | String
| *lazyStartProducer* (producer) | Whether the producer should be started lazy (on the first message). By starting lazy you can use this to allow CamelContext and routes to startup in situations where a producer may otherwise fail during starting and cause the route to fail being started. By deferring this startup to be lazy then the startup failure can be handled during routing messages via Camel's routing error handlers. Beware that when the first message is processed then creating and starting the producer may take a little time and prolong the total processing time of the processing. | false | boolean
| *projectId* (producer) | *Required* Cloud project ID |  | String
| *proxyHost* (producer) | Proxy server ip/hostname |  | String
| *proxyPassword* (producer) | Proxy authentication password |  | String
| *proxyPort* (producer) | Proxy server port |  | int
| *proxyUser* (producer) | Proxy authentication user |  | String
| *region* (producer) | *Required* DMS service region |  | String
| *secretKey* (producer) | *Required* Secret key for the cloud user |  | String
| *serviceKeys* (producer) | Configuration object for cloud service authentication |  | ServiceKeys
|===
// endpoint options: END


== Usage

=== Message properties evaluated by the DMS producer

[width="100%",cols="10%,10%,80%",options="header",]
|=======================================================================
|Header |Type |Description

|`CamelHwCloudDmsOperation` |`String` | Name of operation to invoke

|`CamelHwCloudDmsEngine` |`String` | The message engine. Either kafka or rabbitmq

|`CamelHwCloudDmsInstanceId` |`String` | Instance ID to invoke operation on

|=======================================================================

If any of the above properties are set, they will override their corresponding query parameter.

== List of Supported DMS Operations

- listInstances
- queryInstance

== Using ServiceKey Configuration Bean

Authentication key and secret keys are required to authenticate against cloud DMS service. You can avoid having them being exposed
and scattered over in your endpoint uri by wrapping them inside a bean of class `org.apache.camel.component.huaweicloud.common.models.ServiceKeys`.
Add it to the registry and let Camel look it up by referring the object via endpoint query parameter `serviceKeys`.

Check the following code snippets:

[source,xml]
----
<bean id="myServiceKeyConfig" class="org.apache.camel.component.huaweicloud.common.models.ServiceKeys">
   <property name="authenticationKey" value="your_authentication_key" />
   <property name="secretKey" value="your_secret_key" />
</bean>
----
[source,java]
----
from("direct:triggerRoute")
 .to("hwcloud-dms:listInstances?region=cn-north-4&serviceKeys=#myServiceKeyConfig")
----
