= ZooKeeper Master Component
:doctitle: ZooKeeper Master
:shortname: zookeeper-master
:artifactid: camel-zookeeper-master
:description: Have only a single consumer in a cluster consuming from a given endpoint; with automatic failover if the JVM dies.
:since: 2.19
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only consumer is supported
//Manually maintained attributes
:camel-spring-boot-name: zookeeper-master

*Since Camel {since}*

*{component-header}*

The **zookeeper-master:** endpoint provides a way to ensure only a single consumer in a cluster consumes from a given endpoint;
with automatic failover if that JVM dies.

This can be very useful if you need to consume from some legacy back end which either doesn't support concurrent
consumption or due to commercial or stability reasons you can only have a single connection at any point in time.

== Using the master endpoint

Just prefix any camel endpoint with **zookeeper-master:someName:** where _someName_ is a logical name and is
used to acquire the master lock. e.g.

[source,java]
----
from("zookeeper-master:cheese:jms:foo").to("activemq:wine");
----

The above simulates the [Exclusive Consumers](http://activemq.apache.org/exclusive-consumer.html) type feature in
ActiveMQ; but on any third party JMS provider which maybe doesn't support exclusive consumers.


== URI format

----
zookeeper-master:name:endpoint[?options]
----

Where endpoint is any Camel endpoint you want to run in master/slave mode.



// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END



== Example

You can protect a clustered Camel application to only consume files from one active node.


[source,java]
----
    // the file endpoint we want to consume from
    String url = "file:target/inbox?delete=true";

    // use the zookeeper master component in the clustered group named myGroup
    // to run a master/slave mode in the following Camel url
    from("zookeeper-master:myGroup:" + url)
        .log(name + " - Received file: ${file:name}")
        .delay(delay)
        .log(name + " - Done file:     ${file:name}")
        .to("file:target/outbox");
----

ZooKeeper will by default connect to `localhost:2181`, but you can configure this on the component level.

[source,java]
----
    MasterComponent master = new MasterComponent();
    master.setZooKeeperUrl("myzookeeper:2181");
----

However you can also configure the url of the ZooKeeper ensemble using environment variables.

[source,bash]
----
export ZOOKEEPER_URL = "myzookeeper:2181"
----

== Master RoutePolicy

You can also use a `RoutePolicy` to control routes in master/slave mode.

When doing so you must configure the route policy with

- url to zookeeper ensemble
- name of cluster group
- *important* and set the route to not auto startup

A little example

[source,java]
----
    MasterRoutePolicy master = new MasterRoutePolicy();
    master.setZooKeeperUrl("localhost:2181");
    master.setGroupName("myGroup");

    // its import to set the route to not auto startup
    // as we let the route policy start/stop the routes when it becomes a master/slave etc
    from("file:target/inbox?delete=true").noAutoStartup()
        // use the zookeeper master route policy in the clustered group
        // to run this route in master/slave mode
        .routePolicy(master)
        .log(name + " - Received file: ${file:name}")
        .delay(delay)
        .log(name + " - Done file:     ${file:name}")
        .to("file:target/outbox");
----



include::spring-boot:partial$starter.adoc[]
