= Paho Component
:doctitle: Paho
:shortname: paho
:artifactid: camel-paho
:description: Communicate with MQTT message brokers using Eclipse Paho MQTT Client.
:since: 2.16
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:camel-spring-boot-name: paho

*Since Camel {since}*

*{component-header}*

Paho component provides a connector for the https://en.wikipedia.org/wiki/MQTT[MQTT] messaging protocol using
the https://eclipse.org/paho/[Eclipse Paho] library.
Paho is one of the most popular MQTT libraries, so if you would like to integrate it with
your Java project - Camel Paho connector is a way to go.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-paho</artifactId>
    <version>x.y.z</version>
    <!-- use the same version as your Camel core version -->
</dependency>
----

== URI format

[source]
----
paho:topic[?options]
----

Where `topic` is the name of the topic.


// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END
// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END


== Default payload type

By default, the Camel Paho component operates on the binary payloads
extracted out of (or put into) the MQTT message:

[source,java]
----
// Receive payload
byte[] payload = (byte[]) consumerTemplate.receiveBody("paho:topic");

// Send payload
byte[] payload = "message".getBytes();
producerTemplate.sendBody("paho:topic", payload);
----

Of course, Camel build-in xref:manual::type-converter.adoc[type conversion API] can perform the automatic data type transformations for you.
In the example below Camel automatically converts binary payload into `String` (and conversely):

[source,java]
----
// Receive payload
String payload = consumerTemplate.receiveBody("paho:topic", String.class);

// Send payload
String payload = "message";
producerTemplate.sendBody("paho:topic", payload);
----


== Samples

For example, the following snippet reads messages from the MQTT broker
installed on the same host as the Camel router:

[source,java]
----
from("paho:some/queue")
    .to("mock:test");
----

While the snippet below sends a message to the MQTT broker:

[source,java]
----
from("direct:test")
    .to("paho:some/target/queue");
----

For example, this is how to read messages from the remote MQTT broker:

[source,java]
----
from("paho:some/queue?brokerUrl=tcp://iot.eclipse.org:1883")
    .to("mock:test");
----

And here we override the default topic and set to a dynamic topic

[source,java]
----
from("direct:test")
    .setHeader(PahoConstants.CAMEL_PAHO_OVERRIDE_TOPIC, simple("${header.customerId}"))
    .to("paho:some/target/queue");
----


include::spring-boot:partial$starter.adoc[]
