site:
  title: Apache Camel

content:
  sources:
    - url: ../
      branches: HEAD
      start_path: docs/user-manual
    - url: ../
      branches: HEAD
      start_path: docs/components

ui:
  bundle:
    url: not-used
