== XML Beans DataFormat (deprecated)

*Available as of Camel version 1.2*

XmlBeans is a link:data-format.html[Data Format] which uses the
http://xmlbeans.apache.org/[XmlBeans library] to unmarshal an XML
payload into Java objects or to marshal Java objects into an XML
payload.

[source,java]
-------------------------------
from("activemq:My.Queue").
  unmarshal().xmlBeans().
  to("mqseries:Another.Queue");
-------------------------------

### Options

// dataformat options: START
The XML Beans dataformat supports 2 options which are listed below.



[width="100%",cols="2s,1m,1m,6",options="header"]
|===
| Name | Default | Java Type | Description
| prettyPrint | false | Boolean | To enable pretty printing output nicely formatted. Is by default false.
| contentTypeHeader | false | Boolean | Whether the data format should set the Content-Type header with the type from the data format if the data format is capable of doing so. For example application/xml for data formats marshalling to XML or application/json for data formats marshalling to JSon etc.
|===
// dataformat options: END

### Dependencies

To use XmlBeans in your camel routes you need to add the dependency on
*camel-xmlbeans* which implements this data format.

If you use maven you could just add the following to your pom.xml,
substituting the version number for the latest & greatest release (see
link:download.html[the download page for the latest versions]).

[source,xml]
----------------------------------------------------------
<dependency>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-xmlbeans</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel core version -->
</dependency>
----------------------------------------------------------