= RabbitMQ Component (deprecated)
:doctitle: RabbitMQ
:shortname: rabbitmq
:artifactid: camel-rabbitmq
:description: Send and receive messages from RabbitMQ instances.
:since: 2.12
:supportlevel: Stable-deprecated
:deprecated: *deprecated*
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:camel-spring-boot-name: rabbitmq

*Since Camel {since}*

*{component-header}*

The RabbitMQ component allows you to produce and consume messages from
http://www.rabbitmq.com/[RabbitMQ] instances. Using the RabbitMQ AMQP
client, this component offers a pure RabbitMQ approach over the generic
http://camel.apache.org/amqp.html[AMQP] component.

IMPORTANT: It is recommended to use the xref:components::spring-rabbitmq-component.adoc[Camel Spring RabbitMQ]
component, instead of using this component.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-rabbitmq</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
----

== URI format

----
rabbitmq:exchangeName?[options]
----

The exchange name determines the exchange to which the produced 
messages will be sent to. In the case of consumers, the exchange name 
determines the exchange the queue will be bound to.

// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END



== Using a connection factory

To connect to RabbitMQ you can setup a `ConnectionFactory` (same as with JMS) with the login details such as:

[source,xml]
----
<bean id="rabbitConnectionFactory" class="com.rabbitmq.client.ConnectionFactory">
  <property name="host" value="localhost"/>
  <property name="port" value="5672"/>
  <property name="username" value="camel"/>
  <property name="password" value="bugsbunny"/>
</bean>
----

And then refer to the connection factory in the endpoint uri as shown below:

[source,xml]
----
<camelContext>
  <route>
    <from uri="direct:rabbitMQEx2"/>
    <to uri="rabbitmq:ex2?connectionFactory=#rabbitConnectionFactory"/>
  </route>
</camelContext>
----

The `ConnectionFactory` is auto-detected by default, so you can just do

[source,xml]
----
<camelContext>
  <route>
    <from uri="direct:rabbitMQEx2"/>
    <to uri="rabbitmq:ex2"/>
  </route>
</camelContext>
----

In case you have multiple connection factories in your application or multiple connection factories in your registry, don't forget to set the `autoDetectConnectionFactory` to false.

// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END

== Troubleshooting headers

Watch out when consuming from a RabbitMq queue and producing to *the same* RabbitMq exchange. The header details on the exchange may be populated with headers that will not be overriden by the destination endpoint. The following example will help understand the pitfall.

[source,java]
----
from("rabbitmq:A?queue=IN&declare=false&autoDelete=false&arg.queue.x-message-ttl=20000")
  // ... your route
  .to("rabbitmq:A?queue=OUT&routingKey=OUT&declare=false&autoDelete=false&arg.queue.x-message-ttl=20000");
----

You would think that it would be a straight forward operation. However, if the source queue has a routing key set in the headers, it will pass down to the destination and not be overriden with the URI query parameters. Because the exchange is the same and the routing key is the same, an infinitely growing loop is created.

Either make a second exchange for the producer to avoid the headers to pass through or manually access the exchange headers in a processor and get rid of the misbehaving key.

[source,java]
----
from("rabbitmq:A?queue=IN&declare=false&autoDelete=false&arg.queue.x-message-ttl=20000")
  // ...
  .process(e -> {
    InputModel input = e.getMessage().getBody(InputModel.class);
    e.getMessage().removeHeader("CamelRabbitmqRoutingKey");
    OutputModel output = ...
    e.getMessage().setBody(output);
  })
  // ...
  .to("rabbitmq:A?queue=OUT&routingKey=OUT&declare=false&autoDelete=false&arg.queue.x-message-ttl=20000");
----

Now you are at least guaranteed to not create a loop from the camel route.

== Allowing custom Headers

The `allowCustomHeaders` endpoint option can be used to avoid adding custom headers to the message sent to RabbitMQ.
If set to false, the user will have only CamelRabbitmq* headers in the payload of the message. Default value for this option is true.

[NOTE]
====
If you decide to use the allowCustomHeaders option, don't add sensitive information as header. It's not recommended and it's dangerous. Don't do it.
====

== Message Body

The component will use the camel exchange in body as the rabbit mq
message body. The camel exchange in object must be convertible to a byte
array. Otherwise the producer will throw an exception of unsupported
body type.

== Samples

To receive messages from a queue that is bound to an exchange A with the
routing key B,

[source,java]
----
from("rabbitmq:A?routingKey=B")
  .to("log:cheese");
----

To receive messages from a queue with a single thread with auto
acknowledge disabled.

[source,java]
----
from("rabbitmq:A?routingKey=B&threadPoolSize=1&autoAck=false")
  .to("log:cheese");
----

To send messages to an exchange called C

[source,java]
----
from("direct:foo")
  .to("rabbitmq:C");
----

Declaring a headers exchange and queue

[source,java]
----
from("rabbitmq:ex?exchangeType=headers&queue=q&bindingArgs=#bindArgs")
  .to("log:cheese");
----

and place corresponding `Map<String, Object>` with the id of "bindArgs" in the Registry.

For example declaring a method in Spring

[source,java]
----
@Bean(name = "bindArgs")
public Map<String, Object> bindArgsBuilder() {
    return new HashMap<String, Object>() {{
        put("binding.foo", "bar");
    }};
}
----



include::spring-boot:partial$starter.adoc[]
