== RMI Component

*Available as of Camel version 1.0*

The *rmi:* component binds link:exchange.html[Exchange]s to the RMI
protocol (JRMP).

Since this binding is just using RMI, normal RMI rules still apply
regarding what methods can be invoked. This component supports only
Exchanges that carry a method invocation from an interface that extends
the http://java.sun.com/j2se/1.3/docs/api/java/rmi/Remote.html[Remote]
interface. All parameters in the method should be either
http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html[Serializable]
or `Remote` objects.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-rmi</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

### URI format

[source,java]
------------------------------------------------------------------
rmi://rmi-regisitry-host:rmi-registry-port/registry-path[?options]
------------------------------------------------------------------

For example:

[source,java]
------------------------------------
rmi://localhost:1099/path/to/service
------------------------------------

You can append query options to the URI in the following format,
`?option=value&option=value&...`

### Options


// component options: START
The RMI component has no options.
// component options: END



// endpoint options: START
The RMI endpoint is configured using URI syntax:

----
rmi:hostname:port/name
----

with the following path and query parameters:

==== Path Parameters (3 parameters):

[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *hostname* | Hostname of RMI server | localhost | String
| *name* | *Required* Name to use when binding to RMI server |  | String
| *port* | Port number of RMI server | 1099 | int
|===

==== Query Parameters (6 parameters):

[width="100%",cols="2,5,^1,2",options="header"]
|===
| Name | Description | Default | Type
| *method* (common) | You can set the name of the method to invoke. |  | String
| *remoteInterfaces* (common) | To specific the remote interfaces. |  | List
| *bridgeErrorHandler* (consumer) | Allows for bridging the consumer to the Camel routing Error Handler which mean any exceptions occurred while the consumer is trying to pickup incoming messages or the likes will now be processed as a message and handled by the routing Error Handler. By default the consumer will use the org.apache.camel.spi.ExceptionHandler to deal with exceptions that will be logged at WARN or ERROR level and ignored. | false | boolean
| *exceptionHandler* (consumer) | To let the consumer use a custom ExceptionHandler. Notice if the option bridgeErrorHandler is enabled then this options is not in use. By default the consumer will deal with exceptions that will be logged at WARN or ERROR level and ignored. |  | ExceptionHandler
| *exchangePattern* (consumer) | Sets the exchange pattern when the consumer creates an exchange. |  | ExchangePattern
| *synchronous* (advanced) | Sets whether synchronous processing should be strictly used or Camel is allowed to use asynchronous processing (if supported). | false | boolean
|===
// endpoint options: END


### Using

To call out to an existing RMI service registered in an RMI registry,
create a route similar to the following:

[source,java]
------------------------------------------------
from("pojo:foo").to("rmi://localhost:1099/foo");
------------------------------------------------

To bind an existing camel processor or service in an RMI registry,
define an RMI endpoint as follows:

[source,java]
-------------------------------------------------------------------------
RmiEndpoint endpoint= (RmiEndpoint) endpoint("rmi://localhost:1099/bar");
endpoint.setRemoteInterfaces(ISay.class);
from(endpoint).to("pojo:bar");
-------------------------------------------------------------------------

Note that when binding an RMI consumer endpoint, you must specify the
`Remote` interfaces exposed.

In XML DSL you can do as follows from *Camel 2.7* onwards:

[source,xml]
------------------------------------------------------------------------------------------------------------------------
    <camel:route>
        <from uri="rmi://localhost:37541/helloServiceBean?remoteInterfaces=org.apache.camel.example.osgi.HelloService"/>
        <to uri="bean:helloServiceBean"/>
    </camel:route>
------------------------------------------------------------------------------------------------------------------------

### See Also

* link:configuring-camel.html[Configuring Camel]
* link:component.html[Component]
* link:endpoint.html[Endpoint]
* link:getting-started.html[Getting Started]
