= Slack Component
:doctitle: Slack
:shortname: slack
:artifactid: camel-slack
:description: Send and receive messages to/from Slack.
:since: 2.16
:supportlevel: Stable
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:camel-spring-boot-name: slack

*Since Camel {since}*

*{component-header}*

The Slack component allows you to connect to an instance
of http://www.slack.com/[Slack] and delivers a message contained in the
message body via a pre
established https://api.slack.com/incoming-webhooks[Slack incoming
webhook].

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-slack</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

== URI format

To send a message to a channel.

------------------------
slack:#channel[?options]
------------------------

To send a direct message to a slackuser.

-------------------------
slack:@userID[?options]
-------------------------



// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END


== Configuring in Sprint XML

The SlackComponent with XML must be configured as a Spring or Blueprint
bean that contains the incoming webhook url or the app token for the integration as a
parameter.

[source,xml]
-----------------------------------------------------------------------------------------------------------------------
<bean id="slack" class="org.apache.camel.component.slack.SlackComponent">
    <property name="webhookUrl" value="https://hooks.slack.com/services/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"/>
    <property name="token" value="xoxb-12345678901-1234567890123-xxxxxxxxxxxxxxxxxxxxxxxx"/>
</bean>
-----------------------------------------------------------------------------------------------------------------------

For Java you can configure this using Java code.

== Example

A CamelContext with Blueprint could be as:

[source,xml]
---------------------------------------------------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0" default-activation="lazy">

    <bean id="slack" class="org.apache.camel.component.slack.SlackComponent">
        <property name="webhookUrl" value="https://hooks.slack.com/services/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"/>
    </bean>

    <camelContext xmlns="http://camel.apache.org/schema/blueprint">
        <route>
            <from uri="direct:test"/>
            <to uri="slack:#channel?iconEmoji=:camel:&amp;username=CamelTest"/>
        </route>
    </camelContext>

</blueprint>
---------------------------------------------------------------------------------------------------------------------------

== Producer

You can now use a token to send a message instead of WebhookUrl

[source,java]
---------------------------------------------------------------------------------------------------------------------------
from("direct:test")
    .to("slack:#random?token=RAW(<YOUR_TOKEN>)");
---------------------------------------------------------------------------------------------------------------------------

You can now use the Slack API model to create blocks. You can read more about it here https://api.slack.com/block-kit

[source,java]
---------------------------------------------------------------------------------------------------------------------------
    public void testSlackAPIModelMessage() {
        Message message = new Message();
        message.setBlocks(Collections.singletonList(SectionBlock
                .builder()
                .text(MarkdownTextObject
                        .builder()
                        .text("*Hello from Camel!*")
                        .build())
                .build()));

        template.sendBody(test, message);
    }
---------------------------------------------------------------------------------------------------------------------------

== Consumer

You can use also a consumer for messages in channel

[source,java]
---------------------------------------------------------------------------------------------------------------------------
from("slack://general?token=RAW(<YOUR_TOKEN>)&maxResults=1")
    .to("mock:result");
---------------------------------------------------------------------------------------------------------------------------

In this way you'll get the last message from general channel. The consumer will take track of the timestamp of the last message consumed and in the next poll it will check from that timestamp.

You'll need to create a Slack app and use it on your workspace.

Use the 'Bot User OAuth Access Token' as token for the consumer endpoint.

IMPORTANT: Add the corresponding history (`channels:history` or `groups:history` or `mpim:history` or `im:history`) and
read (`channels:read` or `groups:read` or `mpim:read` or `im:read`) user token scope to your app to grant it permission to
view messages in the corresponding channel. You will need to use the conversationType option to set it up too (`PUBLIC_CHANNEL`, `PRIVATE_CHANNEL`, `MPIM`, `IM`)

The naturalOrder option allows consuming messages from the oldest to the newest.
Originally you would get the newest first and consume backward (message 3 => message 2 => message 1)

IMPORTANT: You can use the conversationType option to read history and messages from a channel that is not only public
(`PUBLIC_CHANNEL`,`PRIVATE_CHANNEL`, `MPIM`, `IM`)


include::spring-boot:partial$starter.adoc[]
