= AWS Managed Streaming for Apache Kafka (MSK) Component
:doctitle: AWS Managed Streaming for Apache Kafka (MSK)
:shortname: aws2-msk
:artifactid: camel-aws2-msk
:description: Manage AWS MSK instances.
:since: 3.1
:supportlevel: Stable
:tabs-sync-option:
:component-header: Only producer is supported
//Manually maintained attributes
:group: AWS
:camel-spring-boot-name: aws2-msk

*Since Camel {since}*

*{component-header}*

The AWS2 MSK component supports create, run, start, stop and terminate
https://aws.amazon.com/msk/[AWS MSK] instances.

Prerequisites

You must have a valid Amazon Web Services developer account, and be
signed up to use Amazon MSK. More information is available at
https://aws.amazon.com/msk/[Amazon MSK].

== URI Format

----
aws2-msk://label[?options]
----

You can append query options to the URI in the following format:

`?options=value&option2=value&...`

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
include::partial$component-endpoint-headers.adoc[]
// component options: END


Required MSK component options

You have to provide the amazonMskClient in the
Registry or your accessKey and secretKey to access
the https://aws.amazon.com/msk/[Amazon MSK] service.

== Usage

=== Static credentials vs Default Credential Provider

You have the possibility of avoiding the usage of explicit static credentials by specifying the useDefaultCredentialsProvider option and set it to true.

 - Java system properties - `aws.accessKeyId` and `aws.secretKey`.
 - Environment variables - `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
 - Web Identity Token from AWS STS.
 - The shared credentials and config files.
 - Amazon ECS container credentials - loaded from the Amazon ECS if the environment variable `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` is set.
 - Amazon EC2 Instance profile credentials. 

For more information about this you can look at https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials.html[AWS credentials documentation]

=== MSK Producer operations

Camel-AWS MSK component provides the following operation on the producer side:

- listClusters
- createCluster
- deleteCluster
- describeCluster

== Examples

=== Producer Examples

- listClusters: this operation will list the available MSK Brokers in AWS

[tabs]
====
Java::
+
[source,java]
----
from("direct:listClusters")
    .to("aws2-msk://test?mskClient=#amazonMskClient&operation=listClusters");
----

XML::
+
[source,xml]
----
<route>
  <from uri="direct:listClusters"/>
  <to uri="aws2-msk://test?mskClient=#amazonMskClient&amp;operation=listClusters"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:listClusters
      steps:
        - to:
            uri: aws2-msk://test
            parameters:
              mskClient: "#amazonMskClient"
              operation: listClusters
----
====

- createCluster: this operation will create an MSK Cluster in AWS

._Java-only: uses AWS SDK `BrokerNodeGroupInfo` builder_
[source,java]
----
from("direct:createCluster")
    .process(exchange -> {
        exchange.getIn().setHeader("CamelAwsMSKClusterName", "test-kafka");
        exchange.getIn().setHeader("CamelAwsMSKClusterKafkaVersion", "2.1.1");
        exchange.getIn().setHeader("CamelAwsMSKBrokerNodesNumber", 2);
        exchange.getIn().setHeader("CamelAwsMSKBrokerNodesGroupInfo",
            BrokerNodeGroupInfo.builder().build());
    })
    .to("aws2-msk://test?mskClient=#amazonMskClient&operation=createCluster");
----

- deleteCluster: this operation will delete an MSK Cluster in AWS

[tabs]
====
Java::
+
[source,java]
----
from("direct:deleteCluster")
    .setHeader("CamelAwsMSKClusterArn", constant("test-kafka"))
    .to("aws2-msk://test?mskClient=#amazonMskClient&operation=deleteCluster");
----

XML::
+
[source,xml]
----
<route>
    <from uri="direct:deleteCluster"/>
    <setHeader name="CamelAwsMSKClusterArn">
        <constant>test-kafka</constant>
    </setHeader>
    <to uri="aws2-msk://test?mskClient=#amazonMskClient&amp;operation=deleteCluster"/>
</route>
----

YAML::
+
[source,yaml]
----
- route:
    from:
      uri: direct:deleteCluster
    steps:
      - setHeader:
          name: CamelAwsMSKClusterArn
          constant: test-kafka
      - to:
          uri: aws2-msk://test
          parameters:
            mskClient: "#amazonMskClient"
            operation: deleteCluster
----
====

._Java-only: uses AWS SDK `BrokerNodeGroupInfo` builder_
[source,java]
----
from("direct:deleteCluster")
    .process(exchange -> {
        exchange.getIn().setHeader("CamelAwsMSKClusterName", "test-kafka");
        exchange.getIn().setHeader("CamelAwsMSKClusterKafkaVersion", "2.1.1");
        exchange.getIn().setHeader("CamelAwsMSKBrokerNodesNumber", 2);
        exchange.getIn().setHeader("CamelAwsMSKBrokerNodesGroupInfo",
            BrokerNodeGroupInfo.builder().build());
    })
    .to("aws2-msk://test?mskClient=#amazonMskClient&operation=deleteCluster");
----

=== Using a POJO as body

Sometimes building an AWS Request can be complex because of multiple options. We introduce the possibility to use a POJO as the body.
In AWS MSK, there are multiple operations you can submit, as an example for List clusters request, you can do something like:

._Java-only: using an AWS SDK POJO request as the message body_
[source,java]
----
from("direct:aws2-msk")
     .setBody(ListClustersRequest.builder().maxResults(10).build())
     .to("aws2-msk://test?mskClient=#amazonMskClient&operation=listClusters&pojoRequest=true")
----

In this way, you'll pass the request directly without the need of passing headers and options specifically related to this operation.

== Dependencies

Maven users will need to add the following dependency to their pom.xml.

*pom.xml*

[source,xml]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-aws2-msk</artifactId>
    <version>${camel-version}</version>
</dependency>
----

where `$\{camel-version}` must be replaced by the actual version of Camel.


include::spring-boot:partial$starter.adoc[]
