#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: PR Build (Camel 3.x)

on:
  pull_request:
    branches:
      - camel-3.20.x
      - camel-3.21.x
      - camel-3.x
    paths-ignore:
      - .github/**
      - README.md
      - SECURITY.md
      - Jenkinsfile
      - Jenkinsfile.*
      - NOTICE.txt

jobs:
  checkstyle:
    if: github.repository == 'apache/camel'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - id: install-mvnd
      uses: ./.github/actions/install-mvnd
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11
        cache: 'maven'
    - name: mvn checkstyle
      run: ${{ steps.install-mvnd.outputs.mvnd-dir }}/mvnd -l checkstyle.log $MVND_OPTS -e checkstyle:checkstyle
    - name: archive logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: checkstyle.log
        path: checkstyle.log
    - name: Generate failure checkstyle summary
      if: failure()
      run: |
        echo ":x: Checkstyle failed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
    - name: Generate successful checkstyle summary
      if: success()
      run: |
        echo ":white_check_mark: Checkstyle passed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
  build:
    if: github.repository == 'apache/camel'
    permissions:
      issues: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11' ]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - id: install-packages
        uses: ./.github/actions/install-packages
      - id: install-mvnd
        uses: ./.github/actions/install-mvnd
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: maven build
        run: ${{ steps.install-mvnd.outputs.mvnd-dir }}/mvnd -l build.log $MVND_OPTS -Pfastinstall -DskipTests install
      - name: archive logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build.log
          path: build.log
      - id: test
        name: Quick test execution for affected components
        uses: ./.github/actions/quick-test
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          start-commit: ${{ github.event.pull_request.base.sha }}
          end-commit: ${{ github.event.after }}
